### ISSUE TITLE
python-scipy's test fail with pillow 2.7, works with 2.6

### ISSUE THREAD

**Issue by doko42** [python-pillow/Pillow#1119]
```
FAIL: test_imresize4 (test_pilutil.TestPILUtil)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/numpy/testing/decorators.py", line 146, in skipper_func
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/scipy/misc/tests/test_pilutil.py", line 57, in test_imresize4
    assert_equal(im2, res)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 260, in assert_equal
    return assert_array_equal(actual, desired, err_msg, verbose)
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 718, in assert_array_equal
    verbose=verbose, header='Arrays are not equal')
  File "/usr/lib/python2.7/dist-packages/numpy/testing/utils.py", line 644, in assert_array_compare
    raise AssertionError(msg)
AssertionError:
Arrays are not equal

(mismatch 75.0%)
 x: array([[ 1. , 1.25, 1.75, 2. ],
       [ 1.5 , 1.75, 2.25, 2.5 ],
       [ 2.5 , 2.75, 3.25, 3.5 ],
       [ 3. , 3.25, 3.75, 4. ]], dtype=float32)
 y: array([[ 1. , 1. , 1.5, 2. ],
       [ 1. , 1. , 1.5, 2. ],
       [ 2. , 2. , 2.5, 3. ],
       [ 3. , 3. , 3.5, 4. ]], dtype=float32)
```
originally submitted at https://launchpad.net/bugs/1426841

**Comment by homm** [comment]
https://github.com/python-pillow/Pillow/issues/1074

> It's been merged in Scipy.
@wiredfool
