### ISSUE TITLE
Pillow install doesnt detect libtiff

### ISSUE THREAD

**Issue by botouser** [python-pillow/Pillow#1132]
I am installing pillow into a setuptools sandbox on a jenkins build box.

the  jenkins box has all the necessary libs. In particular, it has libtiff...

> $ dpkg -l | grep tiff
> ii  libtiff4:amd64                        3.9.6-11                       amd64        Tag Image File Format (TIFF) library (old version)

and  yet, the Pillow install wont detect the lib.

```
00:00:30.822 --------------------------------------------------------------------
00:00:30.822 PIL SETUP SUMMARY
00:00:30.822 --------------------------------------------------------------------
00:00:30.822 version      Pillow 2.7.0
00:00:30.822 platform     linux2 2.7.3 (default, Mar 13 2014, 11:03:55)
00:00:30.822              [GCC 4.7.2]
00:00:30.822 --------------------------------------------------------------------
00:00:30.822 *** TKINTER support not available
00:00:30.822 --- JPEG support available
00:00:30.822 *** OPENJPEG (JPEG2000) support not available
00:00:30.822 --- ZLIB (PNG/ZIP) support available
00:00:30.822 *** LIBTIFF support not available
00:00:30.822 --- FREETYPE2 support available
00:00:30.822 --- LITTLECMS2 support available
00:00:30.822 --- WEBP support available
00:00:30.822 *** WEBPMUX support not available
00:00:30.822 --------------------------------------------------------------------
```

In the logfile, I saw the following warnings, dont know if that has anything to do with it?

```
00:00:22.185 Getting distribution for 'Pillow==2.7.0'.
00:00:25.139 libImaging/Resample.c:87:45: warning: always_inline function might not be inlinable [-Wattributes]
00:00:28.354 Building using 4 processes
00:00:28.792 Building using 4 processes
00:00:29.221 Building using 4 processes
00:00:29.449 Building using 4 processes
00:00:29.979 Building using 4 processes
00:00:30.687 Exception in thread Thread-2:
00:00:30.687 Traceback (most recent call last):
00:00:30.687   File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
00:00:30.687     self.run()
00:00:30.687   File "/usr/lib/python2.7/threading.py", line 505, in run
00:00:30.687     self.__target(*self.__args, **self.__kwargs)
00:00:30.687   File "/usr/lib/python2.7/multiprocessing/pool.py", line 353, in _handle_tasks
00:00:30.687     debug('task handler got sentinel')
00:00:30.687 TypeError: 'NoneType' object is not callable
00:00:30.687 
00:00:30.689 Exception in thread Thread-1:
00:00:30.689 Traceback (most recent call last):
00:00:30.689   File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
00:00:30.689     self.run()
00:00:30.689   File "/usr/lib/python2.7/threading.py", line 505, in run
00:00:30.689     self.__target(*self.__args, **self.__kwargs)
00:00:30.689   File "/usr/lib/python2.7/multiprocessing/pool.py", line 329, in _handle_workers
00:00:30.689     debug('worker handler exiting')
00:00:30.689 TypeError: 'NoneType' object is not callable
00:00:30.689 
00:00:30.821 Error in atexit._run_exitfuncs:
00:00:30.821 Traceback (most recent call last):
00:00:30.821   File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
00:00:30.821     func(*targs, **kargs)
00:00:30.821   File "/usr/lib/python2.7/multiprocessing/util.py", line 284, in _exit_function
00:00:30.822     info('process shutting down')
00:00:30.822 TypeError: 'NoneType' object is not callable
00:00:30.822 Error in sys.exitfunc:
00:00:30.822 Building using 4 processes
00:00:30.822 --------------------------------------------------------------------
00:00:30.822 PIL SETUP SUMMARY
00:00:30.822 --------------------------------------------------------------------
00:00:30.822 version      Pillow 2.7.0
00:00:30.822 platform     linux2 2.7.3 (default, Mar 13 2014, 11:03:55)
00:00:30.822              [GCC 4.7.2]
00:00:30.822 --------------------------------------------------------------------
00:00:30.822 *** TKINTER support not available
00:00:30.822 --- JPEG support available
00:00:30.822 *** OPENJPEG (JPEG2000) support not available
00:00:30.822 --- ZLIB (PNG/ZIP) support available
00:00:30.822 *** LIBTIFF support not available
00:00:30.822 --- FREETYPE2 support available
00:00:30.822 --- LITTLECMS2 support available
00:00:30.822 --- WEBP support available
00:00:30.822 *** WEBPMUX support not available
00:00:30.822 --------------------------------------------------------------------
00:00:30.822 To add a missing option, make sure you have the required
00:00:30.822 library, and set the corresponding ROOT variable in the
00:00:30.822 setup.py script.
```

Can someone help me with this?

**Comment by wiredfool** [comment]
You need the libtiff4-dev package as well.

**Comment by botouser** [comment]
Thanks. That should fix it, hopefully.
