### ISSUE TITLE
Cannot identify XBM file created with filename including underscore

### ISSUE THREAD

**Issue by yachtship** [python-pillow/Pillow#1229]
Pillow 2.8.1, Python 2.7.6 (Anaconda 2.2.0), Windows 7 64bit

When I create git_hub.xbm (with ImageMagick), created file's header contains lines like this.
```C
#define git_hub_width 32
#define git_hub_height 32
```
In XbmImagePlugin.py, regular expression to extract XBM header doesn't match defined macro with more than two underscores like above.This causes an IOError.
```python
# XBM header
xbm_head = re.compile(
    b"\s*#define[ \t]+[^_]*_width[ \t]+(?P<width>[0-9]+)[\r\n]+"
    b"#define[ \t]+[^_]*_height[ \t]+(?P<height>[0-9]+)[\r\n]+"
    b"(?P<hotspot>"
    b"#define[ \t]+[^_]*_x_hot[ \t]+(?P<xhot>[0-9]+)[\r\n]+"
    b"#define[ \t]+[^_]*_y_hot[ \t]+(?P<yhot>[0-9]+)[\r\n]+"
    b")?"
    b"[\\000-\\377]*_bits\\[\\]"
)
```

**Comment by hugovk** [comment]
Reproducible:
```bash
convert hopper.png hopper.xbm
convert hopper.png hopper_test.xbm
python
```

```python
>>> from PIL import Image
>>> im = Image.open("hopper.xbm")
>>> im = Image.open("hopper_test.xbm")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\Python27\lib\site-packages\PIL\Image.py", line 2290, in open
    % (filename if filename else fp))
IOError: cannot identify image file 'hopper_test.xbm'
```

**Comment by hugovk** [comment]
PR https://github.com/python-pillow/Pillow/pull/1230 submitted to fix this.
