### ISSUE TITLE
Test failure on hppa - ERROR: TestFileIco.test_save_to_bytes OverflowError: Python int too large to convert to C ssize_t

### ISSUE THREAD

**Issue by jlec** [python-pillow/Pillow#1258]
See downstream report https://bugs.gentoo.org/show_bug.cgi?id=551422

```python
TestFileIco.test_save_to_bytes ... ERROR

======================================================================
ERROR: TestFileIco.test_save_to_bytes
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/pillow-2.8.1/work/Pillow-2.8.1-python3_3/Tests/test_file_ico.py", line 27, in test_save_to_bytes
    reloaded = Image.open(output)
  File "/var/tmp/portage/dev-python/pillow-2.8.1/work/Pillow-2.8.1-python3_3/build/lib/PIL/Image.py", line 2266, in open
    im = factory(fp, filename)
  File "/var/tmp/portage/dev-python/pillow-2.8.1/work/Pillow-2.8.1-python3_3/build/lib/PIL/ImageFile.py", line 97, in __init__
    self._open()
  File "/var/tmp/portage/dev-python/pillow-2.8.1/work/Pillow-2.8.1-python3_3/build/lib/PIL/IcoImagePlugin.py", line 265, in _open
    self.load()
  File "/var/tmp/portage/dev-python/pillow-2.8.1/work/Pillow-2.8.1-python3_3/build/lib/PIL/IcoImagePlugin.py", line 268, in load
    im = self.ico.getimage(self.size)
  File "/var/tmp/portage/dev-python/pillow-2.8.1/work/Pillow-2.8.1-python3_3/build/lib/PIL/IcoImagePlugin.py", line 151, in getimage
    return self.frame(i)
  File "/var/tmp/portage/dev-python/pillow-2.8.1/work/Pillow-2.8.1-python3_3/build/lib/PIL/IcoImagePlugin.py", line 161, in frame
    self.buf.seek(header['offset'])
OverflowError: Python int too large to convert to C ssize_t
```

**Comment by wiredfool** [comment]
Can you check with this patch: https://github.com/python-pillow/Pillow/pull/1232 ?

**Comment by aclark4life** [comment]
Please reopen if still an issue after you test with patch in #1232. Thanks

**Comment by jlec** [comment]
Patch works here.
