### ISSUE TITLE
Pillow 2.9 and cx_Freeze

### ISSUE THREAD

**Issue by Jenyay** [python-pillow/Pillow#1438]
Hello. I used Pillow 2.8.x for some project which build with cx_Freeze. After upgrade Pillow to 2.9 I get error by running of the exe file:

```---------------------------
cx_Freeze: Python error in main script
---------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\cx_freeze-4.3.4-py2.7-win32.egg\cx_Freeze\initscripts\Console.py", line 27, in <module>
    exec(code, m.__dict__)
  File "runoutwiker.py", line 100, in <module>
  File "runoutwiker.py", line 32, in __init__
  File "C:\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 7981, in __init__
    self._BootstrapApp()
  File "C:\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\_core.py", line 7555, in _BootstrapApp
    return _core_.PyApp__BootstrapApp(*args, **kwargs)
  File "runoutwiker.py", line 49, in OnInit
  File "C:\Users\Jenyay\Documents\projects\outwiker\src\outwiker\gui\mainwindow.py", line 15, in <module>
    from .mainwndcontroller import MainWndController
  File "C:\Users\Jenyay\Documents\projects\outwiker\src\outwiker\gui\mainwndcontroller.py", line 17, in <module>
    from outwiker.actions.addsiblingpage import AddSiblingPageAction
  File "C:\Users\Jenyay\Documents\projects\outwiker\src\outwiker\actions\addsiblingpage.py", line 4, in <module>
    from outwiker.gui.pagedialog import createSiblingPage
  File "C:\Users\Jenyay\Documents\projects\outwiker\src\outwiker\gui\pagedialog.py", line 7, in <module>
    from .basepagedialog import BasePageDialog
  File "C:\Users\Jenyay\Documents\projects\outwiker\src\outwiker\gui\basepagedialog.py", line 9, in <module>
    from outwiker.core.factoryselector import FactorySelector
  File "C:\Users\Jenyay\Documents\projects\outwiker\src\outwiker\core\factoryselector.py", line 6, in <module>
    from outwiker.pages.wiki.wikipage import WikiPageFactory
  File "C:\Users\Jenyay\Documents\projects\outwiker\src\outwiker\pages\wiki\wikipage.py", line 7, in <module>
    from wikipageview import WikiPageView
  File "C:\Users\Jenyay\Documents\projects\outwiker\src\outwiker\pages\wiki\wikipageview.py", line 13, in <module>
    from .htmlgenerator import HtmlGenerator
  File "C:\Users\Jenyay\Documents\projects\outwiker\src\outwiker\pages\wiki\htmlgenerator.py", line 13, in <module>
    from .parserfactory import ParserFactory
  File "C:\Users\Jenyay\Documents\projects\outwiker\src\outwiker\pages\wiki\parserfactory.py", line 4, in <module>
    from parser.wikiparser import Parser
  File "C:\Users\Jenyay\Documents\projects\outwiker\src\outwiker\pages\wiki\parser\wikiparser.py", line 8, in <module>
    from tokenthumbnail import ThumbnailFactory
  File "C:\Users\Jenyay\Documents\projects\outwiker\src\outwiker\pages\wiki\parser\tokenthumbnail.py", line 8, in <module>
    from pagethumbmaker import PageThumbmaker
  File "C:\Users\Jenyay\Documents\projects\outwiker\src\outwiker\pages\wiki\parser\pagethumbmaker.py", line 5, in <module>
    from outwiker.core.thumbmakerpil import ThumbmakerPil
  File "C:\Users\Jenyay\Documents\projects\outwiker\src\outwiker\core\thumbmakerpil.py", line 3, in <module>
    from PIL import Image
  File "build\bdist.win32\egg\PIL\Image.py", line 63, in <module>
  File "build\bdist.win32\egg\PIL\_imaging.py", line 7, in <module>
  File "build\bdist.win32\egg\PIL\_imaging.py", line 4, in __bootstrap__
  File "build\bdist.win32\egg\pkg_resources\__init__.py", line 1161, in resource_filename
  File "build\bdist.win32\egg\pkg_resources\__init__.py", line 1854, in get_resource_filename
NotImplementedError: resource_filename() only supported for .egg, not .zip

**Comment by wiredfool** [comment]
Which installer package did you use?  There are windows wheel, egg, and .exe installers for each platform. It looks like installing the .egg might do it for you.

**Comment by Jenyay** [comment]
I used easy_install. I removed egg and installed from .exe and everything is working. Thanks.
