### ISSUE TITLE
OSX Wheel for Py 3.5

### ISSUE THREAD

**Issue by wiredfool** [python-pillow/Pillow#1454]
As noted in the 3.0.0 release thread (#1411), wheels for Python 3.5 aren't building properly. It looks like an issue that was fixed in a version of wheel that we're using. Trace from travis is here: https://travis-ci.org/python-pillow/pillow-wheels/jobs/83200641

Hoisting here to keep it in view.

**Comment by wiredfool** [comment]
@matthew-brett The error we're getting appears similar to this https://bitbucket.org/pypa/wheel/issues/146/wheel-building-fails-on-cpython-350b3 but we're already on wheel 0.26.0.

**Comment by aclark4life** [comment]
How about other OS X wheels for Pillow 3? I'm seeing this:

```

alexclark@Alexs-iMac:~/ > pip install -U pillow
DEPRECATION: --download-cache has been deprecated and will be removed in the future. Pip now automatically uses and configures its cache.
Collecting pillow
  Downloading Pillow-3.0.0-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (2.9MB)
    100% |████████████████████████████████| 2.9MB 195kB/s 
Installing collected packages: pillow
  Found existing installation: Pillow 3.0.0.dev0
    Uninstalling Pillow-3.0.0.dev0:
      Successfully uninstalled Pillow-3.0.0.dev0
Successfully installed pillow
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 9, in <module>
    load_entry_point('pip==7.1.2', 'console_scripts', 'pip')()
  File "/usr/local/lib/python2.7/site-packages/pip/__init__.py", line 217, in main
    return command.main(cmd_args)
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 248, in main
    pip_version_check(session)
  File "/usr/local/lib/python2.7/site-packages/pip/utils/outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "/usr/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 858, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 629, in __init__
    self.add_entry(entry)
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 685, in add_entry
    for dist in find_distributions(entry, True):
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2075, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1605, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1963, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1843, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/usr/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1783, in load
    mtime = os.stat(path).st_mtime
OSError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/site-packages/Pillow-3.0.0.dev0-py2.7-macosx-10.10-x86_64.egg'
```

**Comment by aclark4life** [comment]
Actually, that may be my "bad" environment …

**Comment by wiredfool** [comment]
2.7 is working OMM.

**Comment by aclark4life** [comment]
Yeah, "bad" environment I think; works OAM:

```
alexclark@MH02001809MACLT:~/ > pip install -U pillow
You are using pip version 7.1.0, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
DEPRECATION: --download-cache has been deprecated and will be removed in the future. Pip now automatically uses and configures its cache.
Requirement already up-to-date: pillow in /usr/local/lib/python2.7/site-packages
alexclark@MH02001809MACLT:~/ > pip install -U --force pillow
You are using pip version 7.1.0, however version 7.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
DEPRECATION: --download-cache has been deprecated and will be removed in the future. Pip now automatically uses and configures its cache.
Collecting pillow
  Downloading Pillow-3.0.0-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (2.9MB)
    100% |████████████████████████████████| 2.9MB 29kB/s 
Installing collected packages: pillow
  Found existing installation: Pillow 3.0.0
    Uninstalling Pillow-3.0.0:
      Successfully uninstalled Pillow-3.0.0
Successfully installed pillow-3.0.0
```

**Comment by matthew-brett** [comment]
I think I've fixed the wheel problem here : https://github.com/python-pillow/pillow-wheels/pull/19

The problem (that I ran into before, and took a while to work out) is that the version of wheel you get in the virtualenv does not depend on the version of wheel you install before creating the virtualenv.  The fix is to re-update wheel inside the virtualenv.
