### ISSUE TITLE
FAIL: TestImageFont.test_free_type_font_get_mask

### ISSUE THREAD

**Issue by jlec** [python-pillow/Pillow#1456]
```python
TestImageFont.test_free_type_font_get_mask ... FAIL

======================================================================
FAIL: TestImageFont.test_free_type_font_get_mask
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/pillow-3.0.0/work/Pillow-3.0.0-python2_7/Tests/test_imagefont.py", line 328, in test_free_type_font_get_mask
    self.assertEqual(mask.size, (108, 13))
AssertionError: Tuples differ: (109, 13) != (108, 13)

First differing element 0:
109
108

- (109, 13)
?    ^

+ (108, 13)
?    ^


----------------------------------------------------------------------
Ran 439 tests in 17.010s
```

This is reproducible with
pypy2
python-2.7
python-3.4
pillow-3.0.0

**Comment by wiredfool** [comment]
What platform and freetype version are you using?

**Comment by jlec** [comment]
Linux 64bit
freetype-2.6

**Comment by wiredfool** [comment]
We're testing against freetype 2.6 on osx and windows, and freetype 2.4 on linux.

**Comment by jlec** [comment]
Similar failure:

```ebuild
======================================================================
FAIL: TestImageFont.test_rotated_transposed_font_get_mask
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/pillow-3.0.0/work/Pillow-3.0.0-pypy/Tests/test_imagefont.py", line 273, in test_rotated_transposed_font_get_mask
    self.assertEqual(mask.size, (13, 108))
AssertionError: Tuples differ: (13, 109) != (13, 108)

First differing element 1:
109
108

- (13, 109)
?        ^

+ (13, 108)
?        ^


----------------------------------------------------------------------
```

**Comment by wiredfool** [comment]
Closing, due to infinality+fontconfig changing the font rendering.
