### ISSUE TITLE
struct.error: unpack requires a string argument of length 4

### ISSUE THREAD

**Issue by whitemice** [python-pillow/Pillow#1480]
Reading a PNG and attempting to convert it fails with this error.  Works on thousands of other images, but not on one in particular.  The image opens without even a warning in GNOME's image viewer.

    >>> rfile = open('StoreServiceDispatchVisitSignature.InputMessage.png', 'rb')
    >>> image = Image.open(rfile)
    >>> image.convert('RGBA')
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/srv/projects/coils-code.git/lib/python2.7/site-packages/PIL/Image.py", line 854, in convert
        self.load()
      File "/srv/projects/coils-code.git/lib/python2.7/site-packages/PIL/ImageFile.py", line 213, in load
        s = read(self.decodermaxblock)
      File "/srv/projects/coils-code.git/lib/python2.7/site-packages/PIL/PngImagePlugin.py", line 565, in load_read
        cid, pos, length = self.png.read()
      File "/srv/projects/coils-code.git/lib/python2.7/site-packages/PIL/PngImagePlugin.py", line 115, in read
        length = i32(s)
      File "/srv/projects/coils-code.git/lib/python2.7/site-packages/PIL/_binary.py", line 57, in i32be
        return unpack(">I", c[o:o+4])[0]
    struct.error: unpack requires a string argument of length 4

**Comment by whitemice** [comment]
![storeservicedispatchvisitsignature inputmessage](https://cloud.githubusercontent.com/assets/45972/10377921/fdaa88ce-6dd3-11e5-9ff6-013f44c3d72f.png)

**Comment by whitemice** [comment]
>>> PIL.VERSION
'1.1.7'
>>> PIL.PILLOW_VERSION
'2.9.0'

**Comment by hugovk** [comment]
Ubutntu 12.04 LTS:

```python
$ cat test.py
from PIL import Image, VERSION, PILLOW_VERSION
print("PIL.VERSON=" + VERSION)
print("PIL.PILLOW_VERSON=" + PILLOW_VERSION)
rfile = open('StoreServiceDispatchVisitSignature.InputMessage.png', 'rb')
image = Image.open(rfile)
image.convert('RGBA')
```

Reproducible with Pillow 2.9.0:
```
$ python test.py
PIL.VERSON=1.1.7
PIL.PILLOW_VERSON=2.9.0
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    image.convert('RGBA')
  File "/vagrant/Pillow/PIL/Image.py", line 854, in convert
    self.load()
  File "/vagrant/Pillow/PIL/ImageFile.py", line 213, in load
    s = read(self.decodermaxblock)
  File "/vagrant/Pillow/PIL/PngImagePlugin.py", line 565, in load_read
    cid, pos, length = self.png.read()
  File "/vagrant/Pillow/PIL/PngImagePlugin.py", line 115, in read
    length = i32(s)
  File "/vagrant/Pillow/PIL/_binary.py", line 57, in i32be
    return unpack(">I", c[o:o+4])[0]
struct.error: unpack requires a string argument of length 4
```

Different error with Pillow 3.0.0:
```
$ python test.py
PIL.VERSON=1.1.7
PIL.PILLOW_VERSON=3.0.0
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    image.convert('RGBA')
  File "/vagrant/Pillow/PIL/Image.py", line 833, in convert
    self.load()
  File "/vagrant/Pillow/PIL/ImageFile.py", line 208, in load
    raise IOError("image file is truncated")
IOError: image file is truncated
```

Pillow can be set to load truncated files:
```python
$ cat test.py
from PIL import Image, ImageFile, VERSION, PILLOW_VERSION
print("PIL.VERSON=" + VERSION)
print("PIL.PILLOW_VERSON=" + PILLOW_VERSION)

print("ImageFile.LOAD_TRUNCATED_IMAGES=" + str(ImageFile.LOAD_TRUNCATED_IMAGES))
ImageFile.LOAD_TRUNCATED_IMAGES = True
print("ImageFile.LOAD_TRUNCATED_IMAGES=" + str(ImageFile.LOAD_TRUNCATED_IMAGES))

rfile = open('StoreServiceDispatchVisitSignature.InputMessage.png', 'rb')
image = Image.open(rfile)
image.convert('RGBA')
```

```
$ python test.py
PIL.VERSON=1.1.7
PIL.PILLOW_VERSON=3.0.0
ImageFile.LOAD_TRUNCATED_IMAGES=False
ImageFile.LOAD_TRUNCATED_IMAGES=True
```

2.9.0 still has the same `struct.error`, so upgrade to 3.0.0.

**Comment by radarhere** [comment]
Can this be considered resolved, and so be closed?

**Comment by hugovk** [comment]
Closing. 

@whitemice Please let us know if this is still a problem.
