### ISSUE TITLE
ZeroDivisionError on _getexif()

### ISSUE THREAD

**Issue by jaddison** [python-pillow/Pillow#1497]
OS: Ubuntu 14.04
Interpreter: Python 2.7.6
Previously used Pillow version: 2.9.0
New Pillow version: 3.0.0

I found this while using sorl-thumbnail with Django. I narrowed it down to the specific Pillow-specific calls (ie. reproduced without sorl-thumbnail) - please see below.  Reverting to Pillow 2.9.0, everything seems to work.

Code:
```
from PIL import Image
im = Image.open('broken_image.JPG')
im._getexif()
```

Traceback:
```
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/vagrant/.virtualenvs/localdev/local/lib/python2.7/site-packages/PIL/JpegImagePlugin.py", line 391, in _getexif
    return _getexif(self)
  File "/home/vagrant/.virtualenvs/localdev/local/lib/python2.7/site-packages/PIL/JpegImagePlugin.py", line 425, in _getexif
    exif.update(info)
  File "/home/vagrant/.virtualenvs/localdev/local/lib/python2.7/site-packages/PIL/TiffImagePlugin.py", line 354, in __getitem__
    self[tag] = handler(self, data, self.legacy_api)  # check type
  File "/home/vagrant/.virtualenvs/localdev/local/lib/python2.7/site-packages/PIL/TiffImagePlugin.py", line 484, in load_rational
    for num, denom in zip(vals[::2], vals[1::2]))
  File "/home/vagrant/.virtualenvs/localdev/local/lib/python2.7/site-packages/PIL/TiffImagePlugin.py", line 484, in <genexpr>
    for num, denom in zip(vals[::2], vals[1::2]))
  File "/home/vagrant/.virtualenvs/localdev/local/lib/python2.7/site-packages/PIL/TiffImagePlugin.py", line 482, in <lambda>
    combine = lambda a, b: (a, b) if legacy_api else a / b
ZeroDivisionError: division by zero
```

Sample broken image is attached to this issue.

![broken_image](https://cloud.githubusercontent.com/assets/101148/10526516/3f418adc-7340-11e5-8295-efbcbe46f8e4.JPG)

Edit: based on #1477, looks like there's other EXIF-related issues.

**Comment by jaddison** [comment]
I'm guessing this is related to the discussion in pull request https://github.com/python-pillow/Pillow/pull/1492

**Comment by wiredfool** [comment]
Thanks for the report.  I'm gong to close this as a dup.
