### ISSUE TITLE
Image.open prints traceback on stderr even if in try: ... except:.. block

### ISSUE THREAD

**Issue by MaxNoe** [python-pillow/Pillow#1532]
Consider this minimal example.py:
```
from PIL import Image

try:
    Image.open('foo.png')
except:
    print('Skipping unreadable image foo.png')
```
If I run:
```
$ touch foo.png
$ python example.py
```
I get a large traceback even though the exception was correctly catched:

```%s
Traceback (most recent call last):
  File "/home/maxnoe/.local/anaconda3/envs/pillow/lib/python3.5/site-packages/PIL/ImageFile.py", line 100, in __init__
    self._open()
  File "/home/maxnoe/.local/anaconda3/envs/pillow/lib/python3.5/site-packages/PIL/IptcImagePlugin.py", line 113, in _open
    layers = i8(self.info[(3, 60)][0])
KeyError: (3, 60)
%s
Traceback (most recent call last):
  File "/home/maxnoe/.local/anaconda3/envs/pillow/lib/python3.5/site-packages/PIL/ImageFile.py", line 100, in __init__
    self._open()
  File "/home/maxnoe/.local/anaconda3/envs/pillow/lib/python3.5/site-packages/PIL/MpegImagePlugin.py", line 71, in _open
    if s.read(32) != 0x1B3:
  File "/home/maxnoe/.local/anaconda3/envs/pillow/lib/python3.5/site-packages/PIL/MpegImagePlugin.py", line 53, in read
    v = self.peek(bits)
  File "/home/maxnoe/.local/anaconda3/envs/pillow/lib/python3.5/site-packages/PIL/MpegImagePlugin.py", line 38, in peek
    c = self.next()
  File "/home/maxnoe/.local/anaconda3/envs/pillow/lib/python3.5/site-packages/PIL/MpegImagePlugin.py", line 34, in next
    return i8(self.fp.read(1))
  File "/home/maxnoe/.local/anaconda3/envs/pillow/lib/python3.5/site-packages/PIL/_binary.py", line 24, in i8
    return c if c.__class__ is int else c[0]
IndexError: index out of range
%s
Traceback (most recent call last):
  File "/home/maxnoe/.local/anaconda3/envs/pillow/lib/python3.5/site-packages/PIL/ImageFile.py", line 100, in __init__
    self._open()
  File "/home/maxnoe/.local/anaconda3/envs/pillow/lib/python3.5/site-packages/PIL/TgaImagePlugin.py", line 57, in _open
    idlen = i8(s[0])
IndexError: index out of range
Skipping unreadable image foo.png
```

I'm using anaconda 2.4 with pillow 3.0.0.

See also https://github.com/scikit-image/scikit-image/issues/1772

**Comment by MaxNoe** [comment]
I can reproduce this also with the current `master`.

**Comment by wiredfool** [comment]
Do you have some logging enabled that dumps to stdout or stderr?  I'm not seeing your results. 

```
$ touch foo.png
$ python
Python 2.7.10 (default, Jul 13 2015, 12:18:59) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
>>> try:
...     Image.open('foo.png')
... except:
...     pass
... 
No handlers could be found for logger "PIL.ImageFile"
```

**Comment by MaxNoe** [comment]
Not that I know of.

Seems to be an anaconda thing. If I use my system python3 I get no error.

**Comment by MaxNoe** [comment]
@wiredfool Could you check with python 3?

**Comment by blink1073** [comment]
Note, I did not see the error with Python 3.4, but did with Python 3.5.

**Comment by MaxNoe** [comment]
I see it also with `python 3.4.3`

**Comment by wiredfool** [comment]
Should be fixed on master

**Comment by faulander** [comment]
i am still running into this issue! :/

**Comment by faulander** [comment]
It's working as expected on my windows machine in the office:
```
Platform: win32
Python: sys.version_info(major=3, minor=7, micro=2, releaselevel='final', serial=0)
Pillow: 5.4.1
Skipping unreadable image
```
I will try in the evening on my Archlinux Box at home.

**Comment by hugovk** [comment]
I get this with an Ubuntu 16.04.3 LTS VM:
```console
$ touch foo.jpg
$ python2 example.py
('Platform:', 'linux2')
('Python:', sys.version_info(major=2, minor=7, micro=12, releaselevel='final', serial=0))
('Pillow:', '5.4.1')
Skipping unreadable image
$ python3 example.py
Platform: linux
Python: sys.version_info(major=3, minor=5, micro=2, releaselevel='final', serial=0)
Pillow: 5.4.1
Skipping unreadable image
```

**Comment by faulander** [comment]
funny fact:
```
(venv) [faulander@lenovo md]$ python PillowTest.py
Platform: linux
Python: sys.version_info(major=3, minor=7, micro=1, releaselevel='final', serial=0)
Pillow: 5.3.0
Skipping unreadable image

```
It's the same Virtual Environment as my other code. I post it once again:
`from PIL import Image as PilImage
`
and the function:
```
def resizeImage(pfad, maxsize=3500):
    this_function_name = sys._getframe().f_code.co_name
    try:
        bild = PilImage.open(pfad)
        width, height = bild.size
        newwidth = width
        newheight = height

        if width >= height and width >= maxsize:
            newwidth = maxsize
            newheight = int(height*(newwidth/width))
        if height >= width and height >= maxsize:
            newheight = maxsize
            newwidth = int(width*(newheight/height))
        newsize = newwidth, newheight

        try:
            bild.thumbnail(newsize, PilImage.ANTIALIAS)
            outfile = os.path.splitext(pfad)[0] + ".jpg"
            tmpLoggerMessage = this_function_name + ": " + outfile + ": " + str(width) + "x" + str(height) + "-->" + str(newwidth) + "x" + str(newheight)
            logger.info(tmpLoggerMessage)
            bild.save(outfile, "JPEG")                                                          #Bild speichern
        except:
            tmpLoggerMessage = this_function_name + ": Error on file: " + outfile
            logger.error(tmpLoggerMessage)
    except:
        tmpLoggerMessage = this_function_name + ": Error on file: " + outfile
        logger.error(tmpLoggerMessage)

```
