### ISSUE TITLE
Crash on save if file has more than one period in name

### ISSUE THREAD

**Issue by mpyatishev** [python-pillow/Pillow#1675]
If file, for example, named as 'some_image.some.jpg' then when do Image.save we got Exception:
```
  File "/home/max/work/env/lib/python3.4/site-packages/PIL/Image.py", line 1662, in save
    format = EXTENSION[ext]
KeyError: '.some'
```
This is result of os.path.splitext which drops last periods (line 1657):
```
ext = os.path.splitext(filename)[1].lower()
```
I think that better would something like:
```
ext = '.' + filename.split('.')[-1].lower()
```

**Comment by radarhere** [comment]
I can't replicate the error on OS X.

Also, when I run `os.path.splitext('a.b.c')` I get `('a.b', '.c')`. If you get something different, I can only imagine that it's a different implementation of `splitext` because of your platform. What operating system are you running?

**Comment by hugovk** [comment]
I can't replicate on Windows 7 / Python 2.7 / Pillow 3.1.0:

```python
>>> from PIL import Image
>>> im = Image.open("input.jpg")
>>> im.save("some_image.some.jpg")
>>>
```

**Comment by mpyatishev** [comment]
Strange thing. If I use python REPL then all clear:
```
Python 3.4.4rc1 (default, Dec  7 2015, 11:09:54) 
[GCC 5.3.1 20151205] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os.path
>>> os.path.splittext('some_thing.some.jpg')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'splittext'
>>> os.path.splitext('some_thing.some.jpg')                                                                                                                                                                         
('some_thing.some', '.jpg')
```
I wil try find a way to reproduce my problem.

**Comment by mpyatishev** [comment]
Sorry, it is my falt.
