### ISSUE TITLE
Errors shown when `sudo pip install pillow` on Ubuntu 14.04 and OSX 

### ISSUE THREAD

**Issue by KellyChan** [python-pillow/Pillow#1689]
Installation

    sudo pip install pillow

Error Message

```
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/pip_build_root/pillow/setup.py", line 767, in <module>

    zip_safe=not debug_build(),

  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup

    dist.run_commands()

  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands

    self.run_command(cmd)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 53, in run

    return _install.run(self)

  File "/usr/lib/python2.7/distutils/command/install.py", line 601, in run

    self.run_command('build')

  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/usr/lib/python2.7/distutils/command/build.py", line 128, in run

    self.run_command(cmd_name)

  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command

    self.distribution.run_command(command)

  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command

    cmd_obj.run()

  File "/usr/lib/python2.7/distutils/command/build_ext.py", line 337, in run

    self.build_extensions()

  File "/tmp/pip_build_root/pillow/setup.py", line 516, in build_extensions

    (f, f))

ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting
```

**Comment by hugovk** [comment]
You're missing the JPEG library, which is now required unless you explicitly disable it using build flags.

You're probably best off including the lib, see here for how to install prerequisites:

https://pillow.readthedocs.org/en/3.1.x/installation.html#building-on-linux

**Comment by KellyChan** [comment]
@hugovk Thanks for your reply, after installing the dependencies, it worked.

```
sudo apt-get install libtiff5-dev libjpeg8-dev zlib1g-dev \
libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python-tk
```

The scenario was I installed python-reportlab which was required pillow, then it was shown this error. For the development purpose, it should be handled such case by reportlab, or by pillow? Thanks.

**Comment by hugovk** [comment]
:+1:
