### ISSUE TITLE
TIFF dependent tests are run without libtiff available

### ISSUE THREAD

**Issue by sofar** [python-pillow/Pillow#1866]
Running the test case ```TestFileTiff.test_page_number_x_0``` will fail if tiff support is not available. This test should be skipped in the same way that e.g. netpbm is skipped. 

```
======================================================================
ERROR: TestFileTiff.test_page_number_x_0
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/builddir/build/BUILD/Pillow-3.0.0/Tests/test_file_tiff.py", line 328, in test_page_number_x_0
    im.save(outfile)
  File "/builddir/build/BUILD/Pillow-3.0.0/PIL/Image.py", line 1633, in save
    self.load()
  File "/builddir/build/BUILD/Pillow-3.0.0/PIL/TiffImagePlugin.py", line 890, in _load_libtiff
    self.decoderconfig)
  File "/builddir/build/BUILD/Pillow-3.0.0/PIL/Image.py", line 415, in _getdecoder
    raise IOError("decoder %s not available" % decoder_name)
IOError: decoder libtiff not available
----------------------------------------------------------------------
Ran 669 tests in 13.285s
FAILED (errors=1, skipped=136)
--------------------------------------------------------------------
PIL SETUP SUMMARY
--------------------------------------------------------------------
version      Pillow 3.0.0
platform     linux2 2.7.11 (default, Feb 16 2016, 12:46:10)
             [GCC 5.3.0]
--------------------------------------------------------------------
*** TKINTER support not available
--- JPEG support available
*** OPENJPEG (JPEG2000) support not available
--- ZLIB (PNG/ZIP) support available
*** LIBTIFF support not available
--- FREETYPE2 support available
*** LITTLECMS2 support not available
*** WEBP support not available
*** WEBPMUX support not available
--------------------------------------------------------------------
```

**Comment by sofar** [comment]
```test_ifd_rational_save``` also needs to be disabled. I did not find additional tests that would fail due to libtiff support not being available.

**Comment by hugovk** [comment]
@sofar Thanks, please could you send a PR?

Here's a couple of examples of skipping tests when tiff support is not available.

https://github.com/python-pillow/Pillow/blob/9fa3fb98f3d7786adcefa11c3763446056c7256b/Tests/test_file_libtiff.py#L18-L21
https://github.com/python-pillow/Pillow/blob/d3727b523ece4f75def72bfc960e1abd104b5dcb/Tests/test_imagesequence.py#L46-L49

Perhaps this duplicate code could also be put in a function imported from Pillow/Tests/helper.py.
