### ISSUE TITLE
Use bitmap fonts for Chinese characters

### ISSUE THREAD

**Issue by felix-hubo** [python-pillow/Pillow#1949]
Hello,

I'm trying to show the Chinese text.
I prefer to use the bitmap font because the character size is very small and the truetype fonts doesn't work good under such situation.

Here is my code:
```python
#! /usr/bin/python
# -*- coding: utf-8 -*-
from PIL import Image
from PIL import ImageDraw
from PIL import ImageFont

ttfont = ImageFont.load ('wenquanyi_13px.pil')
text = u'我能有乾酪？'
image = Image.new ('1', (256, 64));
ImageDraw.Draw (image).text ( (0, 0), text, font = ttfont, fill = 1 )
image.save ('chinese.bmp','bmp')
```

But there was an error related with the encoding:
```python
Traceback (most recent call last):
  File "temp.py", line 11, in <module>
    ImageDraw.Draw (image).text ( (0, 0), text, font = ttfont, fill = 1 )
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageDraw.py", line 259, in text
    mask = font.getmask(text, self.fontmode)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 0-5: ordinal not in range(256)
```

What caused this? Can anyone help me?

**Comment by wiredfool** [comment]
That is the format of the font?  From the name it looks like te pilfont format, which has no support for unicode.

**Comment by felix-hubo** [comment]
You are right wiedfool, I made a mistake here.
After correct the codes a little. Now it works as expected.
The new codes like:
```python
#! /usr/bin/python
# -*- coding: utf-8 -*-

from PIL import Image
from PIL import ImageDraw
from PIL import ImageFont

ttfont = ImageFont.truetype ('wenquanyi_13px.bdf', 14)
text = u'我能有乾酪？'
print text
image = Image.new ('1', (256, 64))
ImageDraw.Draw (image).text ( (0, 15), text, font = ttfont, fill = 1 )
image.save ('chinese.bmp','bmp')
```
One thing to notice is the size of the font needs to be set exactly the same as in the BDF file. Otherwise there'll be an exception.
