### ISSUE TITLE
Images with corrupt EXIF data aren't always handled gracefully

### ISSUE THREAD

**Issue by mgalgs** [python-pillow/Pillow#1950]
### What did you do?

Tried to load an image with corrupt EXIF data.

### What did you expect to happen?

Expected it to load, ignoring any bogus or missing EXIF tags.

### What actually happened?

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/Users/mitchhumpherys/Sites/str-prod/env/lib/python2.7/site-packages/PIL/JpegImagePlugin.py", line 391, in _getexif
        return _getexif(self)
      File "/Users/mitchhumpherys/Sites/str-prod/env/lib/python2.7/site-packages/PIL/JpegImagePlugin.py", line 426, in _getexif
        exif = dict(_fixup_dict(info))
      File "/Users/mitchhumpherys/Sites/str-prod/env/lib/python2.7/site-packages/PIL/JpegImagePlugin.py", line 407, in _fixup_dict
        return dict([(k, _fixup(v)) for k, v in src_dict.items()])
      File "/Users/mitchhumpherys/Sites/str-prod/env/bin/../lib/python2.7/_abcoll.py", line 414, in items
        return [(key, self[key]) for key in self]
      File "/Users/mitchhumpherys/Sites/str-prod/env/lib/python2.7/site-packages/PIL/TiffImagePlugin.py", line 854, in __getitem__
        self._setitem(tag, handler(self, data, legacy), legacy)
      File "/Users/mitchhumpherys/Sites/str-prod/env/lib/python2.7/site-packages/PIL/TiffImagePlugin.py", line 534, in _setitem
        dest[tag], = values
    ValueError: need more than 0 values to unpack

### What versions of Pillow and Python are you using?

Python 2.7.10, Pillow master as of tonight.

Please include code that reproduces the issue and whenever possible, an image that demonstrates the issue. The best reproductions are self-contained scripts with minimal dependencies.

```python
from PIL import Image

Image.open('fail1.jpg')._getexif()
```

![fail1](https://cloud.githubusercontent.com/assets/152014/16032081/53024ae4-31b7-11e6-9f58-d2a33fe145f1.jpg)

**Comment by radarhere** [comment]
Hi. This looks like a duplicate of #1722. Are you happy for it to be closed accordingly?

**Comment by mgalgs** [comment]
Ah yes, looks like a dupe.

**Comment by scythargon** [comment]
still happens with this image for example
http://asburyplace.org/wp-content/uploads/2017/01/AL-Slide-diversity.jpg
