### ISSUE TITLE
Cannot find Tcl during installation

### ISSUE THREAD

**Issue by adamjstewart** [python-pillow/Pillow#1972]
I'm trying to build Pillow 3.2.0 with Python 2.7.11, Tcl 8.6.5, and Tk 8.6.3 from source code. However, I can't get the setup script to find Tcl. Here are the steps that I've tried so far:

#### Editing setup.py

```python
TCL_ROOT = ('/home/ajstewart/spack/opt/spack/linux-fedora23-x86_64/gcc-5.3.1/tcl-8.6.5-qrczoaetyvgjel52wxzxo6jhwiqrd32n/lib', '/home/ajstewart/spack/opt/spack/linux-fedora23-x86_64/gcc-5.3.1/tcl-8.6.5-qrczoaetyvgjel52wxzxo6jhwiqrd32n/include')
```

#### Command line flags

```
python setup.py build_ext --enable-tcl --enable-tk -L/home/ajstewart/spack/opt/spack/linux-fedora23-x86_64/gcc-5.3.1/tcl-8.6.5-qrczoaetyvgjel52wxzxo6jhwiqrd32n/lib:/home/ajstewart/spack/opt/spack/linux-fedora23-x86_64/gcc-5.3.1/tk-8.6.3-h4dawehk5jnupjom5nyxkv3zm6j3dt5i/lib -I/home/ajstewart/spack/opt/spack/linux-fedora23-x86_64/gcc-5.3.1/tcl-8.6.5-qrczoaetyvgjel52wxzxo6jhwiqrd32n/include:/home/ajstewart/spack/opt/spack/linux-fedora23-x86_64/gcc-5.3.1/tk-8.6.3-h4dawehk5jnupjom5nyxkv3zm6j3dt5i/include
python setup.py build_ext --enable-tcl --enable-tk -L/home/ajstewart/spack/opt/spack/linux-fedora23-x86_64/gcc-5.3.1/tcl-8.6.5-qrczoaetyvgjel52wxzxo6jhwiqrd32n/lib:/home/ajstewart/spack/opt/spack/linux-fedora23-x86_64/gcc-5.3.1/tk-8.6.3-h4dawehk5jnupjom5nyxkv3zm6j3dt5i/lib -I/home/ajstewart/spack/opt/spack/linux-fedora23-x86_64/gcc-5.3.1/tcl-8.6.5-qrczoaetyvgjel52wxzxo6jhwiqrd32n/include:/home/ajstewart/spack/opt/spack/linux-fedora23-x86_64/gcc-5.3.1/tk-8.6.3-h4dawehk5jnupjom5nyxkv3zm6j3dt5i/include -ltcl8.6
```

Every time it crashes with the following error message:
```
running build_ext
Traceback (most recent call last):
  File "setup.py", line 767, in <module>
    zip_safe=not debug_build(),
  File "/home/ajstewart/spack/opt/spack/linux-fedora23-x86_64/gcc-5.3.1/python-2.7.11-axrs7vzfbq2ws6dyxusq7ra4lzucf62v/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/ajstewart/spack/opt/spack/linux-fedora23-x86_64/gcc-5.3.1/python-2.7.11-axrs7vzfbq2ws6dyxusq7ra4lzucf62v/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/ajstewart/spack/opt/spack/linux-fedora23-x86_64/gcc-5.3.1/python-2.7.11-axrs7vzfbq2ws6dyxusq7ra4lzucf62v/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/home/ajstewart/spack/opt/spack/linux-fedora23-x86_64/gcc-5.3.1/python-2.7.11-axrs7vzfbq2ws6dyxusq7ra4lzucf62v/lib/python2.7/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "setup.py", line 515, in build_extensions
    % (f, f))
ValueError: --enable-tcl requested but tcl not found, aborting.
```
Any idea what I'm doing wrong here? The contents of these directories are as follows:
```bash
$ ls /home/ajstewart/spack/opt/spack/linux-fedora23-x86_64/gcc-5.3.1/tcl-8.6.5-qrczoaetyvgjel52wxzxo6jhwiqrd32n/lib
itcl4.0.4     libtclstub8.6.a  sqlite3.11.0  tcl8.6        tclooConfig.sh  tdbcmysql1.0.4  tdbcpostgres1.0.4
libtcl8.6.so  pkgconfig        tcl8          tclConfig.sh  tdbc1.0.4       tdbcodbc1.0.4   thread2.7.3
$ ls /home/ajstewart/spack/opt/spack/linux-fedora23-x86_64/gcc-5.3.1/tcl-8.6.5-qrczoaetyvgjel52wxzxo6jhwiqrd32n/include
fakemysql.h  itcl2TclOO.h  itclIntDecls.h         itclTclIntStubsFcn.h  pqStubs.h   tclOODecls.h    tclThread.h        tdbcDecls.h
fakepq.h     itclDecls.h   itclInt.h              mysqlStubs.h          tclDecls.h  tclOO.h         tclTomMathDecls.h  tdbc.h
fakesql.h    itcl.h        itclMigrate2TclCore.h  odbcStubs.h           tcl.h       tclPlatDecls.h  tclTomMath.h       tdbcInt.h
$ ls /home/ajstewart/spack/opt/spack/linux-fedora23-x86_64/gcc-5.3.1/tk-8.6.3-h4dawehk5jnupjom5nyxkv3zm6j3dt5i/lib
libtk8.6.so  libtkstub8.6.a  pkgconfig	tk8.6  tkConfig.sh
$ ls /home/ajstewart/spack/opt/spack/linux-fedora23-x86_64/gcc-5.3.1/tk-8.6.3-h4dawehk5jnupjom5nyxkv3zm6j3dt5i/include/
tkDecls.h  tk.h  tkPlatDecls.h
```

**Comment by wiredfool** [comment]
I don't think it's going to pick up the -L flags from the command line, I think it only looks in environment variables for those. 

You may want to check current master, it's got a patch to link Tcl/Tk at runtime from the version of tkinter that's compiled with python. Barring that, there's also a debug flag in the current master that list where pillow is looking for libraries and headers at setup time.

**Comment by wiredfool** [comment]
There's also an option in the current master providing `--disable-platform-guessing` that is designed for package managers with specific dependencies. 

http://pillow.readthedocs.io/en/latest/installation.html#build-options

**Comment by adamjstewart** [comment]
> I don't think it's going to pick up the -L flags from the command line, I think it only looks in environment variables for those.

It picked up zlib and libtiff from the -L flags (they aren't installed in a normal location). The setup help also lists it as a valid way to pass directories:
```
$ python setup.py --help build_ext
...
  --include-dirs (-I)          list of directories to search for header files
                               (separated by ':')
...
  --library-dirs (-L)          directories to search for external C libraries
                               (separated by ':')
...
  --libraries (-l)             external C libraries to link with
```

I'll try the current master branch and see if I have any luck.

**Comment by adamjstewart** [comment]
Hmm, the current master no longer has `--enable-tk` or `--enable-tcl`. I was able to build just fine but I'm not sure how to tell whether or not Pillow linked to Tk/Tcl. I'm also not sure if the Python package I installed is properly linked to Tk/Tcl either.

**Comment by wiredfool** [comment]
There is a change in the master branch that uses whatever python tkinter is available at runtime, so it's a little different than the compile time one. It should eliminate a whole class of this sort of issue. 

The best way to tell if it's working is to install to a virtualenv and run the tests, for tk it would be: `./test-installed.py -v Tests/test_imagetk.py` .
