### ISSUE TITLE
Image.fromarray does not accept array with dtype=bool

### ISSUE THREAD

**Issue by moi90** [python-pillow/Pillow#2044]
### What did you do?

```
>>> im = Image.new("1", (10,10))
>>> a = np.asarray(im)
>>> a.dtype
dtype('bool')
>>> im2 = Image.fromarray(a)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/moi/Dokumente/Studium/Thesis/Python/local/lib/python2.7/site-packages/PIL/Image.py", line 2167, in fromarray
    raise TypeError("Cannot handle this data type")
TypeError: Cannot handle this data type
```
### What did you expect to happen?

I expect the same image to be convertable back and forth without error.
### What versions of Pillow and Python are you using?

```
python2.7 2.7.6 (default, Jun 22 2015, 17:58:13) 
[GCC 4.8.2]
PIL.VERSION
'1.1.7'
```

**Comment by wiredfool** [comment]
That's a known issue. See #350

**Comment by moi90** [comment]
Thanks for the hint.

**Comment by wlnirvana** [comment]
@wiredfool Any update on this? #350 is already closed and seems to handle 1-bit image to numpy array conversion, but not the other way around. The exception can still be reproduced following the steps given by the OP.

**Comment by wlnirvana** [comment]
Note that it is even more weird that the `mode='1'` works but produces erroneous result when being read back into numpy

```python
In [62]: im = Image.new("1", (10,10))

In [63]: a = np.array(im)

In [64]: a[0][0]=True

In [65]: b = np.array(Image.fromarray(a, mode='1'), dtype=np.bool)

In [66]: b
Out[66]:
array([[False, False, False, False, False, False, False,  True, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]], dtype=bool)

In [67]: b[0][7]
Out[67]: True
```

**Comment by wiredfool** [comment]
So the minimal replication is:
```
a = np.zeros((2,10), dtype=np.bool)
>>> a[0][0] = True 
>>> a
array([[ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]], dtype=bool)
>>> im2 = Image.fromarray(a, '1')
>>> list(im2.getdata())[:10]
[0, 0, 0, 0, 0, 0, 0, 255, 0, 0]
```

We don't actually advertise that we support the '|b1' typestr in the array interface for a, and there's no way to pass in some form of mode/rawmode combo. So when you pass in the '1' mode, it's expecting a bit packed buffer, which is not what's actually coming through.
