### ISSUE TITLE
Compilation on FreeBSD (with pip) fails

### ISSUE THREAD

**Issue by connor557** [python-pillow/Pillow#2066]
### What did you do?
Attempt to compile and/or install pillow on FreeBSD using pip. (pip install --user pillow) Originally trying to compile as dependency of Ajenti web panel. (pip install --user ajenti)

### What did you expect to happen?
I expected Ajenti and/or pillow to compile and install with no errors through pypi.

### What actually happened?
Pypi failed with a jpeg error on pillow independently AND as a dependancy.

### What versions of Pillow and Python are you using?
Python 2.7.12
Pillow 3.3.0
Pip/Pypi 8.1.2

Please include code that reproduces the issue and whenever possible, an image that demonstrates the issue. The best reproductions are self-contained scripts with minimal dependencies.

```
# pip install --user pillow
Collecting pillow
  Using cached Pillow-3.3.0.zip
Installing collected packages: pillow
  Running setup.py install for pillow ... error
    Complete output from command /usr/local/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-R_svIJ/pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-FdvkPd-record/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    Single threaded build, not installing mp_compile:1 processes
    running install
    running build
    running build_py
    creating build
    creating build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7
    creating build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/ImageGrab.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/TiffImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/MicImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/FitsStubImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/ExifTags.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/ImageChops.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/CurImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/ImageEnhance.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/WebPImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/PngImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/DcxImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/TgaImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/PsdImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/JpegPresets.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/GimpPaletteFile.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/GbrImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/OleFileIO.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/PSDraw.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/_binary.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/ImageSequence.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/DdsImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/McIdasImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/IptcImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/ImageTransform.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/PdfImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/JpegImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/FontFile.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/Hdf5StubImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/PcxImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/WalImageFile.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/ImageQt.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/ImageFile.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/IcnsImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/BufrStubImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/EpsImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/TiffTags.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/BmpImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/MpoImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/GimpGradientFile.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/SgiImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/ImageCms.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/ImageDraw2.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/ImageStat.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/_tkinter_finder.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/SpiderImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/ImageWin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/Jpeg2KImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/__init__.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/ImagePalette.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/FtexImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/Image.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/SunImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/ImageFont.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/ImageTk.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/TarIO.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/ImageShow.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/PpmImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/XpmImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/ImageColor.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/PyAccess.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/GifImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/ImagePath.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/ImageFilter.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/ImageMode.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/features.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/GdImageFile.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/ContainerIO.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/MspImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/PalmImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/ImageMath.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/FliImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/MpegImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/PcfFontFile.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/XbmImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/ImageOps.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/ImageDraw.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/PixarImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/BdfFontFile.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/FpxImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/ImImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/IcoImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/ImtImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/PcdImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/PaletteFile.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/_util.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/ImageMorph.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/XVThumbImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/WmfImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    copying PIL/GribStubImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    running egg_info
    writing Pillow.egg-info/PKG-INFO
    writing top-level names to Pillow.egg-info/top_level.txt
    writing dependency_links to Pillow.egg-info/dependency_links.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'Pillow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.sh'
    no previously-included directories found matching 'docs/_static'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.landscape.yaml'
    warning: no previously-included files found matching 'appveyor.yml'
    warning: no previously-included files found matching 'build_children.sh'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    writing manifest file 'Pillow.egg-info/SOURCES.txt'
    copying PIL/OleFileIO-README.md -> build/lib.freebsd-10.3-RELEASE-p4-amd64-2.7/PIL
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-R_svIJ/pillow/setup.py", line 753, in <module>
        zip_safe=not debug_build(), )
      File "/usr/local/lib/python2.7/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/usr/local/lib/python2.7/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python2.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/lib/python2.7/distutils/command/install.py", line 563, in run
        self.run_command('build')
      File "/usr/local/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python2.7/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/usr/local/lib/python2.7/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python2.7/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python2.7/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/tmp/pip-build-R_svIJ/pillow/setup.py", line 521, in build_extensions
        ' using --disable-%s, aborting' % (f, f))
    ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting

    ----------------------------------------
Command "/usr/local/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-R_svIJ/pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-FdvkPd-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-R_svIJ/pillow

```

**Comment by connor557** [comment]
I don't know diddly squat about python (especially pillow) and really just want to install ajenti on my server, so if you can make the fix simple I would appreciate it greatly.

**Comment by wiredfool** [comment]
The installation docs for freebsd are here: http://pillow.readthedocs.io/en/3.3.x/installation.html#freebsd-installation

**Comment by connor557** [comment]
Thank y'all so much. I gave up on this, and moved to debian.

**Comment by wiredfool** [comment]
Did you try installing either the dependencies or the port?
