### ISSUE TITLE
Cannot install using pip (pypy)

### ISSUE THREAD

**Issue by hishamwaleed** [python-pillow/Pillow#2163]
### What did you do?

trying to install pillow
### What did you expect to happen?

Collecting Pillow
Installing collected packages: Pillow
Successfully installed Pillow-3.4.1
### What actually happened?

```
(PYPY_B~1) D:\Graduation Project\pypy_blog\src>pip install pillow
Collecting pillow
  Downloading Pillow-3.4.1.zip (11.0MB)
    100% |################################| 11.0MB 61kB/s
Building wheels for collected packages: pillow
  Running setup.py bdist_wheel for pillow ... error
  Complete output from command d:\gradua~1\pypy_b~1\bin\pypy.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\hisha\\appdata\\local\\temp\\pip-build-ootvc5\\pillow\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d c:\users\hisha\appdata\local\temp\tmp09kyzfpip-wheel- --python-tag pp254:
  Single threaded build for windows
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win32-2.7
  creating build\lib.win32-2.7\PIL
  copying PIL\BdfFontFile.py -> build\lib.win32-2.7\PIL
  copying PIL\BmpImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\BufrStubImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\ContainerIO.py -> build\lib.win32-2.7\PIL
  copying PIL\CurImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\DcxImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\DdsImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\EpsImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\ExifTags.py -> build\lib.win32-2.7\PIL
  copying PIL\features.py -> build\lib.win32-2.7\PIL
  copying PIL\FitsStubImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\FliImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\FontFile.py -> build\lib.win32-2.7\PIL
  copying PIL\FpxImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\FtexImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\GbrImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\GdImageFile.py -> build\lib.win32-2.7\PIL
  copying PIL\GifImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\GimpGradientFile.py -> build\lib.win32-2.7\PIL
  copying PIL\GimpPaletteFile.py -> build\lib.win32-2.7\PIL
  copying PIL\GribStubImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\Hdf5StubImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\IcnsImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\IcoImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\Image.py -> build\lib.win32-2.7\PIL
  copying PIL\ImageChops.py -> build\lib.win32-2.7\PIL
  copying PIL\ImageCms.py -> build\lib.win32-2.7\PIL
  copying PIL\ImageColor.py -> build\lib.win32-2.7\PIL
  copying PIL\ImageDraw.py -> build\lib.win32-2.7\PIL
  copying PIL\ImageDraw2.py -> build\lib.win32-2.7\PIL
  copying PIL\ImageEnhance.py -> build\lib.win32-2.7\PIL
  copying PIL\ImageFile.py -> build\lib.win32-2.7\PIL
  copying PIL\ImageFilter.py -> build\lib.win32-2.7\PIL
  copying PIL\ImageFont.py -> build\lib.win32-2.7\PIL
  copying PIL\ImageGrab.py -> build\lib.win32-2.7\PIL
  copying PIL\ImageMath.py -> build\lib.win32-2.7\PIL
  copying PIL\ImageMode.py -> build\lib.win32-2.7\PIL
  copying PIL\ImageMorph.py -> build\lib.win32-2.7\PIL
  copying PIL\ImageOps.py -> build\lib.win32-2.7\PIL
  copying PIL\ImagePalette.py -> build\lib.win32-2.7\PIL
  copying PIL\ImagePath.py -> build\lib.win32-2.7\PIL
  copying PIL\ImageQt.py -> build\lib.win32-2.7\PIL
  copying PIL\ImageSequence.py -> build\lib.win32-2.7\PIL
  copying PIL\ImageShow.py -> build\lib.win32-2.7\PIL
  copying PIL\ImageStat.py -> build\lib.win32-2.7\PIL
  copying PIL\ImageTk.py -> build\lib.win32-2.7\PIL
  copying PIL\ImageTransform.py -> build\lib.win32-2.7\PIL
  copying PIL\ImageWin.py -> build\lib.win32-2.7\PIL
  copying PIL\ImImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\ImtImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\IptcImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\Jpeg2KImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\JpegImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\JpegPresets.py -> build\lib.win32-2.7\PIL
  copying PIL\McIdasImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\MicImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\MpegImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\MpoImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\MspImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\OleFileIO.py -> build\lib.win32-2.7\PIL
  copying PIL\PaletteFile.py -> build\lib.win32-2.7\PIL
  copying PIL\PalmImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\PcdImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\PcfFontFile.py -> build\lib.win32-2.7\PIL
  copying PIL\PcxImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\PdfImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\PixarImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\PngImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\PpmImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\PsdImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\PSDraw.py -> build\lib.win32-2.7\PIL
  copying PIL\PyAccess.py -> build\lib.win32-2.7\PIL
  copying PIL\SgiImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\SpiderImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\SunImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\TarIO.py -> build\lib.win32-2.7\PIL
  copying PIL\TgaImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\TiffImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\TiffTags.py -> build\lib.win32-2.7\PIL
  copying PIL\WalImageFile.py -> build\lib.win32-2.7\PIL
  copying PIL\WebPImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\WmfImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\XbmImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\XpmImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\XVThumbImagePlugin.py -> build\lib.win32-2.7\PIL
  copying PIL\_binary.py -> build\lib.win32-2.7\PIL
  copying PIL\_tkinter_finder.py -> build\lib.win32-2.7\PIL
  copying PIL\_util.py -> build\lib.win32-2.7\PIL
  copying PIL\__init__.py -> build\lib.win32-2.7\PIL
  running egg_info
  writing Pillow.egg-info\PKG-INFO
  writing dependency_links to Pillow.egg-info\dependency_links.txt
  writing top-level names to Pillow.egg-info\top_level.txt
  warning: manifest_maker: standard file '-c' not found

  reading manifest file 'Pillow.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.sh'
  no previously-included directories found matching 'docs\_static'
  warning: no previously-included files found matching '.coveragerc'
  warning: no previously-included files found matching '.editorconfig'
  warning: no previously-included files found matching '.landscape.yaml'
  warning: no previously-included files found matching 'appveyor.yml'
  warning: no previously-included files found matching 'build_children.sh'
  warning: no previously-included files found matching 'tox.ini'
  warning: no previously-included files matching '.git*' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  writing manifest file 'Pillow.egg-info\SOURCES.txt'
  copying PIL\OleFileIO-README.md -> build\lib.win32-2.7\PIL
  running build_ext
  Traceback (most recent call last):
    File "<module>", line 1, in <module>
    File "c:\users\hisha\appdata\local\temp\pip-build-ootvc5\pillow\setup.py", line 753, in <module>
      zip_safe=not debug_build(), )
    File "c:\pypy\lib-python\2.7\distutils\core.py", line 151, in setup
      dist.run_commands()
    File "c:\pypy\lib-python\2.7\distutils\dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "c:\pypy\lib-python\2.7\distutils\dist.py", line 972, in run_command
      cmd_obj.run()
    File "d:\gradua~1\pypy_b~1\site-packages\wheel\bdist_wheel.py", line 199, in run
      self.run_command('build')
    File "c:\pypy\lib-python\2.7\distutils\cmd.py", line 334, in run_command
      self.distribution.run_command(command)
    File "c:\pypy\lib-python\2.7\distutils\dist.py", line 972, in run_command
      cmd_obj.run()
    File "c:\pypy\lib-python\2.7\distutils\command\build.py", line 127, in run
      self.run_command(cmd_name)
    File "c:\pypy\lib-python\2.7\distutils\cmd.py", line 334, in run_command
      self.distribution.run_command(command)
    File "c:\pypy\lib-python\2.7\distutils\dist.py", line 972, in run_command
      cmd_obj.run()
    File "c:\pypy\lib-python\2.7\distutils\command\build_ext.py", line 347, in run
      self.build_extensions()
    File "c:\users\hisha\appdata\local\temp\pip-build-ootvc5\pillow\setup.py", line 521, in build_extensions
      ' using --disable-%s, aborting' % (f, f))
  ValueError: zlib is required unless explicitly disabled using --disable-zlib, aborting

  ----------------------------------------
  Failed building wheel for pillow
  Running setup.py clean for pillow
Failed to build pillow
Installing collected packages: pillow
  Running setup.py install for pillow ... error
    Complete output from command d:\gradua~1\pypy_b~1\bin\pypy.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\hisha\\appdata\\local\\temp\\pip-build-ootvc5\\pillow\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\hisha\appdata\local\temp\pip-t_tsjz-record\install-record.txt --single-version-externally-managed --compile --install-headers d:\gradua~1\pypy_b~1\include\site\python2.7\pillow:
    Single threaded build for windows
    running install
    running build
    running build_py
    creating build
    creating build\lib.win32-2.7
    creating build\lib.win32-2.7\PIL
    copying PIL\BdfFontFile.py -> build\lib.win32-2.7\PIL
    copying PIL\BmpImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\BufrStubImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\ContainerIO.py -> build\lib.win32-2.7\PIL
    copying PIL\CurImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\DcxImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\DdsImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\EpsImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\ExifTags.py -> build\lib.win32-2.7\PIL
    copying PIL\features.py -> build\lib.win32-2.7\PIL
    copying PIL\FitsStubImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\FliImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\FontFile.py -> build\lib.win32-2.7\PIL
    copying PIL\FpxImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\FtexImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\GbrImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\GdImageFile.py -> build\lib.win32-2.7\PIL
    copying PIL\GifImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\GimpGradientFile.py -> build\lib.win32-2.7\PIL
    copying PIL\GimpPaletteFile.py -> build\lib.win32-2.7\PIL
    copying PIL\GribStubImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\Hdf5StubImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\IcnsImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\IcoImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\Image.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageChops.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageCms.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageColor.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageDraw.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageDraw2.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageEnhance.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageFile.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageFilter.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageFont.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageGrab.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageMath.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageMode.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageMorph.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageOps.py -> build\lib.win32-2.7\PIL
    copying PIL\ImagePalette.py -> build\lib.win32-2.7\PIL
    copying PIL\ImagePath.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageQt.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageSequence.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageShow.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageStat.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageTk.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageTransform.py -> build\lib.win32-2.7\PIL
    copying PIL\ImageWin.py -> build\lib.win32-2.7\PIL
    copying PIL\ImImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\ImtImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\IptcImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\Jpeg2KImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\JpegImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\JpegPresets.py -> build\lib.win32-2.7\PIL
    copying PIL\McIdasImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\MicImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\MpegImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\MpoImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\MspImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\OleFileIO.py -> build\lib.win32-2.7\PIL
    copying PIL\PaletteFile.py -> build\lib.win32-2.7\PIL
    copying PIL\PalmImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\PcdImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\PcfFontFile.py -> build\lib.win32-2.7\PIL
    copying PIL\PcxImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\PdfImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\PixarImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\PngImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\PpmImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\PsdImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\PSDraw.py -> build\lib.win32-2.7\PIL
    copying PIL\PyAccess.py -> build\lib.win32-2.7\PIL
    copying PIL\SgiImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\SpiderImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\SunImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\TarIO.py -> build\lib.win32-2.7\PIL
    copying PIL\TgaImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\TiffImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\TiffTags.py -> build\lib.win32-2.7\PIL
    copying PIL\WalImageFile.py -> build\lib.win32-2.7\PIL
    copying PIL\WebPImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\WmfImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\XbmImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\XpmImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\XVThumbImagePlugin.py -> build\lib.win32-2.7\PIL
    copying PIL\_binary.py -> build\lib.win32-2.7\PIL
    copying PIL\_tkinter_finder.py -> build\lib.win32-2.7\PIL
    copying PIL\_util.py -> build\lib.win32-2.7\PIL
    copying PIL\__init__.py -> build\lib.win32-2.7\PIL
    running egg_info
    writing Pillow.egg-info\PKG-INFO
    writing dependency_links to Pillow.egg-info\dependency_links.txt
    writing top-level names to Pillow.egg-info\top_level.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'Pillow.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.sh'
    no previously-included directories found matching 'docs\_static'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.landscape.yaml'
    warning: no previously-included files found matching 'appveyor.yml'
    warning: no previously-included files found matching 'build_children.sh'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    writing manifest file 'Pillow.egg-info\SOURCES.txt'
    copying PIL\OleFileIO-README.md -> build\lib.win32-2.7\PIL
    running build_ext
    Traceback (most recent call last):
      File "<module>", line 1, in <module>
      File "c:\users\hisha\appdata\local\temp\pip-build-ootvc5\pillow\setup.py", line 753, in <module>
        zip_safe=not debug_build(), )
      File "c:\pypy\lib-python\2.7\distutils\core.py", line 151, in setup
        dist.run_commands()
      File "c:\pypy\lib-python\2.7\distutils\dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "c:\pypy\lib-python\2.7\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "d:\gradua~1\pypy_b~1\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\pypy\lib-python\2.7\distutils\command\install.py", line 573, in run
        self.run_command('build')
      File "c:\pypy\lib-python\2.7\distutils\cmd.py", line 334, in run_command
        self.distribution.run_command(command)
      File "c:\pypy\lib-python\2.7\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "c:\pypy\lib-python\2.7\distutils\command\build.py", line 127, in run
        self.run_command(cmd_name)
      File "c:\pypy\lib-python\2.7\distutils\cmd.py", line 334, in run_command
        self.distribution.run_command(command)
      File "c:\pypy\lib-python\2.7\distutils\dist.py", line 972, in run_command
        cmd_obj.run()
      File "c:\pypy\lib-python\2.7\distutils\command\build_ext.py", line 347, in run
        self.build_extensions()
      File "c:\users\hisha\appdata\local\temp\pip-build-ootvc5\pillow\setup.py", line 521, in build_extensions
        ' using --disable-%s, aborting' % (f, f))
    ValueError: zlib is required unless explicitly disabled using --disable-zlib, aborting

    ----------------------------------------
Command "d:\gradua~1\pypy_b~1\bin\pypy.exe -u -c "import setuptools, tokenize;__file__='c:\\users\\hisha\\appdata\\local\\temp\\pip-build-ootvc5\\pillow\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\users\hisha\appdata\local\temp\pip-t_tsjz-record\install-record.txt --single-version-externally-managed --compile --install-headers d:\gradua~1\pypy_b~1\include\site\python2.7\pillow" failed with error code 1 in c:\users\hisha\appdata\local\temp\pip-build-ootvc5\pillow\
```
### What versions of Pillow and Python are you using?

**pillow 3.4.1
pypy2-v5.4.1-win32**

**Comment by wiredfool** [comment]
Pip is attempting to install from source, and you don't have the dependencies installed. 

While we did have pypy/windows binaries for one recent version, they were not produced for the 3.4 series due to several failing tests in recent versions of pypy.

**Comment by hugovk** [comment]
Here's the PyPy 5.4.1 error:

`TypeError: PyPy does not yet implement the new buffer interface`

https://github.com/python-pillow/Pillow/issues/1129#issuecomment-250961310

**Comment by hishamwaleed** [comment]
got it thank you
