### ISSUE TITLE
FreeBSD 

### ISSUE THREAD

**Issue by orjanTonder** [python-pillow/Pillow#2170]
`pip install Pillow==3.3.0 >> fail_pillow`

### What actually happened?

```
Collecting Pillow==3.3.0
  Using cached Pillow-3.3.0.zip
Building wheels for collected packages: Pillow
  Running setup.py bdist_wheel for Pillow: started
  Running setup.py bdist_wheel for Pillow: finished with status 'error'
  Complete output from command /usr/home/muad/env_pcshop/bin/python3.4 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-e1arobgn/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmp4rvuamtopip-wheel- --python-tag cp34:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4
  creating build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/GimpPaletteFile.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/BdfFontFile.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/ImageTransform.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/ContainerIO.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/ImageChops.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/GifImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/TarIO.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/BmpImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/ImageQt.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/_binary.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/ImageGrab.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/MpoImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/Hdf5StubImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/MpegImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/MspImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/JpegPresets.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/GbrImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/ImageMode.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/PdfImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/PaletteFile.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/IcoImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/PngImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/FpxImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/features.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/DdsImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/FontFile.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/ExifTags.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/JpegImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/GdImageFile.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/IptcImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/PcxImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/ImageSequence.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/PalmImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/IcnsImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/ImageDraw.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/TgaImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/ImageFile.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/ImagePath.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/FliImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/PcdImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/ImageTk.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/PcfFontFile.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/PpmImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/ImageFont.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/ImageEnhance.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/ImImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/TiffTags.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/PsdImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/ImtImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/FtexImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/DcxImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/SpiderImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/_tkinter_finder.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/ImageMorph.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/ImageShow.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/GribStubImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/Jpeg2KImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/OleFileIO.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/__init__.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/XpmImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/WalImageFile.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/WebPImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/ImageColor.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/ImageDraw2.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/PyAccess.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/GimpGradientFile.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/TiffImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/CurImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/ImageCms.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/XVThumbImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/MicImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/WmfImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/SgiImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/FitsStubImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/ImageOps.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/ImagePalette.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/ImageFilter.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/McIdasImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/SunImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/ImageStat.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/PixarImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/_util.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/Image.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/ImageWin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/BufrStubImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/XbmImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/EpsImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/ImageMath.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  copying PIL/PSDraw.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  running egg_info
  writing Pillow.egg-info/PKG-INFO
  writing top-level names to Pillow.egg-info/top_level.txt
  writing dependency_links to Pillow.egg-info/dependency_links.txt
  warning: manifest_maker: standard file '-c' not found
  
  reading manifest file 'Pillow.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.sh'
  no previously-included directories found matching 'docs/_static'
  warning: no previously-included files found matching '.coveragerc'
  warning: no previously-included files found matching '.editorconfig'
  warning: no previously-included files found matching '.landscape.yaml'
  warning: no previously-included files found matching 'appveyor.yml'
  warning: no previously-included files found matching 'build_children.sh'
  warning: no previously-included files found matching 'tox.ini'
  warning: no previously-included files matching '.git*' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  writing manifest file 'Pillow.egg-info/SOURCES.txt'
  copying PIL/OleFileIO-README.md -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
  running build_ext
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-e1arobgn/Pillow/setup.py", line 753, in <module>
      zip_safe=not debug_build(), )
    File "/usr/local/lib/python3.4/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/lib/python3.4/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/local/lib/python3.4/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/home/muad/env_pcshop/lib/python3.4/site-packages/wheel/bdist_wheel.py", line 199, in run
      self.run_command('build')
    File "/usr/local/lib/python3.4/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.4/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.4/distutils/command/build.py", line 126, in run
      self.run_command(cmd_name)
    File "/usr/local/lib/python3.4/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/lib/python3.4/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.4/distutils/command/build_ext.py", line 339, in run
      self.build_extensions()
    File "/tmp/pip-build-e1arobgn/Pillow/setup.py", line 521, in build_extensions
      ' using --disable-%s, aborting' % (f, f))
  ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting
  
  ----------------------------------------
  Running setup.py clean for Pillow
Failed to build Pillow
Installing collected packages: Pillow
  Running setup.py install for Pillow: started
    Running setup.py install for Pillow: finished with status 'error'
    Complete output from command /usr/home/muad/env_pcshop/bin/python3.4 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-e1arobgn/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-wdu4t57x-record/install-record.txt --single-version-externally-managed --compile --install-headers /usr/home/muad/env_pcshop/include/site/python3.4/Pillow:
    running install
    running build
    running build_py
    creating build
    creating build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4
    creating build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/GimpPaletteFile.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/BdfFontFile.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/ImageTransform.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/ContainerIO.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/ImageChops.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/GifImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/TarIO.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/BmpImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/ImageQt.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/_binary.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/ImageGrab.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/MpoImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/Hdf5StubImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/MpegImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/MspImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/JpegPresets.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/GbrImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/ImageMode.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/PdfImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/PaletteFile.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/IcoImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/PngImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/FpxImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/features.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/DdsImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/FontFile.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/ExifTags.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/JpegImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/GdImageFile.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/IptcImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/PcxImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/ImageSequence.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/PalmImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/IcnsImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/ImageDraw.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/TgaImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/ImageFile.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/ImagePath.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/FliImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/PcdImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/ImageTk.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/PcfFontFile.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/PpmImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/ImageFont.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/ImageEnhance.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/ImImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/TiffTags.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/PsdImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/ImtImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/FtexImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/DcxImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/SpiderImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/_tkinter_finder.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/ImageMorph.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/ImageShow.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/GribStubImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/Jpeg2KImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/OleFileIO.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/__init__.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/XpmImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/WalImageFile.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/WebPImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/ImageColor.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/ImageDraw2.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/PyAccess.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/GimpGradientFile.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/TiffImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/CurImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/ImageCms.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/XVThumbImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/MicImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/WmfImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/SgiImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/FitsStubImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/ImageOps.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/ImagePalette.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/ImageFilter.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/McIdasImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/SunImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/ImageStat.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/PixarImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/_util.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/Image.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/ImageWin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/BufrStubImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/XbmImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/EpsImagePlugin.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/ImageMath.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    copying PIL/PSDraw.py -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    running egg_info
    writing dependency_links to Pillow.egg-info/dependency_links.txt
    writing Pillow.egg-info/PKG-INFO
    writing top-level names to Pillow.egg-info/top_level.txt
    warning: manifest_maker: standard file '-c' not found
    
    reading manifest file 'Pillow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.sh'
    no previously-included directories found matching 'docs/_static'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.landscape.yaml'
    warning: no previously-included files found matching 'appveyor.yml'
    warning: no previously-included files found matching 'build_children.sh'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    writing manifest file 'Pillow.egg-info/SOURCES.txt'
    copying PIL/OleFileIO-README.md -> build/lib.freebsd-10.3-RELEASE-p7-amd64-3.4/PIL
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-e1arobgn/Pillow/setup.py", line 753, in <module>
        zip_safe=not debug_build(), )
      File "/usr/local/lib/python3.4/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.4/distutils/dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/home/muad/env_pcshop/lib/python3.4/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/local/lib/python3.4/distutils/command/install.py", line 539, in run
        self.run_command('build')
      File "/usr/local/lib/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.4/distutils/command/build.py", line 126, in run
        self.run_command(cmd_name)
      File "/usr/local/lib/python3.4/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/local/lib/python3.4/distutils/dist.py", line 974, in run_command
        cmd_obj.run()
      File "/usr/local/lib/python3.4/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/tmp/pip-build-e1arobgn/Pillow/setup.py", line 521, in build_extensions
        ' using --disable-%s, aborting' % (f, f))
    ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting
```    

### What versions of Pillow and Python are you using?

```
Python 3.4.5 (default, Oct 11 2016, 01:27:50) 
[GCC 4.2.1 Compatible FreeBSD Clang 3.4.1 (tags/RELEASE_34/dot1-final 208032)] on freebsd10
Type "help", "copyright", "credits" or "license" for more information.
```

Just me or? i

**Comment by wiredfool** [comment]
You're trying to build pillow without pillow being able to find the required dependencies, in this case:

```
    ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting
```

See http://pillow.readthedocs.io/en/3.4.x/installation.html#freebsd-installation or http://pillow.readthedocs.io/en/3.4.x/installation.html#building-on-freebsd .

**Comment by orjanTonder** [comment]
Thanks.
