### ISSUE TITLE
Cannot install with recent PyPy (Linux x86_64)

### ISSUE THREAD

**Issue by dcrosta** [python-pillow/Pillow#2378]
### What did you do?

Attempt to install with `pip install pillow`

### What did you expect to happen?

Pillow should install

### What actually happened?

I got this error:

```
    ...
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    writing manifest file 'Pillow.egg-info/SOURCES.txt'
    running build_ext


    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       http://pillow.readthedocs.io/en/latest/installation.html

    Traceback (most recent call last):
      File "<module>", line 1, in <module>
      File "/tmp/pip-build-dq79lo/pillow/setup.py", line 791, in <module>
        raise RequiredDependencyException(msg)
    RequiredDependencyException:

    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       http://pillow.readthedocs.io/en/latest/installation.html
```

I have zlib and headers installed:

```
$ ls -1 /usr/lib64/libz.so*
/usr/lib64/libz.so
/usr/lib64/libz.so.1
/usr/lib64/libz.so.1.2.7
$ ls -1 /usr/include/zlib.h
/usr/include/zlib.h
```

### What versions of Pillow and Python are you using?

```
$ /usr/local/opt/pypy/bin/pypy --version
Python 2.7.12 (aff251e543859ce4508159dd9f1a82a2f553de00, Nov 12 2016, 08:50:18)
[PyPy 5.6.0 with GCC 6.2.0]
```

This is the portable-pypy x86_64 version from https://github.com/squeaky-pl/portable-pypy.

Pillow 4.0.0

### Additional Notes

I see from http://pillow.readthedocs.io/en/latest/installation.html that PyPy 5.3.1 is the latest claimed-working version of PyPy, and I've found some other issues (#2163, #1129) that seem to be related, or which commenters thought was related. Those have all been closed without a resolution, so I'm opening this in the hopes that we can find a resolution that lets me use more recent PyPy.

**Comment by wiredfool** [comment]
Pypy 5.6 is the version that's running on Ci, so there's no reason that it shouldn't be working. 

The problem that you're getting is finding the headers or library, but it appears that you've got the libraries in a reasonable place. Try running:
```
pip install pillow --global-option="build_ext" --global-option="--debug"
```

That should give a log of everywhere that pip is looking for headers and libraries.

**Comment by dcrosta** [comment]
Here's what that gives:

```
/root/pypy/site-packages/pip/commands/install.py:194: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Collecting pillow
  Using cached Pillow-4.0.0.tar.gz
Requirement already satisfied: olefile in ./pypy/site-packages (from pillow)
Skipping bdist_wheel for pillow, due to binaries being disabled for it.
Installing collected packages: pillow
  Running setup.py install for pillow: started
    Running setup.py install for pillow: finished with status 'error'
    Complete output from command /root/pypy/bin/pypy -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-5_31NL/pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" build_ext --debug install --record /tmp/pip-_a52VC-record/install-record.txt --single-version-externally-managed --compile:
    running build_ext
    Appending path /tmp/pip-build-5_31NL/pillow/libImaging
    Looking for `libjpeg` using pkg-config.
    Package libjpeg was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libjpeg.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libjpeg' found
    Package libjpeg was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libjpeg.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libjpeg' found
    Looking for `libopenjp2` using pkg-config.
    Package libopenjp2 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libopenjp2.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libopenjp2' found
    Package libopenjp2 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libopenjp2.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libopenjp2' found
    Looking for `libtiff-5` using pkg-config.
    Package libtiff-5 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libtiff-5.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libtiff-5' found
    Package libtiff-5 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libtiff-5.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libtiff-5' found
    Looking for `libtiff-4` using pkg-config.
    Package libtiff-4 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libtiff-4.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libtiff-4' found
    Package libtiff-4 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libtiff-4.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libtiff-4' found
    Looking for `zlib` using pkg-config.
    Appending path /tmp/pip-build-5_31NL/pillow
    Appending path /tmp/pip-build-5_31NL/pillow
    Looking for `freetype2` using pkg-config.
    Package freetype2 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `freetype2.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'freetype2' found
    Package freetype2 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `freetype2.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'freetype2' found
    Looking for `lcms2` using pkg-config.
    Package lcms2 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `lcms2.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'lcms2' found
    Package lcms2 was not found in the pkg-config search path.
    Perhaps you should add the directory containing `lcms2.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'lcms2' found
    Looking for `libimagequant` using pkg-config.
    Package libimagequant was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libimagequant.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libimagequant' found
    Package libimagequant was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libimagequant.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libimagequant' found
    Appending path /root/pypy/lib
    Appending path /root/pypy/include
    Appending path /lib64
    Appending path /usr/lib64
    Appending path /usr/local/lib
    Appending path /usr/local/include
    Appending path /usr/lib
    Appending path /usr/include
    Appending path /lib
    Looking for zlib
    Checking for include file zlib.h in /tmp/pip-build-5_31NL/pillow/libImaging
    Checking for include file zlib.h in /tmp/pip-build-5_31NL/pillow
    Checking for include file zlib.h in /root/pypy/include
    Checking for include file zlib.h in /usr/local/include
    Checking for include file zlib.h in /usr/include
    Found zlib.h
    Couldn't find library z in ['/tmp/pip-build-5_31NL/pillow', '/root/pypy/lib', '/lib64', '/usr/lib64', '/usr/local/lib', '/usr/lib', '/lib']
    Looking for jpeg
    Checking for include file jpeglib.h in /tmp/pip-build-5_31NL/pillow/libImaging
    Checking for include file jpeglib.h in /tmp/pip-build-5_31NL/pillow
    Checking for include file jpeglib.h in /root/pypy/include
    Checking for include file jpeglib.h in /usr/local/include
    Checking for include file jpeglib.h in /usr/include
    Found jpeglib.h
    Couldn't find library jpeg in ['/tmp/pip-build-5_31NL/pillow', '/root/pypy/lib', '/lib64', '/usr/lib64', '/usr/local/lib', '/usr/lib', '/lib']
    Looking for jpeg2000
    Checking for openjpeg-#.# in /tmp/pip-build-5_31NL/pillow/libImaging
    Checking for openjpeg-#.# in /tmp/pip-build-5_31NL/pillow
    Checking for openjpeg-#.# in /root/pypy/include
    Checking for openjpeg-#.# in /usr/local/include
    Checking for openjpeg-#.# in /usr/include
    Checking for openjpeg-#.# in /root/pypy/include
    Looking for imagequant
    Checking for include file libimagequant.h in /tmp/pip-build-5_31NL/pillow/libImaging
    Checking for include file libimagequant.h in /tmp/pip-build-5_31NL/pillow
    Checking for include file libimagequant.h in /root/pypy/include
    Checking for include file libimagequant.h in /usr/local/include
    Checking for include file libimagequant.h in /usr/include
    Checking for include file libimagequant.h in /root/pypy/include
    Looking for tiff
    Checking for include file tiff.h in /tmp/pip-build-5_31NL/pillow/libImaging
    Checking for include file tiff.h in /tmp/pip-build-5_31NL/pillow
    Checking for include file tiff.h in /root/pypy/include
    Checking for include file tiff.h in /usr/local/include
    Checking for include file tiff.h in /usr/include
    Checking for include file tiff.h in /root/pypy/include
    Looking for freetype
    Couldn't find library freetype in ['/tmp/pip-build-5_31NL/pillow', '/root/pypy/lib', '/lib64', '/usr/lib64', '/usr/local/lib', '/usr/lib', '/lib']
    Looking for lcms
    Checking for include file lcms2.h in /tmp/pip-build-5_31NL/pillow/libImaging
    Checking for include file lcms2.h in /tmp/pip-build-5_31NL/pillow
    Checking for include file lcms2.h in /root/pypy/include
    Checking for include file lcms2.h in /usr/local/include
    Checking for include file lcms2.h in /usr/include
    Checking for include file lcms2.h in /root/pypy/include
    Looking for webp
    Checking for include file webp/encode.h in /tmp/pip-build-5_31NL/pillow/libImaging
    Checking for include file webp/encode.h in /tmp/pip-build-5_31NL/pillow
    Checking for include file webp/encode.h in /root/pypy/include
    Checking for include file webp/encode.h in /usr/local/include
    Checking for include file webp/encode.h in /usr/include
    Checking for include file webp/encode.h in /root/pypy/include
    Looking for webpmux
    Checking for include file webp/mux.h in /tmp/pip-build-5_31NL/pillow/libImaging
    Checking for include file webp/mux.h in /tmp/pip-build-5_31NL/pillow
    Checking for include file webp/mux.h in /root/pypy/include
    Checking for include file webp/mux.h in /usr/local/include
    Checking for include file webp/mux.h in /usr/include
    Checking for include file webp/mux.h in /root/pypy/include
    
    
    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       http://pillow.readthedocs.io/en/latest/installation.html
    
    Traceback (most recent call last):
      File "<module>", line 1, in <module>
      File "/tmp/pip-build-5_31NL/pillow/setup.py", line 791, in <module>
        raise RequiredDependencyException(msg)
    RequiredDependencyException:
    
    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       http://pillow.readthedocs.io/en/latest/installation.html
    
    
    
    ----------------------------------------
Command "/root/pypy/bin/pypy -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-5_31NL/pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" build_ext --debug install --record /tmp/pip-_a52VC-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-5_31NL/pillow/
```

I tried debugging and stepping through the setup. I see that it's looking for a file named `libz.pypy-41.so` rather than the expected `libz.so`. This is happening in `distutils.unixcompiler.UnixCCompiler` class, but the build in PIL/pillow is fairly complicated so I want to ask here before reporting to pypy or portable-pypy.

This is happening on both our CentOS 6.5 and CentOS 7 build slaves.

**Comment by dcrosta** [comment]
If I install `libjpeg-static` and `zlib-static`, then distutils seems to find the static versions, and link against those. Still, weird that it wouldn't find the shared-object versions, I think. I'll report this upstream to pypy, seems likely that something changed in how/where PyPy looks for shared objects between 5.3 and 5.6.

**Comment by dcrosta** [comment]
Ah: https://bitbucket.org/pypy/pypy/diff/lib-python/2.7/distutils/unixccompiler.py?diff2=66ef3eb6a91e&at=default

So presumably a future PyPy will have fixed this, too. Sorry for nagging you all, I could have self-served this, but at least we all learned something.

**Comment by wiredfool** [comment]
Ok, Looking at the latest CI, I'm seeing pypy 5.4: https://travis-ci.org/python-pillow/Pillow/jobs/196071811 . 5.6 does work locally, so I'm not sure if we've got a different distutils or what. 

```
(vpypy56)erics@builder-1204-x64:~/Pillow$ make clean && python setup.py build_ext --debug 
python setup.py clean
running clean
rm PIL/*.so || true
rm: cannot remove `PIL/*.so': No such file or directory
rm -r build || true
rm: cannot remove `build': No such file or directory
find . -name __pycache__ | xargs rm -r || true
running build_ext
Appending path /home/erics/Pillow/libImaging
Looking for `libjpeg` using pkg-config.
Package libjpeg was not found in the pkg-config search path.
Perhaps you should add the directory containing `libjpeg.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libjpeg' found
Package libjpeg was not found in the pkg-config search path.
Perhaps you should add the directory containing `libjpeg.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libjpeg' found
Looking for `libopenjp2` using pkg-config.
Appending path /home/erics/Pillow
Looking for `libtiff-5` using pkg-config.
Package libtiff-5 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libtiff-5.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libtiff-5' found
Package libtiff-5 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libtiff-5.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libtiff-5' found
Looking for `libtiff-4` using pkg-config.
Package libtiff-4 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libtiff-4.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libtiff-4' found
Package libtiff-4 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libtiff-4.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libtiff-4' found
Looking for `zlib` using pkg-config.
Appending path /home/erics/Pillow
Looking for `freetype2` using pkg-config.
Appending path /usr/include/freetype2
Looking for `lcms2` using pkg-config.
Looking for `libimagequant` using pkg-config.
Package libimagequant was not found in the pkg-config search path.
Perhaps you should add the directory containing `libimagequant.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libimagequant' found
Package libimagequant was not found in the pkg-config search path.
Perhaps you should add the directory containing `libimagequant.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libimagequant' found
Appending path /usr/lib/pypy/include
Appending path /lib64
Appending path /usr/lib/x86_64-linux-gnu
Appending path /usr/lib/x86_64-linux-gnu
Appending path /usr/include/x86_64-linux-gnu
Appending path /usr/local/lib
Appending path /usr/local/include
Appending path /usr/lib
Appending path /usr/include
Appending path /lib
Looking for zlib
Checking for include file zlib.h in /home/erics/Pillow/libImaging
Checking for include file zlib.h in /home/erics/Pillow
Checking for include file zlib.h in /usr/include/freetype2
Checking for include file zlib.h in /usr/lib/pypy/include
Checking for include file zlib.h in /usr/local/include
Checking for include file zlib.h in /usr/include
Found zlib.h
Found library z at /usr/lib/x86_64-linux-gnu/libz.a
Looking for jpeg
Checking for include file jpeglib.h in /home/erics/Pillow/libImaging
Checking for include file jpeglib.h in /home/erics/Pillow
Checking for include file jpeglib.h in /usr/include/freetype2
Checking for include file jpeglib.h in /usr/lib/pypy/include
Checking for include file jpeglib.h in /usr/local/include
Checking for include file jpeglib.h in /usr/include
Found jpeglib.h
Found library jpeg at /usr/lib/x86_64-linux-gnu/libjpeg.a
...
```

**Comment by dcrosta** [comment]
Looks like it's finding the static version -- maybe Ubuntu installs both, or Travis does? At any rate, we've got a work-around until the patch I referenced in PyPy upstream lands, so that's fine for me.

**Comment by wiredfool** [comment]
What os are you on?

**Comment by dcrosta** [comment]
CentOS. Both 6.x and 7.x have the same issue.

**Comment by wiredfool** [comment]
I've confirmed this on Centos6, and I've also run the exact same portable pypy on ubuntu. It does look like what's happening is that it's finding the static library on ubuntu, but not on centos. 

Ubuntu Precise: 
```
> /tmp/pypy-5.6-linux_x86_64-portable/lib-python/2.7/distutils/unixccompiler.py(322)find_library_file()->'/usr/lib/x86...ux-gnu/libz.a'
-> return static
(Pdb) l
317  	            elif os.path.exists(xcode_stub):
318  	                return xcode_stub
319  	            elif os.path.exists(shared):
320  	                return shared
321  	            elif os.path.exists(static):
322  ->	                return static
323  	
324  	        # Oops, didn't find it in *any* of 'dirs'
325  	        return None
[EOF]
(Pdb) static
'/usr/lib/x86_64-linux-gnu/libz.a'
(vpypy) pillow@51fbb469bb6a:/Pillow$ dpkg -L zlib1g-dev
...
/usr/lib/x86_64-linux-gnu/libz.a
/usr/lib/x86_64-linux-gnu/pkgconfig
/usr/lib/x86_64-linux-gnu/pkgconfig/zlib.pc
/usr/lib/x86_64-linux-gnu/libz.so
```

Where on centos I'm getting:
```
(Pdb) l
310  	
311  	            # We're second-guessing the linker here, with not much hard
312  	            # data to go on: GCC seems to prefer the shared library, so I'm
313  	            # assuming that *all* Unix C compilers do.  And of course I'm
314  	            # ignoring even GCC's "-static" option.  So sue me.
315  ->	            if os.path.exists(dylib):
316  	                return dylib
317  	            elif os.path.exists(xcode_stub):
318  	                return xcode_stub
319  	            elif os.path.exists(shared):
320  	                return shared
(Pdb) return
--Return--
> /home/pillow/pypy-5.6-linux_x86_64-portable/lib-python/2.7/distutils/unixccompiler.py(325)find_library_file()->None
-> return None
(Pdb) 
```
