### ISSUE TITLE
Error: cannot identify image file

### ISSUE THREAD

**Issue by rosuH** [python-pillow/Pillow#2498]
### What did you do?
These files should be opened by PIL and then output as an image file.
### What actually happened?

An exception: OSError: cannot identify image file.

### What versions of Pillow and Python are you using?
```
Pillow : 4.1.0
Python: 3.5.1
- - - - - 
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty
hardware-platform : 86_64 GNU/Linux

```

Here is the self-contained scripts.
```
for i in Sticker*; do python3 -c "from PIL import Image; x = Image.open('$i'); print(x.format)"; done;
```
And the error:
```shell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-160796490_227_1493219988.exe'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-160796490_232_1493220087.exe'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-160796490_233_1493220112.exe'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-160796490_237_1493220146.exe'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-160796490_239_1493220159.exe'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-160796490_306_1493221968.exe'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-160796490_326_1493251561.exe'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-160796490_330_1493251785.obj'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-160796490_436_1493259063.obj'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-160796490_518_1493280629.obj'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-160796490_592_1493294543.o'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-160796490_600_1493295370.o'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-160796490_608_1493298020.a'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-160796490_637_1493301217.dll'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-160796490_638_1493301432.dll'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-160796490_639_1493301492.bin'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-160796490_653_1493306157.bin'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-160796490_837_1493366858.a'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-160796490_844_1493367388.a'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-191478191_369_1493255130.obj'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-191478191_379_1493255260.obj'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_221798031_182_1493217871.exe'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_221798031_241_1493220192.exe'

```
I had read the doc, and I think all dependencies had prepared. Please remind me if I forgot something.
This error occurred when I want to send a Telegram's sticker. I had raised a issue in that project.
That author suggested that I can try raise a issue in here.
See this: [https://github.com/blueset/ehForwarderBot/issues/44](url)
**I had upload all file so you can check them.**
Thanks!
- - - - - 
My English is not very good. Here is the Chinese version:

### What did you do?
这些文件应该通过 PIL 打开的，然后输出为一个图像文件。
### What actually happened?

一个异常情况

> OSError: cannot identify image file.

### What versions of Pillow and Python are you using?
```
Pillow : 4.1.0
Python: 3.5.1
```

下面是一个独立的脚本
```
for i in Sticker*; do python3 -c "from PIL import Image; x = Image.open('$i'); print(x.format)"; done;
```
执行之后出现的错误
```shell
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-160796490_227_1493219988.exe'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-160796490_232_1493220087.exe'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-160796490_233_1493220112.exe'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-160796490_237_1493220146.exe'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-160796490_239_1493220159.exe'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-160796490_306_1493221968.exe'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-160796490_326_1493251561.exe'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-160796490_330_1493251785.obj'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-160796490_436_1493259063.obj'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-160796490_518_1493280629.obj'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-160796490_592_1493294543.o'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-160796490_600_1493295370.o'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-160796490_608_1493298020.a'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-160796490_637_1493301217.dll'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-160796490_638_1493301432.dll'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-160796490_639_1493301492.bin'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-160796490_653_1493306157.bin'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-160796490_837_1493366858.a'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-160796490_844_1493367388.a'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-191478191_369_1493255130.obj'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_-191478191_379_1493255260.obj'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_221798031_182_1493217871.exe'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/rosu/.pyenv/versions/3.5.1/lib/python3.5/site-packages/PIL/Image.py", line 2452, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Sticker_221798031_241_1493220192.exe'
```

我已经阅读了本项目的文档，我觉得所有的依赖应该都已经准备好了。如果有所缺漏，麻烦提醒我。
当我在 Telegram 发送贴纸的时候发生了这个错误，我已经在原项目提交了一个 issue。
那个项目的作者建议我可以来此提交一个 issue，他说可能是 PLI 的问题。
那个 issue 地址是：[https://github.com/blueset/ehForwarderBot/issues/44](url)

**我已经上传了测试脚本的文件，以便你们检查里面的问题。**
非常感谢！
[eh_telegram_master.zip](https://github.com/python-pillow/Pillow/files/964133/eh_telegram_master.zip)

**Comment by wiredfool** [comment]
None of those files appear to be image files, they all appear to be code of one form or another.
