### ISSUE TITLE
Wrong error handling in C Extensions (_webp.c)

### ISSUE THREAD

**Issue by adw1n** [python-pillow/Pillow#2514]
### What versions of Pillow are you using?
Pillow version 4.2.0.dev0 -  branch `master` from 10min ago (commit 1e0fbc0f1a524413e6fe77d0cb8de6b1be781302).

### Issue
You made a mistake in the way you handle exceptions returned by basic functions like `PyArg_ParseTuple`. 
Examples:
https://github.com/python-pillow/Pillow/blob/master/_webp.c#L32
https://github.com/python-pillow/Pillow/blob/master/_webp.c#L148
Instead of doing:
```C
return NULL;
```
you are doing:
```C
Py_RETURN_NONE;
```
Why does it matter?
a) error may not be signalized to the user
In python >=3.5 error will be signalized because of https://bugs.python.org/issue23571 but instead of `TypeError`,  `SystemError` will be thrown.
example:
``` python
import PIL._webp
PIL._webp.WebPDecode()
TypeError: function takes exactly 1 argument (0 given)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
SystemError: <built-in function WebPDecode> returned a result with an error set
```
expected (correct) behaviour would be:
```python
import PIL._webp
PIL._webp.WebPDecode()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: function takes exactly 1 argument (0 given)
```

For example this code in python 2.7.10 and 3.4.3 does not raise an error at all!
```
import PIL._webp
PIL._webp.WebPEncode()
```
b) error does not get cleared
Python 2.7.10 or 3.4.3
```python
>>> import PIL._webp
>>> a=PIL._webp.WebPDecode()
>>> type(a)
TypeError: function takes exactly 1 argument (0 given)
>>> type(a)
<type 'NoneType'>
```

Unit test:
```python
import unittest
import PIL._webp


class TestWebpErrorHandling(unittest.TestCase):
    def test_WebPEncode_invalid_num_of_args_raises_type_error(self):
        with self.assertRaises(TypeError):
            PIL._webp.WebPEncode()
    def test_WebPDecode_invalid_num_of_args_raises_type_error(self):
        with self.assertRaises(TypeError):
            PIL._webp.WebPDecode()


if __name__ == '__main__':
    unittest.main()
```

After running the test using Python 3.4.3:
```
EE
======================================================================
ERROR: test_WebPDecode_invalid_num_of_args_raises_type_error (__main__.TestWebpErrorHandling)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 11, in test_WebPDecode_invalid_num_of_args_raises_type_error
    a=PIL._webp.WebPDecode()
  File "/usr/lib/python3.4/unittest/case.py", line 181, in __exit__
    self._raiseFailure("{} not raised".format(exc_name))
TypeError: function takes exactly 1 argument (0 given)

======================================================================
ERROR: test_WebPEncode_invalid_num_of_args_raises_type_error (__main__.TestWebpErrorHandling)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 8, in test_WebPEncode_invalid_num_of_args_raises_type_error
    PIL._webp.WebPEncode()
  File "/usr/lib/python3.4/unittest/case.py", line 181, in __exit__
    self._raiseFailure("{} not raised".format(exc_name))
TypeError: function takes exactly 8 arguments (0 given)

----------------------------------------------------------------------
Ran 2 tests in 0.006s

FAILED (errors=2)
```

**Comment by hugovk** [comment]
Closing because https://github.com/python-pillow/Pillow/pull/2521 has been merged.
