### ISSUE TITLE
Ghostscript test failure on FreeBSD

### ISSUE THREAD

**Issue by wiredfool** [python-pillow/Pillow#2545]
One test is failing on FreeBSD 10.3 and 11.0 with the ghostscript-agpl package installed.  This is python version independent. Pillow 4.1.1 tested.

```
Traceback (most recent call last):
  File "/usr/home/erics/Pillow/Tests/test_file_eps.py", line 152, in test_resize
    image3 = image3.resize(new_size)
  File "/home/erics/vpy36/lib/python3.6/site-packages/Pillow-4.1.1-py3.6-freebsd-11.0-RELEASE-p9-amd64.egg/PIL/Image.py", line 1630, in resize
    self.load()
  File "/home/erics/vpy36/lib/python3.6/site-packages/Pillow-4.1.1-py3.6-freebsd-11.0-RELEASE-p9-amd64.egg/PIL/EpsImagePlugin.py", line 332, in load
    self.im = Ghostscript(self.tile, self.size, self.fp, scale)
  File "/home/erics/vpy36/lib/python3.6/site-packages/Pillow-4.1.1-py3.6-freebsd-11.0-RELEASE-p9-amd64.egg/PIL/EpsImagePlugin.py", line 141, in Ghostscript
    subprocess.check_call(command, stdin=devnull, stdout=devnull)
  File "/usr/local/lib/python3.6/subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['gs', '-q', '-g403x2448', '-r72.000000x72.000000', '-dNOPAUSE', '-dSAFER', '-sDEVICE=ppmraw', '-sOutputFile=/tmp/tmp91y5qlwq', '-c', '0 0 translate', '-f', 'Tests/images/illu10_preview.eps']' returned non-zero exit status 1.
```

**Comment by wiredfool** [comment]
This appears to be a ghostscript bug, in secton 2.2 here: https://ghostscript.com/doc/9.16/Issues.htm

> When CIDFont-CMap pair required by PDF file is not available GS fails with:
/undefinedresource in --findresource--

```
gs -q -g403x2448 -r72.000000x72.000000 -dNOPAUSE -dSAFER -sDEVICE=ppmraw -sOutputFile=/tmp/tmp0rn4a9_8 -c 0 0 translate -f Tests/images/illu10_preview.eps
Error: /undefinedresource in resourcestatus
Operand stack:
   false   ct_StyleDicts   --dict:0/4(L)--   Adobe-Japan1   --dict:0/4(L)--   Serif   HeiseiMin-W3-83pv-RKSJ-H   Font   HeiseiMin-W3   CIDFont
Execution stack:
   %interp_exit   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   false   1   %stopped_push   1967   1   3   %oparray_pop   1967   1   3   %oparray_pop   1966   1   3   %oparray_pop   --nostringval--   1950   1   3   %oparray_pop   1836   1   3   %oparray_pop   --nostringval--   %errorexec_pop   .runexec2   --nostringval--   --nostringval--   --nostringval--   2   %stopped_push   --nostringval--   --nostringval--   --nostringval--   1915   10   9   %oparray_pop
Dictionary stack:
   --dict:1190/1684(ro)(G)--   --dict:0/20(G)--   --dict:94/200(L)--   --dict:57/75(L)--   --dict:2/10(L)--   --dict:39/70(L)--   --dict:0/4(L)--   --dict:0/4(L)--   --dict:20/27(ro)(G)--   --dict:20/26(ro)(G)--
Current allocation mode is local
Last OS error: Invalid argument
GPL Ghostscript 9.16: Unrecoverable error
```

**Comment by radarhere** [comment]
Just to note here - in #2559, @HinTak says that this
> is not a ghostscript bug. It is a FreeBSD mispackaging. Building ghostscript from git works correctly.

**Comment by radarhere** [comment]
FreeBSD 10 is no longer supported. Testing on a 11.2 VM, I find no problems, so I imagine this was resolved elsewhere.
