### ISSUE TITLE
Cannot upgrade from 2.6.1 to 4.1.1

### ISSUE THREAD

**Issue by kocicky** [python-pillow/Pillow#2565]
### What did you do?
pip install Pillow --upgrade --global-option="build_ext" --global-option="--debug"

### Platform
OSMC on RPi2 - Debian

### What actually happened?

```
/usr/local/lib/python2.7/dist-packages/pip/commands/install.py:194: UserWarning: Disabling all use of wheels due to the use of --build-options / --global-options / --install-options.
  cmdoptions.check_install_build_global(options)
Collecting Pillow
  Using cached Pillow-4.1.1.tar.gz
Requirement already up-to-date: olefile in /usr/local/lib/python2.7/dist-packages (from Pillow)
Installing collected packages: Pillow
  Found existing installation: Pillow 2.6.1
    Uninstalling Pillow-2.6.1:
      Successfully uninstalled Pillow-2.6.1
  Running setup.py install for Pillow ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-XJpMp5/Pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" build_ext --debug install --record /tmp/pip-0YuWky-record/install-record.txt --single-version-externally-managed --compile:
    running build_ext
    Appending path /tmp/pip-build-XJpMp5/Pillow/libImaging
    Appending path /usr/lib
    Appending path /usr/include
    Appending path /usr/local/lib
    Appending path /usr/local/include
    Appending path /lib
    Looking for zlib
    Checking for include file zlib.h in /tmp/pip-build-XJpMp5/Pillow/libImaging
    Checking for include file zlib.h in /usr/include
    Found zlib.h
    Couldn't find library z in ['/usr/lib', '/usr/local/lib', '/lib']
    Looking for jpeg
    Checking for include file jpeglib.h in /tmp/pip-build-XJpMp5/Pillow/libImaging
    Checking for include file jpeglib.h in /usr/include
    Checking for include file jpeglib.h in /usr/local/include
    Checking for include file jpeglib.h in /usr/include/python2.7
    Looking for jpeg2000
    Checking for openjpeg-#.# in /tmp/pip-build-XJpMp5/Pillow/libImaging
    Checking for openjpeg-#.# in /usr/include
    Checking for openjpeg-#.# in /usr/local/include
    Checking for openjpeg-#.# in /usr/include/python2.7
    Looking for imagequant
    Checking for include file libimagequant.h in /tmp/pip-build-XJpMp5/Pillow/libImaging
    Checking for include file libimagequant.h in /usr/include
    Checking for include file libimagequant.h in /usr/local/include
    Checking for include file libimagequant.h in /usr/include/python2.7
    Looking for tiff
    Checking for include file tiff.h in /tmp/pip-build-XJpMp5/Pillow/libImaging
    Checking for include file tiff.h in /usr/include
    Checking for include file tiff.h in /usr/local/include
    Checking for include file tiff.h in /usr/include/python2.7
    Looking for freetype
    Couldn't find library freetype in ['/usr/lib', '/usr/local/lib', '/lib']
    Looking for lcms
    Checking for include file lcms2.h in /tmp/pip-build-XJpMp5/Pillow/libImaging
    Checking for include file lcms2.h in /usr/include
    Checking for include file lcms2.h in /usr/local/include
    Checking for include file lcms2.h in /usr/include/python2.7
    Looking for webp
    Checking for include file webp/encode.h in /tmp/pip-build-XJpMp5/Pillow/libImaging
    Checking for include file webp/encode.h in /usr/include
    Checking for include file webp/encode.h in /usr/local/include
    Checking for include file webp/encode.h in /usr/include/python2.7
    Looking for webpmux
    Checking for include file webp/mux.h in /tmp/pip-build-XJpMp5/Pillow/libImaging
    Checking for include file webp/mux.h in /usr/include
    Checking for include file webp/mux.h in /usr/local/include
    Checking for include file webp/mux.h in /usr/include/python2.7
    
    
    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-XJpMp5/Pillow/setup.py", line 756, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:
    
    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
```

**Comment by wiredfool** [comment]
I'm not familiar with the file layout of OSMC, though since we're compatible with Debian, one would expect that it should work. Since we're not getting zlib (which is a default library) it pretty clear that there's a library directory that's missing.
