### ISSUE TITLE
getmask2() got an unexpected keyword argument 'align'

### ISSUE THREAD

**Issue by skeith** [python-pillow/Pillow#2639]
### What did you do?
Run a py script that uses PIL

### What did you expect to happen?
The script uses PIL to show an image with text

### What actually happened?
Error happened

### What versions of Pillow and Python are you using?
PIL 4.2.1 and Python 3.5.2

Here is the script I am using 
https://github.com/Aioxas/ax-cogs/blob/master/horoscope/horoscope.py

and the traceback is
```python
Exception in command 'tsujiura'
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/yukirin/Kanon/cogs/horoscope.py", line 152, in _cookie
    self.fortune_process(fortune[0])
  File "/home/yukirin/Kanon/cogs/horoscope.py", line 213, in fortune_process
    draw.text((134, 165), line1, (0, 0, 0), font=font, align="center")
  File "lib/PIL/ImageDraw.py", line 217, in text
    mask, offset = font.getmask2(text, self.fontmode, *args, **kwargs)
TypeError: getmask2() got an unexpected keyword argument 'align'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: getmask2() got an unexpected keyword argument 'align'
```

I fixed it by reverting to PIL 4.0.0, so I assume PIL 4.2.1 breaking it?
(I was asked by the dev of that script I use to post an issue here)

**Comment by wiredfool** [comment]
What kind of font are you using?

**Comment by hugovk** [comment]
From https://github.com/Aioxas/ax-cogs/blob/master/horoscope/horoscope.py#L204-L216:
```python
    def fortune_process(self, fortune):
        img = Image.open("data/horoscope/cookie.png")
        draw = ImageDraw.Draw(img)
        font = ImageFont.truetype("data/horoscope/FortuneCookieNF.ttf", 15)
        line = fortune.split()
        sep = " "
        line1 = sep.join(line[:5])
        line2 = sep.join(line[5:10])
        line3 = sep.join(line[10:])
        draw.text((134, 165), line1, (0, 0, 0), font=font, align="center")
        draw.text((134, 180), line2, (0, 0, 0), font=font, align="center")
        draw.text((134, 195), line3, (0, 0, 0), font=font, align="center")
        img.save("data/horoscope/cookie-edit.png")
```

Font is here: https://github.com/Aioxas/ax-cogs/blob/master/horoscope/data/horoscope/FortuneCookieNF.ttf

**Comment by hugovk** [comment]
Reproducible with Pillow 4.2.1/Python 2.7.13/macOS:

```python
from PIL import Image, ImageDraw, ImageFont
img = Image.new("RGB", (400,400))
draw = ImageDraw.Draw(img)
font = ImageFont.truetype("FortuneCookieNF.ttf", 15)
line1 = "some text"
draw.text((134, 165), line1, (0, 0, 0), font=font, align="center")
```

And also when changing the font:
```python
from PIL import Image, ImageDraw, ImageFont
img = Image.new("RGB", (400,400))
draw = ImageDraw.Draw(img)
font = ImageFont.truetype("/Library/Fonts/Arial.ttf", 15)
line1 = "some text"
draw.text((134, 165), line1, (0, 0, 0), font=font, align="center")
```
```
Traceback (most recent call last):
  File "2639.py", line 6, in <module>
    draw.text((134, 165), line1, (0, 0, 0), font=font, align="center")
  File "/usr/local/lib/python2.7/site-packages/PIL/ImageDraw.py", line 217, in text
    mask, offset = font.getmask2(text, self.fontmode, *args, **kwargs)
TypeError: getmask2() got an unexpected keyword argument 'align'
```

**Comment by hugovk** [comment]
Can be fixed by adding `*args, **kwargs` into:
```python
def getmask2(self, text, mode="", fill=Image.core.fill, direction=None, features=None):
 ```
