### ISSUE TITLE
cannot identify image file with Pillow 4.2.1

### ISSUE THREAD

**Issue by Zephor5** [python-pillow/Pillow#2665]
```python
Image.open('test.jpg')

>Traceback (most recent call last):  
 File "<stdin>", line 1, in <module>
   File "D:\Python27\lib\site-packages\PIL\Image.py", line 2519, in open
     % (filename if filename else fp))
 IOError: cannot identify image file 'test.jpg'
```

Python 2.7.11 2.7.13 tested    with Pillow 4.2.1
[test.jpg.gz](https://github.com/python-pillow/Pillow/files/1211140/test.jpg.gz)

**Comment by hugovk** [comment]
Reproducible with macOS Sierra / Python 2.7.13 / Pillow 4.2.1:

```python
Python 2.7.13 (default, Jul 18 2017, 09:17:00)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
>>> Image.PILLOW_VERSION
'4.2.1'
>>> im = Image.open("test.jpg")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/PIL/Image.py", line 2519, in open
    % (filename if filename else fp))
IOError: cannot identify image file 'test.jpg'
```

Not reproducible with latest master:
```python
Python 2.7.13 (default, Jul 18 2017, 09:17:00)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
>>> Image.PILLOW_VERSON
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'PILLOW_VERSON'
>>> Image.PILLOW_VERSION
'4.3.0.dev0'
>>> im = Image.open("test.jpg")
>>> im
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1074x664 at 0x10745ED50>
>>> im.show()
```
![image](https://user-images.githubusercontent.com/1324225/29128565-dda360cc-7d2c-11e7-8e35-1f5f267bbbf4.png)

Please can you also test latest master? The next quarterly release is on 1st October.

**Comment by Zephor5** [comment]
@hugovk  latest master is ok, thx.

**Comment by hugovk** [comment]
Good to hear, and in any case thanks for the report!
