### ISSUE TITLE
Can't load gif: tile cannot extend outside image

### ISSUE THREAD

**Issue by vinicius-ronconi** [python-pillow/Pillow#2733]
### What did you do?
I'm trying to copy some Gifs, but an ValueError: tile cannot extend outside image is raised

### What did you expect to happen?
The image should be copied to another variable.

### What actually happened?
ValueError: tile cannot extend outside image

### What versions of Pillow and Python are you using?
Python 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Pillow 4.2.1

I'm attaching some gifs to reproduce the problem. The file struggle_bus.gif is not animated, while all the others are animated gifs.
[gifs.zip](https://github.com/python-pillow/Pillow/files/1296984/gifs.zip)

Here is the code used to reproduce the problem:

```python
>>> from PIL import Image
>>> img = Image.open('struggle_bus.gif')
>>> x = img.copy()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ronconi/Workspaces/PythonVirtualEnvs/rebelmouse/lib/python2.7/site-packages/PIL/Image.py", line 1026, in copy
    self.load()
  File "/Users/ronconi/Workspaces/PythonVirtualEnvs/rebelmouse/lib/python2.7/site-packages/PIL/ImageFile.py", line 204, in load
    decoder.setimage(self.im, extents)
ValueError: tile cannot extend outside image
>>> img.show()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ronconi/Workspaces/PythonVirtualEnvs/rebelmouse/lib/python2.7/site-packages/PIL/Image.py", line 1940, in show
    _show(self, title=title, command=command)
  File "/Users/ronconi/Workspaces/PythonVirtualEnvs/rebelmouse/lib/python2.7/site-packages/PIL/Image.py", line 2728, in _show
    _showxv(image, **options)
  File "/Users/ronconi/Workspaces/PythonVirtualEnvs/rebelmouse/lib/python2.7/site-packages/PIL/Image.py", line 2733, in _showxv
    ImageShow.show(image, title, **options)
  File "/Users/ronconi/Workspaces/PythonVirtualEnvs/rebelmouse/lib/python2.7/site-packages/PIL/ImageShow.py", line 51, in show
    if viewer.show(image, title=title, **options):
  File "/Users/ronconi/Workspaces/PythonVirtualEnvs/rebelmouse/lib/python2.7/site-packages/PIL/ImageShow.py", line 73, in show
    image = image.convert(base)
  File "/Users/ronconi/Workspaces/PythonVirtualEnvs/rebelmouse/lib/python2.7/site-packages/PIL/Image.py", line 860, in convert
    self.load()
  File "/Users/ronconi/Workspaces/PythonVirtualEnvs/rebelmouse/lib/python2.7/site-packages/PIL/ImageFile.py", line 204, in load
    decoder.setimage(self.im, extents)
ValueError: tile cannot extend outside image
```

**Comment by wiredfool** [comment]
It's not copy, it's the initial load of the image. 

The issue is when loading the GIF, there is a dispose-extents flag that extends beyond the bounds of the image. In this case, all the images are consistent that there's an offset from the origin, and then a size. 

We've seen this before with animated images that get larger and larger (and occasionally, big enough to exhaust memory if allowed.)

**Comment by radarhere** [comment]
This looks like the same issue as #2383
