### ISSUE TITLE
ReadTheDocs badge is red

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#2763]
### What did you do?

Check the ReadTheDocs badge on the README.

### What did you expect to happen?

It to be green.

### What actually happened?

It's red.

![image](https://user-images.githubusercontent.com/1324225/30955885-f152d2d2-a43d-11e7-99d2-9ec82adaaaf7.png)

**Comment by hugovk** [comment]
Quite a few of the recent build failed at https://readthedocs.org/projects/pillow/builds/

![image](https://user-images.githubusercontent.com/1324225/30955996-4da08dcc-a43e-11e7-92da-b29fff44518a.png)

Here's the failing step of a failing build:

```
python /home/docs/checkouts/readthedocs.org/user_builds/pillow/envs/latest/bin/pip install --use-wheel -U --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/pillow/.cache/pip Pygments==2.2.0 setuptools==28.8.0 docutils==0.13.1 mock==1.0.1 pillow==2.6.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.5.4 recommonmark==0.4.0 sphinx==1.5.3 sphinx-rtd-theme<0.3 readthedocs-sphinx-ext<0.6
Collecting Pygments==2.2.0
  Using cached Pygments-2.2.0-py2.py3-none-any.whl
Requirement already up-to-date: setuptools==28.8.0 in /home/docs/checkouts/readthedocs.org/user_builds/pillow/envs/latest/lib/python2.7/site-packages
Collecting docutils==0.13.1
  Using cached docutils-0.13.1-py2-none-any.whl
Requirement already up-to-date: mock==1.0.1 in /home/docs/checkouts/readthedocs.org/user_builds/pillow/envs/latest/lib/python2.7/site-packages
Collecting pillow==2.6.1
Collecting alabaster!=0.7.5,<0.8,>=0.7
  Using cached alabaster-0.7.10-py2.py3-none-any.whl
Requirement already up-to-date: commonmark==0.5.4 in /home/docs/checkouts/readthedocs.org/user_builds/pillow/envs/latest/lib/python2.7/site-packages
Requirement already up-to-date: recommonmark==0.4.0 in /home/docs/checkouts/readthedocs.org/user_builds/pillow/envs/latest/lib/python2.7/site-packages
Collecting sphinx==1.5.3
  Using cached Sphinx-1.5.3-py2.py3-none-any.whl
Collecting sphinx-rtd-theme<0.3
  Using cached sphinx_rtd_theme-0.2.4-py2.py3-none-any.whl
Requirement already up-to-date: readthedocs-sphinx-ext<0.6 in /home/docs/checkouts/readthedocs.org/user_builds/pillow/envs/latest/lib/python2.7/site-packages
Collecting six>=1.5 (from sphinx==1.5.3)
  Using cached six-1.11.0-py2.py3-none-any.whl
Collecting requests>=2.0.0 (from sphinx==1.5.3)
  Using cached requests-2.18.4-py2.py3-none-any.whl
Requirement already up-to-date: imagesize in /home/docs/checkouts/readthedocs.org/user_builds/pillow/envs/latest/lib/python2.7/site-packages (from sphinx==1.5.3)
Collecting babel!=2.0,>=1.3 (from sphinx==1.5.3)
  Using cached Babel-2.5.1-py2.py3-none-any.whl
Requirement already up-to-date: snowballstemmer>=1.1 in /home/docs/checkouts/readthedocs.org/user_builds/pillow/envs/latest/lib/python2.7/site-packages (from sphinx==1.5.3)
Collecting Jinja2>=2.3 (from sphinx==1.5.3)
  Using cached Jinja2-2.9.6-py2.py3-none-any.whl
Requirement already up-to-date: nilsimsa>=0.3.7 in /home/docs/checkouts/readthedocs.org/user_builds/pillow/envs/latest/lib/python2.7/site-packages (from readthedocs-sphinx-ext<0.6)
Requirement already up-to-date: urllib3<1.23,>=1.21.1 in /home/docs/checkouts/readthedocs.org/user_builds/pillow/envs/latest/lib/python2.7/site-packages (from requests>=2.0.0->sphinx==1.5.3)
Requirement already up-to-date: idna<2.7,>=2.5 in /home/docs/checkouts/readthedocs.org/user_builds/pillow/envs/latest/lib/python2.7/site-packages (from requests>=2.0.0->sphinx==1.5.3)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /home/docs/checkouts/readthedocs.org/user_builds/pillow/envs/latest/lib/python2.7/site-packages (from requests>=2.0.0->sphinx==1.5.3)
Requirement already up-to-date: certifi>=2017.4.17 in /home/docs/checkouts/readthedocs.org/user_builds/pillow/envs/latest/lib/python2.7/site-packages (from requests>=2.0.0->sphinx==1.5.3)
Collecting pytz>=0a (from babel!=2.0,>=1.3->sphinx==1.5.3)
  Using cached pytz-2017.2-py2.py3-none-any.whl
Collecting MarkupSafe>=0.23 (from Jinja2>=2.3->sphinx==1.5.3)
Installing collected packages: Pygments, docutils, pillow, alabaster, six, requests, pytz, babel, MarkupSafe, Jinja2, sphinx, sphinx-rtd-theme
  Found existing installation: Pygments 2.1.3
    Uninstalling Pygments-2.1.3:
      Successfully uninstalled Pygments-2.1.3
  Found existing installation: docutils 0.12
    Uninstalling docutils-0.12:
      Successfully uninstalled docutils-0.12
  Found existing installation: Pillow 4.3.0.dev0
    Uninstalling Pillow-4.3.0.dev0:
      Successfully uninstalled Pillow-4.3.0.dev0
  Found existing installation: alabaster 0.7.7
    Uninstalling alabaster-0.7.7:
      Successfully uninstalled alabaster-0.7.7
  Found existing installation: six 1.10.0
    Uninstalling six-1.10.0:
      Successfully uninstalled six-1.10.0
  Found existing installation: requests 2.9.1
    Uninstalling requests-2.9.1:
      Successfully uninstalled requests-2.9.1
  Found existing installation: pytz 2016.2
    Uninstalling pytz-2016.2:
      Successfully uninstalled pytz-2016.2
  Found existing installation: Babel 2.2.0
    Uninstalling Babel-2.2.0:
      Successfully uninstalled Babel-2.2.0
  Found existing installation: MarkupSafe 0.23
    Uninstalling MarkupSafe-0.23:
      Successfully uninstalled MarkupSafe-0.23
  Found existing installation: Jinja2 2.8
    Uninstalling Jinja2-2.8:
      Successfully uninstalled Jinja2-2.8
  Found existing installation: Sphinx 1.3.6
    Uninstalling Sphinx-1.3.6:
      Successfully uninstalled Sphinx-1.3.6
  Found existing installation: sphinx-rtd-theme 0.1.9
    Uninstalling sphinx-rtd-theme-0.1.9:
      Successfully uninstalled sphinx-rtd-theme-0.1.9
Successfully installed Jinja2-2.9.6 MarkupSafe-1.0 Pygments-2.2.0 alabaster-0.7.10 babel-2.5.1 docutils-0.13.1 pillow-2.6.1 pytz-2017.2 requests-2.18.4 six-1.11.0 sphinx-1.5.3 sphinx-rtd-theme-0.2.4
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pillow/envs/latest/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/home/docs/checkouts/readthedocs.org/user_builds/pillow/envs/latest/local/lib/python2.7/site-packages/pip/__init__.py", line 233, in main
    return command.main(cmd_args)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pillow/envs/latest/local/lib/python2.7/site-packages/pip/basecommand.py", line 252, in main
    pip_version_check(session)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pillow/envs/latest/local/lib/python2.7/site-packages/pip/utils/outdated.py", line 102, in pip_version_check
    installed_version = get_installed_version("pip")
  File "/home/docs/checkouts/readthedocs.org/user_builds/pillow/envs/latest/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 838, in get_installed_version
    working_set = pkg_resources.WorkingSet()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pillow/envs/latest/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 644, in __init__
    self.add_entry(entry)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pillow/envs/latest/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 700, in add_entry
    for dist in find_distributions(entry, True):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pillow/envs/latest/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1949, in find_eggs_in_zip
    if metadata.has_metadata('PKG-INFO'):
  File "/home/docs/checkouts/readthedocs.org/user_builds/pillow/envs/latest/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1463, in has_metadata
    return self.egg_info and self._has(self._fn(self.egg_info, name))
  File "/home/docs/checkouts/readthedocs.org/user_builds/pillow/envs/latest/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1823, in _has
    return zip_path in self.zipinfo or zip_path in self._index()
  File "/home/docs/checkouts/readthedocs.org/user_builds/pillow/envs/latest/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1703, in zipinfo
    return self._zip_manifests.load(self.loader.archive)
  File "/home/docs/checkouts/readthedocs.org/user_builds/pillow/envs/latest/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources/__init__.py", line 1643, in load
    mtime = os.stat(path).st_mtime
OSError: [Errno 2] No such file or directory: '/home/docs/checkouts/readthedocs.org/user_builds/pillow/envs/latest/local/lib/python2.7/site-packages/Pillow-4.3.0.dev0-py2.7-linux-x86_64.egg'
Command time: 25s Return: 1
```
https://readthedocs.org/projects/pillow/builds/6013268/

Here's the same step in a passing build:
```
python /home/docs/checkouts/readthedocs.org/user_builds/pillow/envs/latest/bin/pip install --use-wheel -U --cache-dir /home/docs/checkouts/readthedocs.org/user_builds/pillow/.cache/pip Pygments==2.2.0 setuptools==28.8.0 docutils==0.13.1 mock==1.0.1 pillow==2.6.1 alabaster>=0.7,<0.8,!=0.7.5 commonmark==0.5.4 recommonmark==0.4.0 sphinx==1.5.3 sphinx-rtd-theme<0.3 readthedocs-sphinx-ext<0.6
Collecting Pygments==2.2.0
  Downloading Pygments-2.2.0-py2.py3-none-any.whl (841kB)
Requirement already up-to-date: setuptools==28.8.0 in /home/docs/checkouts/readthedocs.org/user_builds/pillow/envs/latest/lib/python2.7/site-packages
Collecting docutils==0.13.1
  Downloading docutils-0.13.1-py2-none-any.whl (537kB)
Collecting mock==1.0.1
  Downloading mock-1.0.1.zip (861kB)
Collecting pillow==2.6.1
  Downloading Pillow-2.6.1.zip (7.5MB)
Collecting alabaster!=0.7.5,<0.8,>=0.7
  Downloading alabaster-0.7.10-py2.py3-none-any.whl
Collecting commonmark==0.5.4
  Downloading CommonMark-0.5.4.tar.gz (120kB)
Collecting recommonmark==0.4.0
  Downloading recommonmark-0.4.0-py2.py3-none-any.whl
Collecting sphinx==1.5.3
  Downloading Sphinx-1.5.3-py2.py3-none-any.whl (1.6MB)
Collecting sphinx-rtd-theme<0.3
  Downloading sphinx_rtd_theme-0.2.4-py2.py3-none-any.whl (1.4MB)
Collecting readthedocs-sphinx-ext<0.6
  Downloading readthedocs_sphinx_ext-0.5.5-py2.py3-none-any.whl
Collecting snowballstemmer>=1.1 (from sphinx==1.5.3)
  Downloading snowballstemmer-1.2.1-py2.py3-none-any.whl (64kB)
Collecting six>=1.5 (from sphinx==1.5.3)
  Downloading six-1.11.0-py2.py3-none-any.whl
Collecting imagesize (from sphinx==1.5.3)
  Downloading imagesize-0.7.1-py2.py3-none-any.whl
Collecting Jinja2>=2.3 (from sphinx==1.5.3)
  Downloading Jinja2-2.9.6-py2.py3-none-any.whl (340kB)
Collecting requests>=2.0.0 (from sphinx==1.5.3)
  Downloading requests-2.18.4-py2.py3-none-any.whl (88kB)
Collecting babel!=2.0,>=1.3 (from sphinx==1.5.3)
  Downloading Babel-2.5.1-py2.py3-none-any.whl (6.8MB)
Collecting nilsimsa>=0.3.7 (from readthedocs-sphinx-ext<0.6)
  Downloading nilsimsa-0.3.8.tar.gz (276kB)
Collecting MarkupSafe>=0.23 (from Jinja2>=2.3->sphinx==1.5.3)
  Downloading MarkupSafe-1.0.tar.gz
Collecting urllib3<1.23,>=1.21.1 (from requests>=2.0.0->sphinx==1.5.3)
  Downloading urllib3-1.22-py2.py3-none-any.whl (132kB)
Collecting idna<2.7,>=2.5 (from requests>=2.0.0->sphinx==1.5.3)
  Downloading idna-2.6-py2.py3-none-any.whl (56kB)
Collecting chardet<3.1.0,>=3.0.2 (from requests>=2.0.0->sphinx==1.5.3)
  Downloading chardet-3.0.4-py2.py3-none-any.whl (133kB)
Collecting certifi>=2017.4.17 (from requests>=2.0.0->sphinx==1.5.3)
  Downloading certifi-2017.7.27.1-py2.py3-none-any.whl (349kB)
Collecting pytz>=0a (from babel!=2.0,>=1.3->sphinx==1.5.3)
  Downloading pytz-2017.2-py2.py3-none-any.whl (484kB)
Building wheels for collected packages: mock, pillow, commonmark, nilsimsa, MarkupSafe
  Running setup.py bdist_wheel for mock: started
  Running setup.py bdist_wheel for mock: finished with status 'done'
  Stored in directory: /home/docs/checkouts/readthedocs.org/user_builds/pillow/.cache/pip/wheels/b2/f8/fe/920b7d3b279878045354cde14646f73864cf944501f19e4a1b
  Running setup.py bdist_wheel for pillow: started
  Running setup.py bdist_wheel for pillow: finished with status 'done'
  Stored in directory: /home/docs/checkouts/readthedocs.org/user_builds/pillow/.cache/pip/wheels/d0/3d/6f/4a3dbe290c7053073e6c32734c146d7174f2ad7675030b6137
  Running setup.py bdist_wheel for commonmark: started
  Running setup.py bdist_wheel for commonmark: finished with status 'done'
  Stored in directory: /home/docs/checkouts/readthedocs.org/user_builds/pillow/.cache/pip/wheels/fd/3a/ea/9ead7944d8ba3771888487ca4f6ef39bcde9fd4e986c32f442
  Running setup.py bdist_wheel for nilsimsa: started
  Running setup.py bdist_wheel for nilsimsa: finished with status 'done'
  Stored in directory: /home/docs/checkouts/readthedocs.org/user_builds/pillow/.cache/pip/wheels/77/f8/25/539c7b52ecbfcb7ed9b6c7189f9fdde48706c41fe529a64c9f
  Running setup.py bdist_wheel for MarkupSafe: started
  Running setup.py bdist_wheel for MarkupSafe: finished with status 'done'
  Stored in directory: /home/docs/checkouts/readthedocs.org/user_builds/pillow/.cache/pip/wheels/88/a7/30/e39a54a87bcbe25308fa3ca64e8ddc75d9b3e5afa21ee32d57
Successfully built mock pillow commonmark nilsimsa MarkupSafe
Installing collected packages: Pygments, docutils, mock, pillow, alabaster, commonmark, recommonmark, snowballstemmer, six, imagesize, MarkupSafe, Jinja2, urllib3, idna, chardet, certifi, requests, pytz, babel, sphinx, sphinx-rtd-theme, nilsimsa, readthedocs-sphinx-ext
Successfully installed Jinja2-2.9.6 MarkupSafe-1.0 Pygments-2.2.0 alabaster-0.7.10 babel-2.5.1 certifi-2017.7.27.1 chardet-3.0.4 commonmark-0.5.4 docutils-0.13.1 idna-2.6 imagesize-0.7.1 mock-1.0.1 nilsimsa-0.3.8 pillow-2.6.1 pytz-2017.2 readthedocs-sphinx-ext-0.5.5 recommonmark-0.4.0 requests-2.18.4 six-1.11.0 snowballstemmer-1.2.1 sphinx-1.5.3 sphinx-rtd-theme-0.2.4 urllib3-1.22
Command time: 29s Return: 0
```
https://readthedocs.org/projects/pillow/builds/6043884/

I triggered a build, it failed.

I switched the Python interpreter from "CPython 2.x to "CPython 3.x" (https://readthedocs.org/dashboard/pillow/advanced/) and triggered a build, it passed.

![image](https://user-images.githubusercontent.com/1324225/30956153-f61f4cc2-a43e-11e7-989c-370a0f4fbd90.png)


Let's see if that sorts it.

**Comment by wiredfool** [comment]
One thing that I noticed recently setting up a new dev vm is that a lot of the dependencies in the docs requirements are rather old -- I was getting errors with `make doc` until I just had pip upgrade everything.

**Comment by hugovk** [comment]
requirements.txt was frozen in March 2016 in https://github.com/python-pillow/Pillow/pull/1776.

https://github.com/python-pillow/Pillow/commits/master/requirements.txt

How about we just unfreeze it, like in PR https://github.com/python-pillow/Pillow/pull/2766?

**Comment by aclark4life** [comment]
For whatever it's worth, I occasionally unfreeze everything, install, then refreeze to upgrade all the packages. In fact, I think I'll add an unfreeze (i.e. replace everything past and include "==" to EOL with nothing) to my [project-makefile](https://github.com/aclark4life/project-makefile) to complement my freeze target (which I :heart:): https://github.com/aclark4life/project-makefile/blob/master/Makefile#L231

**Comment by radarhere** [comment]
I'd be interested in testing whether something like https://docs.readthedocs.io/en/latest/yaml-config.html#python-pip-install could solve this problem - but my personal ReadTheDocs account never experiences this problem. Is there a way to test out solutions to this aside from merging into master?

**Comment by hugovk** [comment]
It's worth a shot! 

Looks like we can configure which branches are built here:

https://readthedocs.org/dashboard/pillow/versions/

You can create a branch in this repo to experiment on.
