### ISSUE TITLE
Upgrade fails with "'NoneType' object is not callable"

### ISSUE THREAD

**Issue by iarspider** [python-pillow/Pillow#2819]
### What did you do?
Tried updating Pillow from 4.0.0 to 4.3.0 using `easy_install-2.7 -U pillow`

### What did you expect to happen?
Successful update.

### What actually happened?
```
Moving Pillow-4.3.0-py2.7-linux-x86_64.egg to /home/razumov/.virtualenvs/test_pillow/lib/python2.7/site-packages
Adding Pillow 4.3.0 to easy-install.pth file
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 366, in _handle_tasks
    debug('task handler got sentinel')
TypeError: 'NoneType' object is not callable

Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 330, in _handle_workers
    debug('worker handler exiting')
TypeError: 'NoneType' object is not callable

Exception TypeError: TypeError("'NoneType' object does not support item deletion",) in <Finalize object, dead> ignored
```

### What versions of Pillow and Python are you using?
Python 2.7.12, easy_install from setuptools 34.3.3, pillow was 4.0.0, upgrading to 4.3.0

**Comment by hugovk** [comment]
I can reproduce (macOS, Python 2.7.1, setuptools 36.6.0).

However, we recommend using pip instead. Please can you try that? Then it will use a prebuilt wheel rather than building an egg from source.

It's also a good idea to keep the tools updated:
```
pip install -U pip setuptools wheel
pip install -U pillow
```

https://pillow.readthedocs.io/en/4.3.x/installation.html

**Comment by iarspider** [comment]
Yup, that worked.
