### ISSUE TITLE
Cannot install Pillow on Devuan ARM

### ISSUE THREAD

**Issue by mittorn** [python-pillow/Pillow#3008]
### What did you do?
pip install pillow in virtualenv
virtualenv is set to /mnt/ext/synapse (for synapse setup)
### What did you expect to happen?
pillow installed
### What actually happened?
pillow cannot find zlib and libjpeg headers
### What versions of Pillow and Python are you using?
python-2.7, pillow-5.0.0
Please include **code** that reproduces the issue and whenever possible, an **image** that demonstrates the issue. Please upload images to GitHub, not to third-party file hosting sites. If necessary, add the image to a zip or tar archive.

The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as plone, Django, or buildout, try to replicate the issue just using Pillow. 
```
   Complete output from command /mnt/ext/synapse/bin/python2.7 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-eo9L5S/pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" build_ext --debug install --record /tmp/pip-vajx4J-record/install-record.txt --single-version-externally-managed --compile --install-headers /mnt/ext/synapse/include/site/python2.7/pillow:
    running build_ext
    Appending path /tmp/pip-build-eo9L5S/pillow/src/libImaging
    Appending path /mnt/ext/synapse/lib
    Appending path /mnt/ext/synapse/include
    Appending path /usr/local/lib
    Appending path /usr/local/include
    Appending path /usr/lib
    Appending path /usr/include
    Appending path /lib
    Looking for zlib
    Checking for include file zlib.h in /tmp/pip-build-eo9L5S/pillow/src/libImaging
    Checking for include file zlib.h in /mnt/ext/synapse/include
    Checking for include file zlib.h in /usr/local/include
    Checking for include file zlib.h in /usr/include
    Found zlib.h
    Couldn't find library z in ['/mnt/ext/synapse/lib', '/usr/local/lib', '/usr/lib', '/lib']
    Looking for jpeg
    Checking for include file jpeglib.h in /tmp/pip-build-eo9L5S/pillow/src/libImaging
    Checking for include file jpeglib.h in /mnt/ext/synapse/include
    Checking for include file jpeglib.h in /usr/local/include
    Checking for include file jpeglib.h in /usr/include
    Found jpeglib.h
    Couldn't find library jpeg in ['/mnt/ext/synapse/lib', '/usr/local/lib', '/usr/lib', '/lib']
    Looking for jpeg2000
    Checking for openjpeg-#.# in /tmp/pip-build-eo9L5S/pillow/src/libImaging
    Checking for openjpeg-#.# in /mnt/ext/synapse/include
    Checking for openjpeg-#.# in /usr/local/include
    Checking for openjpeg-#.# in /usr/include
    Checking for openjpeg-#.# in /usr/include/python2.7
    Looking for imagequant
    Checking for include file libimagequant.h in /tmp/pip-build-eo9L5S/pillow/src/libImaging
    Checking for include file libimagequant.h in /mnt/ext/synapse/include
    Checking for include file libimagequant.h in /usr/local/include
    Checking for include file libimagequant.h in /usr/include
    Checking for include file libimagequant.h in /usr/include/python2.7
    Looking for tiff
    Checking for include file tiff.h in /tmp/pip-build-eo9L5S/pillow/src/libImaging
    Checking for include file tiff.h in /mnt/ext/synapse/include
    Checking for include file tiff.h in /usr/local/include
    Checking for include file tiff.h in /usr/include
    Checking for include file tiff.h in /usr/include/python2.7
    Looking for freetype
    Couldn't find library freetype in ['/mnt/ext/synapse/lib', '/usr/local/lib', '/usr/lib', '/lib']
    Looking for lcms
    Checking for include file lcms2.h in /tmp/pip-build-eo9L5S/pillow/src/libImaging
    Checking for include file lcms2.h in /mnt/ext/synapse/include
    Checking for include file lcms2.h in /usr/local/include
    Checking for include file lcms2.h in /usr/include
    Checking for include file lcms2.h in /usr/include/python2.7
    Looking for webp
    Checking for include file webp/encode.h in /tmp/pip-build-eo9L5S/pillow/src/libImaging
    Checking for include file webp/encode.h in /mnt/ext/synapse/include
    Checking for include file webp/encode.h in /usr/local/include
    Checking for include file webp/encode.h in /usr/include
    Checking for include file webp/encode.h in /usr/include/python2.7
    Looking for webpmux
    Checking for include file webp/mux.h in /tmp/pip-build-eo9L5S/pillow/src/libImaging
    Checking for include file webp/mux.h in /mnt/ext/synapse/include
    Checking for include file webp/mux.h in /usr/local/include
    Checking for include file webp/mux.h in /usr/include
    Checking for include file webp/mux.h in /usr/include/python2.7


    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-eo9L5S/pillow/setup.py", line 804, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:

    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    ----------------------------------------
```
I do not know, is this virtualenv or pillow bug, but virtualenv does not seems to change ld-library-path.
libraries are actually are in /lib/<arch> and /usr/lib/<arch>
temporary workaround is simlinking required libraries to /usr/local/lib

**Comment by wiredfool** [comment]
I don't think virtualenvs ever change the LD_LIBRARY_PATH, though you could edit the activate script to make it happen that way. 

Looking at the trace, it is looking for libz and libjpeg in /lib and /usr/lib, but doesn't appear to be finding them for some reason. Can you check that they're actually there?

How different is devuan from Debian? I know that there were some changes recently that fixed arm builds on Debian, they may be applicable to your situation.

**Comment by mittorn** [comment]
Debian-based distros uses something like /usr/lib/arm-linux-gnueabihf and libz, libjpeg not present in /lib and /usr/lib

**Comment by radarhere** [comment]
Note that Python 2.7 is no longer supported by Pillow, in favour of Python 3.

**Comment by radarhere** [comment]
Consider that ASCII is based on Stretch, this is conceivably related to #3462

**Comment by radarhere** [comment]
Have you tried installing zlib1g-dev?

**Comment by radarhere** [comment]
Running Devuan Ascii in VirtualBox on a 64-bit Intel, I was able to install Pillow with just

```
sudo apt-get update
sudo apt-get install python-pip
sudo apt-get install zlib1g-dev libjpeg62-turbo-dev
python -m pip install pillow --no-binary :all:
```

Before I ran `sudo apt-get install zlib1g-dev libjpeg62-turbo-dev`, zlib.h and jpeglib.h were not present on the filesystem, and Pillow did not install.

After, they were present at /usr/include/zlib.h and /usr/include/jpeglib.h and Pillow was able to install.
