### ISSUE TITLE
Cannot get PIL.ImageFont.PIL.ImageFont.ImageFont.getmask with libraqm

### ISSUE THREAD

**Issue by eroux** [python-pillow/Pillow#3054]
### What did you do?

I tried to add some text in an image using OpenType features

### What did you expect to happen?

I expected pillow to typeset the text with the asked OpenType features

### What actually happened?

An error in the call to `PIL.ImageFont.PIL.ImageFont.ImageFont.getmask`:

```txt
KeyError: 'setting text direction or font features is not supported without libraqm'
```

### What versions of Pillow and Python are you using?

I've just installed the latest Pillow with:

```
# pip3 install PIllow
```

I'm under an up-to-date Debian stable. I have the latest version of libraqm. Python is Debian stable's `Python 3.5.3`.

The strange thing is that I can use libraqm as a layout engine in other Pillow calls:

```python
from PIL import Image, ImageDraw, ImageFont

img = Image.new('RGB', (800, 300), color = (73, 109, 137))
d = ImageDraw.Draw(img)
fnt = ImageFont.truetype('NotoSansTibetan-Regular.ttf', 24, layout_engine=ImageFont.LAYOUT_RAQM)
d.text((10, 10), "༄༅། །སྒྲུབ།", font=fnt, fill=(255, 255, 0))
img.save('result.png')
```

works just fine (and doesn't if I don't have raqm installed), while:

```python
from PIL import Image, ImageDraw, ImageFont

fnt = ImageFont.truetype('NotoSansTibetan-Regular.ttf', 24, layout_engine=ImageFont.LAYOUT_RAQM)
res = fnt.getmask("༄༅། །སྒྲུབ།", features=['ccmp', 'abvs', 'blws', 'calt', 'liga', 'kern', 'abvm', 'blwm', 'mkmk'])
```

gives me:

```txt
Traceback (most recent call last):
  File "testmarchepas.py", line 4, in <module>
    res = fnt.getmask("༄༅། །སྒྲུབ།", features=['ccmp', 'abvs', 'blws', 'calt', 'liga', 'kern', 'abvm', 'blwm', 'mkmk'])
  File "/usr/local/lib/python3.5/dist-packages/PIL/ImageFont.py", line 163, in getmask
    return self.getmask2(text, mode, direction=direction, features=features)[0]
  File "/usr/local/lib/python3.5/dist-packages/PIL/ImageFont.py", line 166, in getmask2
    size, offset = self.font.getsize(text, direction, features)
KeyError: 'setting text direction or font features is not supported without libraqm'
```

**Comment by wiredfool** [comment]
What version of Pillow are you running, and does it think that it has access to libraqm?

```
from PIL import Image, features
print(features.check('raqm'))
print(Image.PILLOW_VERSION)
```

**Comment by eroux** [comment]
I guess there was some path update that didn't take place in my last attempt, you script gives:

```
True
5.0.0
```

the previously failing script is still failing but with a different message:

```
Traceback (most recent call last):
  File "testmarchepas.py", line 8, in <module>
    d.text((10, 10), "༄༅། །སྒྲུབ།", font=fnt, fill=(255, 255, 0))
  File "/usr/local/lib/python3.5/dist-packages/PIL/ImageDraw.py", line 220, in text
    mask, offset = font.getmask2(text, self.fontmode, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/PIL/ImageFont.py", line 166, in getmask2
    size, offset = self.font.getsize(text, direction, features)
OSError: invalid face handle
Erreur de segmentation
```

so I guess this issue can be closed and I'll open a new one if I can't fix this new error. Thanks and sorry for the noise!
