### ISSUE TITLE
OSError: cannot identify image file <io.BytesIO object>

### ISSUE THREAD

**Issue by jkarimi91** [python-pillow/Pillow#3104]
Trying to simulate opening an image which has been sent as a base64 encoded string but I keep getting an `OSError: cannot identify image file <_io.BytesIO object at 0x7f21f23c3830>`.

python version: 3.6.5
pillow version: 5.1.0

code:
```python
from PIL import Image
from io import BytesIO
import base64


# Convert img to base64 encoded utf-8 string
img = Image.open('test.jpg')
img_buffer = BytesIO()
img.save(img_buffer, format='JPEG')
img_b64 = str(base64.b64encode(img_buffer.getvalue()))

# Convert string back to original img
img_buffer = BytesIO(base64.b64decode(img_b64.encode()))
img = Image.open(img_buffer)
```

traceback:
```python
/home/jkarimi91/Apps/miniconda2/envs/gender/bin/python /home/jkarimi91/Projects/doppler/example-app-gender/pil_error.py
Traceback (most recent call last):
  File "/home/jkarimi91/Projects/doppler/example-app-gender/pil_error.py", line 15, in <module>
    img = Image.open(img_buffer)
  File "/home/jkarimi91/Apps/miniconda2/envs/gender/lib/python3.6/site-packages/PIL/Image.py", line 2590, in open
    % (filename if filename else fp))
OSError: cannot identify image file <_io.BytesIO object at 0x7fb1670ba410>
```

**Comment by jkarimi91** [comment]
found the issue, calling `str` converts the bytes to ascii not utf-8; change `img_b64` to:
```python
img_b64 = base64.b64encode(img_buffer.getvalue()).decode()
```
