### ISSUE TITLE
BEE2 crashes with ModuleNotFoundError

### ISSUE THREAD

**Issue by slawekwaga** [python-pillow/Pillow#3240]
I'm using Linux Manjaro 17.
Compilation went all fine.
Running Bee2 executable produces this log: 
```
Traceback (most recent call last):
  File "/home/slawomir/BEE2.4/src/img.py", line 194, in color_square
    return cached_squares[key]
KeyError: (0.0, 0.0, 0.0, 64)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/slawomir/.local/share/virtualenvs/src-W1pAgXMY/lib/python3.6/site-packages/PIL/ImageTk.py", line 188, in paste
    tk.call("PyImagingPhoto", self.__photo, block.id)
_tkinter.TclError: invalid command name "PyImagingPhoto"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/slawomir/.local/share/virtualenvs/src-W1pAgXMY/lib/python3.6/site-packages/cx_Freeze/initscripts/__startup__.py", line 14, in run
    module.run()
  File "/home/slawomir/.local/share/virtualenvs/src-W1pAgXMY/lib/python3.6/site-packages/cx_Freeze/initscripts/Console.py", line 26, in run
    exec(code, m.__dict__)
  File "BEE2_launch.pyw", line 17, in <module>
  File "/home/slawomir/BEE2.4/src/BEE2.py", line 9, in <module>
    import tk_tools
  File "/home/slawomir/BEE2.4/src/tk_tools.py", line 64, in <module>
    import img
  File "/home/slawomir/BEE2.4/src/img.py", line 222, in <module>
    BLACK_64 = color_square(Vec(0, 0, 0), size=64)
  File "/home/slawomir/BEE2.4/src/img.py", line 201, in color_square
    tk_img = ImageTk.PhotoImage(image=img)
  File "/home/slawomir/.local/share/virtualenvs/src-W1pAgXMY/lib/python3.6/site-packages/PIL/ImageTk.py", line 127, in __init__
    self.paste(image)
  File "/home/slawomir/.local/share/virtualenvs/src-W1pAgXMY/lib/python3.6/site-packages/PIL/ImageTk.py", line 192, in paste
    from . import _imagingtk
  File "ExtensionLoader_PIL__imagingtk.py", line 23, in <module>
  File "ExtensionLoader_PIL__imagingtk.py", line 15, in __bootstrap__
  File "/home/slawomir/.local/share/virtualenvs/src-W1pAgXMY/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ModuleNotFoundError: No module named 'PIL._tkinter_finder'
```

**Comment by slawekwaga** [comment]
Closing as it's not related to pillow directly
