### ISSUE TITLE
Failing to compile with py2app (badly compiled libtiff.5.dylib)

### ISSUE THREAD

**Issue by peircej** [python-pillow/Pillow#3297]
### What did you do?

Run py2app on an application containing PIL (with in the setup packages list)

### What actually happened?

Fails due to the libtiff.5.dylib lib being compiled on mac without the flag `-headerpad_max_install_names`

See https://bitbucket.org/ronaldoussoren/py2app/issues/219/new-mach-o-header-is-too-large-to-relocate for further info about the general problem

error: 
```
WARNING: Mach-O header in '/Users/lpzjwp/code/psychopy/git/dist/PsychoPy3.app/Contents/Resources/lib/python2.7/PIL/.dylibs/libtiff.5.dylib' may be too large to relocate
Traceback (most recent call last):
  File "setupApp.py", line 134, in <module>
    CFBundleTypeRole='Editor')],
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/py2app/build_app.py", line 825, in run
    self._run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/py2app/build_app.py", line 1040, in _run
    self.run_normal()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/py2app/build_app.py", line 1152, in run_normal
    self.create_binaries(py_files, pkgdirs, extensions, loader_files)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/py2app/build_app.py", line 1512, in create_binaries
    platfiles = mm.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/macholib/MachOStandalone.py", line 146, in run
    node.write(f)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/macholib/MachO.py", line 133, in write
    header.write(f)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/macholib/MachO.py", line 343, in write
    self.synchronize_size()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/macholib/MachO.py", line 333, in synchronize_size
    self.parent.filename, self.total_size + self.sizediff, self.low_offset, self.sizediff))
ValueError: New Mach-O header is too large to relocate in '/Users/lpzjwp/code/psychopy/git/dist/PsychoPy3.app/Contents/Resources/lib/python2.7/PIL/.dylibs/libtiff.5.dylib' (new size=2072L, max size=2016L, delta=168L)
setupApp.py failed
```

### What versions of Pillow and Python are you using?
PIL 5.2
Python 2.7

**Comment by peircej** [comment]
Just confirmed that this occurs on Py3.6 installation of PIL5.2 as well

**Comment by radarhere** [comment]
Hi. A few questions -
- What version of macOS are you running?
- What version of py2app are you running?
- What method did you use to install Pillow? pip, etc.?
- You say that this fails due to libtiff being compiled without `-headerpad_max_install_names`. Is there a reason that you can't use that option, or are you just interested in seeing this problem solved?
- Just so I understand, why do you feel this is a Pillow issue? It sounds to me so far like a py2app issue.

**Comment by peircej** [comment]
>> You say that this fails due to libtiff being compiled without -headerpad_max_install_names. Is there a reason that you can't use that option, or are you just interested in seeing this problem solved?
> - Yes, I can make it work fine by manually compiling on my own machine.

Ah, I was wrong about this. It turns out that the build I was making was dynamically linked to the local dylibs so failed on other machines where those were different or not installed. What's the mechanism you have for bundling your libs into your wheel? Is there a flag I can set somewhere?

**Comment by radarhere** [comment]
The [pillow-wheels](https://github.com/python-pillow/pillow-wheels) repo uses the [multibuild](https://github.com/matthew-brett/multibuild) command `build_wheel` - https://github.com/python-pillow/pillow-wheels/blob/master/.travis.yml#L103

The `build_wheel` function is defined at https://github.com/matthew-brett/multibuild/blob/devel/common_utils.sh#L264. I suspect the line that you would be interested in is https://github.com/matthew-brett/multibuild/blob/devel/common_utils.sh#L239 - `pip wheel $(pip_opts) -w $abs_wheelhouse --no-deps .`

**Comment by ronaldoussoren** [comment]
I think I can fix this on my side, and that should fix this for everyone that ships wheels using a similar toolset.  

Problem is that p2yapp tries to fix MachO load headers that don't need to be fixed because the extensions and shared libraries shipped in the wheel are already relocatable.

**Comment by peircej** [comment]
Ah @ronaldoussoren that's great if it can be fixed in py2app instead. That is definitely preferable if it's possible! (This is the 3rd time it's cropped up in some wheel or other that I include) :-)

**Comment by radarhere** [comment]
@peircej in the py2app thread, this issue is said to have been fixed in macholib. So is this now resolved for you?

**Comment by peircej** [comment]
Yes, we can close this now. Thanks

null
