### ISSUE TITLE
thumbnail(64) dies with TypeError: 'int' object has no attribute '__getitem__'

### ISSUE THREAD

**Issue by raould** [python-pillow/Pillow#3302]
### What did you do?
tried to convert this image from jpg to rgb to thumbnail.
![part1](https://user-images.githubusercontent.com/77176/43998940-3876dba0-9db6-11e8-8e5e-5d1c4ea6a6fe.jpg)

### What did you expect to happen?
no exception

### What actually happened?
exception

### What versions of Pillow and Python are you using?
pillow 5.1.0
python 2.7.12
Linux lamachine 4.4.0-130-generic #156-Ubuntu SMP Thu Jun 14 08:53:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

```
$ python
Python 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
>>> i = Image.open("/home/xyzpdq/Downloads/part1.jpg")
>>> i = i.convert("RGB")
>>> i
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=692x551 at 0x7F2E0D340410>
>>> i.thumbnail(64)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 2060, in thumbnail
    if x > size[0]:
TypeError: 'int' object has no attribute '__getitem__'
>>> import PIL
>>> PIL.PILLOW_VERSION
'5.1.0'
```

**Comment by raould** [comment]
oh. the size argument i have to supply has to be (width, height) tuple, not a single int. figured that out by looking a the code ha ha. >>> i
<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=692x551 at 0x7F2E0D340410>
