### ISSUE TITLE
Failing to convert png to jpeg2000

### ISSUE THREAD

**Issue by bagipriyank** [python-pillow/Pillow#3330]
### What did you do?
Trying to convert a png to jpeg2000

### What did you expect to happen?
successful conversion of file 

### What actually happened?
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PIL/Image.py", line 1698, in save
    save_handler(self, fp, filename)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PIL/Jpeg2KImagePlugin.py", line 264, in _save
    ImageFile._save(im, fp, [('jpeg2k', (0, 0)+im.size, 0, kind)])
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PIL/ImageFile.py", line 500, in _save
    raise IOError("encoder error %d when writing image file" % s)
IOError: encoder error -2 when writing image file
```

### What versions of Pillow and Python are you using?
```
>>> PIL.PILLOW_VERSION
'3.4.2'
>>> PIL.VERSION
'1.1.7'
```

```
pbagrecha-mpb15:~$ python --version
Python 2.7.13
```

### Code that reproduces the issue
```
Python 2.7.13 (default, Apr  4 2017, 08:47:57)
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
>>> Image.open('image.png').save('image.jp2', 'JPEG2000', quality_mode='dB', quality_layers=[41])
```

Attaching the image with which I am facing this issue
![image](https://user-images.githubusercontent.com/3229967/45058401-76fc0b80-b04d-11e8-94af-2e20a0dd3acd.png)

I was able to convert the same image to jpeg2000 using an online tool.

**Comment by radarhere** [comment]
While this is not necessarily the direct cause of the issue, I note that the image is in P mode. Converting it to RGBA, the following code runs without crashing -
```
from PIL import Image
im = Image.open('image.png')
im.convert("RGBA").save('image.jp2', 'JPEG2000', quality_mode='dB', quality_layers=[41])
```

**Comment by bagipriyank** [comment]
From: https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#jpeg-2000
```
PIL reads and writes JPEG 2000 files containing L, LA, RGB or RGBA data. It can also read files containing YCbCr data, which it converts on read into RGB or RGBA depending on whether or not there is an alpha channel. PIL supports JPEG 2000 raw codestreams (.j2k files), as well as boxed JPEG 2000 files (.j2p or .jpx files). PIL does not support files whose components have different sampling frequencies.
```

So this is working as intended.
