### ISSUE TITLE
Cannot save TIFF with big-endian byte order

### ISSUE THREAD

**Issue by okdzhimiev** [python-pillow/Pillow#3332]
How to save (multi-)page tiff in big-endian byte order (MM) instead of little-endian (II)?

I am trying to generate a multi-page TIFF file for ImageJ. The files generated by ImageJ are big-endian, while Pillow saves in little-endian - so when opening with ImageJ it just reads reversed 'magic' numbers from its custom tag which is 50839 (accompanied by 50838). I can work around this but it leads to another problem related to Pillow duplicating TIFF header for each image of the stack - don't know if it's a bug or not yet.

Tried:
```python
for i in range(N):
    im = Image.fromarray(imgs[i])
im[0].mode = "F;32BF"
im[0].save("result.tiff",save_all=True,append_images=imlist[1:],tiffinfo=someIFD)
```
Getting:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/PIL/ImageFile.py", line 477, in _save
    fh = fp.fileno()
AttributeError: 'AppendingTiffWriter' object has no attribute 'fileno'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "imagej_tiffwriter_test.py", line 237, in <module>
    imlist[0].save("result.tiff",save_all=True,append_images=imlist[1:],tiffinfo=__get_IJ_IFD(NT,NZ,NC))
  File "/usr/local/lib/python3.5/dist-packages/PIL/Image.py", line 1935, in save
    save_handler(self, fp, filename)
  File "/usr/local/lib/python3.5/dist-packages/PIL/TiffImagePlugin.py", line 1814, in _save_all
    _save(ims, tf, filename)
  File "/usr/local/lib/python3.5/dist-packages/PIL/TiffImagePlugin.py", line 1541, in _save
    ("raw", (0, 0)+im.size, offset, (rawmode, stride, 1))
  File "/usr/local/lib/python3.5/dist-packages/PIL/ImageFile.py", line 482, in _save
    e = Image._getencoder(im.mode, e, a, im.encoderconfig)
  File "/usr/local/lib/python3.5/dist-packages/PIL/Image.py", line 459, in _getencoder
    return encoder(mode, *args + extra)
ValueError: No packer found from F;32BF to F;32BF
```

Workaround (5 images in stack):
  for BE: ijmagic = b'IJIJinfo\x00\x00\x00\x01labl\x00\x00\x00\x05'
  for LE: ijmagic = b'JIJIofni\x01\x00\x00\x00lbal\x05\x00\x00\x00'

\>\>\> PIL.\_\_version__
'5.1.0'
\>\>\> Image.VERSION
'1.1.7'

Thanks

**Comment by okdzhimiev** [comment]
Actually, made it work using little-endian. Nevermind.
Helper function from **tifffile.py**:
```python
def imagej_metadata_tags(metadata, byteorder):
    """Return IJMetadata and IJMetadataByteCounts tags from metadata dict.

    The tags can be passed to the TiffWriter.save function as extratags.

    """
    header = [{'>': b'IJIJ', '<': b'JIJI'}[byteorder]]
    bytecounts = [0]
    body = []

    def writestring(data, byteorder):
        return data.encode('utf-16' + {'>': 'be', '<': 'le'}[byteorder])

    def writedoubles(data, byteorder):
        return struct.pack(byteorder+('d' * len(data)), *data)

    def writebytes(data, byteorder):
        return data.tobytes()

    metadata_types = (
        ('Info', b'info', 1, writestring),
        ('Labels', b'labl', None, writestring),
        ('Ranges', b'rang', 1, writedoubles),
        ('LUTs', b'luts', None, writebytes),
        ('Plot', b'plot', 1, writebytes),
        ('ROI', b'roi ', 1, writebytes),
        ('Overlays', b'over', None, writebytes))

    for key, mtype, count, func in metadata_types:
        if key not in metadata:
            continue
        if byteorder == '<':
            mtype = mtype[::-1]
        values = metadata[key]
        if count is None:
            count = len(values)
        else:
            values = [values]
        header.append(mtype + struct.pack(byteorder+'I', count))
        for value in values:
            data = func(value, byteorder)
            body.append(data)
            bytecounts.append(len(data))

    body = b''.join(body)
    header = b''.join(header)
    data = header + body
    bytecounts[0] = len(header)
    bytecounts = struct.pack(byteorder+('I' * len(bytecounts)), *bytecounts)
    return ((50839, 'B', len(data), data, True),
            (50838, 'I', len(bytecounts)//4, bytecounts, True))
```

The next problem-in-line was Pillow saving IFDs in the beginning of pages (which is fine) while ImageJ reader wanted [IFD[0] is in the beginning of the file, and IFD[1:] are stacked in the end of the file](https://github.com/imagej/imagej/issues/213). The solution was to switch to **tifffile** - it has ImageJ-specific modifications.

**Comment by okdzhimiev** [comment]
[imagej_tiffwriter.py](https://git.elphel.com/Elphel/python3-imagej-tiff/blob/master/imagej_tiffwriter.py)
