### ISSUE TITLE
Cannot read TIFF file

### ISSUE THREAD

**Issue by gabdube** [python-pillow/Pillow#3536]
### What did you do?
Generated cubemaps in a .TIFF format
Tried to read the output with Pillow

### What did you expect to happen?
I expected to be able to read the file.

### What actually happened?
Got a `ValueError: seek of closed file`. See my code sample just below.

### What are your OS, Python and Pillow versions?

* OS: Linux / Ubuntu 16.10
* Python: 3.7.1
* Pillow: 5.4.0

### Other notes
* I have libtiff installed
* I have tried to open a reference file from https://www.fileformat.info/format/tiff/sample/index.htm and it works fine (its included in the zip)

```
>>> from PIL import Image
>>> Image.open('irr_cubemap.tiff')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gab/.pyenv/versions/3.7.1/lib/python3.7/site-packages/PIL/Image.py", line 2672, in open
    im = _open_core(fp, filename, prefix)
  File "/home/gab/.pyenv/versions/3.7.1/lib/python3.7/site-packages/PIL/Image.py", line 2657, in _open_core
    fp.seek(0)
ValueError: seek of closed file
```

Files:
[tmp.zip](https://github.com/python-pillow/Pillow/files/2725290/tmp.zip)

**Comment by cgohlke** [comment]
I don't think PIL can handle float32 RGB images.

Besides that, it seems the TiffImagePlugin closes file handles that it does not own.

This might work:
```diff
diff --git a/src/PIL/Image.py b/src/PIL/Image.py
index 092cc804..2868953a 100644
--- a/src/PIL/Image.py
+++ b/src/PIL/Image.py
@@ -611,12 +611,12 @@ class Image(object):

     if sys.version_info.major >= 3:
         def __del__(self):
-            if (hasattr(self, 'fp') and hasattr(self, '_exclusive_fp')
-               and self.fp and self._exclusive_fp):
-                self.fp.close()
-            self.fp = None
-            if hasattr(self, "_close__fp"):
-                self._close__fp()
+            if hasattr(self, '_exclusive_fp') and self._exclusive_fp:
+                if hasattr(self, 'fp') and self.fp:
+                    self.fp.close()
+                    self.fp = None
+                if hasattr(self, "_close__fp"):
+                    self._close__fp()

     def _copy(self):
         self.load()
```

**Comment by radarhere** [comment]
The `ValueError: seek of closed file` error has now been fixed in #3540.

**Comment by radarhere** [comment]
Are you happy for the rest of this to be considered part of #1888, and for this issue to be closed?
