### ISSUE TITLE
'OSError: cannot identify image file' when opening large TIF file

### ISSUE THREAD

**Issue by anpr** [python-pillow/Pillow#3815]
### What did you do?

I tried to open [this large TIF file](https://umg-public-image-bucket.s3-eu-west-1.amazonaws.com/alp-1978-big-tif.tif) with Pillow 6.0.0 in the following way:
`image = Image.open(input_path)`

### What did you expect to happen?

No exception. And later I want to able to create thumbnails from the image.

### What actually happened?

An exception was thrown: 
`OSError: cannot identify image file '/code/assets/lib/tests/test_data/alp-1978-big-tif.tif'
`

### What are your OS, Python and Pillow versions?

* OS: Inside a Docker container, Debian stretch 9
* Python: Python 3.6.7
* Pillow: 6.0.0

This is possibly related to https://github.com/python-pillow/Pillow/issues/3372

**Comment by hugovk** [comment]
Debugging like this:

```diff
diff --git a/src/PIL/Image.py b/src/PIL/Image.py
index 18121c6f..476187da 100644
--- a/src/PIL/Image.py
+++ b/src/PIL/Image.py
@@ -2680,6 +2680,8 @@ def open(fp, mode="r"):
                 # Leave disabled by default, spams the logs with image
                 # opening failures that are entirely expected.
                 # logger.debug("", exc_info=True)
+                if i == "TIFF":
+                    raise
                 continue
             except BaseException:
                 if exclusive_fp:
diff --git a/src/PIL/TiffImagePlugin.py b/src/PIL/TiffImagePlugin.py
index 44dde199..6f37241e 100644
--- a/src/PIL/TiffImagePlugin.py
+++ b/src/PIL/TiffImagePlugin.py
@@ -69,7 +69,7 @@ except ImportError:
 # __version__ is deprecated and will be removed in a future version. Use
 # PIL.__version__ instead.
 __version__ = "1.3.5"
-DEBUG = False  # Needs to be merged with the new logging approach.
+DEBUG = True  # Needs to be merged with the new logging approach.

 # Set these to true to force use of libtiff for reading or writing.
 READ_LIBTIFF = False
```

Gives this:
```
*** TiffImageFile._open ***
- __first: 8
- ifh:  b'II*\x00\x08\x00\x00\x00'
Seeking to frame 0, on frame -1, __next 8, location: 8
Loading tags, location: 8
tag: NewSubfileType (254) - type: long (4) - value: 0
tag: ImageWidth (256) - type: short (3) - value: 1348
tag: ImageLength (257) - type: short (3) - value: 1989
tag: BitsPerSample (258) - type: short (3) Tag Location: 58 - Data Location: 302 - value: (16, 16, 16, 16)
tag: Compression (259) - type: short (3) - value: 5
tag: PhotometricInterpretation (262) - type: short (3) - value: 5
tag: ImageDescription (270) - type: string (2) Tag Location: 94 - Data Location: 310 - value: S_ 063
tag: StripOffsets (273) - type: long (4) Tag Location: 106 - Data Location: 318 - value: <table: 332 bytes>
tag: Orientation (274) - type: short (3) - value: 1
tag: SamplesPerPixel (277) - type: short (3) - value: 4
tag: RowsPerStrip (278) - type: short (3) - value: 24
tag: StripByteCounts (279) - type: long (4) Tag Location: 154 - Data Location: 650 - value: <table: 332 bytes>
tag: XResolution (282) - type: rational (5) Tag Location: 166 - Data Location: 982 - value: 300.0
tag: YResolution (283) - type: rational (5) Tag Location: 178 - Data Location: 990 - value: 300.0
tag: PlanarConfiguration (284) - type: short (3) - value: 1
tag: ResolutionUnit (296) - type: short (3) - value: 2
tag: Software (305) - type: string (2) Tag Location: 214 - Data Location: 998 - value: Adobe Photoshop CC (Macintosh)
tag: DateTime (306) - type: string (2) Tag Location: 226 - Data Location: 1030 - value: 2019:03:25 17:51:38
tag: Artist (315) - type: string (2) Tag Location: 238 - Data Location: 1050 - value: Scanner
tag: XMP (700) - type: undefined (7) Tag Location: 250 - Data Location: 1060 - value: <table: 16780 bytes>
tag: IptcNaaInfo (33723) - type: undefined (7) Tag Location: 262 - Data Location: 17840 - value: <table: 68 bytes>
tag: PhotoshopInfo (34377) - type: undefined (7) Tag Location: 274 - Data Location: 17924 - value: <table: 7786 bytes>
tag: ExifIFD (34665) - type: long (4) - value: 29666400
tag: ICCProfile (34675) - type: undefined (7) Tag Location: 298 - Data Location: 25710 - value: <table: 1829093 bytes>
tag: NewSubfileType (254) - type: long (4) - value: 0
tag: ImageWidth (256) - type: short (3) - value: 1348
tag: ImageLength (257) - type: short (3) - value: 1989
tag: BitsPerSample (258) - type: short (3) Tag Location: 58 - Data Location: 302 - value: (16, 16, 16, 16)
tag: Compression (259) - type: short (3) - value: 5
tag: PhotometricInterpretation (262) - type: short (3) - value: 5
tag: ImageDescription (270) - type: string (2) Tag Location: 94 - Data Location: 310 - value: S_ 063
tag: StripOffsets (273) - type: long (4) Tag Location: 106 - Data Location: 318 - value: <table: 332 bytes>
tag: Orientation (274) - type: short (3) - value: 1
tag: SamplesPerPixel (277) - type: short (3) - value: 4
tag: RowsPerStrip (278) - type: short (3) - value: 24
tag: StripByteCounts (279) - type: long (4) Tag Location: 154 - Data Location: 650 - value: <table: 332 bytes>
tag: XResolution (282) - type: rational (5) Tag Location: 166 - Data Location: 982 - value: 300.0
tag: YResolution (283) - type: rational (5) Tag Location: 178 - Data Location: 990 - value: 300.0
tag: PlanarConfiguration (284) - type: short (3) - value: 1
tag: ResolutionUnit (296) - type: short (3) - value: 2
tag: Software (305) - type: string (2) Tag Location: 214 - Data Location: 998 - value: Adobe Photoshop CC (Macintosh)
tag: DateTime (306) - type: string (2) Tag Location: 226 - Data Location: 1030 - value: 2019:03:25 17:51:38
tag: Artist (315) - type: string (2) Tag Location: 238 - Data Location: 1050 - value: Scanner
tag: XMP (700) - type: undefined (7) Tag Location: 250 - Data Location: 1060 - value: <table: 16780 bytes>
tag: IptcNaaInfo (33723) - type: undefined (7) Tag Location: 262 - Data Location: 17840 - value: <table: 68 bytes>
tag: PhotoshopInfo (34377) - type: undefined (7) Tag Location: 274 - Data Location: 17924 - value: <table: 7786 bytes>
tag: ExifIFD (34665) - type: long (4) - value: 29666400
tag: ICCProfile (34675) - type: undefined (7) Tag Location: 298 - Data Location: 25710 - value: <table: 1829093 bytes>
*** Summary ***
- compression: tiff_lzw
- photometric_interpretation: 5
- planar_configuration: 1
- fill_order: 1
- YCbCr subsampling: None
- size: (1348, 1989)
format key: (b'II', 5, (1,), 1, (16, 16, 16, 16), ())
- unsupported format
Traceback (most recent call last):
  File "/Users/hugo/github/Pillow/src/PIL/TiffImagePlugin.py", line 1238, in _setup
    self.mode, rawmode = OPEN_INFO[key]
KeyError: (b'II', 5, (1,), 1, (16, 16, 16, 16), ())

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "3815.py", line 3, in <module>
    image = Image.open(input_path)
  File "/Users/hugo/github/Pillow/src/PIL/Image.py", line 2692, in open
    im = _open_core(fp, filename, prefix)
  File "/Users/hugo/github/Pillow/src/PIL/Image.py", line 2676, in _open_core
    im = factory(fp, filename)
  File "/Users/hugo/github/Pillow/src/PIL/ImageFile.py", line 103, in __init__
    self._open()
  File "/Users/hugo/github/Pillow/src/PIL/TiffImagePlugin.py", line 1001, in _open
    self._seek(0)
  File "/Users/hugo/github/Pillow/src/PIL/TiffImagePlugin.py", line 1056, in _seek
    self._setup()
  File "/Users/hugo/github/Pillow/src/PIL/TiffImagePlugin.py", line 1242, in _setup
    raise SyntaxError("unknown pixel mode")
SyntaxError: unknown pixel mode
```

So `(b'II', 5, (1,), 1, (16, 16, 16, 16), ())` isn't supported.

The supported list:

https://github.com/python-pillow/Pillow/blob/7d378a8e4ccbe75eca38bd8246618c4ba68fb55d/src/PIL/TiffImagePlugin.py#L145-L273

**Comment by radarhere** [comment]
Do you have an image that we are able to include in the test suite, under the Pillow license?

**Comment by anpr** [comment]
Hi,

Thanks for the investigation. I'm sorry, you can use the image to debug this, but I does not have the   Pillow license. Would it be possible to add support for this anyway?

**Comment by radarhere** [comment]
I've created PR #3817. If you could test it, that would be good.

**Comment by radarhere** [comment]
Let me ask this - I presume that you're not just interested in opening a file and creating a thumbnail from it, you'd also like to then do something with that data. Save the images as files? Convert them to a different mode? Get the individual pixel values?

**Comment by anpr** [comment]
I'd like to save the thumbnail as file, exactly.

**Comment by radarhere** [comment]
Closing with the merge of #3817
