### ISSUE TITLE
Support Unicode (UTF-8), not Latin-1

### ISSUE THREAD

**Issue by evandrix** [python-pillow/Pillow#3878]
### Error message

```
Traceback (most recent call last):
  File "/usr/local/bin/vcsi", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3/dist-packages/vcsi/__init__.py", line 3, in main
    vcsi.vcsi.main()
  File "/usr/local/lib/python3/dist-packages/vcsi/vcsi.py", line 1467, in main
    process_file(filename, args)
  File "/usr/local/lib/python3/dist-packages/vcsi/vcsi.py", line 1596, in process_file
    image = compose_contact_sheet(media_info, selected_frames, args)
  File "/usr/local/lib/python3/dist-packages/vcsi/vcsi.py", line 867, in compose_contact_sheet
    template_path=args.metadata_template_path)
  File "/usr/local/lib/python3/dist-packages/vcsi/vcsi.py", line 778, in prepare_metadata_text_lines
    text=remaining_chars)
  File "/usr/local/lib/python3/dist-packages/vcsi/vcsi.py", line 742, in max_line_length
    text_width = 0 if len(text_chunk) == 0 else metadata_font.getsize(text_chunk)[0]
  File "/usr/local/lib/python3/dist-packages/PIL/ImageFont.py", line 112, in getsize
    return self.font.getsize(text)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u5496' in position 0: ordinal not in range(256)
```

### Fix

add `text = text.encode("utf-8")` to /usr/local/lib/python3/dist-packages/PIL/ImageFont.py:

```
def getsize(self, text, *args, **kwargs):
    text = text.encode("utf-8")
    return self.font.getsize(text)

  def getmask(self, text, mode="", *args, **kwargs):
    text = text.encode("utf-8")
    return self.font.getmask(text, mode)
```

### What are your OS, Python and Pillow versions?

* OS: Ubuntu 16.04.6 LTS
* Python: 3.7.3
* Pillow: 6.0.0

**Comment by radarhere** [comment]
Could you provide a complete example? A small script containing the font you were using and the string you were getting the size of?

**Comment by radarhere** [comment]
For the record, the following code reproduces the error -

```python
from PIL import ImageFont
font = ImageFont.load_default()
font.getsize("\u5496")
```

The line number in the traceback you've provided means that you're using the default font. However, https://github.com/python-pillow/Pillow/issues/2779#issuecomment-333798938 notes that the default font is Latin-1 only.
