### ISSUE TITLE
UnboundLocalError when opening images

### ISSUE THREAD

**Issue by Wicloz** [python-pillow/Pillow#3883]
### What did you do?
Open an image

### What did you expect to happen?
The image is opened and available for use

### What actually happened?
The following error is thrown:
```
Traceback (most recent call last):
  File "C:/Users/wdboer/Desktop/RIP PIL/main.py", line 2, in <module>
    Image.open('broken.jpg')
  File "C:\Users\wdboer\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\Image.py", line 2690, in open
    im = _open_core(fp, filename, prefix)
  File "C:\Users\wdboer\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\Image.py", line 2676, in _open_core
    im = factory(fp, filename)
  File "C:\Users\wdboer\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\JpegImagePlugin.py", line 783, in jpeg_factory
    im = JpegImageFile(fp, filename)
  File "C:\Users\wdboer\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\ImageFile.py", line 103, in __init__
    self._open()
  File "C:\Users\wdboer\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\JpegImagePlugin.py", line 373, in _open
    handler(self, i)
  File "C:\Users\wdboer\AppData\Local\Programs\Python\Python37\lib\site-packages\PIL\JpegImagePlugin.py", line 139, in APP
    self.info["photoshop"] = photoshop
UnboundLocalError: local variable 'photoshop' referenced before assignment
```

### What are your OS, Python and Pillow versions?

* OS:  Windows 10
* Python: 3.7.2
* Pillow: 6.0.0

Please include **code** that reproduces the issue and whenever possible, an **image** that demonstrates the issue. Please upload images to GitHub, not to third-party file hosting sites. If necessary, add the image to a zip or tar archive.

The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as plone, Django, or buildout, try to replicate the issue just using Pillow.

```
from PIL import Image
Image.open('broken.jpg')
```

![broken](https://user-images.githubusercontent.com/8057570/58768933-2dbbf680-85a2-11e9-917e-9756fc745724.jpg)

**Comment by Wicloz** [comment]
I just looked at `JpegImagePlugin.py` and it would seem this issue has been resolved on master. The code at https://github.com/python-pillow/Pillow/blob/593217f8976364e4ce4ae595c83a92c79ca2f1d9/src/PIL/JpegImagePlugin.py#L107 looks different from the other if statements though, which might lead to other obscure issues.

**Comment by hugovk** [comment]
Thanks for the report. This has been fixed in https://github.com/python-pillow/Pillow/issues/3769 and will be in the next release.

**Comment by radarhere** [comment]
Pillow 6.1.0 has now been released, with the fix for this.
