### ISSUE TITLE
Can’t install Pillow on virtual environment with Python 3.7

### ISSUE THREAD

**Issue by Dezyox** [python-pillow/Pillow#3979]
### What did you do?
pip install Pillow
### What did you expect to happen?
Installing Pillow correctly
### What actually happened?
Pillow can’t be installed
### What are your OS, Python and Pillow versions?

* OS: Raspbian Stretch
* Python: 3.7.2
* Pillow: N/A
* Using Virtual Environment

```python
ERROR: Complete output from command /home/pi/Red/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-_6p1h5bj/pillow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-kynqd_eu/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/Red/include/site/python3.7/pillow:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-3.7
    creating build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImagePath.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageOps.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/_binary.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageMode.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/GimpPaletteFile.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/DdsImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ContainerIO.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/FtexImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PdfParser.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageColor.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PsdImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/BmpImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageShow.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/BdfFontFile.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageTransform.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageDraw.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/XbmImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/GdImageFile.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PcfFontFile.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/TgaImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/BlpImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/IptcImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageQt.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/XpmImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageFilter.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/_tkinter_finder.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/SunImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/SgiImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageCms.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/__main__.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PyAccess.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/MicImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PpmImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/_util.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/FliImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/FontFile.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/WebPImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/JpegImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageStat.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/IcoImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PSDraw.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/GimpGradientFile.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/CurImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/TiffImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PdfImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/TiffTags.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageMorph.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/DcxImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageFont.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/WalImageFile.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/JpegPresets.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/__init__.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/features.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/MpegImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImtImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/FpxImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/Image.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageDraw2.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ExifTags.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/GbrImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageFile.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PaletteFile.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageWin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PixarImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageEnhance.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageSequence.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PcdImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/MpoImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageGrab.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageChops.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/EpsImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/TarIO.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/_version.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PalmImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/MspImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PngImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/WmfImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PcxImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageMath.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImagePalette.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/GifImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageTk.py -> build/lib.linux-armv7l-3.7/PIL
    running egg_info
    writing src/Pillow.egg-info/PKG-INFO
    writing dependency_links to src/Pillow.egg-info/dependency_links.txt
    writing top-level names to src/Pillow.egg-info/top_level.txt
    reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.c'
    warning: no files found matching '*.h'
    warning: no files found matching '*.sh'
    no previously-included directories found matching 'docs/_static'
    warning: no previously-included files found matching '.appveyor.yml'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.codecov.yml'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.landscape.yaml'
    warning: no previously-included files found matching '.readthedocs.yml'
    warning: no previously-included files found matching 'azure-pipelines.yml'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    no previously-included directories found matching '.azure-pipelines'
    no previously-included directories found matching '.travis'
    writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
    running build_ext
    
    
    The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    Traceback (most recent call last):
      File "/tmp/pip-install-_6p1h5bj/pillow/setup.py", line 873, in <module>
        zip_safe=not (debug_build() or PLATFORM_MINGW),
      File "/home/pi/Red/lib/python3.7/site-packages/setuptools/__init__.py", line 143, in setup
        return distutils.core.setup(**attrs)
      File "/home/pi/.pyenv/versions/3.7.2/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/pi/.pyenv/versions/3.7.2/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/pi/.pyenv/versions/3.7.2/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/pi/Red/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/pi/.pyenv/versions/3.7.2/lib/python3.7/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/pi/.pyenv/versions/3.7.2/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/pi/.pyenv/versions/3.7.2/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/pi/.pyenv/versions/3.7.2/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/pi/.pyenv/versions/3.7.2/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/pi/.pyenv/versions/3.7.2/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/pi/.pyenv/versions/3.7.2/lib/python3.7/distutils/command/build_ext.py", line 339, in run
        self.build_extensions()
      File "/tmp/pip-install-_6p1h5bj/pillow/setup.py", line 674, in build_extensions
        raise RequiredDependencyException(f)
    __main__.RequiredDependencyException: jpeg
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-_6p1h5bj/pillow/setup.py", line 888, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:
    
    The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    
    ----------------------------------------
ERROR: Command "/home/pi/Red/bin/python3.7 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-_6p1h5bj/pillow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-kynqd_eu/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/Red/include/site/python3.7/pillow" failed with error code 1 in /tmp/pip-install-_6p1h5bj/pillow/
```

**Comment by radarhere** [comment]
The error is saying that you're missing a jpeg dependency.

https://www.techcoil.com/blog/how-to-setup-python-imaging-library-pillow-on-raspbian-stretch-lite-for-processing-images-on-your-raspberry-pi/ looks like a reasonable tutorial for your scenario. It recommends `sudo apt-get install libjpeg-dev` before installing Pillow.

**Comment by Dezyox** [comment]
Exactly what I was missing ! Thank !
