### ISSUE TITLE
OSError: cannot identify image file <InMemoryUploadedFile: image.jpg (image/jpeg)>

### ISSUE THREAD

**Issue by sultan-karybaev** [python-pillow/Pillow#4028]
Here is my code:

```python
def image_upload_2(request):
    img = Image.open(request.FILES["file"])
```

After running it shows up the error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 126, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python3.7/site-packages/django/core/handlers/base.py", line 124, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.7/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/Users/sultankarybaev/Desktop/MyProjects/bali_rest/app/core/views.py", line 51, in image_upload_2
    img = Image.open(request.FILES["file"])
  File "/usr/local/lib/python3.7/site-packages/PIL/Image.py", line 2705, in open
    % (filename if filename else fp))
OSError: cannot identify image file <InMemoryUploadedFile: Untitled-11.jpg (image/jpeg)>
```

I just returned to coding some functions with Pillow and I clearly remember that code used to work

**Comment by radarhere** [comment]
Do you find this with any image that you try, or just Untitled-11.jpg? Could you provide a copy of Untitled-11.jpg?

**Comment by sultan-karybaev** [comment]
> Do you find this with any image that you try, or just Untitled-11.jpg? Could you provide a copy of Untitled-11.jpg?

It happens with all images that I try to upload

**Comment by radarhere** [comment]
Are you able to provide a self-contained example? Code that can be run by itself to demonstrate the problem?

**Comment by sultan-karybaev** [comment]
It was my fault. I set custom FileUploadHandler thus request.FILES["file"] was 0 byte size. That was the reason of the error
