### ISSUE TITLE
RequiredDependencyException

### ISSUE THREAD

**Issue by Hakonmh** [python-pillow/Pillow#4159]
### What did you do?
`pip install pillow`

### What did you expect to happen?
A successful installation.

### What actually happened?
 `__main__.RequiredDependencyException: zlib` (full output below)

### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python: 3.8.0
* Pillow: 6.2.1

`> pip install pillow`
```Collecting pillow
  Using cached https://files.pythonhosted.org/packages/5b/b
/cdc8086db1f15d0664dd22a62c69613cdc00f1dd430b5b19df1bea83f2a3/Pillow-6.2.1.tar.gz
Installing collected packages: pillow
    Running setup.py install for pillow ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\python\python\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] =
'"'"'C:\\Users\\haako\\AppData\\Local\\Temp\\pip-install-551r8pt3\\pillow\\setup.py'"'"';
__file__='"'"'C:\\Users\\haako\\AppData\\Local\\Temp\\pip-install-551r8pt3\\pillow\\setup.py'"'"'
f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"',
'"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\haak
\AppData\Local\Temp\pip-record-_p4heaa6\install-record.txt' --single-version-externally-managed
--compile
         cwd: C:\Users\haako\AppData\Local\Temp\pip-install-551r8pt3\pillow\
    Complete output (174 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.8
    creating build\lib.win-amd64-3.8\PIL
    copying src\PIL\BdfFontFile.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\BlpImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\BmpImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\BufrStubImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ContainerIO.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\CurImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\DcxImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\DdsImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\EpsImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ExifTags.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\features.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\FitsStubImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\FliImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\FontFile.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\FpxImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\FtexImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\GbrImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\GdImageFile.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\GifImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\GimpGradientFile.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\GimpPaletteFile.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\GribStubImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\Hdf5StubImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\IcnsImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\IcoImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\Image.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageChops.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageCms.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageColor.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageDraw.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageDraw2.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageEnhance.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageFile.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageFilter.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageFont.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageGrab.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageMath.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageMode.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageMorph.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageOps.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImagePalette.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImagePath.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageQt.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageSequence.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageShow.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageStat.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageTk.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageTransform.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImageWin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\ImtImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\IptcImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\Jpeg2KImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\JpegImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\JpegPresets.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\McIdasImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\MicImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\MpegImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\MpoImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\MspImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\PaletteFile.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\PalmImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\PcdImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\PcfFontFile.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\PcxImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\PdfImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\PdfParser.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\PixarImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\PngImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\PpmImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\PsdImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\PSDraw.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\PyAccess.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\SgiImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\SpiderImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\SunImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\TarIO.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\TgaImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\TiffImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\TiffTags.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\WalImageFile.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\WebPImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\WmfImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\XbmImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\XpmImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\XVThumbImagePlugin.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\_binary.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\_tkinter_finder.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\_util.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\_version.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\__init__.py -> build\lib.win-amd64-3.8\PIL
    copying src\PIL\__main__.py -> build\lib.win-amd64-3.8\PIL
    running egg_info
    writing src\Pillow.egg-info\PKG-INFO
    writing dependency_links to src\Pillow.egg-info\dependency_links.txt
    writing top-level names to src\Pillow.egg-info\top_level.txt
    reading manifest file 'src\Pillow.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.c'
    warning: no files found matching '*.h'
    warning: no files found matching '*.sh'
    warning: no previously-included files found matching '.appveyor.yml'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.codecov.yml'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.readthedocs.yml'
    warning: no previously-included files found matching 'azure-pipelines.yml'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    no previously-included directories found matching '.azure-pipelines'
    no previously-included directories found matching '.travis'
    writing manifest file 'src\Pillow.egg-info\SOURCES.txt'
    running build_ext


    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html

    Traceback (most recent call last):
      File "C:\Users\haako\AppData\Local\Temp\pip-install-551r8pt3\pillow\setup.py", line 852, in <module>
        setup(
      File "c:\python\python\lib\site-packages\setuptools\__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "c:\python\python\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\python\python\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\python\python\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\python\python\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\python\python\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\python\python\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\python\python\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\python\python\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\python\python\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\python\python\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\python\python\lib\distutils\command\build_ext.py", line 340, in run
        self.build_extensions()
      File "C:\Users\haako\AppData\Local\Temp\pip-install-551r8pt3\pillow\setup.py", line 687, in build_extensions
        raise RequiredDependencyException(f)
    __main__.RequiredDependencyException: zlib

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\haako\AppData\Local\Temp\pip-install-551r8pt3\pillow\setup.py", line 903, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:

    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html


    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\python\python\python.exe' -u -c 'import sys,
setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\haako\\AppData\\Local\\Temp\\pip-install
551r8pt3\\pillow\\setup.py'"'"'; __file__='"'"'C:\\Users\\haako\\AppData\\Local\\Temp\\pip-install
551r8pt3\\pillow\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"',
open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__,
'"'"'exec'"'"'))' install --record 'C:\Users\haako\AppData\Local\Temp\pip-record-_p4heaa6\install
record.txt' --single-version-externally-managed --compile Check the logs for full command output.
```

**Comment by hugovk** [comment]
Probably the same as #4158.

**Comment by Hakonmh** [comment]
Yes, this ended up as a duplicate. #4158 got posted while i was formatting this post.
