### ISSUE TITLE
Pillow Install and Build Fail

### ISSUE THREAD

**Issue by toekneechin777** [python-pillow/Pillow#4162]
MacOS

```
Building wheels for collected packages: Pillow
  Building wheel for Pillow (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/local/opt/python/bin/python3.7 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/g2/2p6mzzds03j8_18vz6s1_qcnw8_rtl/T/pip-install-5yu3iq0j/Pillow/setup.py'"'"'; __file__='"'"'/private/var/folders/g2/2p6mzzds03j8_18vz6s1_qcnw8_rtl/T/pip-install-5yu3iq0j/Pillow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/g2/2p6mzzds03j8_18vz6s1_qcnw8_rtl/T/pip-wheel-jdz2bin1 --python-tag cp37
       cwd: /private/var/folders/g2/2p6mzzds03j8_18vz6s1_qcnw8_rtl/T/pip-install-5yu3iq0j/Pillow/
  Complete output (174 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.14-x86_64-3.7
  creating build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/MpoImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/ImageMode.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/PngImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/XbmImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/PcxImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/SunImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/ImageFile.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/SpiderImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/TarIO.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/FitsStubImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/MpegImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/BdfFontFile.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/GribStubImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/ImageStat.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/PixarImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/GimpPaletteFile.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/version.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/ImageColor.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/ContainerIO.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/MspImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/MicImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/ImtImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/GifImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/PalmImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/ImageQt.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/ImageMath.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/PaletteFile.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/FontFile.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/PdfParser.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/ExifTags.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/ImageCms.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/FpxImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/ImageChops.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/BufrStubImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/PSDraw.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/PcdImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/ImageFilter.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/ImageDraw2.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/ImagePath.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/DcxImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/__init__.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/JpegPresets.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/features.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/ImageDraw.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/GimpGradientFile.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/ImageWin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/IcoImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/_tkinter_finder.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/EpsImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/TgaImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/ImageMorph.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/WalImageFile.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/PcfFontFile.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/BlpImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/ImageTk.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/GbrImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/ImageOps.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/PdfImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/ImageShow.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/ImageEnhance.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/WmfImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/ImageGrab.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/WebPImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/FliImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/TiffTags.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/CurImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/_util.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/GdImageFile.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/TiffImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/IptcImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/ImagePalette.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/BmpImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/ImageTransform.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/IcnsImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/McIdasImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/XpmImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/OleFileIO.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/DdsImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/ImageSequence.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/PyAccess.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/_binary.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/Image.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/XVThumbImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/SgiImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/ImImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/PsdImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/JpegImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/ImageFont.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/PpmImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  copying src/PIL/FtexImagePlugin.py -> build/lib.macosx-10.14-x86_64-3.7/PIL
  running egg_info
  writing src/Pillow.egg-info/PKG-INFO
  writing dependency_links to src/Pillow.egg-info/dependency_links.txt
  writing top-level names to src/Pillow.egg-info/top_level.txt
  reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.c'
  warning: no files found matching '*.h'
  warning: no files found matching '*.sh'
  no previously-included directories found matching 'docs/_static'
  warning: no previously-included files found matching '.appveyor.yml'
  warning: no previously-included files found matching '.coveragerc'
  warning: no previously-included files found matching '.codecov.yml'
  warning: no previously-included files found matching '.editorconfig'
  warning: no previously-included files found matching '.landscape.yaml'
  warning: no previously-included files found matching '.travis'
  warning: no previously-included files found matching '.travis/*'
  warning: no previously-included files found matching 'build_children.sh'
  warning: no previously-included files found matching 'tox.ini'
  warning: no previously-included files matching '.git*' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
  running build_ext
  
  
  The headers or library files could not be found for jpeg,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  
  Traceback (most recent call last):
    File "/private/var/folders/g2/2p6mzzds03j8_18vz6s1_qcnw8_rtl/T/pip-install-5yu3iq0j/Pillow/setup.py", line 794, in <module>
      zip_safe=not (debug_build() or PLATFORM_MINGW), )
    File "/usr/local/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/private/var/folders/g2/2p6mzzds03j8_18vz6s1_qcnw8_rtl/T/pip-install-5yu3iq0j/Pillow/setup.py", line 582, in build_extensions
      raise RequiredDependencyException(f)
  __main__.RequiredDependencyException: jpeg
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/private/var/folders/g2/2p6mzzds03j8_18vz6s1_qcnw8_rtl/T/pip-install-5yu3iq0j/Pillow/setup.py", line 806, in <module>
      raise RequiredDependencyException(msg)
  __main__.RequiredDependencyException:
  
  The headers or library files could not be found for jpeg,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  
  
  ----------------------------------------
  ERROR: Failed building wheel for Pillow
```

**Comment by hugovk** [comment]
The headers or library files could not be found for jpeg,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
