### ISSUE TITLE
PNG read or write corruption on certain RGB bitmaps

### ISSUE THREAD

**Issue by flagadum** [python-pillow/Pillow#4249]
* OS: MacOS 10.14.6
* Python: 3.7
* Pillow: 5.4.0

Some RGB bitmaps seem not properly handled by PNG read/write.

Such bitmap can be perfectly worked with. However, writing it to a PNG file then reopening it causes a crash to whatever command applied to it.

One of the offending bitmap:

![test](https://user-images.githubusercontent.com/58535996/70193531-c83af500-16ff-11ea-8096-7312dc245c7d.png)

Note that none of my 3rd-party image utilities have found any issues with the original bitmap, and the one created by Pillow.

```python
#!/usr/bin/env python3

from PIL import Image

# Let's open the offending image
img = Image.open("test.png")

# We can work with this image, for example histogram or whatever else
print(img.histogram())

# We save the image to a new file
img.save("test1.png")

# Now let's open the file we just created
img1 = Image.open("test1.png")

# Boom ???
print(img1.histogram())


# Traceback (most recent call last):
#   File "/Users/admin/Desktop/pngbug.py", line 15, in <module>
#     print(img1.histogram())
#   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PIL/Image.py", line 1366, in histogram
#     self.load()
#   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PIL/ImageFile.py", line 250, in load
#     self.load_end()
#   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PIL/PngImagePlugin.py", line 677, in load_end
#     self.png.call(cid, pos, length)
#   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PIL/PngImagePlugin.py", line 140, in call
#     return getattr(self, "chunk_" + cid.decode('ascii'))(pos, length)
#   File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PIL/PngImagePlugin.py", line 356, in chunk_IDAT
#     raise EOFError
# EOFError
```

**Comment by hugovk** [comment]
I can reproduce with Pillow 5.4.0 but not with the latest Pillow 6.2.1. Please upgrade:

```
pip install --upgrade pillow
```
