### ISSUE TITLE
No Pillow 6.2.1 binaries for Python 3.7 on raspberry pi  

### ISSUE THREAD

**Issue by stalakerob** [python-pillow/Pillow#4268]
### What did you do?
Trying to install pillow 6.2.1 on raspbian Buster and python 3.7.3
### What actually happened?
Pip is trying to install pillow 6.2.1 from source but that fails
### What are your OS, Python and Pillow versions?

* OS: Raspian Buster 
* Python: 3.7.3 virtual environment
* Pillow: 6.2.1
* Pip: 19.3.1

pip install --upgrade Pillow

```python

Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting Pillow
  Using cached https://files.pythonhosted.org/packages/5b/bb/cdc8086db1f15d0664dd22a62c69613cdc00f1dd430b5b19df1bea83f2a3/Pillow-6.2.1.tar.gz
Building wheels for collected packages: Pillow
  Building wheel for Pillow (setup.py): started
  Building wheel for Pillow (setup.py): finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /srv/homeassistant/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3xgilj8z/Pillow/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3xgilj8z/Pillow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-ug4ybbcm --python-tag cp37
       cwd: /tmp/pip-install-3xgilj8z/Pillow/
  Complete output (172 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-armv7l-3.7
  creating build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/__init__.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/WmfImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/TiffTags.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/ImageTk.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/ImagePalette.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/_tkinter_finder.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/GimpGradientFile.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/BlpImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/FtexImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/ExifTags.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/ContainerIO.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/IcoImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/XpmImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/_util.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/ImageStat.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/JpegImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/ImageWin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/ImageQt.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/ImtImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/PcxImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/ImageColor.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/ImageMath.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/JpegPresets.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/ImageDraw.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/SunImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/FliImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/PcfFontFile.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/_version.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/DcxImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/PdfImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/BdfFontFile.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/WalImageFile.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/ImageMode.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/FontFile.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/BmpImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/ImageDraw2.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/IptcImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/PcdImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/CurImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/GbrImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/PsdImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/ImageGrab.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/ImageShow.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/PSDraw.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/TarIO.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/ImageSequence.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/XbmImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/ImageCms.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/ImageFile.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/PpmImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/SgiImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/features.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/PixarImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/ImageEnhance.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/_binary.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/GdImageFile.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/PaletteFile.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/ImageFilter.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/PalmImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/ImageMorph.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/ImageTransform.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/WebPImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/MspImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/FpxImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/ImagePath.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/ImageOps.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/DdsImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/__main__.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/EpsImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/PyAccess.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/TiffImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/PngImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/GimpPaletteFile.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/MpegImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/MicImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/TgaImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/ImImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/GifImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/Image.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/MpoImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/ImageChops.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/PdfParser.py -> build/lib.linux-armv7l-3.7/PIL
  copying src/PIL/ImageFont.py -> build/lib.linux-armv7l-3.7/PIL
  running egg_info
  writing src/Pillow.egg-info/PKG-INFO
  writing dependency_links to src/Pillow.egg-info/dependency_links.txt
  writing top-level names to src/Pillow.egg-info/top_level.txt
  reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.c'
  warning: no files found matching '*.h'
  warning: no files found matching '*.sh'
  warning: no previously-included files found matching '.appveyor.yml'
  warning: no previously-included files found matching '.coveragerc'
  warning: no previously-included files found matching '.codecov.yml'
  warning: no previously-included files found matching '.editorconfig'
  warning: no previously-included files found matching '.readthedocs.yml'
  warning: no previously-included files found matching 'azure-pipelines.yml'
  warning: no previously-included files matching '.git*' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  no previously-included directories found matching '.azure-pipelines'
  no previously-included directories found matching '.travis'
  writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
  running build_ext
  
  
  The headers or library files could not be found for jpeg,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  
  Traceback (most recent call last):
    File "/tmp/pip-install-3xgilj8z/Pillow/setup.py", line 888, in <module>
      zip_safe=not (debug_build() or PLATFORM_MINGW),
    File "/srv/homeassistant/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/srv/homeassistant/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 192, in run
      self.run_command('build')
    File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.7/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/tmp/pip-install-3xgilj8z/Pillow/setup.py", line 687, in build_extensions
      raise RequiredDependencyException(f)
  __main__.RequiredDependencyException: jpeg
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-3xgilj8z/Pillow/setup.py", line 903, in <module>
      raise RequiredDependencyException(msg)
  __main__.RequiredDependencyException:
  
  The headers or library files could not be found for jpeg,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  
  
  ----------------------------------------
  ERROR: Failed building wheel for Pillow
  Running setup.py clean for Pillow
Failed to build Pillow
Installing collected packages: Pillow
  Found existing installation: Pillow 6.2.0
    Uninstalling Pillow-6.2.0:
      Successfully uninstalled Pillow-6.2.0
    Running setup.py install for Pillow: started
    Running setup.py install for Pillow: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /srv/homeassistant/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3xgilj8z/Pillow/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3xgilj8z/Pillow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-gwry6bbk/install-record.txt --single-version-externally-managed --compile --install-headers /srv/homeassistant/include/site/python3.7/Pillow
         cwd: /tmp/pip-install-3xgilj8z/Pillow/
    Complete output (174 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-armv7l-3.7
    creating build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/__init__.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/WmfImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/TiffTags.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageTk.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImagePalette.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/_tkinter_finder.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/GimpGradientFile.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/BlpImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/FtexImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ExifTags.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ContainerIO.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/IcoImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/XpmImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/_util.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageStat.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/JpegImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageWin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageQt.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImtImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PcxImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageColor.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageMath.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/JpegPresets.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageDraw.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/SunImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/FliImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PcfFontFile.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/_version.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/DcxImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PdfImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/BdfFontFile.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/WalImageFile.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageMode.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/FontFile.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/BmpImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageDraw2.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/IptcImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PcdImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/CurImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/GbrImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PsdImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageGrab.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageShow.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PSDraw.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/TarIO.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageSequence.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/XbmImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageCms.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageFile.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PpmImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/SgiImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/features.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PixarImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageEnhance.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/_binary.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/GdImageFile.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PaletteFile.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageFilter.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PalmImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageMorph.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageTransform.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/WebPImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/MspImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/FpxImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImagePath.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageOps.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/DdsImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/__main__.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/EpsImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PyAccess.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/TiffImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PngImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/GimpPaletteFile.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/MpegImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/MicImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/TgaImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/GifImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/Image.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/MpoImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageChops.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/PdfParser.py -> build/lib.linux-armv7l-3.7/PIL
    copying src/PIL/ImageFont.py -> build/lib.linux-armv7l-3.7/PIL
    running egg_info
    writing src/Pillow.egg-info/PKG-INFO
    writing dependency_links to src/Pillow.egg-info/dependency_links.txt
    writing top-level names to src/Pillow.egg-info/top_level.txt
    reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.c'
    warning: no files found matching '*.h'
    warning: no files found matching '*.sh'
    warning: no previously-included files found matching '.appveyor.yml'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.codecov.yml'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.readthedocs.yml'
    warning: no previously-included files found matching 'azure-pipelines.yml'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    no previously-included directories found matching '.azure-pipelines'
    no previously-included directories found matching '.travis'
    writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
    running build_ext
    
    
    The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    Traceback (most recent call last):
      File "/tmp/pip-install-3xgilj8z/Pillow/setup.py", line 888, in <module>
        zip_safe=not (debug_build() or PLATFORM_MINGW),
      File "/srv/homeassistant/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/srv/homeassistant/lib/python3.7/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.7/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.7/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/tmp/pip-install-3xgilj8z/Pillow/setup.py", line 687, in build_extensions
        raise RequiredDependencyException(f)
    __main__.RequiredDependencyException: jpeg
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-3xgilj8z/Pillow/setup.py", line 903, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:
    
    The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    
    ----------------------------------------
  Rolling back uninstall of Pillow
  Moving to /srv/homeassistant/lib/python3.7/site-packages/PIL/
   from /srv/homeassistant/lib/python3.7/site-packages/~IL
  Moving to /srv/homeassistant/lib/python3.7/site-packages/Pillow-6.2.0.dist-info/
   from /srv/homeassistant/lib/python3.7/site-packages/~illow-6.2.0.dist-info
ERROR: Command errored out with exit status 1: /srv/homeassistant/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3xgilj8z/Pillow/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3xgilj8z/Pillow/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-gwry6bbk/install-record.txt --single-version-externally-managed --compile --install-headers /srv/homeassistant/include/site/python3.7/Pillow Check the logs for full command output.

```

**Comment by radarhere** [comment]
Hi. Could you clarify, are you just installed in binary wheels, or are you looking for help in building from source, or both?

**Comment by radarhere** [comment]
If you'd like to fix the jpeg errors you're getting when trying to build from source, I would suggest `sudo apt-get install libjpeg-dev`.

It's true that Pillow 6.2.1 is not available on https://www.piwheels.org/project/Pillow/

If it's helpful, there's not any difference between Pillow 6.2.0 and 6.2.1 for Python 3.7 - the only reason 6.2.1 was released was to add Python 3.8.

**Comment by stalakerob** [comment]
Hi. Thanks. I tried to install Home Assistant 0.103.0. This is the first version that requires Pillow 6.2.1 if certain components are enabled (eg image processing). Since it did not find it on my system it tried to pull and compile the sources which also failed. I was stuck here. I have not tried yet installing `libjpeg-dev`  before using the image processing component in Home Assistant but plan to do so soon. Anyway it might be better to include the binaries for Python 3.7 on raspberry pi.

**Comment by bennuttall** [comment]
wheels now available from piwheels.org - thanks all

https://www.piwheels.org/project/Pillow/

**Comment by radarhere** [comment]
Thanks. @stalakerob so, are you able to install from the binary wheels now?

**Comment by stalakerob** [comment]
Yes, the installation now works. I'm closing this issue. 
Thanks again.
