### ISSUE TITLE
Error inserting icc color profile into image using Pillow ImageCMS

### ISSUE THREAD

**Issue by srubs** [python-pillow/Pillow#4464]
I am trying to insert an ICC color profile into an image. Using code from this [post](https://stackoverflow.com/a/14537273/520779) as an example my code looks like this:

```python
from PIL import Image, ImageCms

# Read image
img = Image.open(IMG_PATH)

# Read profile
profile = ImageCms.getOpenProfile(PROFILE_PATH)

# Save image with profile
img.save(OUT_IMG_PATH, icc_profile=profile)
```
I get the following error
```
Traceback (most recent call last):
  File "/home/----/Documents/code_projects/hfss-misc/icc_profiles/insert_icc_profile_into_image.py", line 17, in <module>
    img.save(OUT_IMG_PATH, icc_profile=srgb_profile)
  File "/home/----/.virtualenvs/color-correction/lib/python3.6/site-packages/PIL/Image.py", line 2102, in save
    save_handler(self, fp, filename)
  File "/home/----/.virtualenvs/color-correction/lib/python3.6/site-packages/PIL/JpegImagePlugin.py", line 706, in _save
    markers.append(icc_profile[:MAX_DATA_BYTES_IN_MARKER])
TypeError: 'PIL._imagingcms.CmsProfile' object is not subscriptable
```
I thought that there might be a problem with my ICC profile so I tried to use one generated by Pillow.
```python
from PIL import Image, ImageCms

# Read image
img = Image.open(IMG_PATH)

# Creating sRGB profile
profile = ImageCms.createProfile("sRGB")

# Save image with profile
img.save(OUT_IMG_PATH, icc_profile=profile)
```
I still get the same error, however.

Does anyone know what the cause for this error is?

My system environment is as follows:

 - Ubuntu 18.04
 - Python 3.6
 - Pillow==7.0.0

**Comment by radarhere** [comment]
I would suggest
```python
from PIL import Image, ImageCms

# Read image
img = Image.open(IMG_PATH)

# Read profile
profile = ImageCms.getOpenProfile(PROFILE_PATH)

# Save image with profile
img.save(OUT_IMG_PATH, icc_profile=profile.tobytes())
```

If you do want to use `createProfile`,
```python
from PIL import Image, ImageCms

# Read image
img = Image.open(IMG_PATH)

# Creating sRGB profile
profile = ImageCms.createProfile("sRGB")
profile2 = ImageCms.ImageCmsProfile(profile)

# Save image with profile
img.save(OUT_IMG_PATH, icc_profile=profile2.tobytes())
```

**Comment by srubs** [comment]
@radarhere 's answer (https://github.com/python-pillow/Pillow/issues/4464#issuecomment-597534385) solves my issue. Thank you.
