### ISSUE TITLE
png image processing bug

### ISSUE THREAD

**Issue by 1271** [python-pillow/Pillow#4592]
### What did you do?
I need to handle this image with Pillow
[001_R2.zip](https://github.com/python-pillow/Pillow/files/4535520/001_R2.zip)

### What actually happened?
```PIL.UnidentifiedImageError: cannot identify image file '001_R2.png'```

### What are your OS, Python and Pillow versions?

* OS: Any (checked at windows/linux)
* Python: Any (checked 3.6-3.9)
* Pillow: I checked at 6.*, 7.* Maybe any

```python
from PIL import Image

Image.open('001_R2.png')   # exception
```

I can fix this by simply doing:

convert 001_R2.png 001_R2_fixed.png

`file` utility shows file identity

![image](https://user-images.githubusercontent.com/1452243/80311048-2b7c0f80-87e6-11ea-8e79-81bb1062aefd.png)

Problem persists on all PCs on which i could check it.
Thanks

**Comment by hugovk** [comment]
With logging:
```python
from PIL import Image
import logging

logging.basicConfig(level=logging.DEBUG)

Image.open('001_R2.png')   # exception
```
I get:
```
DEBUG:PIL.PngImagePlugin:STREAM b'IHDR' 16 13
DEBUG:PIL.PngImagePlugin:STREAM b'zTXt' 41 12791
DEBUG:PIL.PngImagePlugin:STREAM b'iCCP' 12844 390
DEBUG:PIL.PngImagePlugin:iCCP profile name b'ICC PROFILE'
DEBUG:PIL.PngImagePlugin:Compression method 0
DEBUG:PIL.Image:
Traceback (most recent call last):
  File "/Users/hugo/github/Pillow/src/PIL/Image.py", line 2869, in _open_core
    im = factory(fp, filename)
  File "/Users/hugo/github/Pillow/src/PIL/ImageFile.py", line 117, in __init__
    self._open()
  File "/Users/hugo/github/Pillow/src/PIL/PngImagePlugin.py", line 661, in _open
    self.png.crc(cid, s)
  File "/Users/hugo/github/Pillow/src/PIL/PngImagePlugin.py", line 170, in crc
    raise SyntaxError("broken PNG file (bad header checksum in %r)" % cid)
  File "<string>", line None
SyntaxError: broken PNG file (bad header checksum in b'iCCP')
DEBUG:PIL.Image:Importing BlpImagePlugin
DEBUG:PIL.Image:Importing BmpImagePlugin
DEBUG:PIL.Image:Importing BufrStubImagePlugin
DEBUG:PIL.Image:Importing CurImagePlugin
DEBUG:PIL.Image:Importing DcxImagePlugin
DEBUG:PIL.Image:Importing DdsImagePlugin
DEBUG:PIL.Image:Importing EpsImagePlugin
DEBUG:PIL.Image:Importing FitsStubImagePlugin
DEBUG:PIL.Image:Importing FliImagePlugin
DEBUG:PIL.Image:Importing FpxImagePlugin
DEBUG:PIL.Image:Importing FtexImagePlugin
DEBUG:PIL.Image:Importing GbrImagePlugin
DEBUG:PIL.Image:Importing GifImagePlugin
DEBUG:PIL.Image:Importing GribStubImagePlugin
DEBUG:PIL.Image:Importing Hdf5StubImagePlugin
DEBUG:PIL.Image:Importing IcnsImagePlugin
DEBUG:PIL.Image:Importing IcoImagePlugin
DEBUG:PIL.Image:Importing ImImagePlugin
DEBUG:PIL.Image:Importing ImtImagePlugin
DEBUG:PIL.Image:Importing IptcImagePlugin
DEBUG:PIL.Image:Importing JpegImagePlugin
DEBUG:PIL.Image:Importing Jpeg2KImagePlugin
DEBUG:PIL.Image:Importing McIdasImagePlugin
DEBUG:PIL.Image:Importing MicImagePlugin
DEBUG:PIL.Image:Importing MpegImagePlugin
DEBUG:PIL.Image:Importing MpoImagePlugin
DEBUG:PIL.Image:Importing MspImagePlugin
DEBUG:PIL.Image:Importing PalmImagePlugin
DEBUG:PIL.Image:Importing PcdImagePlugin
DEBUG:PIL.Image:Importing PcxImagePlugin
DEBUG:PIL.Image:Importing PdfImagePlugin
DEBUG:PIL.Image:Importing PixarImagePlugin
DEBUG:PIL.Image:Importing PngImagePlugin
DEBUG:PIL.Image:Importing PpmImagePlugin
DEBUG:PIL.Image:Importing PsdImagePlugin
DEBUG:PIL.Image:Importing SgiImagePlugin
DEBUG:PIL.Image:Importing SpiderImagePlugin
DEBUG:PIL.Image:Importing SunImagePlugin
DEBUG:PIL.Image:Importing TgaImagePlugin
DEBUG:PIL.Image:Importing TiffImagePlugin
DEBUG:PIL.Image:Importing WebPImagePlugin
DEBUG:PIL.Image:Importing WmfImagePlugin
DEBUG:PIL.Image:Importing XbmImagePlugin
DEBUG:PIL.Image:Importing XpmImagePlugin
DEBUG:PIL.Image:Importing XVThumbImagePlugin
DEBUG:PIL.PngImagePlugin:STREAM b'IHDR' 16 13
DEBUG:PIL.PngImagePlugin:STREAM b'zTXt' 41 12791
DEBUG:PIL.PngImagePlugin:STREAM b'iCCP' 12844 390
DEBUG:PIL.PngImagePlugin:iCCP profile name b'ICC PROFILE'
DEBUG:PIL.PngImagePlugin:Compression method 0
DEBUG:PIL.Image:
Traceback (most recent call last):
  File "/Users/hugo/github/Pillow/src/PIL/Image.py", line 2869, in _open_core
    im = factory(fp, filename)
  File "/Users/hugo/github/Pillow/src/PIL/ImageFile.py", line 117, in __init__
    self._open()
  File "/Users/hugo/github/Pillow/src/PIL/PngImagePlugin.py", line 661, in _open
    self.png.crc(cid, s)
  File "/Users/hugo/github/Pillow/src/PIL/PngImagePlugin.py", line 170, in crc
    raise SyntaxError("broken PNG file (bad header checksum in %r)" % cid)
  File "<string>", line None
SyntaxError: broken PNG file (bad header checksum in b'iCCP')
DEBUG:PIL.Image:
Traceback (most recent call last):
  File "/Users/hugo/github/Pillow/src/PIL/Image.py", line 2869, in _open_core
    im = factory(fp, filename)
  File "/Users/hugo/github/Pillow/src/PIL/ImageFile.py", line 117, in __init__
    self._open()
  File "/Users/hugo/github/Pillow/src/PIL/ImImagePlugin.py", line 202, in _open
    raise SyntaxError(
  File "<string>", line None
SyntaxError: Syntax error in IM header: �PNG
DEBUG:PIL.Image:
Traceback (most recent call last):
  File "/Users/hugo/github/Pillow/src/PIL/Image.py", line 2869, in _open_core
    im = factory(fp, filename)
  File "/Users/hugo/github/Pillow/src/PIL/ImageFile.py", line 128, in __init__
    raise SyntaxError("not identified by this driver")
  File "<string>", line None
SyntaxError: not identified by this driver
DEBUG:PIL.Image:
Traceback (most recent call last):
  File "/Users/hugo/github/Pillow/src/PIL/Image.py", line 2869, in _open_core
    im = factory(fp, filename)
  File "/Users/hugo/github/Pillow/src/PIL/ImageFile.py", line 117, in __init__
    self._open()
  File "/Users/hugo/github/Pillow/src/PIL/IptcImagePlugin.py", line 86, in _open
    tag, size = self.field()
  File "/Users/hugo/github/Pillow/src/PIL/IptcImagePlugin.py", line 66, in field
    raise SyntaxError("invalid IPTC/NAA file")
  File "<string>", line None
SyntaxError: invalid IPTC/NAA file
DEBUG:PIL.Image:
Traceback (most recent call last):
  File "/Users/hugo/github/Pillow/src/PIL/Image.py", line 2869, in _open_core
    im = factory(fp, filename)
  File "/Users/hugo/github/Pillow/src/PIL/ImageFile.py", line 117, in __init__
    self._open()
  File "/Users/hugo/github/Pillow/src/PIL/MpegImagePlugin.py", line 70, in _open
    raise SyntaxError("not an MPEG file")
  File "<string>", line None
SyntaxError: not an MPEG file
DEBUG:PIL.Image:
Traceback (most recent call last):
  File "/Users/hugo/github/Pillow/src/PIL/Image.py", line 2869, in _open_core
    im = factory(fp, filename)
  File "/Users/hugo/github/Pillow/src/PIL/ImageFile.py", line 117, in __init__
    self._open()
  File "/Users/hugo/github/Pillow/src/PIL/PcdImagePlugin.py", line 39, in _open
    raise SyntaxError("not a PCD file")
  File "<string>", line None
SyntaxError: not a PCD file
DEBUG:PIL.Image:
Traceback (most recent call last):
  File "/Users/hugo/github/Pillow/src/PIL/Image.py", line 2869, in _open_core
    im = factory(fp, filename)
  File "/Users/hugo/github/Pillow/src/PIL/ImageFile.py", line 117, in __init__
    self._open()
  File "/Users/hugo/github/Pillow/src/PIL/SpiderImagePlugin.py", line 113, in _open
    raise SyntaxError("not a valid Spider file")
  File "<string>", line None
SyntaxError: not a valid Spider file
DEBUG:PIL.Image:
Traceback (most recent call last):
  File "/Users/hugo/github/Pillow/src/PIL/Image.py", line 2869, in _open_core
    im = factory(fp, filename)
  File "/Users/hugo/github/Pillow/src/PIL/ImageFile.py", line 117, in __init__
    self._open()
  File "/Users/hugo/github/Pillow/src/PIL/TgaImagePlugin.py", line 74, in _open
    raise SyntaxError("not a TGA file")
  File "<string>", line None
SyntaxError: not a TGA file
Traceback (most recent call last):
  File "4592.py", line 6, in <module>
    Image.open('001_R2.png')   # exception
  File "/Users/hugo/github/Pillow/src/PIL/Image.py", line 2897, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file '001_R2.png'
```
The important bit is:
```
  File "/Users/hugo/github/Pillow/src/PIL/PngImagePlugin.py", line 170, in crc
    raise SyntaxError("broken PNG file (bad header checksum in %r)" % cid)
```
So a bad header.

You can tell Pillow to ignore this check with `ImageFile.LOAD_TRUNCATED_IMAGES = True`:

```python
from PIL import Image
import logging

logging.basicConfig(level=logging.DEBUG)

from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True

Image.open('001_R2.png')   # no exception
```

**Comment by 1271** [comment]
Oh. Thank you so much!
