### ISSUE TITLE
python -m pip -r requirements.txt 

### ISSUE THREAD

**Issue by uda3** [python-pillow/Pillow#4598]
### What did you do?
i run this code python -m pip -r requirements.txt
### What did you expect to happen?
to instal manim but not work 
### What actually happened?
his give my an erorr 
### What are your OS, Python and Pillow versions?
can any body help my thank you

* Python: 

```python
code goes here
```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\Manim\manim_3_feb>python -m pip install -r requirements.txt
Collecting argparse==1.4.0
  Using cached argparse-1.4.0-py2.py3-none-any.whl (23 kB)
Collecting colour==0.1.5
  Using cached colour-0.1.5-py2.py3-none-any.whl (23 kB)
Collecting numpy==1.15.0
  Using cached numpy-1.15.0.zip (4.5 MB)
Collecting Pillow==5.2.0
  Using cached Pillow-5.2.0.tar.gz (14.5 MB)
Collecting progressbar==2.5
  Using cached progressbar-2.5.tar.gz (10 kB)
Collecting scipy==1.1.0
  Using cached scipy-1.1.0.tar.gz (15.6 MB)
    ERROR: Command errored out with exit status 1:
     command: 'C:\Python\Python38-32\python.exe' -c 'import sys, setuptools, tok
enize; sys.argv[0] = '"'"'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp
\\pip-install-az7pl6bc\\scipy\\setup.py'"'"'; __file__='"'"'C:\\Users\\Public\\D
ocuments\\Wondershare\\CreatorTemp\\pip-install-az7pl6bc\\scipy\\setup.py'"'"';f
=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r
\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))'
egg_info --egg-base 'C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-pip-e
gg-info-6tovks6n'
         cwd: C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-install-az7p
l6bc\scipy\
    Complete output (101 lines):
    Processing numpy/random\_bounded_integers.pxd.in
    Processing numpy/random\mtrand.pyx
    Traceback (most recent call last):
      File "C:\Users\Public\Documents\Wondershare\CreatorTemp\easy_install-5bqmw
koi\numpy-1.18.3\tools\cythonize.py", line 61, in process_pyx
        from Cython.Compiler.Version import version as cython_version
    ModuleNotFoundError: No module named 'Cython'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "C:\Users\Public\Documents\Wondershare\CreatorTemp\easy_install-5bqmw
koi\numpy-1.18.3\tools\cythonize.py", line 238, in <module>
        main()
      File "C:\Users\Public\Documents\Wondershare\CreatorTemp\easy_install-5bqmw
koi\numpy-1.18.3\tools\cythonize.py", line 234, in main
        find_process_files(root_dir)
      File "C:\Users\Public\Documents\Wondershare\CreatorTemp\easy_install-5bqmw
koi\numpy-1.18.3\tools\cythonize.py", line 225, in find_process_files
        process(root_dir, fromfile, tofile, function, hash_db)
      File "C:\Users\Public\Documents\Wondershare\CreatorTemp\easy_install-5bqmw
koi\numpy-1.18.3\tools\cythonize.py", line 191, in process
        processor_function(fromfile, tofile)
      File "C:\Users\Public\Documents\Wondershare\CreatorTemp\easy_install-5bqmw
koi\numpy-1.18.3\tools\cythonize.py", line 66, in process_pyx
        raise OSError('Cython needs to be installed in Python as a module')
    OSError: Cython needs to be installed in Python as a module
    Running from numpy source directory.
    C:\Users\Public\Documents\Wondershare\CreatorTemp\easy_install-5bqmwkoi\nump
y-1.18.3\setup.py:461: UserWarning: Unrecognized setuptools command, proceeding
with generating Cython sources and expanding templates
      run_build = parse_setuppy_commands()
    Traceback (most recent call last):
      File "C:\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line
 154, in save_modules
        yield saved
      File "C:\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line
 195, in setup_context
        yield
      File "C:\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line
 250, in run_setup
        _execfile(setup_script, ns)
      File "C:\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line
 45, in _execfile
        exec(code, globals, locals)
      File "C:\Users\Public\Documents\Wondershare\CreatorTemp\easy_install-5bqmw
koi\numpy-1.18.3\setup.py", line 488, in <module>
      File "C:\Users\Public\Documents\Wondershare\CreatorTemp\easy_install-5bqmw
koi\numpy-1.18.3\setup.py", line 469, in setup_package

      File "C:\Users\Public\Documents\Wondershare\CreatorTemp\easy_install-5bqmw
koi\numpy-1.18.3\setup.py", line 275, in generate_cython
        return False
    RuntimeError: Running cythonize failed!

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-install-az7pl6
bc\scipy\setup.py", line 474, in <module>
        setup_package()
      File "C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-install-az7pl6
bc\scipy\setup.py", line 470, in setup_package
        setup(**metadata)
      File "C:\Python\Python38-32\lib\site-packages\setuptools\__init__.py", lin
e 144, in setup
        _install_setup_requires(attrs)
      File "C:\Python\Python38-32\lib\site-packages\setuptools\__init__.py", lin
e 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "C:\Python\Python38-32\lib\site-packages\setuptools\dist.py", line 71
6, in fetch_build_eggs
        resolved_dists = pkg_resources.working_set.resolve(
      File "C:\Python\Python38-32\lib\site-packages\pkg_resources\__init__.py",
line 780, in resolve
        dist = best[req.key] = env.best_match(
      File "C:\Python\Python38-32\lib\site-packages\pkg_resources\__init__.py",
line 1065, in best_match
        return self.obtain(req, installer)
      File "C:\Python\Python38-32\lib\site-packages\pkg_resources\__init__.py",
line 1077, in obtain
        return installer(requirement)
      File "C:\Python\Python38-32\lib\site-packages\setuptools\dist.py", line 78
6, in fetch_build_egg
        return cmd.easy_install(req)
      File "C:\Python\Python38-32\lib\site-packages\setuptools\command\easy_inst
all.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "C:\Python\Python38-32\lib\site-packages\setuptools\command\easy_inst
all.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "C:\Python\Python38-32\lib\site-packages\setuptools\command\easy_inst
all.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "C:\Python\Python38-32\lib\site-packages\setuptools\command\easy_inst
all.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "C:\Python\Python38-32\lib\site-packages\setuptools\command\easy_inst
all.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "C:\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line
 253, in run_setup
        raise
      File "C:\Python\Python38-32\lib\contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line
 195, in setup_context
        yield
      File "C:\Python\Python38-32\lib\contextlib.py", line 131, in __exit__
        self.gen.throw(type, value, traceback)
      File "C:\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line
 166, in save_modules
        saved_exc.resume()
      File "C:\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line
 141, in resume
        six.reraise(type, exc, self._tb)
      File "C:\Python\Python38-32\lib\site-packages\setuptools\_vendor\six.py",
line 685, in reraise
        raise value.with_traceback(tb)
      File "C:\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line
 154, in save_modules
        yield saved
      File "C:\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line
 195, in setup_context
        yield
      File "C:\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line
 250, in run_setup
        _execfile(setup_script, ns)
      File "C:\Python\Python38-32\lib\site-packages\setuptools\sandbox.py", line
 45, in _execfile
        exec(code, globals, locals)
      File "C:\Users\Public\Documents\Wondershare\CreatorTemp\easy_install-5bqmw
koi\numpy-1.18.3\setup.py", line 488, in <module>
      File "C:\Users\Public\Documents\Wondershare\CreatorTemp\easy_install-5bqmw
koi\numpy-1.18.3\setup.py", line 469, in setup_package

      File "C:\Users\Public\Documents\Wondershare\CreatorTemp\easy_install-5bqmw
koi\numpy-1.18.3\setup.py", line 275, in generate_cython
        return False
    RuntimeError: Running cythonize failed!
    Cythonizing sources
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check th
e logs for full command output.

C:\Manim\manim_3_feb>

**Comment by radarhere** [comment]
Hi. This is the Pillow repository. Are you sure you didn't mean to create an issue at https://github.com/3b1b/manim ?

**Comment by radarhere** [comment]
To be helpful though, I would suggest `python -m pip install cython` and then re-running your command.

**Comment by uda3** [comment]
Thank you
