### ISSUE TITLE
Unrecognized Tiff from srtm

### ISSUE THREAD

**Issue by progserega** [python-pillow/Pillow#4819]
Get data from srtm: http://srtm.csi.cgiar.org/wp-content/uploads/files/srtm_5x5/TIFF/srtm_64_03.zip
Try open tif by pillow and code is crash:
```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import sys
import os
import numpy
from PIL import Image

image = Image.open(sys.argv[1])
print(image)
image.rotate(45).show()
image.save('1.png', 'png')
image.show()
```
I can not show, save, rotate, transform to numpy.array.

```
<PIL.TiffImagePlugin.TiffImageFile image mode=I;16S size=6000x6000 at 0x7F500FD68978>
Traceback (most recent call last):
  File "./test.py", line 23, in <module>
    image.rotate(45).show()
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 1596, in rotate
    self.load()
  File "/usr/lib/python3/dist-packages/PIL/ImageFile.py", line 177, in load
    self.load_prepare()
  File "/usr/lib/python3/dist-packages/PIL/ImageFile.py", line 251, in load_prepare
    self.im = Image.core.new(self.mode, self.size)
ValueError: unrecognized mode

```

**Comment by radarhere** [comment]
I'm able to run your code without a problem. What version of Pillow are you running?

**Comment by wiredfool** [comment]
This should be a single band Float32 image, which should be readable from Pillow.  

Did you forget to unzip the file first?

**Comment by progserega** [comment]
file says that it is not zip file:
```
Serega@host $ file srtm/srtm_63_04/srtm_63_04.tif
srtm/srtm_63_04/srtm_63_04.tif: TIFF image data, little-endian
Serega@host $ ./test.py srtm/srtm_63_04/srtm_63_04.tif
<PIL.TiffImagePlugin.TiffImageFile image mode=I;16S size=6000x6000 at 0x7F5602E63940>
Traceback (most recent call last):
  File "./test.py", line 22, in <module>
    image.rotate(45).show()
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 1596, in rotate
    self.load()
  File "/usr/lib/python3/dist-packages/PIL/ImageFile.py", line 177, in load
    self.load_prepare()
  File "/usr/lib/python3/dist-packages/PIL/ImageFile.py", line 251, in load_prepare
    self.im = Image.core.new(self.mode, self.size)
ValueError: unrecognized mode

```
Code:
```
      1 #!/usr/bin/env python3
      2 # -*- coding: utf-8 -*-
      3 
      4 #import httplib
      5 import sys
      6 import os
      7 import traceback
      8 import datetime
      9 import psycopg2
     10 import psycopg2.extras
     11 import tempfile
     12 import numpy
     13 import logging
     14 from logging import handlers
     15 from PIL import Image
     16 import configparser
     17 import path
     18 
     19 
     20 image = Image.open(sys.argv[1])
     21 print(image)
     22 image.rotate(45).show()
     23 image.save('1.png', 'png')
     24 image.show()
     25 sys.exit()

```

**Comment by progserega** [comment]
> This should be a single band Float32 image, which should be readable from Pillow.

It is 16 bit gray - one channel (it is success opened in qgis):
![1](https://user-images.githubusercontent.com/1297163/89112508-fba86c00-d4a6-11ea-8d5f-812cba97e110.png)

**Comment by progserega** [comment]
> I'm able to run your code without a problem. What version of Pillow are you running?

ii  python3-pil:amd64                             3.1.2-0ubuntu1.4                                         amd64        Python Imaging Library (Python3)

**Comment by progserega** [comment]
I remove dist package, install from pip:
```
pip3 install pillow
Collecting pillow
  Downloading Pillow-7.2.0-cp35-cp35m-manylinux1_x86_64.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB 386 kB/s
Installing collected packages: pillow
Successfully installed pillow-7.2.0
```
And it is start work correctry! Thank you very match! It my mistake - I was not understand out from pip:
```
pip3 install pillow
Requirement already satisfied: pillow in /usr/lib/python3/dist-packages (3.1.2)
```
I was undestand this as "already installed latest version"...

Thank you! I close bug.
