### ISSUE TITLE
SystemError on Image.new / fill for 32-bit mode with color tuple

### ISSUE THREAD

**Issue by bertsky** [python-pillow/Pillow#4925]
The following works smoothly:

```python
>>> PIL.Image.new('L', (200,100), (255,)) # accepts tuple
```

However, for 32-bit modes, this does not work:
```python
>>> PIL.Image.new('F', (200,100), (255,)) # fails okay
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/python3.6/site-packages/PIL/Image.py", line 2613, in new
    return im._new(core.fill(mode, size, color))
TypeError: must be real number, not tuple
>>> PIL.Image.new('I', (200,100), (255,)) # fails badly
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lib/python3.6/site-packages/PIL/Image.py", line 2613, in new
    return im._new(core.fill(mode, size, color))
SystemError: <built-in function fill> returned NULL without setting an error
```

At least the error message in the latter case should be improved.

But why not be more tolerant in both cases (I or F), like above (L or P)?

(Seen with Pillow 7.2.0 on Python 3.6.7 Linux x86_64.)

**Comment by bertsky** [comment]
Note: always allowing tuple would make it easier to pass values from `ImageStat.Stat().median` etc. (without checking for bands and unlisting)

**Comment by nulano** [comment]
With #4882 in master the last one has a proper error message:
```python
>>> PIL.Image.new('I', (200,100), (255,))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\git\pillow\src\PIL\Image.py", line 2621, in new
    return im._new(core.fill(mode, size, color))
TypeError: color must be int
```

**Comment by radarhere** [comment]
I've created PR #4927 as a suggestion to resolve this.
