### ISSUE TITLE
ValueError: unknown file extension: .png

### ISSUE THREAD

**Issue by angeloc** [python-pillow/Pillow#5034]
I was testing my compilation from sources.
Log says:
```
--------------------------------------------------------------------
PIL SETUP SUMMARY
--------------------------------------------------------------------
version      Pillow 8.0.1
platform     linux 3.9.0 (default, Nov  8 2020, 00:13:07)
             [GCC 9.3.0]
--------------------------------------------------------------------
--- JPEG support available
--- OPENJPEG (JPEG2000) support available (2.3)
--- ZLIB (PNG/ZIP) support available
*** LIBIMAGEQUANT support not available
--- LIBTIFF support available
*** FREETYPE2 support not available
*** LITTLECMS2 support not available
--- WEBP support available
*** WEBPMUX support not available
*** XCB (X protocol) support not available
--------------------------------------------------------------------
```
So I suppose everything is ok. 

Running this code
```python
from PIL import Image
 
img = Image.new('RGB', (60, 30), color = 'red')
img.save('pil_red.jpg')
img.save('pil_red.tiff')
img.save('pil_red.webp')
img.save('pil_red.png')
```

I obtain:
```
# python sample_python_pillow.py
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/PIL/Image.py", line 2131, in save
KeyError: '.png'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/sample_python_pillow.py", line 7, in <module>
    img.save('pil_red.png')
  File "/usr/lib/python3.9/site-packages/PIL/Image.py", line 2133, in save
ValueError: unknown file extension: .png
```
I'm running python3

**Comment by radarhere** [comment]
This will involve some back and forth, trying to figure out how this occurred. Would you be able to run this code on your system and report back the output?
```python
from PIL import Image

def register_extensions(id, extensions):
	print("register_extensions", extensions)
	for extension in extensions:
		Image.register_extension(id, extension)

Image.register_extensions = register_extensions

img = Image.new('RGB', (60, 30), color='red')
try:
	img.save('pil_red.png')
	print("png save sucessful")
except KeyError:
	print("png KeyErrror")
print()
print("extensions present", Image.EXTENSION)
print()

try:
	from PIL import PngImagePlugin
	print("PngImagePlugin import successful")
except:
	print("PngImagePlugin import failed")
	raise
```

**Comment by angeloc** [comment]
```
# python sample_python_pillow.py
register_extensions ['.tif', '.tiff']
register_extensions ['.jfif', '.jpe', '.jpg', '.jpeg']
register_extensions ['.pbm', '.pgm', '.ppm', '.pnm']
register_extensions ['.ps', '.eps']
register_extensions ['.fit', '.fits']
register_extensions ['.fli', '.flc']
register_extensions ['.ftc', '.ftu']
register_extensions ['.h5', '.hdf']
register_extensions ['.jp2', '.j2k', '.jpc', '.jpf', '.jpx', '.j2c']
register_extensions ['.mpg', '.mpeg']
register_extensions ['.bw', '.rgb', '.rgba', '.sgi']
register_extensions ['.tga', '.icb', '.vda', '.vst']
register_extensions ['.wmf', '.emf']
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/PIL/Image.py", line 2131, in save
KeyError: '.png'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/sample_python_pillow.py", line 12, in <module>
    img.save('pil_red.png')
  File "/usr/lib/python3.9/site-packages/PIL/Image.py", line 2133, in save
ValueError: unknown file extension: .png
```

**Comment by angeloc** [comment]
I think I found the problem. My version of self compiled Python doesn't have python zlib module enabled. This error gave me a clue
```
 File "/usr/lib/python3.9/site-packages/PIL/PngImagePlugin.py", line 39, in <module>
ModuleNotFoundError: No module named 'zlib'
```
