### ISSUE TITLE
OSError: encoder error -2 when saving JPEG2000 image

### ISSUE THREAD

**Issue by angeloc** [python-pillow/Pillow#5035]
Pillow compiled with this configuration
```
--------------------------------------------------------------------
PIL SETUP SUMMARY
--------------------------------------------------------------------
version      Pillow 8.0.1
platform     linux 3.9.0 (default, Nov  8 2020, 00:13:07)
             [GCC 9.3.0]
--------------------------------------------------------------------
--- JPEG support available
--- OPENJPEG (JPEG2000) support available (2.3)
--- ZLIB (PNG/ZIP) support available
*** LIBIMAGEQUANT support not available
--- LIBTIFF support available
*** FREETYPE2 support not available
*** LITTLECMS2 support not available
--- WEBP support available
*** WEBPMUX support not available
*** XCB (X protocol) support not available
--------------------------------------------------------------------
```

When I execute this code
```python
from PIL import Image
 
img = Image.new('RGB', (60, 30), color = 'red')
img.save('pil_red.jpg')
img.save('pil_red.jp2')
img.save('pil_red.tiff')
img.save('pil_red.webp')
img.save('pil_red.png')
```

I obtain this error
```
# python sample_python_pillow.py
Traceback (most recent call last):
  File "/root/sample_python_pillow.py", line 5, in <module>
    img.save('pil_red.jp2')
  File "/usr/lib/python3.9/site-packages/PIL/Image.py", line 2151, in save
  File "/usr/lib/python3.9/site-packages/PIL/Jpeg2KImagePlugin.py", line 300, in _save
  File "/usr/lib/python3.9/site-packages/PIL/ImageFile.py", line 544, in _save
OSError: encoder error -2 when writing image file
```

**Comment by radarhere** [comment]
Tracing the error, it is coming from
https://github.com/python-pillow/Pillow/blob/2d6e51e26c7683f067d29bd69f4fdf8eef003643/src/libImaging/Jpeg2KEncode.c#L500-L503

**Comment by angeloc** [comment]
Now I see, thanks.

So the codec is somewhat broken. I'll look into this, thanks again!
