### ISSUE TITLE
Unpopular `formats` argument of `PIL.Image.open` cause exceptions

### ISSUE THREAD

**Issue by tsangwpx** [python-pillow/Pillow#5036]
In `open()`, `preinit()`  only initialize popular formats, 
`_open_core()` will raise if the  given  formats have not been initialized. The `init()` failback become unreachable. 
https://github.com/python-pillow/Pillow/blob/2d6e51e26c7683f067d29bd69f4fdf8eef003643/src/PIL/Image.py#L2901-L2934

### What did you do?

```python
from __future__ import annotations

from PIL import Image


def main():
    with open('any.webp', 'rb') as f:
        try:
            im = Image.open(f, formats=('WEBP',))
        except Exception:
            print(Image.ID)  # No WEBP in the list
            raise
        else:
            print(im.size)


if __name__ == '__main__':
    main()

```

### What did you expect to happen?
Output the size
```console
(640, 480)
```

### What actually happened?
```console
['BMP', 'DIB', 'GIF', 'TIFF', 'JPEG', 'PPM', 'PNG']
Traceback (most recent call last):
  File "pil_debug.py", line 18, in <module>
    main()
  File "pil_debug.py", line 9, in main
    im = Image.open(f, formats=('WEBP',))
  File "lib\site-packages\PIL\Image.py", line 2929, in open
    im = _open_core(fp, filename, prefix, formats)
  File "lib\site-packages\PIL\Image.py", line 2909, in _open_core
    factory, accept = OPEN[i]
KeyError: 'WEBP'
```

### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python: 3.8
* Pillow: 8.0.1

**Comment by nulano** [comment]
You can import the WebP plugin explicitly to make sure it is loaded:
```python
from PIL import Image, WebPImagePlugin
im = Image.open("Downloads/1.webp", formats=("WEBP",))
# im = <PIL.WebPImagePlugin.WebPImageFile image mode=RGB size=550x368 at 0x233A9546508>
```

**Comment by radarhere** [comment]
I've created PR #5037 to resolve this.
