### ISSUE TITLE
Pillow 

### ISSUE THREAD

**Issue by StevenBucher98** [python-pillow/Pillow#5094]
I am having issues with reading an image that is a JPEG format with PILLOW, below is the short version of the error I get:

`PIL.UnidentifiedImageError: cannot identify image file <_io.BufferedReader name='data/ground/train/dirt/image6.JPEG'>`

I am using PIL version 8.0.1 and see that JPEG is a compatible format. Is this an issue with Pillow? I am thinking it might also be an issue with torchvision that I am also using in this program. I am using the [jetson-inference tutorial](https://github.com/dusty-nv/jetson-inference/blob/master/docs/pytorch-collect.md) for training my own model. Any help or insights onto what might be causing this issue would be greatly appreciated! Thank you and forgive me for naivety, I am new to a lot of this and python packages in general. 

Full error message:

`python3 train.py --model-dir=models/ground data/ground
Use GPU: 0 for training
=> dataset classes:  4 ['asphalt', 'concrete', 'dirt', 'gravel']
=> using pre-trained model 'resnet18'
=> reshaped ResNet fully-connected layer with: Linear(in_features=512, out_features=4, bias=True)
Epoch: [0][  0/236]	Time  9.345 ( 9.345)	Data  1.156 ( 1.156)	Loss 1.7914e+00 (1.7914e+00)	Acc@1  12.50 ( 12.50)	Acc@5 100.00 (100.00)
Traceback (most recent call last):
  File "train.py", line 506, in <module>
    main()
  File "train.py", line 135, in main
    main_worker(args.gpu, ngpus_per_node, args)
  File "train.py", line 277, in main_worker
    train(train_loader, model, criterion, optimizer, epoch, num_classes, args)
  File "train.py", line 321, in train
    for i, (images, target) in enumerate(train_loader):
  File "/home/steven/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 363, in __next__
    data = self._next_data()
  File "/home/steven/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 971, in _next_data
    return self._process_data(data)
  File "/home/steven/.local/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1014, in _process_data
    data.reraise()
  File "/home/steven/.local/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
PIL.UnidentifiedImageError: Caught UnidentifiedImageError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/home/steven/.local/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 185, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/steven/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/steven/.local/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.6/dist-packages/torchvision-0.7.0a0+78ed10c-py3.6-linux-aarch64.egg/torchvision/datasets/folder.py", line 137, in __getitem__
    sample = self.loader(path)
  File "/usr/local/lib/python3.6/dist-packages/torchvision-0.7.0a0+78ed10c-py3.6-linux-aarch64.egg/torchvision/datasets/folder.py", line 173, in default_loader
    return pil_loader(path)
  File "/usr/local/lib/python3.6/dist-packages/torchvision-0.7.0a0+78ed10c-py3.6-linux-aarch64.egg/torchvision/datasets/folder.py", line 155, in pil_loader
    img = Image.open(f)
  File "/usr/local/lib/python3.6/dist-packages/Pillow-8.0.1-py3.6-linux-aarch64.egg/PIL/Image.py", line 2944, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file <_io.BufferedReader name='data/ground/train/dirt/image6.JPEG'>`

**Comment by StevenBucher98** [comment]
Corrupted files, apologies for the inconvenience
