### ISSUE TITLE
[Errno 24] Too many open files when opening files with Pillow

### ISSUE THREAD

**Issue by uri-rodberg** [python-pillow/Pillow#5132]
### What did you do?
I executed this code in a loop, for about 6000 files:

```python
import logging
import boto3
from datetime import timedelta
from PIL import Image
from sorl.thumbnail import get_thumbnail

from django.core.management import BaseCommand
from django.utils.timezone import now
from django.template.loader import render_to_string

from speedy.core.accounts.models import User
from speedy.core.base.utils import is_transparent

logger = logging.getLogger(__name__)


class Command(BaseCommand):
    def handle(self, *args, **options):
        users = User.objects.filter(
            photo__date_created__lte=(now() - timedelta(minutes=5)),
        ).distinct(
        ).order_by('photo__date_created')
        for user in users:
            image = user.photo
            if ((image is not None) and (image.aws_image_moderation_time is not None) and (image.date_created <= (now() - timedelta(minutes=5)))):
                photo_is_valid = False
                labels_detected = False
                labels_detected_list = []
                try:
                    with Image.open(image.file) as _image:
                        if (getattr(_image, "is_animated", False)):
                            photo_is_valid = False
                            logger.error("moderate_unmoderated_photos::image is animated. user={user}, registered {registered_days_ago} days ago).".format(
                                user=user,
                                registered_days_ago=(now() - user.date_created).days,
                            ))
                        elif (is_transparent(_image)):
                            photo_is_valid = False
                            logger.error("moderate_unmoderated_photos::image is transparent. user={user}, registered {registered_days_ago} days ago).".format(
                                user=user,
                                registered_days_ago=(now() - user.date_created).days,
                            ))
                            image.visible_on_website = False
                            image.aws_image_moderation_time = now()
                            image.aws_raw_image_moderation_results = None
                            image.aws_raw_facial_analysis_results = None
                            image.aws_facial_analysis_time = None
                            image.number_of_faces = None
                            image.save()
                            user.speedy_match_profile.profile_picture_months_offset = 5
                            user.speedy_match_profile.save()
                        else:
                            photo_is_valid = True
                            logger.debug("moderate_unmoderated_photos::photo is valid. user={user}, registered {registered_days_ago} days ago).".format(
                                user=user,
                                registered_days_ago=(now() - user.date_created).days,
                            ))

                except Exception as e:
                    logger.error('moderate_unmoderated_photos::user={user}, Exception={e} (registered {registered_days_ago} days ago)'.format(
                        user=user,
                        e=str(e),
                        registered_days_ago=(now() - user.date_created).days,
                    ))



def is_transparent(image):
    """
    :type image: PIL.Image.Image
    """
    if ('transparency' in image.info):
        return True

    elif (image.mode == 'RGBA'):
        extrema = image.getextrema()
        if (extrema[3][0] < 255):
            return True

    return False

```

### What did you expect to happen?

The loop should work without exceptions.

### What actually happened?

If the loop is about 1000 files, everything is OK. But after around ~1010 files, I get this exception:

```
Traceback (most recent call last):
  File "/home/ubuntu/speedy-net/speedy/net/accounts/management/commands/1111_moderate_unmoderated_photos.py", line 30, in handle
    with Image.open(image.file) as _image:
  File "/home/ubuntu/speedy-net/env/lib/python3.6/site-packages/PIL/Image.py", line 2895, in open
    fp.seek(0)
  File "/home/ubuntu/speedy-net/env/lib/python3.6/site-packages/django/core/files/utils.py", line 20, in <lambda>
    seek = property(lambda self: self.file.seek)
  File "/home/ubuntu/speedy-net/env/lib/python3.6/site-packages/django/db/models/fields/files.py", line 43, in _get_file
    self._file = self.storage.open(self.name, 'rb')
  File "/home/ubuntu/speedy-net/env/lib/python3.6/site-packages/django/core/files/storage.py", line 36, in open
    return self._open(name, mode)
  File "/home/ubuntu/speedy-net/env/lib/python3.6/site-packages/django/core/files/storage.py", line 231, in _open
    return File(open(self.path(name), mode))
OSError: [Errno 24] Too many open files: '/home/ubuntu/speedy-net/media/../../../...jpg'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/speedy-net/speedy/net/manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/speedy-net/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/speedy-net/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/speedy-net/env/lib/python3.6/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/speedy-net/env/lib/python3.6/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/speedy-net/speedy/net/accounts/management/commands/1111_moderate_unmoderated_photos.py", line 63, in handle
    registered_days_ago=(now() - user.date_created).days,
  File "/usr/lib/python3.6/logging/__init__.py", line 1337, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/lib/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 865, in handle
    self.emit(record)
  File "/home/ubuntu/speedy-net/env/lib/python3.6/site-packages/django/utils/log.py", line 120, in emit
    message = "%s\n\n%s" % (self.format(no_exc_record), reporter.get_traceback_text())
  File "/home/ubuntu/speedy-net/env/lib/python3.6/site-packages/django/views/debug.py", line 335, in get_traceback_text
    with Path(CURRENT_DIR, 'templates', 'technical_500.txt').open(encoding='utf-8') as fh:
  File "/usr/lib/python3.6/pathlib.py", line 1183, in open
    opener=self._opener)
  File "/usr/lib/python3.6/pathlib.py", line 1037, in _opener
    return self._accessor.open(self, flags, mode)
  File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
OSError: [Errno 24] Too many open files: '/home/ubuntu/speedy-net/env/lib/python3.6/site-packages/django/views/templates/technical_500.txt'
```

If I run the same code without `logger`, it works without raising exceptions. But the same code with only `logger`, without using Pillow, works well without raising exceptions either. Therefore, it looks like a bug in Pillow.

### What are your OS, Python and Pillow versions?

* OS: Ubuntu 18.04.5 LTS
* Python: Python 3.6.9
* Pillow: Pillow==8.0.1
* Django: Django==3.1.4

**Comment by uri-rodberg** [comment]
OK, I managed to simplify the code. If I run this code:

```python
import logging
import boto3
from datetime import timedelta
from PIL import Image
from sorl.thumbnail import get_thumbnail

from django.core.management import BaseCommand
from django.utils.timezone import now
from django.template.loader import render_to_string

from speedy.core.accounts.models import User
from speedy.core.base.utils import is_transparent

logger = logging.getLogger(__name__)


class Command(BaseCommand):
    def handle(self, *args, **options):
        users = User.objects.filter(
            photo__date_created__lte=(now() - timedelta(minutes=5)),
        ).distinct(
        ).order_by('photo__date_created')
        for user in users:
            image = user.photo
            if ((image is not None) and (image.aws_image_moderation_time is not None) and (image.date_created <= (now() - timedelta(minutes=5)))):
                photo_is_valid = False
                labels_detected = False
                labels_detected_list = []
                with Image.open(image.file) as _image:
                    pass

```

I still get this exception:

```
Traceback (most recent call last):
  File "/home/ubuntu/speedy-net/speedy/net/manage.py", line 14, in <module>
    execute_from_command_line(sys.argv)
  File "/home/ubuntu/speedy-net/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/home/ubuntu/speedy-net/env/lib/python3.6/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/ubuntu/speedy-net/env/lib/python3.6/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/ubuntu/speedy-net/env/lib/python3.6/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/home/ubuntu/speedy-net/speedy/net/accounts/management/commands/5555_moderate_unmoderated_photos.py", line 29, in handle
    with Image.open(image.file) as _image:
  File "/home/ubuntu/speedy-net/env/lib/python3.6/site-packages/PIL/Image.py", line 2895, in open
    fp.seek(0)
  File "/home/ubuntu/speedy-net/env/lib/python3.6/site-packages/django/core/files/utils.py", line 20, in <lambda>
    seek = property(lambda self: self.file.seek)
  File "/home/ubuntu/speedy-net/env/lib/python3.6/site-packages/django/db/models/fields/files.py", line 43, in _get_file
    self._file = self.storage.open(self.name, 'rb')
  File "/home/ubuntu/speedy-net/env/lib/python3.6/site-packages/django/core/files/storage.py", line 36, in open
    return self._open(name, mode)
  File "/home/ubuntu/speedy-net/env/lib/python3.6/site-packages/django/core/files/storage.py", line 231, in _open
    return File(open(self.path(name), mode))
OSError: [Errno 24] Too many open files: '/home/ubuntu/speedy-net/media/../../../...jpg'
```

**Comment by acjh** [comment]
`image.file` is implicitly opened by the interaction between Pillow's `Image` and Django's `FieldFile`, so it has to be closed.

```diff
- with Image.open(image.file) as _image:
+ with image.file, Image.open(image.file) as _image:
```

# Explanation

`image.file` is of type `FieldFile`.

In `Image.open(image.file)`, where `fp` is `image.file`, `fp.seek(0)` accesses `FileProxyMixin.seek`:

```python
seek = property(lambda self: self.file.seek)
```

`self.file` accesses `FieldFile.file`, which opens the file:

```python
def _get_file(self):
    self._require_file()
    if getattr(self, '_file', None) is None:
        self._file = self.storage.open(self.name, 'rb')
    return self._file

def _set_file(self, file):
    self._file = file

def _del_file(self):
    del self._file

file = property(_get_file, _set_file, _del_file)
```

This behaviour in Django was present since Django 1.0 (https://github.com/django/django/commit/7899568e01fc9c68afe995fa71de915dd9fcdd76) but was never documented in https://docs.djangoproject.com/en/3.1/topics/files/#using-files-in-models.

To change this behaviour in Django would be a major breaking change.

Pillow could handle this with:

```python
if fp.closed:
    exclusive_fp = True
```

**Comment by uri-rodberg** [comment]
> `image.file` is of type `FieldFile`.

@acjh Do you mean `FileField`?

**Comment by acjh** [comment]
No, I do mean `FieldFile`.

```python
class FileField(Field):

    # The class to wrap instance attributes in. Accessing the file object off
    # the instance will always return an instance of attr_class.
    attr_class = FieldFile
```

**Comment by uri-rodberg** [comment]
@acjh Thank you, I was not aware that they are 2 different classes.

**Comment by radarhere** [comment]
So from our side, Pillow looks at the open file handle, and believes that if someone else opened it, then it is best to leave it for someone else to close.

> Pillow could handle this with:
> 
> ```python
> if fp.closed:
>     exclusive_fp = True
> ```

@acjh thanks for your write up. This part isn't clear to me though - where do you think this should go?

> `image.file` is implicitly opened by the interaction between Pillow's `Image` and Django's `FieldFile`, so it has to be closed.
> 
> ```diff
> - with Image.open(image.file) as _image:
> + with image.file, Image.open(image.file) as _image:
> ```
> 
@uri-rodberg were you able to give this a try?

**Comment by acjh** [comment]
It should go before `fp.seek(0)`, since the file would be opened when `seek` is accessed.

```diff
  def open(fp, mode="r", formats=None):
      ...

      if filename:
          fp = builtins.open(filename, "rb")
          exclusive_fp = True

+     if fp.closed:
+         # Wrappers (e.g. Django's FieldFile) may implicitly open the file when seek is accessed or called
+         exclusive_fp = True

      try:
          fp.seek(0)
      except (AttributeError, io.UnsupportedOperation):
          fp = io.BytesIO(fp.read())
          exclusive_fp = True
```

**Comment by uri-rodberg** [comment]
> > `image.file` is implicitly opened by the interaction between Pillow's `Image` and Django's `FieldFile`, so it has to be closed.
> > ```diff
> > - with Image.open(image.file) as _image:
> > + with image.file, Image.open(image.file) as _image:
> > ```
> 
> @uri-rodberg were you able to give this a try?

@radarhere Yes, changing to `with image.file, Image.open(image.file) as _image:` solves the problem - there are no exceptions even for 6000 files.

**Comment by uri-rodberg** [comment]
>     if fp.closed:
>         # Wrappers (e.g. Django's FieldFile) may implicitly open the file when seek is accessed or called
>         exclusive_fp = True

@acjh It looks to me like these lines might raise an exception. Maybe they should be put in try..except.

**Comment by radarhere** [comment]
I'm trying to figure out why that should change anything. The [Django closed property](https://github.com/django/django/blob/429d089d0a8fbd400e0c010708df4f0d16218970/django/db/models/fields/files.py#L116-L119)
```python
@property
def closed(self):
    file = getattr(self, '_file', None)
    return file is None or file.closed
```
doesn't seem to do anything unexpected, so surely it would not be closed at the time when Pillow `open` is called.

**Comment by acjh** [comment]
In `closed`, `file` is `None` before `FieldFile.file` is accessed, so it returns `True`.

**Comment by radarhere** [comment]
Ok, I understand now.

This seems like a bit of a gray area, because Pillow is not opening the file handle itself, nor being handed an open file handle. Pillow is unknowingly asking other code to open the file handle.

I'm more inclined to say that the behaviour should stay as is. If a user wanted to use `image.file` with Pillow, and then still use it afterwards, say -

```python
with Image.open(image.file) as _image:
    pass
with Image.open(image.file) as _image:
    pass
```

your change would cause this situation to fail, since the file pointer has been closed.

**Comment by uri-rodberg** [comment]
> I'm more inclined to say that the behaviour should stay as is. If a user wanted to use `image.file` with Pillow, and then still use it afterwards, say -
> 
> ```python
> with Image.open(image.file) as _image:
>     pass
> with Image.open(image.file) as _image:
>     pass
> ```
> 
> your change would cause this situation to fail, since the file pointer has been closed.

I think in this case, it will just open the file twice. It will not fail.

**Comment by radarhere** [comment]
When I test it, it fails. Let me know if you find otherwise.

**Comment by acjh** [comment]
Yes, it fails as `FieldFile._get_file` (code above) only opens the file when `self._file` is `None`.

Alternatively, Pillow could disallow this with:

```python
if hasattr(fp, 'closed') and fp.closed:
    raise ValueError("I/O operation on closed file")
```

...since the docstring of `Image.open` mentions:

```
The file object must implement ...
... methods,
and be opened in binary mode.
```

Then the usage should be:

```python
with image.file.open(), Image.open(image.file) as _image:
```

```python
with image.file.open():
    with Image.open(image.file) as _image:
        pass
    with Image.open(image.file) as _image:
        pass
```

**Comment by uri-rodberg** [comment]
> Then the usage should be:
> 
> ```python
> with image.file.open(), Image.open(image.file) as _image:
> ```

This will break existing code such as `with Image.open(image.file) as _image:` or `with image.file, Image.open(image.file) as _image:`.

**Comment by acjh** [comment]
Well, that existing code is relying on behaviour that contradicts the documented requirement: "must ... be opened"

That said, it can be made to be turned on by a feature flag until the next major version of Pillow.

I think it is better than silently leaving open files.

**Comment by wiredfool** [comment]
I don't think that Pillow should do 'magic' stuff based on a closed attribute from other code. 

The responsibility here is pretty clear:
* If Pillow opens the file and it can close it, it does. 
* If you open the file, you're responsible for it. 

(ymmv with animated files).

This is an edge case, but it's pretty clear that it's the outside code doing unexpected things. This is probably not a problem in 99% of cases, because the file will be closed at the end of a request when the objects are destroyed. It's only a problem when iterating over many files.

**Comment by radarhere** [comment]
Closed, as there is a clear solution to the original problem, and it doesn't seem that Pillow needs to change its behaviour.
