### ISSUE TITLE
 The headers or library files could not be found for zlib, a required dependency when compiling Pillow from source

### ISSUE THREAD

**Issue by hwkin** [python-pillow/Pillow#5241]
os: windows10 2004 proworkstation, with windows feature experience pack 120.27512.10351.0.
python version:3.9.0rc2.
pip.exe version:21.0
Problem:
I am installing easyocr (by the command 'pip install easyocr') . As the pip.exe was trying to uninstall pillow8.1.0 which was installed alone and install pillow 6.2.2 which may fit easyocr, the question occured.
I had searched about it but the issue contents did answered nothing.
Here are some logs:

```
  **Attempting uninstall: Pillow
    Found existing installation: pillow 8.1.0
    Uninstalling pillow-8.1.0:
      Successfully uninstalled pillow-8.1.0
    Running setup.py install for Pillow ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\tony\appdata\local\programs\python\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\tony\\AppData\\Local\\Temp\\pip-install-gaanm2k_\\pillow_10b52e7e901b49ebba6ea09d411fb694\\setup.py'"'"'; __file__='"'"'C:\\Users\\tony\\AppData\\Local\\Temp\\pip-install-gaanm2k_\\pillow_10b52e7e901b49ebba6ea09d411fb694\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\tony\AppData\Local\Temp\pip-record-xtto4u5m\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\tony\appdata\local\programs\python\python39\Include\Pillow'
         cwd: C:\Users\tony\AppData\Local\Temp\pip-install-gaanm2k_\pillow_10b52e7e901b49ebba6ea09d411fb694\
    Complete output (176 lines):
    C:\Users\tony\AppData\Local\Temp\pip-install-gaanm2k_\pillow_10b52e7e901b49ebba6ea09d411fb694\setup.py:28: RuntimeWarning: Pillow does not yet support Python 3.9 and does not yet provide prebuilt Windows binaries. We do not recommend building from source on Windows.
      warnings.warn(
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\PIL
    copying src\PIL\BdfFontFile.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\BlpImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\BmpImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\BufrStubImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ContainerIO.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\CurImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\DcxImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\DdsImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\EpsImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ExifTags.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\features.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\FitsStubImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\FliImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\FontFile.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\FpxImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\FtexImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\GbrImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\GdImageFile.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\GifImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\GimpGradientFile.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\GimpPaletteFile.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\GribStubImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\Hdf5StubImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\IcnsImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\IcoImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\Image.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageChops.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageCms.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageColor.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageDraw.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageDraw2.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageEnhance.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageFile.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageFilter.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageFont.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageGrab.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageMath.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageMode.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageMorph.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageOps.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImagePalette.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImagePath.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageQt.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageSequence.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageShow.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageStat.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageTk.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageTransform.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageWin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImtImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\IptcImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\Jpeg2KImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\JpegImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\JpegPresets.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\McIdasImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\MicImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\MpegImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\MpoImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\MspImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PaletteFile.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PalmImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PcdImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PcfFontFile.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PcxImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PdfImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PdfParser.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PixarImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PngImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PpmImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PsdImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PSDraw.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PyAccess.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\SgiImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\SpiderImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\SunImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\TarIO.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\TgaImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\TiffImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\TiffTags.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\WalImageFile.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\WebPImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\WmfImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\XbmImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\XpmImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\XVThumbImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\_binary.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\_tkinter_finder.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\_util.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\_version.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\__init__.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\__main__.py -> build\lib.win-amd64-3.9\PIL
    running egg_info
    writing src\Pillow.egg-info\PKG-INFO
    writing dependency_links to src\Pillow.egg-info\dependency_links.txt
    writing top-level names to src\Pillow.egg-info\top_level.txt
    reading manifest file 'src\Pillow.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.c'
    warning: no files found matching '*.h'
    warning: no files found matching '*.sh'
    warning: no previously-included files found matching '.appveyor.yml'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.codecov.yml'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.readthedocs.yml'
    warning: no previously-included files found matching 'azure-pipelines.yml'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    no previously-included directories found matching '.azure-pipelines'
    no previously-included directories found matching '.travis'
    writing manifest file 'src\Pillow.egg-info\SOURCES.txt'
    running build_ext


    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html

    Traceback (most recent call last):
      File "C:\Users\tony\AppData\Local\Temp\pip-install-gaanm2k_\pillow_10b52e7e901b49ebba6ea09d411fb694\setup.py", line 852, in <module>
        setup(
      File "c:\users\tony\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 165, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\tony\appdata\local\programs\python\python39\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\tony\appdata\local\programs\python\python39\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\tony\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\tony\appdata\local\programs\python\python39\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\tony\appdata\local\programs\python\python39\lib\distutils\command\install.py", line 546, in run
        self.run_command('build')
      File "c:\users\tony\appdata\local\programs\python\python39\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\tony\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\tony\appdata\local\programs\python\python39\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\users\tony\appdata\local\programs\python\python39\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\tony\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\tony\appdata\local\programs\python\python39\lib\distutils\command\build_ext.py", line 340, in run
        self.build_extensions()
      File "C:\Users\tony\AppData\Local\Temp\pip-install-gaanm2k_\pillow_10b52e7e901b49ebba6ea09d411fb694\setup.py", line 687, in build_extensions
        raise RequiredDependencyException(f)
    __main__.RequiredDependencyException: zlib

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\tony\AppData\Local\Temp\pip-install-gaanm2k_\pillow_10b52e7e901b49ebba6ea09d411fb694\setup.py", line 903, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:

    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html**


    ----------------------------------------
  Rolling back uninstall of pillow
  Moving to c:\users\tony\appdata\local\programs\python\python39\lib\site-packages\pil\
   from C:\Users\tony\AppData\Local\Programs\Python\Python39\Lib\site-packages\~il
  Moving to c:\users\tony\appdata\local\programs\python\python39\lib\site-packages\pillow-8.1.0.dist-info\
   from C:\Users\tony\AppData\Local\Programs\Python\Python39\Lib\site-packages\~illow-8.1.0.dist-info
```

I am trying to make a little progress by doing some research on 'zlib'. If there has been already some solutions, please stick them here, thanks.
ps. No one can push me to return python to any other version, so do pip or operating system.

**Comment by hugovk** [comment]
You're trying to install Pillow 6.2.2 for Python 3.9.

In your logs it says:

> RuntimeWarning: Pillow does not yet support Python 3.9 and does not yet provide prebuilt Windows binaries. We do not recommend building from source on Windows.

So we only support Python 3.9 from Pillow 8.0 and up:

https://pillow.readthedocs.io/en/stable/installation.html#python-support

Because we don't support it, there are no prebuilt binary wheels, and it's attempting to build 6.2. from source, which is tricky on Windows. You need to install prerequisites (https://pillow.readthedocs.io/en/stable/installation.html#python-support) and a compiler.

Which is why for Windows, we strongly recommend using Pillow 8.0+.

Looks like EasyOCR has fixed some problems which meant they pinned Pillow to an old version: 

* https://github.com/JaidedAI/EasyOCR/issues/99
* https://github.com/JaidedAI/EasyOCR/issues/237

What version of EasyOCR are you trying to install? I suggest first updating pip (`pip install -U pip`), and then `pip install -U easyocr`.

**Comment by radarhere** [comment]
Closing, as there is a straightforward solution, and no response. This can be re-opened if there are any further questions.

**Comment by sanketsans** [comment]
Since in the error it says a dependency is missing. 
`The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.`

You can try installing those dependency. It worked for me since for me jpeg dependency was missing. I installed thanks to the answer here. https://stackoverflow.com/questions/54496599/pip-cant-install-pillow

**Comment by PaulLam0907** [comment]
I've got the same problem when compiling to Android x86_64
Just want to suggest a solution for others as a reference
( compiled successfully , but don't know if it's work )

- after the first build failed
- in your project dir
- go to  `./.buildozer/android/platform/python-for-android/pythonforandroid/recipes/`  to change the `NDK` and `xlib` path for required recipes
- in e.g.  `./Pillow/`  or  `./Python3/`
- find sth like :
```
ndk_lib_dir = join(self.ctx.ndk_platform, 'usr', 'lib')
```
```
zlib_lib_path = join(self.ctx.ndk_platform, 'usr', 'lib')
```
- and comment or replace it with
```
ndk_lib_dir = join(self.ctx.ndk_platform, 'usr', 'lib64')
```
```
zlib_lib_path = join(self.ctx.ndk_platform, 'usr', 'lib64')
```

- save it and try re-build the project


ref. :
Question : [Android x86_64 instant crash with hello world app, missing zlib](https://issueexplorer.com/issue/kivy/python-for-android/2460)

docs. : [grep](https://help.ubuntu.com/community/grep)

stackexchange question : [How to search strings inside files like in Windows without search monkey?](https://askubuntu.com/questions/513046/how-to-search-strings-inside-files-like-in-windows-without-search-monkey)

stackoverflow question : [How to grep and replace](https://stackoverflow.com/questions/15402770/how-to-grep-and-replace)

**Comment by narva8916** [comment]
setting this env variables works for me 

export PKG_CONFIG_PATH="/usr/local/opt/zlib/lib/pkgconfig" 
export LDFLAGS="-L/usr/local/opt/zlib/lib"                
export CPPFLAGS="-I/usr/local/opt/zlib/include"
