### ISSUE TITLE
Incompatible libjpeg.9.dylib version in PIL/.dylibs

### ISSUE THREAD

**Issue by yoramzarai** [python-pillow/Pillow#5257]
### What did you do?
I created a virtual environment with python version 3.9, activated it and pip installed Matplotlib. Then, in the Python prompt, I ran ```import matplotlib.pyplot as plt```, and received the error message (see below) pointing to an issue with the ```libjpeg.9.dylib``` version.

The same behavior was also observed with Python version 3.8.

### What did you expect to happen?
package imported successfully.

### What actually happened?
Got an error (see below)

### What are your OS, Python and Pillow versions?

* OS: MAC OS 10.15.7
* Python: 3.9.1
* Pillow: 8.1.0

Following are all the steps that I did.
```
yoramzarai@Yorams-MacBook-Pro-retina.local  ~/work/Temp 
37%>python3.9 --version
Python 3.9.1

yoramzarai@Yorams-MacBook-Pro-retina.local  ~/work/Temp 
38%>python3.9 -m venv ./v39

yoramzarai@Yorams-MacBook-Pro-retina.local  ~/work/Temp 
39%>source ./v39/bin/activate
(v39) 
yoramzarai@Yorams-MacBook-Pro-retina.local  ~/work/Temp 
40%>pip install pip --upgrade
Collecting pip
  Using cached pip-21.0.1-py3-none-any.whl (1.5 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.2.3
    Uninstalling pip-20.2.3:
      Successfully uninstalled pip-20.2.3
Successfully installed pip-21.0.1
(v39) 
yoramzarai@Yorams-MacBook-Pro-retina.local  ~/work/Temp 
41%>pip install matplotlib
Collecting matplotlib
  Using cached matplotlib-3.3.4-cp39-cp39-macosx_10_9_x86_64.whl (8.5 MB)
Collecting kiwisolver>=1.0.1
  Using cached kiwisolver-1.3.1-cp39-cp39-macosx_10_9_x86_64.whl (61 kB)
Collecting numpy>=1.15
  Using cached numpy-1.20.1-cp39-cp39-macosx_10_9_x86_64.whl (16.1 MB)
Collecting cycler>=0.10
  Using cached cycler-0.10.0-py2.py3-none-any.whl (6.5 kB)
Collecting python-dateutil>=2.1
  Using cached python_dateutil-2.8.1-py2.py3-none-any.whl (227 kB)
Collecting pillow>=6.2.0
  Using cached Pillow-8.1.0-cp39-cp39-macosx_10_10_x86_64.whl (2.2 MB)
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3
  Using cached pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Installing collected packages: six, python-dateutil, pyparsing, pillow, numpy, kiwisolver, cycler, matplotlib
Successfully installed cycler-0.10.0 kiwisolver-1.3.1 matplotlib-3.3.4 numpy-1.20.1 pillow-8.1.0 pyparsing-2.4.7 python-dateutil-2.8.1 six-1.15.0
(v39) 
yoramzarai@Yorams-MacBook-Pro-retina.local  ~/work/Temp 
42%>python
Python 3.9.1 (default, Dec  8 2020, 11:42:15) 
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib.pyplot as plt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yoramzarai/work/Temp/v39/lib/python3.9/site-packages/matplotlib/pyplot.py", line 36, in <module>
    import matplotlib.colorbar
  File "/Users/yoramzarai/work/Temp/v39/lib/python3.9/site-packages/matplotlib/colorbar.py", line 44, in <module>
    import matplotlib.contour as contour
  File "/Users/yoramzarai/work/Temp/v39/lib/python3.9/site-packages/matplotlib/contour.py", line 17, in <module>
    import matplotlib.text as text
  File "/Users/yoramzarai/work/Temp/v39/lib/python3.9/site-packages/matplotlib/text.py", line 16, in <module>
    from .textpath import TextPath  # Unused, but imported by others.
  File "/Users/yoramzarai/work/Temp/v39/lib/python3.9/site-packages/matplotlib/textpath.py", line 11, in <module>
    from matplotlib.mathtext import MathTextParser
  File "/Users/yoramzarai/work/Temp/v39/lib/python3.9/site-packages/matplotlib/mathtext.py", line 27, in <module>
    from PIL import Image
  File "/Users/yoramzarai/work/Temp/v39/lib/python3.9/site-packages/PIL/Image.py", line 94, in <module>
    from . import _imaging as core
ImportError: dlopen(/Users/yoramzarai/work/Temp/v39/lib/python3.9/site-packages/PIL/_imaging.cpython-39-darwin.so, 2): Library not loaded: @loader_path/.dylibs/libjpeg.9.dylib
  Referenced from: /Users/yoramzarai/work/Temp/v39/lib/python3.9/site-packages/PIL/_imaging.cpython-39-darwin.so
  Reason: Incompatible library version: _imaging.cpython-39-darwin.so requires version 14.0.0 or later, but libjpeg.9.dylib provides version 13.0.0
>>> 

```

**Comment by radarhere** [comment]
Thanks for the detailed report.

If you don't `import matplotlib`, but just run `from PIL import Image`, does the error still occur?

**Comment by yoramzarai** [comment]
Yes:

```
yoramzarai@Yorams-MacBook-Pro-retina.local  ~/work/Temp 
45%>source ./v39/bin/activate
(v39) 
yoramzarai@Yorams-MacBook-Pro-retina.local  ~/work/Temp 
46%>python
Python 3.9.1 (default, Dec  8 2020, 11:42:15) 
[Clang 11.0.3 (clang-1103.0.32.62)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/yoramzarai/work/Temp/v39/lib/python3.9/site-packages/PIL/Image.py", line 94, in <module>
    from . import _imaging as core
ImportError: dlopen(/Users/yoramzarai/work/Temp/v39/lib/python3.9/site-packages/PIL/_imaging.cpython-39-darwin.so, 2): Library not loaded: @loader_path/.dylibs/libjpeg.9.dylib
  Referenced from: /Users/yoramzarai/work/Temp/v39/lib/python3.9/site-packages/PIL/_imaging.cpython-39-darwin.so
  Reason: Incompatible library version: _imaging.cpython-39-darwin.so requires version 14.0.0 or later, but libjpeg.9.dylib provides version 13.0.0
>>> 
```

**Comment by radarhere** [comment]
I tried to replicate this on GitHub Actions - https://github.com/radarhere/pillow-wheels/commit/ce2bae982e7f6a8265fbf0f86dfd78f23755c08d - but it [passes](https://github.com/radarhere/pillow-wheels/runs/1969921585). So I have to conclude there is something specific about your setup that is triggering this.

**Comment by yoramzarai** [comment]
Thank you.

Any idea what can cause this, as it seems that both ```_imaging.cpython-39-darwin.so``` and ```.dylibs/libjpeg.9.dylib``` are under the ```PIL``` folder in the virtual environment (```v39/lib/python3.9/site-packages/PIL/```)?

**Comment by yoramzarai** [comment]
I had in my ```.bashrc``` the following: ```export DYLD_LIBRARY_PATH=/Applications/Inkscape.app/Contents/Resources/lib```. I commented this out and now ```import matplotlib.pyplot as plt``` works fine. Not sure why this caused the issue.

**Comment by wiredfool** [comment]
Well, on my machine, that folder contains libfreetype and libjpeg and libtiff, and harfbuzz, and.... so it's not surprising that there were some version conflicts.

**Comment by yoramzarai** [comment]
Thank you. Closing.

**Comment by chasonyu** [comment]
The solution can be found here [How to run pyhdf with Anaconda Python3](http://hdfeos.org/forums/showthread.php?t=817)
```
[nene:~/anaconda3/bin] hyoklee% mv  ~/anaconda3/lib/libjpeg.9.dylib ~/anaconda3/lib/libjpeg.9.dylib-
[nene:~/anaconda3/bin] hyoklee% cd ~/anaconda3/lib
[nene:~/anaconda3/lib] hyoklee% ln -s /usr/local/lib/libjpeg.9.dylib
```

**Comment by arunppsg** [comment]
I reinstalled `pillow` and it worked!

**Comment by bitratek** [comment]
conda install -c conda-forge dlib

This worked like a charm for me

**Comment by renli1024** [comment]
For me it's because `torchvision` package restrict the `jpeg` package's version. You can try uninstall `torchvision` and conda will automatically upgrade the `jpeg` package, then it should be fixed.

**Comment by harshaut** [comment]
> conda install -c conda-forge dlib

Yes, this worked for me too!

**Comment by mystoryshine** [comment]
just `conda update conda` and it worked!

**Comment by kourouklides** [comment]
None of the above solution worked for me. However, `brew upgrade jpeg` worked.
