### ISSUE TITLE
Cannot open JPEG exported with Adobe Photoshop Lightroom Classic 10.1 (Macintosh)

### ISSUE THREAD

**Issue by janokruta** [python-pillow/Pillow#5486]
### Problem
Opening a JPEG image exported with `Adobe Photoshop Lightroom Classic 10.1 (Macintosh)`, raises a `PIL.UnidentifiedImageError`.

### Code
```python
from PIL import Image

img = Image.open("image.jpg")
```

### Output
```
Traceback (most recent call last):
  File "script.py", line 3, in <module>
    img = Image.open("image.jpg")
  File ".virtualenvs/venv/lib/python3.9/site-packages/PIL/Image.py", line 2967, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file 'image.jpg'
```

### Image metadata
```python
{
    'EXIF ColorSpace': (0xA001) Short=sRGB @ 220,
    'EXIF DateTimeOriginal': (0x9003) ASCII=2017:12:31 19:11:46 @ 228,
    'EXIF ExifVersion': (0x9000) Undefined=0231 @ 184,
    'EXIF OffsetTime': (0x9010) ASCII=-08:00 @ 248,
    'Image DateTime': (0x0132) ASCII=2021:02:02 20:07:02 @ 154,
    'Image ExifOffset': (0x8769) Long=174 @ 78,
    'Image ResolutionUnit': (0x0128) Short=Pixels/Inch @ 42,
    'Image Software': (0x0131) ASCII=Adobe Photoshop Lightroom Classic 10.1 (Macintosh) @ 102,
    'Image XResolution': (0x011A) Ratio=240 @ 86,
    'Image YResolution': (0x011B) Ratio=240 @ 94,
    'Thumbnail Compression': (0x0103) Short=JPEG (old-style) @ 266,
    'Thumbnail JPEGInterchangeFormat': (0x0201) Long=350 @ 314,
    'Thumbnail JPEGInterchangeFormatLength': (0x0202) Long=31874 @ 326,
    'Thumbnail ResolutionUnit': (0x0128) Short=Pixels/Inch @ 302,
    'Thumbnail XResolution': (0x011A) Ratio=72 @ 334,
    'Thumbnail YResolution': (0x011B) Ratio=72 @ 342
}
```

### Conclusion
Overriding the image with Gimp fixes the problem, so I assume `'Image Software': (0x0131) ASCII=Adobe Photoshop Lightroom Classic 10.1 (Macintosh) @ 102` is guilty.

* OS: Ubuntu 20.04.2 LTS
* Python: 3.9.5
* Pillow: 8.2.0

**Comment by radarhere** [comment]
@janokruta without a copy of the image, this is hard to debug.

I doubt that this is actually a problem with all JPEGs exported by that software. I'm not even sure if it possible to acquire a copy of exactly Adobe Photoshop Lightroom Classic 10.1, considering that it is not listed at https://helpx.adobe.com/lightroom-classic/help/whats-new.html.

**Comment by radarhere** [comment]
Closing, due to lack of a response.
