### ISSUE TITLE
PNG: SyntaxError: not a TIFF file

### ISSUE THREAD

**Issue by doublex** [python-pillow/Pillow#5528]
This PNG throws error (I don't know if this is an issue or not): 
![000000000396](https://user-images.githubusercontent.com/274624/121161768-9b642280-c84d-11eb-8f1b-db9d1a3d6a4c.png)

````python
import PIL.Image, PIL.ImageOps
with PIL.Image.open('/tmp/121161768-9b642280-c84d-11eb-8f1b-db9d1a3d6a4c.png') as img:
    img = PIL.ImageOps.exif_transpose( img )
````

Throws:
````
Traceback (most recent call last):
  File "r1.py", line 3, in <module>
    img = PIL.ImageOps.exif_transpose( img )
  File "/home/max/.local/lib/python3.8/site-packages/PIL/ImageOps.py", line 550, in exif_transpose
    exif = image.getexif()
  File "/home/max/.local/lib/python3.8/site-packages/PIL/PngImagePlugin.py", line 977, in getexif
    return super().getexif()
  File "/home/max/.local/lib/python3.8/site-packages/PIL/Image.py", line 1324, in getexif
    self._exif.load(exif_info)
  File "/home/max/.local/lib/python3.8/site-packages/PIL/Image.py", line 3353, in load
    self._info = TiffImagePlugin.ImageFileDirectory_v2(self.head)
  File "/home/max/.local/lib/python3.8/site-packages/PIL/TiffImagePlugin.py", line 470, in __init__
    raise SyntaxError(f"not a TIFF file (header {repr(ifh)} not valid)")
SyntaxError: not a TIFF file (header b'\x00\x08\x00\x02\x01\x12\x00\x03' not valid)
````

**Comment by radarhere** [comment]
exiftool agrees that there is a problem with the image's Exif data.

```
$ exiftool issue.png | grep -i exif
ExifTool Version Number         : 12.16
Warning                         : Error inflating eXIf
```

**Comment by doublex** [comment]
@radarhere 
If this is not an issue `pillow` should handle - please close this ticket.

**Comment by radarhere** [comment]
pngcheck also agrees.
```
$ pngcheck -v sample.png | grep -i exif
  chunk eXIf at offset 0x34893, length 124: EXIF metadata, unrecognized format: 0x00 0x08 0x00 0x02
```
So yes, I would conclude that there is a problem with the EXIF data.
