### ISSUE TITLE
OSError: cannot open resource on Japanese Windows 10

### ISSUE THREAD

**Issue by KeitoTobi1** [python-pillow/Pillow#5543]
### What did you do?

I tried the following code to get the text into the image:

```python
ANNOTATION_FONT_SIZE = 20
fnt = ImageFont.truetype("C:\windows\font\arial.ttf", ANNOTATION_FONT_SIZE)
text = "Test Text"
text_color = (64, 148, 224)
draw = ImageDraw.draw()
draw.text((50, 50), text, text_color, font=fnt)
```

### What did you expect to happen?

Text Drawing.

### What actually happened?

Application Crashed, 

```
Traceback (most recent call last):
  File "bug_issue.py", line 4, in <module>
    fnt = ImageFont.truetype("C:\windows\font\arial.ttf", ANNOTATION_FONT_SIZE)
  File "C:\Users\KeitoTobi1\anaconda3\envs\base\lib\site-packages\PIL\ImageFont.py", line 853, in truetype
    return freetype(font)
  File "C:\Users\KeitoTobi1\anaconda3\envs\base\lib\site-packages\PIL\ImageFont.py", line 850, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "C:\Users\KeitoTobi1\anaconda3\envs\base\lib\site-packages\PIL\ImageFont.py", line 210, in __init__
    font, size, index, encoding, layout_engine=layout_engine
OSError: cannot open resource
```

### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python: 3.7.10
* Pillow: 8.2.0

```python
ANNOTATION_FONT_SIZE = 20
fnt = ImageFont.truetype("C:\windows\font\arial.ttf", ANNOTATION_FONT_SIZE)
text = "Test Text"
text_color = (64, 148, 224)
draw = ImageDraw.draw()
draw.text((50, 50), text, text_color, font=fnt)
```

**Comment by radarhere** [comment]
Are you certain that you have the correct path for your font? If you run this code, does Python think the path exists?
```python
import os
print(os.path.exists("C:\windows\font\arial.ttf"))
```

**Comment by KeitoTobi1** [comment]
As a result of input, it was like this: 
```
False
```

**Comment by KeitoTobi1** [comment]
Sorry. Resolved.
