### ISSUE TITLE
OSError: invalid argument for chinese fonts name

### ISSUE THREAD

**Issue by wanghaisheng** [python-pillow/Pillow#5685]
pillow  8.3.1
windows 10

if i remove encoding parameter, it works but there is a lot missing text showing in the output image
```console
$ python font.py 
Traceback (most recent call last):
  File "D:\Program Files\anaconda3\lib\site-packages\PIL\ImageFont.py", line 204, in __init__
    font_bytes_path.decode("ascii")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 14: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "font.py", line 3, in <module>
    text_font=ImageFont.truetype('image/default/经典繁毛楷.TTF',40,encoding="big5")
  File "D:\Program Files\anaconda3\lib\site-packages\PIL\ImageFont.py", line 855, in truetype
    return freetype(font)
  File "D:\Program Files\anaconda3\lib\site-packages\PIL\ImageFont.py", line 852, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "D:\Program Files\anaconda3\lib\site-packages\PIL\ImageFont.py", line 209, in __init__
    load_from_bytes(f)
  File "D:\Program Files\anaconda3\lib\site-packages\PIL\ImageFont.py", line 196, in load_from_bytes
    self.font = core.getfont(
OSError: invalid argument
(base) 

````

```python
from PIL import ImageFont

text_font=ImageFont.truetype('image/default/经典繁毛楷.TTF',40,encoding="big5")
```

i also try to change path to 

```python
from PIL import ImageFont

text_font=ImageFont.truetype('经典繁毛楷.TTF',40,encoding="big5")
def printFontPath(path):
	import os
	windir = os.environ.get("WINDIR")
	if windir:
		print("Note: Searches in "+os.path.join(windir, "fonts"))
	else:
		print("Note: No WINDIR present")
	
	from PIL import ImageFont
	freeType = ImageFont.FreeTypeFont

	class FreeTypeFont(freeType):
		def __init__(self, font=None, size=10, index=0, encoding="", layout_engine=None):
			if font != path:
				print(font)
			super().__init__(font, size, index, encoding, layout_engine)

	ImageFont.FreeTypeFont = FreeTypeFont
	try:
		ImageFont.truetype(path)
	except OSError:
		pass

printFontPath("经典繁毛楷.TTF")
```
```console
$ python font.py
Note: Searches in C:\Windows\fonts
(base) 
```

third try to rename ttf filename to english characters
```console
$ python font.py 
Traceback (most recent call last):
  File "font.py", line 3, in <module>
    text_font=ImageFont.truetype('image/default/fanmaokai.TTF',40,encoding="big5")
  File "D:\Program Files\anaconda3\lib\site-packages\PIL\ImageFont.py", line 855, in truetype
    return freetype(font)
  File "D:\Program Files\anaconda3\lib\site-packages\PIL\ImageFont.py", line 852, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "D:\Program Files\anaconda3\lib\site-packages\PIL\ImageFont.py", line 211, in __init__
    self.font = core.getfont(
OSError: invalid argument
(base) 
```

i also tried to convert fonts using fontforge and online tools 
Trying to inspect the font with https://fontdrop.info,  it seems fine

[经典繁毛楷.zip](https://github.com/sam210723/xrit-rx/files/7033709/default.zip)

**Comment by radarhere** [comment]
If I install https://github.com/fonttools/fonttools and try to convert this font to TTX to find out more information, I get an error -

```
AssertionError: In format 4 cmap, range (97), the calculated index (20498) into the glyph index array is not less than the length of the array (20498) !
```

Perhaps this font is corrupted.
