### ISSUE TITLE
libfreetype6-dev _imagingft C module not loaded, Python 3.9 on Debian

### ISSUE THREAD

**Issue by Jerichi** [python-pillow/Pillow#5733]
Hello!

OS: Debian Buster (10)
Python: 3.9.7
Pillow: 8.3.2

I am experiencing an exception when using pillow to load a FreeType font contained on my machine. Below is the specific code.

```python
font = ImageFont.truetype(r"/usr/share/fonts/truetype/freefont/FreeMono.ttf", 12)
```

This code was previously run on 3.7 and ran with no issue. However, when run on 3.9, I get the following exception.

```
Traceback (most recent call last):
  File "/home/pi/Desktop/koibot/pillowtest.py", line 3, in <module>
    font = ImageFont.truetype(r"/usr/share/fonts/truetype/freefont/FreeMono.ttf", 12)
  File "/home/pi/.local/lib/python3.9/site-packages/PIL/ImageFont.py", line 855, in truetype
    return freetype(font)
  File "/home/pi/.local/lib/python3.9/site-packages/PIL/ImageFont.py", line 852, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/home/pi/.local/lib/python3.9/site-packages/PIL/ImageFont.py", line 187, in __init__
    if core.HAVE_RAQM:
  File "/home/pi/.local/lib/python3.9/site-packages/PIL/ImageFont.py", line 44, in __getattr__
    raise ImportError("The _imagingft C module is not installed")
ImportError: The _imagingft C module is not installed
```
(Full disclosure: I experienced this error in a Discord bot I am working on but the exception above is from running this line in isolation)

I have uninstalled and reinstalled pillow in various ways, remade and reinstalled my Python 3.9 build and attempted to reinstall the relevant library, all with no change. I also installed 3.9 myself from the tar since the packed in version is still on 3.8.

**Comment by radarhere** [comment]
To be clear - so you have installed libfreetype6-dev?

> reinstalled pillow in various ways

What ways?

**Comment by Jerichi** [comment]
I installed and I believe at one point also uninstalled and reinstalled libfreetype6-dev. It's definitely on my machine and works just fine with Python 3.7, which is presumably also using libfreetype6-dev.

> What ways?

I have done so through pip primarily but I have also attempted to install pillow through Debian directly (I also forgot to mention this is on a Raspberry Pi) which seemed to change nothing. I've also attempted to reinstall it with --enable-freetype but pip didn't seem to accept the argument and ignored it. The only thing I've yet to try is a manual install though that was my next thing to attempt (I don't have any experience with manual package install though).

**Comment by radarhere** [comment]
To use `--enable-freetype`, I would suggest
```
python3.9 -m pip install --upgrade Pillow --global-option="build_ext" --global-option="--enable-freetype"
```

**Comment by Jerichi** [comment]
I attempted the above and got the following error.

```ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xdacu6ba/pillow_cdcc5b3ffa2741018af189d0d5d27613/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xdacu6ba/pillow_cdcc5b3ffa2741018af189d0d5d27613/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' build_ext --enable-freetype install --record /tmp/pip-record-a92f89kt/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/pi/.local/include/python3.9/Pillow
         cwd: /tmp/pip-install-xdacu6ba/pillow_cdcc5b3ffa2741018af189d0d5d27613/
    Complete output (43 lines):
    running build_ext
    
    
    The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    Traceback (most recent call last):
      File "/tmp/pip-install-xdacu6ba/pillow_cdcc5b3ffa2741018af189d0d5d27613/setup.py", line 976, in <module>
        setup(
      File "/home/pi/.local/lib/python3.9/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/local/lib/python3.9/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/local/lib/python3.9/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/local/lib/python3.9/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/pi/.local/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/usr/local/lib/python3.9/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/tmp/pip-install-xdacu6ba/pillow_cdcc5b3ffa2741018af189d0d5d27613/setup.py", line 788, in build_extensions
        raise RequiredDependencyException(f)
    __main__.RequiredDependencyException: jpeg
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xdacu6ba/pillow_cdcc5b3ffa2741018af189d0d5d27613/setup.py", line 1035, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:
    
    The headers or library files could not be found for jpeg,
    a required dependency when compiling Pillow from source.
    
    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
    
    
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python3.9 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-xdacu6ba/pillow_cdcc5b3ffa2741018af189d0d5d27613/setup.py'"'"'; __file__='"'"'/tmp/pip-install-xdacu6ba/pillow_cdcc5b3ffa2741018af189d0d5d27613/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' build_ext --enable-freetype install --record /tmp/pip-record-a92f89kt/install-record.txt --single-version-externally-managed --user --prefix= --compile --install-headers /home/pi/.local/include/python3.9/Pillow Check the logs for full command output```

**Comment by radarhere** [comment]
As it says, it's missing a jpeg dependency. Install libjpeg62-turbo-dev and try again.

**Comment by Jerichi** [comment]
Seems to have solved it, thanks!
