### ISSUE TITLE
CIFuzz failures

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#5764]
https://github.com/python-pillow/Pillow/actions/workflows/cifuzz.yml

Last pass:

https://github.com/python-pillow/Pillow/runs/3870958606?check_suite_focus=true

Started failing today in:

https://github.com/python-pillow/Pillow/runs/3891941904?check_suite_focus=true

Not new from that PR, also failed in `master` when essentially the same code earlier passed:

https://github.com/radarhere/Pillow/runs/3893711843?check_suite_focus=true

Produces a 14 MB of logs, best viewed by downloading:

![image](https://user-images.githubusercontent.com/1324225/137384118-05aafc24-9894-42cf-9acc-de1e9b316943.png)

Lots and lots of entries like:

```
2021-10-14T11:27:41.7501117Z Fax3DecodeRLE: Bad code word at line 2280 of strip 15 (x 0).
2021-10-14T11:27:41.7501712Z Fax3DecodeRLE: Bad code word at line 2281 of strip 15 (x 0).
2021-10-14T11:27:41.7502303Z Fax3DecodeRLE: Bad code word at line 2282 of strip 15 (x 0).
2021-10-14T11:27:41.7502875Z Fax3DecodeRLE: Bad code word at line 2283 of strip 15 (x 0).
2021-10-14T11:27:41.7503460Z Fax3DecodeRLE: Bad code word at line 2284 of strip 15 (x 0).
2021-10-14T11:27:41.7504031Z Fax3DecodeRLE: Bad code word at line 2285 of strip 15 (x 0).
2021-10-14T11:27:41.7504621Z Fax3DecodeRLE: Bad code word at line 2286 of strip 15 (x 0).
2021-10-14T11:27:41.7505388Z Fax3DecodeRLE: Bad code word at line 2287 of strip 15 (x 0).
2021-10-14T11:27:41.7506002Z Fax3DecodeRLE: Bad code word at line 2288 of strip 15 (x 0).
2021-10-14T11:27:41.7506609Z Fax3DecodeRLE: Bad code word at line 2289 of strip 15 (x 0).
```

Then at the end, `TimeoutError: Reproducing timed out`:

```
2021-10-14T11:38:05.9140314Z /github/workspace/build-out/fuzz_font.pkg: Running 1 inputs 100 time(s) each.
2021-10-14T11:38:05.9141644Z Running: /github/workspace/out/artifacts/timeout-79b44afaa36cc462e934521aa46573bafd689735
2021-10-14T11:38:05.9144185Z Traceback (most recent call last):
2021-10-14T11:38:05.9145196Z   File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers_entrypoint.py", line 104, in <module>
2021-10-14T11:38:05.9145835Z     sys.exit(main())
2021-10-14T11:38:05.9146843Z   File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers_entrypoint.py", line 100, in main
2021-10-14T11:38:05.9147500Z     return run_fuzzers_entrypoint()
2021-10-14T11:38:05.9148942Z   File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers_entrypoint.py", line 63, in run_fuzzers_entrypoint
2021-10-14T11:38:05.9149765Z     result = run_fuzzers.run_fuzzers(config)
2021-10-14T11:38:05.9150674Z   File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers.py", line 298, in run_fuzzers
2021-10-14T11:38:05.9151348Z     if not fuzz_target_runner.run_fuzz_targets():
2021-10-14T11:38:05.9152194Z   File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers.py", line 139, in run_fuzz_targets
2021-10-14T11:38:05.9152860Z     result = self.run_fuzz_target(target)
2021-10-14T11:38:05.9153693Z   File "/opt/oss-fuzz/infra/cifuzz/run_fuzzers.py", line 235, in run_fuzz_target
2021-10-14T11:38:05.9154314Z     return fuzz_target_obj.fuzz()
2021-10-14T11:38:05.9155084Z   File "/opt/oss-fuzz/infra/cifuzz/fuzz_target.py", line 162, in fuzz
2021-10-14T11:38:05.9155744Z     if self.is_crash_reportable(crash.input_path):
2021-10-14T11:38:05.9156660Z   File "/opt/oss-fuzz/infra/cifuzz/fuzz_target.py", line 253, in is_crash_reportable
2021-10-14T11:38:05.9157667Z     reproducible_on_code_change = self.is_reproducible(
2021-10-14T11:38:05.9159173Z   File "/opt/oss-fuzz/infra/cifuzz/fuzz_target.py", line 220, in is_reproducible
2021-10-14T11:38:05.9162657Z     result = engine_impl.reproduce(target_path,
2021-10-14T11:38:05.9163967Z   File "/usr/local/lib/python3.8/dist-packages/clusterfuzz/_internal/bot/fuzzers/libFuzzer/engine.py", line 391, in reproduce
2021-10-14T11:38:05.9165161Z     raise TimeoutError('Reproducing timed out\n' + result.output)
2021-10-14T11:38:05.9165865Z TimeoutError: Reproducing timed out
2021-10-14T11:38:05.9166407Z INFO: Using preloaded libfuzzer
2021-10-14T11:38:05.9167003Z INFO: Running with entropic power schedule (0xFF, 100).
2021-10-14T11:38:05.9167505Z INFO: Seed: 2173671605
2021-10-14T11:38:05.9168551Z INFO: Loaded 3 modules   (15583 inline 8-bit counters): 9893 [0x7ffa6895d200, 0x7ffa6895f8a5), 350 [0x7ffa686188f0, 0x7ffa68618a4e), 5340 [0x622000019900, 0x62200001addc), 
2021-10-14T11:38:05.9169671Z INFO: Loaded 3 PC tables (15583 PCs): 9893 [0x7ffa6895f8a8,0x7ffa689862f8), 350 [0x7ffa68618a50,0x7ffa6861a030), 5340 [0x632000000800,0x6320000155c0), 
2021-10-14T11:38:05.9171389Z /github/workspace/build-out/fuzz_font.pkg: Running 1 inputs 100 time(s) each.
2021-10-14T11:38:05.9172695Z Running: /github/workspace/out/artifacts/timeout-79b44afaa36cc462e934521aa46573bafd689735
2021-10-14T11:38:05.9173445Z 
2021-10-14T11:38:06.3028761Z ##[group]Run actions/upload-artifact@v2
2021-10-14T11:38:06.3029268Z with:
2021-10-14T11:38:06.3029631Z   name: artifacts
2021-10-14T11:38:06.3030021Z   path: ./out/artifacts
2021-10-14T11:38:06.3030484Z   if-no-files-found: warn
2021-10-14T11:38:06.3030909Z ##[endgroup]
2021-10-14T11:38:06.5976537Z With the provided path, there will be 2 files uploaded
2021-10-14T11:38:06.6774980Z events.js:187
2021-10-14T11:38:06.6776564Z       throw er; // Unhandled 'error' event
2021-10-14T11:38:06.6777308Z       ^
2021-10-14T11:38:06.6777742Z 
2021-10-14T11:38:06.6778857Z Error: EACCES: permission denied, open '/home/runner/work/Pillow/Pillow/out/artifacts/tmp4qmtp4_t'
2021-10-14T11:38:06.6780128Z Emitted 'error' event on ReadStream instance at:
2021-10-14T11:38:06.6780967Z     at internal/fs/streams.js:120:12
2021-10-14T11:38:06.6781775Z     at FSReqCallback.oncomplete (fs.js:146:23) {
2021-10-14T11:38:06.6782691Z   errno: -13,
2021-10-14T11:38:06.6783452Z   code: 'EACCES',
2021-10-14T11:38:06.6784410Z   syscall: 'open',
2021-10-14T11:38:06.6785458Z   path: '/home/runner/work/Pillow/Pillow/out/artifacts/tmp4qmtp4_t'
2021-10-14T11:38:06.6854685Z }
2021-10-14T11:38:06.7031176Z Cleaning up orphan processes
```

**Comment by hugovk** [comment]
Reported at https://github.com/google/oss-fuzz/issues/6619.

**Comment by radarhere** [comment]
The oss-fuzz issue has been closed, and CIFuzz is passing again - https://github.com/python-pillow/Pillow/runs/4079635415
