### ISSUE TITLE
Installing Pillow on macOS 10.15.7 / Zope5.5 / python 3.10

### ISSUE THREAD

**Issue by gpzope** [python-pillow/Pillow#6131]
Trying to install pillow on macOS 10.15.7 / Zope5.5 / python 3.10

I get this :

An internal error occurred due to a bug in either zc.buildout or in a recipe being used:
```
Traceback (most recent call last):
  File "/Applications/zope55/lib/python3.10/site-packages/zc/buildout/buildout.py", line 2182, in main
    getattr(buildout, command)(args)
  File "/Applications/zope55/lib/python3.10/site-packages/zc/buildout/buildout.py", line 825, in install
    installed_files = self[part]._call(recipe.install)
  File "/Applications/zope55/lib/python3.10/site-packages/zc/buildout/buildout.py", line 1611, in _call
    return f()
  File "/Applications/zope55/eggs/zc.recipe.egg-2.0.7-py3.10.egg/zc/recipe/egg/egg.py", line 227, in install
    reqs, ws = self.working_set()
  File "/Applications/zope55/eggs/zc.recipe.egg-2.0.7-py3.10.egg/zc/recipe/egg/egg.py", line 78, in working_set
    ws = self._working_set(
  File "/Applications/zope55/eggs/zc.recipe.egg-2.0.7-py3.10.egg/zc/recipe/egg/egg.py", line 161, in _working_set
    ws = zc.buildout.easy_install.install(
  File "/Applications/zope55/lib/python3.10/site-packages/zc/buildout/easy_install.py", line 963, in install
    return installer.install(specs, working_set)
  File "/Applications/zope55/lib/python3.10/site-packages/zc/buildout/easy_install.py", line 688, in install
    for dist in self._get_dist(requirement, ws):
  File "/Applications/zope55/lib/python3.10/site-packages/zc/buildout/easy_install.py", line 580, in _get_dist
    dists = [_move_to_eggs_dir_and_compile(dist, self._dest)]
  File "/Applications/zope55/lib/python3.10/site-packages/zc/buildout/easy_install.py", line 1751, in _move_to_eggs_dir_and_compile
    [tmp_loc] = glob.glob(os.path.join(tmp_dest, '*'))
ValueError: not enough values to unpack (expected 1, got 0)
```
My buildup.cfg file looks like this:
```
[buildout]
extends =
    https://zopefoundation.github.io/Zope/releases/5.5/versions-prod.cfg
parts =
    zopescripts

[zopescripts]
recipe = zc.recipe.egg
interpreter = zopepy
eggs =
    Zope
    Paste
    Products.ExternalMethod
	Products.BTreeFolder2
	Products.PythonScripts
	Products.PluggableAuthService
	Products.SiteErrorLog
	Products.MailHost
	Products.TemporaryFolder
	Pillow
```
Thank you!

**Comment by radarhere** [comment]
Hi. https://stackoverflow.com/questions/65897934/cant-install-zc-buildout-with-zc-recipe-egg-with-python-3-6-or-higher talks about your problem, and suggests that you downgrade setuptools to < 52.

This is not just a random workaround - this is also the [official solution](https://github.com/buildout/buildout/pull/549) until [buildout v3 is released.](https://stackoverflow.com/a/66255879/4093019)

**Comment by radarhere** [comment]
@gpzope did that solve your problem?

**Comment by gpzope** [comment]
Hi. Yes indeed! Thanks so much.
