### ISSUE TITLE
Pillow upgrade to 9.1.0 not possible on RPI Zero

### ISSUE THREAD

**Issue by EFeru** [python-pillow/Pillow#6193]
On Raspberry Pi Zero, Pillow fails on upgrade (see below full log):

`python3 -m pip install --upgrade Pillow`

### What are your OS, Python and Pillow versions?

* OS: Raspbian GNU/Linux 11 (bullseye)
* Python: 3.9
* Pillow: 9.1.0

```python
pi@raspberrypi:/ $ python3 -m pip install --upgrade Pillow
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: Pillow in /usr/local/lib/python3.9/dist-packages (9.0.1)
Collecting Pillow
  Using cached Pillow-9.1.0.tar.gz (49.8 MB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: Pillow
  Building wheel for Pillow (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [177 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-armv7l-3.9
      creating build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageTk.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageDraw2.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageOps.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/FontFile.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/_tkinter_finder.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/PyAccess.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/__main__.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/GifImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/FpxImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/PSDraw.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageCms.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageFont.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/GimpGradientFile.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/MpegImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/CurImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/MicImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/_version.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/IptcImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/TarIO.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/PsdImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/__init__.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/PalmImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/GimpPaletteFile.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageMode.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageMath.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/GbrImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/PngImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/TgaImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageTransform.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageDraw.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageChops.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageEnhance.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/FitsImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImtImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/GdImageFile.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/SunImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/BdfFontFile.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageGrab.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/JpegImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/PdfParser.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/JpegPresets.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageShow.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ExifTags.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImagePalette.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/WalImageFile.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/FtexImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/XpmImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/TiffImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/features.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/BmpImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageQt.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/XbmImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/PcfFontFile.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/PpmImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/PixarImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageMorph.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImagePath.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/PcdImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/WmfImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/FliImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/DdsImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/BlpImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/Image.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ContainerIO.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/DcxImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/PaletteFile.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/_binary.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/MpoImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageFilter.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/WebPImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/TiffTags.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/EpsImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/_util.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/IcoImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageStat.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageColor.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageWin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/MspImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/PdfImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/SgiImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageFile.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/PcxImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageSequence.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      running egg_info
      writing src/Pillow.egg-info/PKG-INFO
      writing dependency_links to src/Pillow.egg-info/dependency_links.txt
      writing requirements to src/Pillow.egg-info/requires.txt
      writing top-level names to src/Pillow.egg-info/top_level.txt
      reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.c'
      warning: no files found matching '*.h'
      warning: no files found matching '*.sh'
      warning: no files found matching '*.txt'
      warning: no previously-included files found matching '.appveyor.yml'
      warning: no previously-included files found matching '.clang-format'
      warning: no previously-included files found matching '.coveragerc'
      warning: no previously-included files found matching '.editorconfig'
      warning: no previously-included files found matching '.readthedocs.yml'
      warning: no previously-included files found matching 'codecov.yml'
      warning: no previously-included files matching '.git*' found anywhere in distribution
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      no previously-included directories found matching '.ci'
      writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
      running build_ext


      The headers or library files could not be found for jpeg,
      a required dependency when compiling Pillow from source.

      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html

      Traceback (most recent call last):
        File "/tmp/pip-install-hx1flpkh/pillow_d3790c549f11413cb49cda5ed2c01446/setup.py", line 989, in <module>
          setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 223, in run
          self.run_command('build')
        File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.9/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/usr/lib/python3.9/distutils/command/build_ext.py", line 340, in run
          self.build_extensions()
        File "/tmp/pip-install-hx1flpkh/pillow_d3790c549f11413cb49cda5ed2c01446/setup.py", line 804, in build_extensions
          raise RequiredDependencyException(f)
      __main__.RequiredDependencyException: jpeg

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-hx1flpkh/pillow_d3790c549f11413cb49cda5ed2c01446/setup.py", line 1009, in <module>
          raise RequiredDependencyException(msg)
      __main__.RequiredDependencyException:

      The headers or library files could not be found for jpeg,
      a required dependency when compiling Pillow from source.

      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html


      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Pillow
  Running setup.py clean for Pillow
Failed to build Pillow
Installing collected packages: Pillow
  Running setup.py install for Pillow ... error
  error: subprocess-exited-with-error

  × Running setup.py install for Pillow did not run successfully.
  │ exit code: 1
  ╰─> [179 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build/lib.linux-armv7l-3.9
      creating build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageTk.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageDraw2.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageOps.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/FontFile.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/_tkinter_finder.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/PyAccess.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/__main__.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/GifImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/FpxImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/PSDraw.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageCms.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageFont.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/GimpGradientFile.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/MpegImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/CurImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/MicImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/_version.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/IptcImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/TarIO.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/PsdImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/__init__.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/PalmImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/GimpPaletteFile.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageMode.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageMath.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/GbrImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/PngImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/TgaImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageTransform.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageDraw.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageChops.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageEnhance.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/FitsImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImtImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/GdImageFile.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/SunImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/BdfFontFile.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageGrab.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/JpegImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/PdfParser.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/JpegPresets.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageShow.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ExifTags.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImagePalette.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/WalImageFile.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/FtexImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/XpmImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/TiffImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/features.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/BmpImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageQt.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/XbmImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/PcfFontFile.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/PpmImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/PixarImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageMorph.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImagePath.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/PcdImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/WmfImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/FliImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/DdsImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/BlpImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/Image.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ContainerIO.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/DcxImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/PaletteFile.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/_binary.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/MpoImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageFilter.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/WebPImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/TiffTags.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/EpsImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/_util.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/IcoImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageStat.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageColor.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageWin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/MspImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/PdfImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/SgiImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageFile.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/PcxImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/ImageSequence.py -> build/lib.linux-armv7l-3.9/PIL
      copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-armv7l-3.9/PIL
      running egg_info
      writing src/Pillow.egg-info/PKG-INFO
      writing dependency_links to src/Pillow.egg-info/dependency_links.txt
      writing requirements to src/Pillow.egg-info/requires.txt
      writing top-level names to src/Pillow.egg-info/top_level.txt
      reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.c'
      warning: no files found matching '*.h'
      warning: no files found matching '*.sh'
      warning: no files found matching '*.txt'
      warning: no previously-included files found matching '.appveyor.yml'
      warning: no previously-included files found matching '.clang-format'
      warning: no previously-included files found matching '.coveragerc'
      warning: no previously-included files found matching '.editorconfig'
      warning: no previously-included files found matching '.readthedocs.yml'
      warning: no previously-included files found matching 'codecov.yml'
      warning: no previously-included files matching '.git*' found anywhere in distribution
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      no previously-included directories found matching '.ci'
      writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
      running build_ext


      The headers or library files could not be found for jpeg,
      a required dependency when compiling Pillow from source.

      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html

      Traceback (most recent call last):
        File "/tmp/pip-install-hx1flpkh/pillow_d3790c549f11413cb49cda5ed2c01446/setup.py", line 989, in <module>
          setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
          return orig.install.run(self)
        File "/usr/lib/python3.9/distutils/command/install.py", line 590, in run
          self.run_command('build')
        File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.9/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 79, in run
          _build_ext.run(self)
        File "/usr/lib/python3.9/distutils/command/build_ext.py", line 340, in run
          self.build_extensions()
        File "/tmp/pip-install-hx1flpkh/pillow_d3790c549f11413cb49cda5ed2c01446/setup.py", line 804, in build_extensions
          raise RequiredDependencyException(f)
      __main__.RequiredDependencyException: jpeg

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-hx1flpkh/pillow_d3790c549f11413cb49cda5ed2c01446/setup.py", line 1009, in <module>
          raise RequiredDependencyException(msg)
      __main__.RequiredDependencyException:

      The headers or library files could not be found for jpeg,
      a required dependency when compiling Pillow from source.

      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html


      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> Pillow

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

```

**Comment by nulano** [comment]
It looks like you have an ARMv7 system. Pillow provides (prebuild) binary wheels for x86, x86_64, and ARM64, but not ARMv7, so in your case it is attempting a source build, and you do not appear to have the required dependencies installed. You can see the install instructions here: https://pillow.readthedocs.io/en/stable/installation.html#building-on-linux

I suspect when you installed Pillow 9.0.1, it took an unofficial wheel from https://www.piwheels.org/project/pillow/. As you can see on that website, they haven't yet provided a wheel for Pillow 9.1.0 (released a week ago), so a source build is currently your only option if you require the latest version.

**Comment by EFeru** [comment]
Hi @nulano, thank you for the response.
The thing is if want to install Pillow on a fresh system, it will try to install the latest one and then also fail. What are the options, to fix it to version 9.0.1?

**Comment by nulano** [comment]
Looking at the website, it seems PiWheels has an automated system for building wheels, and the Pillow 9.1.0 build failed to find the sources for the latest version: https://www.piwheels.org/logs/0000/0801/9419.txt

However, the build seems to have triggered at 14:57 UTC and PyPI shows that the source archive was already uploaded at 14:39 UTC: https://pypi.org/project/Pillow/9.1.0/#files It might be contacting them to see if they can fix Pillow 9.1.0.

**Comment by nulano** [comment]
> What are the options, to fix it to version 9.0.1?

```
python3 -m pip install Pillow==9.1.0
```

**Comment by EFeru** [comment]
Ok, then I guess it will be fixed soon. Until then I use the version 9.0.1
I will close the issue here.

**Comment by bennuttall** [comment]
Thanks for the heads up! It's available now: https://piwheels.org/project/pillow/
