### ISSUE TITLE
Stripping the pillow libraries fails makes pyinstaller binary fail at runtime

### ISSUE THREAD

**Issue by simaoafonso-pwt** [python-pillow/Pillow#6289]
### What did you do?

When using PyInstaller to freeze an application that contains pillow as a dependency, the `--strip` option runs `strip` on the libraries. This fails on the `_imaging` pillow library.

### What did you expect to happen?

The pillow C libraries should still be loaded when stripped.

I'm not *exactly* sure this is a Pillow issue, but since it works without stripping, I guess it is.

The unstripped binary is 3MB, stripping brings it down to 636kB.

[libs.tar.gz](https://github.com/python-pillow/Pillow/files/8681010/libs.tar.gz)

### What actually happened?

```
ELF load command address/offset not page-aligned
```

### What are your OS, Python and Pillow versions?

* OS: Arch Linux
* Python: 3.10.4
* Pillow: 9.1.0

```
$ cd "$(mktemp -d)"
$ python3.10 -m venv .
$ source bin/activate
$ pip install pillow pyinstaller
$ $EDITOR pilstrip.py
$ pyinstall -n pil-nostrip pilstrip.py
$ dist/pil-nostrip/pil-nostrip
<module 'PIL.Image' from '/tmp/tmp.5d4W8x0r8d/dist/pil-nostrip/PIL/Image.pyc'>
$ pyinstaller -n pil-strip --strip pilstrip.py
$ dist/pil-strip/pil-strip
Traceback (most recent call last):
  File "pilstrip.py", line 1, in <module>
    from PIL import Image
  File "PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "PIL/Image.py", line 132, in <module>
ImportError: /tmp/tmp.5d4W8x0r8d/dist/pil-strip/PIL/_imaging.cpython-310-x86_64-linux-gnu.so: ELF load command address/offset not page-aligned
[221404] Failed to execute script 'pilstrip' due to unhandled exception!
```

```python
from PIL import Image

print(Image)
```

**Comment by simaoafonso-pwt** [comment]
It seems `strip` removes all symbols. I don't know enough about C to know why this works for other libraries...

Here's a diff, using the `libs.tar.gz` above: `diff -u --color=always <(objdump -x dist/pil-nostrip/PIL/_imaging.cpython-310-x86_64-linux-gnu.so) <(objdump -x dist/pil-strip/PIL/_imaging.cpython-310-x86_64-linux-gnu.so)`

https://gist.github.com/simaoafonso-pwt/9b87af101295c3ebb1f0cf16ccfc5780

**Comment by simaoafonso-pwt** [comment]
https://github.com/pyinstaller/pyinstaller/blob/3dded2226c81b957ff4faf95690c68ebe8a485f1/PyInstaller/building/utils.py#L297-L302

PyInstaller runs `strip` directly, except on MacOS, where it uses `-S`.

**Comment by radarhere** [comment]
Here's a Dockerfile that reproduces the problem using your code - [Dockerfile.zip](https://github.com/python-pillow/Pillow/files/8694387/Dockerfile.zip)

**Comment by radarhere** [comment]
I've found that if you install Pillow from source, your code works - [Dockerfile_fromSource.zip](https://github.com/python-pillow/Pillow/files/8704238/Dockerfile_fromSource.zip)

**Comment by simaoafonso-pwt** [comment]
Thanks for the reproduction, can confirm that works. Weird, does it mean the PyPI wheel binaries are broken?

I my case, `pillow` is an indirect dependency (for matplotlib), so I can only control this by using the following `requirements.txt`:

```
--no-binary pillow  # https://github.com/python-pillow/Pillow/issues/6289
matplotlib
```

It also needs an hidden import when running PyInstaller: `--hidden-import='PIL._tkinter_finder'`.

For new venv, installing those requirements works well.
For existing venv, I will uninstall pillow (`pip uninstall -y pillow`), reinstall the requirements (which will use the source version), and PyInstaller can strip the binaries.

**Comment by radarhere** [comment]
I've found https://github.com/pypa/auditwheel/pull/376, and created https://github.com/python-pillow/pillow-wheels/pull/298 to include it.

If that is merged, then this can be considered resolved, and the fix will be available in the following release of Pillow. The next Pillow release is currently due out on July 1.

**Comment by radarhere** [comment]
Here's a fixed wheel for Pillow 9.1.1 - [Pillow-9.1.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.zip](https://github.com/python-pillow/Pillow/files/8758342/Pillow-9.1.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.zip)

**Comment by simaoafonso-pwt** [comment]
Can confirm that wheel fixes the original issue.

I'm using Python 3.8 on CentOS 7 in another project, but I can wait for the release to double check, unless you have a fixed wheel for Python 3.8 lying around...

**Comment by radarhere** [comment]
[Pillow-9.1.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.zip](https://github.com/python-pillow/Pillow/files/8762444/Pillow-9.1.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.zip)

**Comment by simaoafonso-pwt** [comment]
Yes, it works, many thanks.

This will be released on July? That's fine by me, thanks for the quick response.

**Comment by radarhere** [comment]
The PR still needs to be reviewed, but I would expect it to be part of the July release, yes.
