### ISSUE TITLE
Install failed for 3.11.0b3

### ISSUE THREAD

**Issue by onyx-and-iris** [python-pillow/Pillow#6363]
```
Building wheels for collected packages: pillow
  Building wheel for pillow (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [210 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-311
      creating build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\BdfFontFile.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\BlpImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\BmpImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\BufrStubImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ContainerIO.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\CurImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\DcxImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\DdsImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\EpsImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ExifTags.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\features.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\FitsImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\FitsStubImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\FliImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\FontFile.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\FpxImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\FtexImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\GbrImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\GdImageFile.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\GifImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\GimpGradientFile.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\GimpPaletteFile.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\GribStubImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\Hdf5StubImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\IcnsImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\IcoImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\Image.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageChops.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageCms.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageColor.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageDraw.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageDraw2.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageEnhance.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageFile.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageFilter.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageFont.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageGrab.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageMath.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageMode.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageMorph.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageOps.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImagePalette.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImagePath.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageQt.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageSequence.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageShow.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageStat.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageTk.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageTransform.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImageWin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\ImtImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\IptcImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\Jpeg2KImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\JpegImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\JpegPresets.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\McIdasImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\MicImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\MpegImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\MpoImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\MspImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PaletteFile.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PalmImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PcdImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PcfFontFile.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PcxImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PdfImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PdfParser.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PixarImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PngImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PpmImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PsdImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PSDraw.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\PyAccess.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\SgiImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\SpiderImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\SunImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\TarIO.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\TgaImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\TiffImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\TiffTags.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\WalImageFile.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\WebPImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\WmfImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\XbmImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\XpmImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\XVThumbImagePlugin.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\_binary.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\_tkinter_finder.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\_util.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\_version.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\__init__.py -> build\lib.win-amd64-cpython-311\PIL
      copying src\PIL\__main__.py -> build\lib.win-amd64-cpython-311\PIL
      running egg_info
      writing src\Pillow.egg-info\PKG-INFO
      writing dependency_links to src\Pillow.egg-info\dependency_links.txt
      writing requirements to src\Pillow.egg-info\requires.txt
      writing top-level names to src\Pillow.egg-info\top_level.txt
      reading manifest file 'src\Pillow.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.c'
      warning: no files found matching '*.h'
      warning: no files found matching '*.sh'
      warning: no files found matching '*.txt'
      warning: no previously-included files found matching '.appveyor.yml'
      warning: no previously-included files found matching '.clang-format'
      warning: no previously-included files found matching '.coveragerc'
      warning: no previously-included files found matching '.editorconfig'
      warning: no previously-included files found matching '.readthedocs.yml'
      warning: no previously-included files found matching 'codecov.yml'
      warning: no previously-included files matching '.git*' found anywhere in distribution
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      no previously-included directories found matching '.ci'
      adding license file 'LICENSE'
      writing manifest file 'src\Pillow.egg-info\SOURCES.txt'
      running build_ext


      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.

      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html

      Traceback (most recent call last):
        File "C:\Users\__\AppData\Local\Temp\pip-install-0c8scl0c\pillow_b6d16806dee346ec9b471ebf88d12dbb\setup.py", line 989, in <module>
          setup(
          ^^^^^^
        File "F:\scripts\xair_api\venv\Lib\site-packages\setuptools\__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "F:\scripts\xair_api\venv\Lib\site-packages\setuptools\_distutils\core.py", line 177, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "F:\scripts\xair_api\venv\Lib\site-packages\setuptools\_distutils\core.py", line 193, in run_commands
          dist.run_commands()
          ^^^^^^^^^^^^^^^^^^^
        File "F:\scripts\xair_api\venv\Lib\site-packages\setuptools\_distutils\dist.py", line 968, in run_commands
          self.run_command(cmd)
          ^^^^^^^^^^^^^^^^^^^^^
        File "F:\scripts\xair_api\venv\Lib\site-packages\setuptools\dist.py", line 1229, in run_command
          super().run_command(command)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "F:\scripts\xair_api\venv\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
          ^^^^^^^^^^^^^
        File "F:\scripts\xair_api\venv\Lib\site-packages\wheel\bdist_wheel.py", line 299, in run
          self.run_command('build')
          ^^^^^^^^^^^^^^^^^^^^^^^^^
        File "F:\scripts\xair_api\venv\Lib\site-packages\setuptools\_distutils\cmd.py", line 317, in run_command
          self.distribution.run_command(command)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "F:\scripts\xair_api\venv\Lib\site-packages\setuptools\dist.py", line 1229, in run_command
          super().run_command(command)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "F:\scripts\xair_api\venv\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
          ^^^^^^^^^^^^^
        File "F:\scripts\xair_api\venv\Lib\site-packages\setuptools\command\build.py", line 24, in run
          super().run()
          ^^^^^^^^^^^^^
        File "F:\scripts\xair_api\venv\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "F:\scripts\xair_api\venv\Lib\site-packages\setuptools\_distutils\cmd.py", line 317, in run_command
          self.distribution.run_command(command)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "F:\scripts\xair_api\venv\Lib\site-packages\setuptools\dist.py", line 1229, in run_command
          super().run_command(command)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "F:\scripts\xair_api\venv\Lib\site-packages\setuptools\_distutils\dist.py", line 987, in run_command
          cmd_obj.run()
          ^^^^^^^^^^^^^
        File "F:\scripts\xair_api\venv\Lib\site-packages\setuptools\command\build_ext.py", line 79, in run
          _build_ext.run(self)
          ^^^^^^^^^^^^^^^^^^^^
        File "F:\scripts\xair_api\venv\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 339, in run
          self.build_extensions()
          ^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\__\AppData\Local\Temp\pip-install-0c8scl0c\pillow_b6d16806dee346ec9b471ebf88d12dbb\setup.py", line 802, in build_extensions
          if not getattr(feature, f) and feature.require(f):
                                         ^^^^^^^^^^^^^^^^^^
      RequiredDependencyException: zlib

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\__\AppData\Local\Temp\pip-install-0c8scl0c\pillow_b6d16806dee346ec9b471ebf88d12dbb\setup.py", line 1009, in <module>
          raise RequiredDependencyException(msg)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      RequiredDependencyException:

      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.

      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
```
Hi, just letting you know pillow seems to have trouble with 3.11.0b3.

**Comment by radarhere** [comment]
Hi. We're currently testing [Python 3.11.0b3 on GitHub Actions](https://github.com/python-pillow/Pillow/runs/6859584415?check_suite_focus=true#step:4:11), and it runs without a problem.

Your error doesn't look like a problem specific to Python 3.11.0b3. It looks like you don't have zlib installed, once of Pillow's required dependencies. I expect that you would have the same problem under Python 3.10.

If you would like to [build Pillow from source on Windows,](https://pillow.readthedocs.io/en/stable/installation.html#building-on-windows)
> you can use the build scripts in the winbuild directory used for CI testing and development. These scripts require Visual Studio 2017 or newer and NASM.

On July 1, the next release of Pillow is due out, and it may include wheels for Windows built with Python 3.11.0 b4 (due out on June 16).

**Comment by onyx-and-iris** [comment]
ok thank you for the quick response! I will try to build from source as you mention.

**Comment by hugovk** [comment]
There's also unofficial Python 3.11 wheels at https://www.lfd.uci.edu/~gohlke/pythonlibs/#_pillow

Download a cp311 one and pip install it.

**Comment by radarhere** [comment]
@onyx-and-iris you liked the comment about the unofficial wheels. Does that mean that you were able to successfully install Pillow?

**Comment by onyx-and-iris** [comment]
@radarhere I was able to install the unofficial wheel yes. thank you for your help.
