### ISSUE TITLE
"OSError: X connection failed: error 5"

### ISSUE THREAD

**Issue by aChickensz** [python-pillow/Pillow#6364]
### What did you do?
Executed a script using WSL
### What did you expect to happen?
A bot that clicks when a certain pixel is a certain color
### What actually happened?
```
Traceback (most recent call last):
  File "reactiontest2.py", line 4, in <module>
    rgb = PIL.ImageGrab.grab().load()[75,180]
  File "/home/kevin/.local/lib/python3.8/site-packages/PIL/ImageGrab.py", line 68, in grab
    size, data = Image.core.grabscreen_x11(xdisplay)
OSError: X connection failed: error 5
```
### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python: 3.8.10
* Pillow: 9.0.1

```python
import PIL.ImageGrab
import mouse
print("running")
while True:
    rgb = PIL.ImageGrab.grab().load()[75,180]
    rgb2=(78, 221, 113)
    if rgb == rgb2:
        mouse.click()
```
When I run this code in Visual Studio Code (on windows), it runs perfectly. However, when I run it on ubuntu using WSL (on the same device), it shows the error mentioned above.
Using WSL:
![image_2022-06-14_153537584](https://user-images.githubusercontent.com/98770695/173673810-ae2db70e-0a4c-4e5c-b0f7-ca7c027d51a9.png)
Using Powershell:
![image_2022-06-14_153739023](https://user-images.githubusercontent.com/98770695/173674149-a583a0f3-d882-41b1-b39d-5b5f94f29f92.png)

**Comment by aChickensz** [comment]
@nulano Understood, thanks!
