### ISSUE TITLE
color must be int or tuple

### ISSUE THREAD

**Issue by Meysamii** [python-pillow/Pillow#6379]
my code is this:

```python
from PIL import Image , ImageOps , ImageDraw

img = Image.open('Desktop/Pythontest/122.jpg')
img = ImageOps.grayscale(img)
img = ImageOps.equalize(img)

dicew = 20

dicesize = int (img.width * 1.0 / dicew ) 
diceh = int (img.height * 1.0 / img.width * dicew)

nim = Image.new("L" , (img.width, img.height), 'white')
nimd = ImageDraw.Draw(nim)

print('you will need %s dices for this!'% (dicew * diceh))

for y in range(0, img.height-dicesize, dicesize):
    for x in range(0, img.width-dicesize, dicesize):
        thisSectorColor = 0
        for dicex in range(0, dicesize):
            for dicey in range(0, dicesize):
                thisColor = img.getpixel((x+dicex, y+dicey))
                thisSectorColor += thisColor
        thisSectorColor /= (dicesize ** 2)
        nimd.rectangle([(x,y), (x+dicesize, y+dicesize)], thisSectorColor)
        
        diceNumber = (255-thisSectorColor) + 6 / 255 + 1
        print (diceNumber),
```
why my result is this:
```
eysam@LearnUbuntu:~$ /bin/python3 "/home/meysam/Desktop/Pythontest/from PIL import Image.py"
you will need 260 dices for this!
Traceback (most recent call last):
  File "/home/meysam/Desktop/Pythontest/from PIL import Image.py", line 25, in <module>
    nimd.rectangle([(x,y), (x+dicesize, y+dicesize)], thisSectorColor)
  File "/usr/lib/python3/dist-packages/PIL/ImageDraw.py", line 275, in rectangle
    ink, fill = self._getink(outline, fill)
  File "/usr/lib/python3/dist-packages/PIL/ImageDraw.py", line 119, in _getink
    fill = self.draw.draw_ink(fill)
TypeError: color must be int or tuple
```

**Comment by radarhere** [comment]
```pycon
>>> thisSectorColor = 5
>>> dicesize = 2
>>> thisSectorColor /= (dicesize ** 2)
>>> thisSectorColor
1.25
>>> 
```
So `thisSectorColor` is not an int or tuple. I suggest changing
```python
nimd.rectangle([(x,y), (x+dicesize, y+dicesize)], thisSectorColor)
```
to
```python
nimd.rectangle([(x,y), (x+dicesize, y+dicesize)], int(thisSectorColor))
```

**Comment by radarhere** [comment]
@Meysamii you liked my comment. Does that mean that it worked for you and this issue can be closed?

**Comment by Meysamii** [comment]
> @Meysamii you liked my comment. Does that mean that it worked for you and this issue can be closed?

Yes bro
Thank you.
