### ISSUE TITLE
Error installing Pillow in PyPy

### ISSUE THREAD

**Issue by Ad101DP** [python-pillow/Pillow#6412]
When I try to install Pillow in PyPy the installation fails. I tried with "pypy -m pip install pillow", also with  "pypy -m pip install --upgrade pillow", I have the last version of PyPy and pip, the error is:
```
      Traceback (most recent call last):
        File "C:\Users\user\AppData\Local\Temp\pip-install-62z6bjbm\pillow_b00e7c0dc96743cda3576534ac2319d3\setup.py", line 995, in <module>
          setup(
        File "C:\Program Files\pypy3.9-v7.3.9-win64\lib\site-packages\setuptools\__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "C:\Program Files\pypy3.9-v7.3.9-win64\Lib\distutils\core.py", line 148, in setup
          dist.run_commands()
        File "C:\Program Files\pypy3.9-v7.3.9-win64\Lib\distutils\dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "C:\Program Files\pypy3.9-v7.3.9-win64\Lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Program Files\pypy3.9-v7.3.9-win64\lib\site-packages\setuptools\command\install.py", line 61, in run
          return orig.install.run(self)
        File "C:\Program Files\pypy3.9-v7.3.9-win64\Lib\distutils\command\install.py", line 553, in run
          self.run_command('build')
        File "C:\Program Files\pypy3.9-v7.3.9-win64\Lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Program Files\pypy3.9-v7.3.9-win64\Lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Program Files\pypy3.9-v7.3.9-win64\Lib\distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
        File "C:\Program Files\pypy3.9-v7.3.9-win64\Lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Program Files\pypy3.9-v7.3.9-win64\Lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Program Files\pypy3.9-v7.3.9-win64\lib\site-packages\setuptools\command\build_ext.py", line 79, in run
          _build_ext.run(self)
        File "C:\Program Files\pypy3.9-v7.3.9-win64\Lib\distutils\command\build_ext.py", line 343, in run
          self.build_extensions()
        File "C:\Users\user\AppData\Local\Temp\pip-install-62z6bjbm\pillow_b00e7c0dc96743cda3576534ac2319d3\setup.py", line 810, in build_extensions
          raise RequiredDependencyException(f)
      RequiredDependencyException: zlib

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\user\AppData\Local\Temp\pip-install-62z6bjbm\pillow_b00e7c0dc96743cda3576534ac2319d3\setup.py", line 1015, in <module>
          raise RequiredDependencyException(msg)
      RequiredDependencyException:

      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.

      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html


      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

├ù Encountered error while trying to install package.
Ôò░ÔöÇ> pillow

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
```

**Comment by hugovk** [comment]
Duplicate of https://github.com/python-pillow/Pillow/issues/6405.

We don't have precompiled binary wheels for PyPy3.9 because it's a beta release:

* https://www.pypy.org/posts/2022/03/pypy-v738-release.html

So instead it's trying to build from source, and it can be tricky to set up the compiler on Windows. See:

* https://pillow.readthedocs.io/en/stable/installation.html#building-on-windows

Instead, you might be best off using PyPy3.8, which does have wheels available.

**Comment by radarhere** [comment]
@Ad101DP did either of those options (downgrading or compiling from source) work for you?

**Comment by nulano** [comment]
In case it is helpful, there were unofficial wheels for PyPy3.9 uploaded in the release ticket for Pillow 9.3.0:
Linux: https://github.com/python-pillow/Pillow/issues/6460#issuecomment-1296103190
Windows: https://github.com/python-pillow/Pillow/issues/6460#issuecomment-1296358176

**Comment by radarhere** [comment]
PyPy3.9 has now been [released](https://www.pypy.org/posts/2022/12/pypy-v7310-release.html), and #6782 has added prebuilt wheels for Windows for the next Pillow release.
