### ISSUE TITLE
[TIFF] OverflowError is raised when the offset to first IFD is too large

### ISSUE THREAD

**Issue by ks888sk** [python-pillow/Pillow#6432]
### What did you do?

```python3

import io

from PIL import Image

# offset is \x00\x00\x00\x00\x00\x00\x00\xff (17293822569102705000), larger than C ssize_t.
bigtiff_header = b"\x49\x49\x2b\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff"
data = bigtiff_header

# OverflowError: Python int too large to convert to C ssize_t
input = io.BytesIO(data)
with Image.open(input) as im:
    im.load()

```

### What did you expect to happen?

According to [the spec of BigTIFF](https://www.awaresystems.be/imaging/tiff/bigtiff.html), offset to first IFD is *unsigned* 8 byte. So maybe OverflowError should not be raised here.

### What actually happened?

```
Traceback (most recent call last):
  File "issue.py", line 11, in <module>
    with Image.open(input) as im:
  File "/usr/local/lib/python3.8/dist-packages/PIL/Image.py", line 3133, in open
    im = _open_core(fp, filename, prefix, formats)
  File "/usr/local/lib/python3.8/dist-packages/PIL/Image.py", line 3119, in _open_core
    im = factory(fp, filename)
  File "/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py", line 1058, in __init__
    super().__init__(fp, filename)
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFile.py", line 116, in __init__
    self._open()
  File "/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py", line 1085, in _open
    self._seek(0)
  File "/usr/local/lib/python3.8/dist-packages/PIL/TiffImagePlugin.py", line 1122, in _seek
    self.fp.seek(self.__next)
OverflowError: Python int too large to convert to C ssize_t
```

### What are your OS, Python and Pillow versions?

* OS: ubuntu:focal-20220426
* Python: 3.8.10
* Pillow: 9.2.0

**Comment by radarhere** [comment]
`self.fp` is a `io.BytesIO` instance. If I run the following code in my console, then I get the same error.
```
>>> import io
>>> io.BytesIO().seek(17293822569102705000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OverflowError: Python int too large to convert to C ssize_t
```
So it is not a Pillow error as much as it is a Python error. The offset you have specified is for a file that is at least... 17 exabytes.

If I change your code to `bigtiff_header = b"\x49\x49\x2b\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x79"`, then the error becomes a `PIL.UnidentifiedImageError` instead. So Pillow can still handle seeking up to 8718968878589280256 at least, or 8.7 exabytes.

If we arrive at a future where we are dealing with over 8 exabyte images, I imagine Python support for large files will have changed by then.

I'm inclined to close this.

**Comment by ks888sk** [comment]
Yes, practically speaking, the error case almost never occur. It's ok for me to close this issue.
