### ISSUE TITLE
Cannot install in arm alpine

### ISSUE THREAD

**Issue by arily** [python-pillow/Pillow#6471]
### What did you do?
```dockerfile
FROM --platform=$BUILDPLATFORM python:3.9-alpine
RUN apk add tiff-dev jpeg-dev openjpeg-dev zlib-dev freetype-dev lcms2-dev \
    libwebp-dev tcl-dev tk-dev harfbuzz-dev fribidi-dev libimagequant-dev \
    libxcb-dev libpng-dev
RUN python3.9 -m pip install Pillow 
```
### What did you expect to happen?
pillow installed successfully
### What actually happened?
```
#0 96.91   Running setup.py install for Pillow: started
#0 97.13   Running setup.py install for Pillow: finished with status 'error'
#0 97.15   error: subprocess-exited-with-error
#0 97.15   
#0 97.15   × Running setup.py install for Pillow did not run successfully.
#0 97.15   │ exit code: 1
#0 97.15   ╰─> [193 lines of output]
#0 97.15       running install
#0 97.15       /usr/local/lib/python3.9/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
#0 97.15         warnings.warn(
#0 97.15       running build
#0 97.15       running build_py
#0 97.15       creating build
#0 97.15       creating build/lib.linux-aarch64-cpython-39
#0 97.15       creating build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/features.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/ImageDraw2.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/ImageOps.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/PyAccess.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/FliImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/ImageStat.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/FpxImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/BdfFontFile.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/ImageMode.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/PSDraw.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/PcfFontFile.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/__main__.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/XbmImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/GimpPaletteFile.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/PcdImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/ImageColor.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/BmpImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/FtexImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/ImageTransform.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/TiffTags.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/PdfParser.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/ImageEnhance.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/WalImageFile.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/ImageDraw.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/ImageSequence.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/TgaImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/ImagePalette.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/ImageWin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/ContainerIO.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/WmfImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/SunImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/XpmImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/ImtImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/JpegImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/ImagePath.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/ImageChops.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/FontFile.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/_version.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/EpsImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/_util.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/PdfImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/_binary.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/GimpGradientFile.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/_tkinter_finder.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/MicImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/IcoImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/PpmImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/PixarImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/TiffImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/ExifTags.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/DdsImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/PalmImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/FitsImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/ImageCms.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/PaletteFile.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/__init__.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/MspImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/ImageTk.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/ImageShow.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/PcxImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/JpegPresets.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/ImageMorph.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/IptcImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/_deprecate.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/TarIO.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/ImageFilter.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/ImImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/PsdImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/ImageMath.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/CurImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/ImageFont.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/GdImageFile.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/BlpImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/SgiImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/ImageGrab.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/MpoImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/DcxImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/PngImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/Image.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/GifImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/WebPImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/MpegImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/ImageQt.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/ImageFile.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       copying src/PIL/GbrImagePlugin.py -> build/lib.linux-aarch64-cpython-39/PIL
#0 97.15       running egg_info
#0 97.15       writing src/Pillow.egg-info/PKG-INFO
#0 97.15       writing dependency_links to src/Pillow.egg-info/dependency_links.txt
#0 97.15       writing requirements to src/Pillow.egg-info/requires.txt
#0 97.15       writing top-level names to src/Pillow.egg-info/top_level.txt
#0 97.15       reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
#0 97.15       reading manifest template 'MANIFEST.in'
#0 97.15       warning: no files found matching '*.c'
#0 97.15       warning: no files found matching '*.h'
#0 97.15       warning: no files found matching '*.sh'
#0 97.15       warning: no files found matching '*.txt'
#0 97.15       warning: no previously-included files found matching '.appveyor.yml'
#0 97.15       warning: no previously-included files found matching '.clang-format'
#0 97.15       warning: no previously-included files found matching '.coveragerc'
#0 97.15       warning: no previously-included files found matching '.editorconfig'
#0 97.15       warning: no previously-included files found matching '.readthedocs.yml'
#0 97.15       warning: no previously-included files found matching 'codecov.yml'
#0 97.15       warning: no previously-included files matching '.git*' found anywhere in distribution
#0 97.15       warning: no previously-included files matching '*.pyc' found anywhere in distribution
#0 97.15       warning: no previously-included files matching '*.so' found anywhere in distribution
#0 97.15       no previously-included directories found matching '.ci'
#0 97.15       adding license file 'LICENSE'
#0 97.15       writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
#0 97.15       running build_ext
#0 97.15       
#0 97.15       
#0 97.15       The headers or library files could not be found for zlib,
#0 97.15       a required dependency when compiling Pillow from source.
#0 97.15       
#0 97.15       Please see the install instructions at:
#0 97.15          https://pillow.readthedocs.io/en/latest/installation.html
#0 97.15       
#0 97.15       Traceback (most recent call last):
#0 97.15         File "/tmp/pip-install-as11ony6/pillow_d6cd4926581d4a71b106f74097947b91/setup.py", line 995, in <module>
#0 97.15           setup(
#0 97.15         File "/usr/local/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
#0 97.15           return distutils.core.setup(**attrs)
#0 97.15         File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 185, in setup
#0 97.15           return run_commands(dist)
#0 97.15         File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
#0 97.15           dist.run_commands()
#0 97.15         File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
#0 97.15           self.run_command(cmd)
#0 97.15         File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
#0 97.15           super().run_command(command)
#0 97.15         File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
#0 97.15           cmd_obj.run()
#0 97.15         File "/usr/local/lib/python3.9/site-packages/setuptools/command/install.py", line 68, in run
#0 97.15           return orig.install.run(self)
#0 97.15         File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/command/install.py", line 698, in run
#0 97.15           self.run_command('build')
#0 97.15         File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
#0 97.15           self.distribution.run_command(command)
#0 97.15         File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
#0 97.15           super().run_command(command)
#0 97.15         File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
#0 97.15           cmd_obj.run()
#0 97.15         File "/usr/local/lib/python3.9/site-packages/setuptools/command/build.py", line 24, in run
#0 97.15           super().run()
#0 97.15         File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/command/build.py", line 132, in run
#0 97.15           self.run_command(cmd_name)
#0 97.15         File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/cmd.py", line 319, in run_command
#0 97.15           self.distribution.run_command(command)
#0 97.15         File "/usr/local/lib/python3.9/site-packages/setuptools/dist.py", line 1217, in run_command
#0 97.15           super().run_command(command)
#0 97.15         File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
#0 97.15           cmd_obj.run()
#0 97.15         File "/usr/local/lib/python3.9/site-packages/setuptools/command/build_ext.py", line 79, in run
#0 97.15           _build_ext.run(self)
#0 97.15         File "/usr/local/lib/python3.9/site-packages/setuptools/_distutils/command/build_ext.py", line 346, in run
#0 97.15           self.build_extensions()
#0 97.15         File "/tmp/pip-install-as11ony6/pillow_d6cd4926581d4a71b106f74097947b91/setup.py", line 810, in build_extensions
#0 97.15           raise RequiredDependencyException(f)
#0 97.15       __main__.RequiredDependencyException: zlib
#0 97.15       
#0 97.15       During handling of the above exception, another exception occurred:
#0 97.15       
#0 97.15       Traceback (most recent call last):
#0 97.15         File "<string>", line 2, in <module>
#0 97.15         File "<pip-setuptools-caller>", line 34, in <module>
#0 97.15         File "/tmp/pip-install-as11ony6/pillow_d6cd4926581d4a71b106f74097947b91/setup.py", line 1015, in <module>
#0 97.15           raise RequiredDependencyException(msg)
#0 97.15       __main__.RequiredDependencyException:
#0 97.15       
#0 97.15       The headers or library files could not be found for zlib,
#0 97.15       a required dependency when compiling Pillow from source.
#0 97.15       
#0 97.15       Please see the install instructions at:
#0 97.15          https://pillow.readthedocs.io/en/latest/installation.html
#0 97.15       
#0 97.15       
#0 97.15       [end of output]
#0 97.15   
#0 97.15   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 97.15 error: legacy-install-failure
#0 97.15 
#0 97.15 × Encountered error while trying to install package.
#0 97.15 ╰─> Pillow
#0 97.15 
#0 97.15 note: This is an issue with the package mentioned above, not pip.
#0 97.15 hint: See above for output from the failure.
```
for whatever reason zlib is not recognized by Pillow
### What are your OS, Python and Pillow versions?

* OS: ARM alpine / docker / macOS
* Python: 3.9
* Pillow: 9.2.0

```python
code goes here
```

**Comment by TimotheusBachinger** [comment]
same on our side  for x68 ubuntu 20.04 / 22.04. 
this may be related to the new [setuptools](https://github.com/pypa/setuptools/tree/v63.3.0) version 63.3.0 as it was working in 62.2.0

**Comment by nanonyme** [comment]
@TimotheusBachinger our auto-updater would confirm your suspicion https://gitlab.com/freedesktop-sdk/freedesktop-sdk/-/merge_requests/9278; setuptools update indeed triggers this failure.

**Comment by TimotheusBachinger** [comment]
I think I already found the concerning commit in setuptools - reverting that hunk resolves the issue:
https://github.com/pypa/setuptools/commit/25dcca2902780146a1ee298f18648334eb3cddff

**Comment by TimotheusBachinger** [comment]
FYI: I've added a pull request both in setuptools and in distutils repo - it's unclear where they need the fix. hopefully we have a new release soon...

**Comment by chrismaddalena** [comment]
I was troubleshooting this issue with my build that uses `python:3.8-alpine3.14` and found my way here. My Django project had `Pillow==9.0.0` pinned and my build pipeline failed because of this. Same output as @arily. It looks like the PR is being reviewed, but I went looking for a simple workaround. On a whim, I tried upgrading to `Pillow==9.2.0` from earlier this month. My build succeeded with the latest `setuptools` v63.3.0 and `Pillow` v9.2.0.

I get reliable results with the following:

1. Change `Pillow` in requirements to: `Pillow==9.0.0`
2. Build Alpine Docker container with `--no-cache` to force a full re-build: `docker-compose -f local.yml build --no-cache`
3. Observe build fails when `Pillow` does not compile (same errors as above that suggest `zlib` is the problem)
4. Change requirements line to: `Pillow==9.2.0`
5. Build again without the cache
6. Observe the build succeed

I don't know what might be different for me, but thought it might be useful info. @arily mentioned using v9.2.0, so it would seem it's not just the version of `Pillow` that matters.

**Comment by TimotheusBachinger** [comment]
@chrismaddalena we're also looking for a simple workaround. I am wondering how yours can actually work out as the issue itself is residing in `setuptools==63.3.0`. Have you double checked that this version is **really** used?

**Comment by chrismaddalena** [comment]
@TimotheusBachinger In my working build with `Pillow==9.2.0`, the output of `pip list` shows the following (trimmed for brevity):

```
$ docker-compose -f local.yml run --rm django python -m pip list                                                                            130 ↵
[+] Running 1/0
 ⠿ Container ghostwriter-postgres-1  Running                                                                                                   0.0s
PostgreSQL is available
Package                       Version
----------------------------- -----------

« snip »

pickleshare                   0.7.5
Pillow                        9.2.0
pip                           22.2.1

« snip »

service-identity              21.1.0
setuptools                    63.3.0
six                           1.16.0

« snip »
```

I am also unsure why upgrading `Pillow` helped in my case. I committed the change to verify if it was local to my machine and Docker builds. The GitHub workflows were executed successfully with the change, so upgrading `Pillow` also got everything compiled on a GitHub workflow runner with a fresh environment.

**Comment by nulano** [comment]
The reason Pillow 9.2.0 installs correctly while Pillow 9.0.0 doesn't is likely because releases starting with Pillow 9.1.0 have included pre-built binary wheels for x86_64. Anyone failing to install and build Pillow on x86_64 might be interested in installing the `wheel` package first. However, no wheels are provided for ARM.

Latest Pillow can install using wheel:
```sh
$ docker run --rm -it alpine
/ # apk add python3
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.16/community/x86_64/APKINDEX.tar.gz
(1/13) Installing libbz2 (1.0.8-r1)
(2/13) Installing expat (2.4.8-r0)
(3/13) Installing libffi (3.4.2-r1)
(4/13) Installing gdbm (1.23-r0)
(5/13) Installing xz-libs (5.2.5-r1)
(6/13) Installing libgcc (11.2.1_git20220219-r2)
(7/13) Installing libstdc++ (11.2.1_git20220219-r2)
(8/13) Installing mpdecimal (2.5.1-r1)
(9/13) Installing ncurses-terminfo-base (6.3_p20220521-r0)
(10/13) Installing ncurses-libs (6.3_p20220521-r0)
(11/13) Installing readline (8.1.2-r0)
(12/13) Installing sqlite-libs (3.38.5-r0)
(13/13) Installing python3 (3.10.5-r0)
Executing busybox-1.35.0-r13.trigger
OK: 57 MiB in 27 packages
/ # python3 -m ensurepip
Looking in links: /tmp/tmp02vndzlh
Processing /tmp/tmp02vndzlh/setuptools-58.1.0-py3-none-any.whl
Processing /tmp/tmp02vndzlh/pip-22.0.4-py3-none-any.whl
Installing collected packages: setuptools, pip
Successfully installed pip-22.0.4 setuptools-58.1.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
/ # python3 -m pip install -U pip wheel
Requirement already satisfied: pip in /usr/lib/python3.10/site-packages (22.0.4)
Collecting pip
  Downloading pip-22.2.1-py3-none-any.whl (2.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 13.4 MB/s eta 0:00:00
Collecting wheel
  Downloading wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel, pip
  Attempting uninstall: pip
    Found existing installation: pip 22.0.4
    Uninstalling pip-22.0.4:
      Successfully uninstalled pip-22.0.4
Successfully installed pip-22.2.1 wheel-0.37.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
/ # python3 -m pip install Pillow
Collecting Pillow
  Downloading Pillow-9.2.0-cp310-cp310-musllinux_1_1_x86_64.whl (3.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 19.1 MB/s eta 0:00:00
Installing collected packages: Pillow
Successfully installed Pillow-9.2.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
/ #
```

Pillow 9.0.0 attempts to build wheel from source (and fails because I did not install zlib):

```sh
/ # python3 -m pip install 'Pillow==9.0.0'
Collecting Pillow==9.0.0
  Downloading Pillow-9.0.0.tar.gz (49.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.5/49.5 MB 30.1 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: Pillow
  Building wheel for Pillow (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [175 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-x86_64-3.10
      creating build/lib.linux-x86_64-3.10/PIL
      copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-x86_64-3.10/PIL

[snip]

      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.

      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html


      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Pillow
  Running setup.py clean for Pillow
Failed to build Pillow
Installing collected packages: Pillow
  Attempting uninstall: Pillow
    Found existing installation: Pillow 9.2.0
    Uninstalling Pillow-9.2.0:
      Successfully uninstalled Pillow-9.2.0
  Running setup.py install for Pillow ... error
  error: subprocess-exited-with-error

  × Running setup.py install for Pillow did not run successfully.
  │ exit code: 1
  ╰─> [177 lines of output]
      running install

[snip]

        File "/tmp/pip-install-anckv3zf/pillow_f11ba9282cda43f2abc35fba3cd7e0af/setup.py", line 804, in build_extensions
          raise RequiredDependencyException(f)
      __main__.RequiredDependencyException: zlib

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-anckv3zf/pillow_f11ba9282cda43f2abc35fba3cd7e0af/setup.py", line 1009, in <module>
          raise RequiredDependencyException(msg)
      __main__.RequiredDependencyException:

      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.

      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html


      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  Rolling back uninstall of Pillow
  Moving to /usr/lib/python3.10/site-packages/PIL/
   from /usr/lib/python3.10/site-packages/~IL
  Moving to /usr/lib/python3.10/site-packages/Pillow-9.2.0.dist-info/
   from /usr/lib/python3.10/site-packages/~illow-9.2.0.dist-info
  Moving to /usr/lib/python3.10/site-packages/Pillow.libs/
   from /usr/lib/python3.10/site-packages/~illow.libs
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> Pillow

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
/ #
```

**Comment by radarhere** [comment]
@TimotheusBachinger I see you closed https://github.com/pypa/distutils/pull/163, but I'm not seeing a reason why?

**Comment by TimotheusBachinger** [comment]
@radarhere yes you're right, added a comment. basically it got fixed in https://github.com/pypa/distutils/commit/f700a6b5f9965b3a886827d523271a2c9388edb5
btw. regarding @nulano 's comment... we need to build pillow from source, so we cannot used the wheels...

**Comment by radarhere** [comment]
Cool. It looks like setuptools 63.4.0 included that, so is this now resolved?

**Comment by TimotheusBachinger** [comment]
I would assume yes - but yesterday we managed to use again the old setuptools 63.2.0 (where the pillow build was possible), so I can only assume it is working again. @arily may confirm

**Comment by arily** [comment]
I can install successfully now, in both older setup tools or the latest one.

**Comment by radarhere** [comment]
Nice. Thanks to all who helped investigate this.
