### ISSUE TITLE
cannot identify image file <_io.BytesIO object at 0x00000189116CACA0>

### ISSUE THREAD

**Issue by Tamada4a** [python-pillow/Pillow#6589]
Hello! When i trying to open photo

``` py
import urllib.request
from PIL import Image

url = "https://disk.yandex.ru/client/disk/%D0%A2%D1%83%D1%80%D0%BD%D0%B8%D1%80%D1%8B/ZGL%20Pugachev%202022/%D0%A2%D1%83%D1%80%D0%BD%D0%B8%D1%80.%20%D0%A4%D0%BE%D1%82%D0%BE%20%D1%81%20%D1%85%D1%80%D0%BE%D0%BC%D0%B0%D0%BA%D0%BE%D0%BC?idApp=client&dialog=slider&idDialog=%2Fdisk%2F%D0%A2%D1%83%D1%80%D0%BD%D0%B8%D1%80%D1%8B%2FZGL%20Pugachev%202022%2F%D0%A2%D1%83%D1%80%D0%BD%D0%B8%D1%80.%20%D0%A4%D0%BE%D1%82%D0%BE%20%D1%81%20%D1%85%D1%80%D0%BE%D0%BC%D0%B0%D0%BA%D0%BE%D0%BC%2FMIK_8727.jpg"
response = urllib.request.urlopen(url)
img = Image.open(response)
```
I get the following error:
```
Traceback (most recent call last):
  File "C:\Users\volce\PycharmProjects\FaceRecognitionTest\main.py", line 66, in <module>
    main()
  File "C:\Users\volce\PycharmProjects\FaceRecognitionTest\main.py", line 62, in main
    train_model_by_img("Kirill")
  File "C:\Users\volce\PycharmProjects\FaceRecognitionTest\main.py", line 27, in train_model_by_img
    img = Image.open(response)
  File "C:\Users\volce\PycharmProjects\FaceRecognitionTest\venv\lib\site-packages\PIL\Image.py", line 3147, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x00000189116CACA0>
```
Whats happening? Why i get this error?

**Comment by radarhere** [comment]
If I run
```python
import urllib.request

url = "https://disk.yandex.ru/client/disk/%D0%A2%D1%83%D1%80%D0%BD%D0%B8%D1%80%D1%8B/ZGL%20Pugachev%202022/%D0%A2%D1%83%D1%80%D0%BD%D0%B8%D1%80.%20%D0%A4%D0%BE%D1%82%D0%BE%20%D1%81%20%D1%85%D1%80%D0%BE%D0%BC%D0%B0%D0%BA%D0%BE%D0%BC?idApp=client&dialog=slider&idDialog=%2Fdisk%2F%D0%A2%D1%83%D1%80%D0%BD%D0%B8%D1%80%D1%8B%2FZGL%20Pugachev%202022%2F%D0%A2%D1%83%D1%80%D0%BD%D0%B8%D1%80.%20%D0%A4%D0%BE%D1%82%D0%BE%20%D1%81%20%D1%85%D1%80%D0%BE%D0%BC%D0%B0%D0%BA%D0%BE%D0%BC%2FMIK_8727.jpg"
response = urllib.request.urlopen(url)
print(response.read())
```
and look at the output, I don't see image data, but HTML. It would appear that your image is hidden behind a login system, making this a urllib problem rather than a Pillow problem.

**Comment by Tamada4a** [comment]
@radarhere oh... what should I get when everything should work correctly?

**Comment by radarhere** [comment]
To use one of our test images,
```python
import urllib.request

url = "https://github.com/python-pillow/Pillow/raw/main/Tests/images/icc-after-SOF.jpg"
response = urllib.request.urlopen(url)
print(response.read())
```
gives
```
b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xe2\x00\x17ICC_PROFILE\x00\x01\x01profile\xff\xdb\x00C\x00\x08\x06\x06\x07\x06\x05\x08\x07\x07\x07\t\t\x08\n\x0c\x14\r\x0c\x0b\x0b\x0c\x19\x12\x13\x0f\x14\x1d\x1a\x1f\x1e\x1d\x1a\x1c\x1c $.\' ",#\x1c\x1c(7),01444\x1f\'9=82<.342\xff\xc0\x00\x0b\x08\x00\n\x00\n\x01\x01\x11\x00\xff\xc4\x00\x15\x00\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x08\xff\xe2\x00\x17ICC_PROFILE\x00\x01\x01profile\xff\xc4\x00\x14\x10\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xff\xda\x00\x08\x01\x01\x00\x00?\x00\x9f\xc0\x7f\xff\xd9'
```

The `b"\xff\xd8\xff"` at the start identifies the image as a JPEG. This is known as the [magic number.](https://en.wikipedia.org/wiki/JPEG)

**Comment by Tamada4a** [comment]
@radarhere thanks
