### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode character '\uXXX' in position 0: ordinal not in range(256) on font.getsize(text)

### ISSUE THREAD

**Issue by Mogztter** [python-pillow/Pillow#6745]
### What did you do?
```
$ python3 --version
Python 3.10.6
$ python3 -m venv .venv
$ source .venv/bin/activate
$ pip install Pillow==9.3.0
```

**test.py**
```py
# coding: utf-8
import sys
from PIL import Image, ImageDraw

out = Image.new("RGB", (150, 100), (255, 255, 255))

draw = ImageDraw.Draw(out)
bbox = draw.textbbox(text='春', xy=(0,0), font=None)
```
```console
$ python3 test.py
Traceback (most recent call last):
  File "/home/guillaume/workspace/yuzutech/kroki/pil/test.py", line 8, in <module>
    bbox = draw.textbbox(text='春', xy=(0,0), font=None)
  File "/home/guillaume/workspace/yuzutech/kroki/pil/.venv/lib/python3.10/site-packages/PIL/ImageDraw.py", line 729, in textbbox
    bbox = font.getbbox(
  File "/home/guillaume/workspace/yuzutech/kroki/pil/.venv/lib/python3.10/site-packages/PIL/ImageFont.py", line 189, in getbbox
    width, height = self.font.getsize(text)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u6625' in position 0: ordinal not in range(256)
```

### What did you expect to happen?

I was expecting the `textbbox` method to support unicode character. It was working fine on a previous version via Blockdiag.
For reference, Blockdiag was using `textsize` which is deprecated but I get the same error using `textsize` or `textbbox`.

### What actually happened?

Stacktrace ☝🏻 

### What are your OS, Python and Pillow versions?

* OS

```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```
* Python: 3.10.6
* Pillow: 9.3.0

**Comment by radarhere** [comment]
You are not supplying a font. The default Pillow font is "[better than nothing](https://pillow.readthedocs.io/en/stable/reference/ImageFont.html#PIL.ImageFont.load_default)", and [can only handle latin-1 characters.](https://github.com/python-pillow/Pillow/issues/2779#issuecomment-333798938)

I expect when you say it was working fine on a previous version, you were supplying a font at the time.

So just modify your code to something like
```python
import sys
from PIL import Image, ImageDraw, ImageFont

out = Image.new("RGB", (150, 100), (255, 255, 255))

draw = ImageDraw.Draw(out)
font = ImageFont.truetype('/System/Library/Fonts/Supplemental/Times New Roman.ttf')
bbox = draw.textbbox(text='春', xy=(0,0), font=font)
```
and the error should be resolved.

**Comment by Mogztter** [comment]
Thanks for the explanation @radarhere !
Now I need to understand why the font is not found anymore by Blockdiag 🤔
