### ISSUE TITLE
No module named 'PIL' with Pillow 9.3.0

### ISSUE THREAD

**Issue by AmphibianDev** [python-pillow/Pillow#6829]
### What did you do?
I am using [Tesstrain](https://github.com/tesseract-ocr/tesstrain) to train [Tesseract](https://github.com/tesseract-ocr/tesseract) using `make training ...`
And I have install the `pip install -r requirements.txt` in a conda env
Sorry if I posted in the wrong repository, but I think it's more of a problem with Pillow than Tesstrain.

### What did you expect to happen?
Running without errors

### What actually happened?
```
PYTHONIOENCODING=utf-8 python3 generate_line_box.py -i "data/DATA-ground-truth/000.tif" -t "data/DATA-ground-truth/000.gt.txt" > "data/DATA-ground-truth/000.box"
Traceback (most recent call last):
  File "/home/gg/tesstrain/generate_line_box.py", line 6, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
make: *** [Makefile:236: data/DATA-ground-truth/000.box] Error 1
```

### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Using WSL: Ubuntu 22.04.1 LTS
* Conda: 4.10.3
* Python: 3.10.6
* Pillow: 9.3.0

```console
$ python3 -m pip list
Package                Version
---------------------- ---------------
blinker                1.4
command-not-found      0.3
contourpy              1.0.6
cryptography           3.4.8
cycler                 0.11.0
dbus-python            1.2.18
distro                 1.7.0
distro-info            1.1build1
fonttools              4.38.0
httplib2               0.20.2
importlib-metadata     4.6.4
jeepney                0.7.1
keyring                23.5.0
kiwisolver             1.4.4
launchpadlib           1.10.16
lazr.restfulclient     0.14.4
lazr.uri               1.0.6
matplotlib             3.6.2
more-itertools         8.10.0
netifaces              0.11.0
numpy                  1.24.1
oauthlib               3.2.0
packaging              22.0
pandas                 1.5.2
Pillow                 9.3.0
pip                    22.3.1
PyGObject              3.42.1
PyJWT                  2.3.0
pyparsing              2.4.7
python-apt             2.3.0+ubuntu2.1
python-bidi            0.4.2
python-dateutil        2.8.2
pytz                   2022.7
PyYAML                 5.4.1
SecretStorage          3.3.1
setuptools             59.6.0
six                    1.16.0
systemd-python         234
ubuntu-advantage-tools 27.11.2
ufw                    0.36.1
unattended-upgrades    0.1
wadllib                1.3.6
wheel                  0.37.1
zipp                   1.0.0
```

**Comment by hugovk** [comment]
Rather than running `pip list`, what do you get for `python3 -m pip list`?

See https://snarky.ca/why-you-should-use-python-m-pip/

**Comment by AmphibianDev** [comment]
@hugovk I edited `pip list` with `python3 -m pip list` and it's the same.

**Comment by radarhere** [comment]
Hi. Some more questions.

1. Are you running
`python3 -m pip list`
from the same environment as
`PYTHONIOENCODING=utf-8 python3 generate_line_box.py -i "data/DATA-ground-truth/000.tif" -t "data/DATA-ground-truth/000.gt.txt" > "data/DATA-ground-truth/000.box"`
?
This might be nothing, but
`PYTHONIOENCODING=utf-8 python3 generate_line_box.py -i "data/DATA-ground-truth/000.tif" -t "data/DATA-ground-truth/000.gt.txt" > "data/DATA-ground-truth/000.box"`
doesn't start with a dollar sign in your first comment, so it makes me wonder.

2. If you run `python3 -m PIL`, does it work?

3. If you create a simple 'test.py' script with `from PIL import Image` and then run `python3 test.py`, does it work?

**Comment by AmphibianDev** [comment]
@radarhere I am not sure in what env `generate_line_box.py` is on, because is run by a another python script, but every command here has ben run on my "tess" conda env.
```
$ sudo TESSDATA_PREFIX=../tesseract/tessdata make training PSM=7 MODEL_NAME=DATA START_MODEL=eng TESSDATA=../tesseract/tessdata MAX_ITERATIONS=100
Bad box coordinates in boxfile string! 705
Extracting unicharset from plain text file data/DATA/all-gt
Wrote unicharset file data/DATA/my.unicharset
merge_unicharsets data/eng/DATA.lstm-unicharset data/DATA/my.unicharset "data/DATA/unicharset"
Loaded unicharset of size 112 from file data/eng/DATA.lstm-unicharset
Loaded unicharset of size 14 from file data/DATA/my.unicharset
Wrote unicharset file data/DATA/unicharset.
PYTHONIOENCODING=utf-8 python3 generate_line_box.py -i "data/DATA-ground-truth/000.tif" -t "data/DATA-ground-truth/000.gt.txt" > "data/DATA-ground-truth/000.box"
Traceback (most recent call last):
  File "/home/gg/tesstrain/generate_line_box.py", line 6, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'
make: *** [Makefile:236: data/DATA-ground-truth/000.box] Error 1
```
```
$ cat test.py
from PIL import Image
print(Image)

$ python3 test.py
<module 'PIL.Image' from '/home/gg/.local/lib/python3.10/site-packages/PIL/Image.py'>
```
```
$ python3 -m PIL
--------------------------------------------------------------------
Pillow 9.3.0
Python 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
--------------------------------------------------------------------
Python modules loaded from /home/gg/.local/lib/python3.10/site-packages/PIL
Binary modules loaded from /home/gg/.local/lib/python3.10/site-packages/PIL
--------------------------------------------------------------------
--- PIL CORE support ok, compiled for 9.3.0
*** TKINTER support not installed
--- FREETYPE2 support ok, loaded 2.12.1
--- LITTLECMS2 support ok, loaded 2.13.1
--- WEBP support ok, loaded 1.2.4
--- WEBP Transparency support ok
--- WEBPMUX support ok
--- WEBP Animation support ok
--- JPEG support ok, compiled for libjpeg-turbo 2.1.4
--- OPENJPEG (JPEG2000) support ok, loaded 2.5.0
--- ZLIB (PNG/ZIP) support ok, loaded 1.2.11
--- LIBTIFF support ok, loaded 4.4.0
--- RAQM (Bidirectional Text) support ok, loaded 0.9.0, fribidi 1.0.8, harfbuzz 5.3.1
*** LIBIMAGEQUANT (Quantization method) support not installed
--- XCB (X protocol) support ok
--------------------------------------------------------------------
BLP
Extensions: .blp
Features: open, save, encode
--------------------------------------------------------------------
BMP image/bmp
Extensions: .bmp
Features: open, save
--------------------------------------------------------------------
....
```

**Comment by radarhere** [comment]
So Pillow is correctly installed. I just have to presume that you have more than one Python environment somehow.

I'm not overly optimistic about this idea, but you used `sudo` for the tesseract command. If you run `sudo python3 -m pip list`, is Pillow missing from that?

**Comment by AmphibianDev** [comment]
@radarhere  You are amazing, that was exactly the problem.
Thanks a lot, and happy new year.
