### ISSUE TITLE
Error importing PIL since package upgrade - Endevour OS (Arch) Linux

### ISSUE THREAD

**Issue by lewis-morris** [python-pillow/Pillow#6864]
Recently updated my packages with  `pacman` and since I've been unable to import `PIL.Image`

(6.1.1-arch1-1)

After this python was complaining about not being able to find;

libtiff.so.5

Checked the install log and couldn't easily find the offending package...

So I just created a symlink to 6 -> 5 as 5 no longer existed.

`sudo ln -s /usr/lib/libtiff.so.6 /usr/lib/libtiff.so.5`

Hacky but its working haha

**Comment by Th3N3rdyGam3r** [comment]
I'm experiencing the same issue, with it causing the following error trying to launch Lutris
```
Traceback (most recent call last):
  File "/usr/bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/usr/lib/python3.10/site-packages/lutris/gui/application.py", line 40, in <module>
    from lutris.game import Game, export_game, import_game
  File "/usr/lib/python3.10/site-packages/lutris/game.py", line 24, in <module>
    from lutris.runners import InvalidRunner, import_runner, wine
  File "/usr/lib/python3.10/site-packages/lutris/runners/wine.py", line 24, in <module>
    from lutris.util.wine.extract_icon import PEFILE_AVAILABLE, ExtractIcon
  File "/usr/lib/python3.10/site-packages/lutris/util/wine/extract_icon.py", line 12, in <module>
    from PIL import Image
  File "/home/cameron/.local/lib/python3.10/site-packages/PIL/Image.py", line 109, in <module>
    from . import _imaging as core
ImportError: libtiff.so.5: cannot open shared object file: No such file or directory
```
Pillow 9.4.0-2 is installed through the python-pillow package from the arch community repository. I've reinstalled libtiff, python-pillow, and lutris in that order with the same error occurring.

**Comment by radarhere** [comment]
If so, then it sounds like this is a problem to be reported at https://archlinux.org/packages/community/x86_64/python-pillow/, not here. We only control the Pillow source code and wheels, not the arch package.

**Comment by Th3N3rdyGam3r** [comment]
Not sure what happened, but reinstalling with sudo failed while without sudo seems to have fixed it for me after upgrading it from an old version.
```
[cameron@desktop ~]$ sudo pip install pillow --force-reinstall
[sudo] password for cameron: 
Collecting pillow
  Using cached Pillow-9.4.0-cp310-cp310-manylinux_2_28_x86_64.whl (3.4 MB)
Installing collected packages: pillow
  Attempting uninstall: pillow
    Found existing installation: Pillow 9.4.0
    Uninstalling Pillow-9.4.0:
      Successfully uninstalled Pillow-9.4.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
qmk 1.1.1 requires pyserial, which is not installed.
Successfully installed pillow-9.4.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
[cameron@desktop ~]$ lutris
Traceback (most recent call last):
  File "/usr/bin/lutris", line 52, in <module>
    from lutris.gui.application import Application  # pylint: disable=no-name-in-module
  File "/usr/lib/python3.10/site-packages/lutris/gui/application.py", line 40, in <module>
    from lutris.game import Game, export_game, import_game
  File "/usr/lib/python3.10/site-packages/lutris/game.py", line 24, in <module>
    from lutris.runners import InvalidRunner, import_runner, wine
  File "/usr/lib/python3.10/site-packages/lutris/runners/wine.py", line 24, in <module>
    from lutris.util.wine.extract_icon import PEFILE_AVAILABLE, ExtractIcon
  File "/usr/lib/python3.10/site-packages/lutris/util/wine/extract_icon.py", line 12, in <module>
    from PIL import Image
  File "/home/cameron/.local/lib/python3.10/site-packages/PIL/Image.py", line 109, in <module>
    from . import _imaging as core
ImportError: libtiff.so.5: cannot open shared object file: No such file or directory
[cameron@desktop ~]$ pip install pillow --force-reinstall
Defaulting to user installation because normal site-packages is not writeable
Collecting pillow
  Downloading Pillow-9.4.0-cp310-cp310-manylinux_2_28_x86_64.whl (3.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.4/3.4 MB 25.1 MB/s eta 0:00:00
Installing collected packages: pillow
  Attempting uninstall: pillow
    Found existing installation: Pillow 8.2.0
    Uninstalling Pillow-8.2.0:
      Successfully uninstalled Pillow-8.2.0
Successfully installed pillow-9.4.0
[cameron@desktop ~]$ lutris
2023-01-06 00:14:37,253: Starting Lutris 0.5.12
2023-01-06 00:14:37,374: Using NVIDIA drivers 525.60.11 for x86_64
2023-01-06 00:14:37,374: GPU: NVIDIA GeForce GTX 1070
2023-01-06 00:14:37,374: GPU: 10DE:1B81 1043:8599 (nvidia drivers)
2023-01-06 00:14:38,290: Runtime is fully updated.
2023-01-06 00:14:40,601: Startup complete
```

**Comment by radarhere** [comment]
I would imagine that the difference is that you also aren't running lutris with sudo. There was similar problem recently where [Pillow wasn't detected when running sudo, but was without it](https://github.com/python-pillow/Pillow/issues/6829#issuecomment-1367050119).

**Comment by Th3N3rdyGam3r** [comment]
I decided to test and removed pillow from the user (non sudo) environment, and Lutris still ran. My guess would be that the update from pacman is in the root (sudo) environment, but an older version that was installed to the user environment was being prioritized and not updated along with the rest of the system. Thanks for your help!

**Comment by lewis-morris** [comment]
> If you install Pillow through pip, rather than through the package, does it work?

To be fair, this didn't even
