### ISSUE TITLE
Runtime error - mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64')

### ISSUE THREAD

**Issue by rcwestlake** [python-pillow/Pillow#6910]
### What did you do?
I installed `reportlab` which adds `Pillow` as a dependency. It installs fine. When I run my code, it errors.

### What did you expect to happen?
I expect that it should run without errors. 

### What actually happened?
With this code in my view:

```python
class XGenReport(APIView):
    def get(self, request, format="pdf"):
        # Create the PDF object, using the response object as its "file."
        response = HttpResponse(content_type="application/pdf")
        response["Content-Disposition"] = 'attachment; filename="somefilename.pdf"'
        p = canvas.Canvas(response)

        # Draw things on the PDF. Here's where the PDF generation happens.
        # See the ReportLab documentation for the full list of functionality.
        p.drawString(100, 100, "Hello world.")

        # Close the PDF object cleanly, and we're done.
        p.showPage()
        p.save()
        return response
```

I get this error:
```pytb
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/ryanwestlake/Documents/Dev/challenger-api/venv/lib/python3.8/site-packages/django/utils/autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "/Users/ryanwestlake/Documents/Dev/challenger-api/venv/lib/python3.8/site-packages/django/core/management/commands/runserver.py", line 134, in inner_run
    self.check(display_num_errors=True)
  File "/Users/ryanwestlake/Documents/Dev/challenger-api/venv/lib/python3.8/site-packages/django/core/management/base.py", line 475, in check
    all_issues = checks.run_checks(
  File "/Users/ryanwestlake/Documents/Dev/challenger-api/venv/lib/python3.8/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/Users/ryanwestlake/Documents/Dev/challenger-api/venv/lib/python3.8/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/Users/ryanwestlake/Documents/Dev/challenger-api/venv/lib/python3.8/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/Users/ryanwestlake/Documents/Dev/challenger-api/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/Users/ryanwestlake/Documents/Dev/challenger-api/venv/lib/python3.8/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/ryanwestlake/Documents/Dev/challenger-api/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Users/ryanwestlake/Documents/Dev/challenger-api/venv/lib/python3.8/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/Users/ryanwestlake/Documents/Dev/challenger-api/venv/lib/python3.8/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/ryanwestlake/Documents/Dev/challenger-api/core/urls.py", line 9, in <module>
    path("api/", include("api.urls")),
  File "/Users/ryanwestlake/Documents/Dev/challenger-api/venv/lib/python3.8/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/ryanwestlake/Documents/Dev/challenger-api/api/urls.py", line 7, in <module>
    path("v02/", include("api.version.v02.urls")),
  File "/Users/ryanwestlake/Documents/Dev/challenger-api/venv/lib/python3.8/site-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/ryanwestlake/Documents/Dev/challenger-api/api/version/v02/urls.py", line 30, in <module>
    from esa.hradmin.reporting.views import GenerateMonthlyReportView
  File "/Users/ryanwestlake/Documents/Dev/challenger-api/esa/hradmin/reporting/views.py", line 3, in <module>
    from reportlab.pdfgen import canvas
  File "/Users/ryanwestlake/Documents/Dev/challenger-api/venv/lib/python3.8/site-packages/reportlab/pdfgen/canvas.py", line 16, in <module>
    from reportlab import rl_config
  File "/Users/ryanwestlake/Documents/Dev/challenger-api/venv/lib/python3.8/site-packages/reportlab/rl_config.py", line 45, in <module>
    _DEFAULTS=_defaults_init()
  File "/Users/ryanwestlake/Documents/Dev/challenger-api/venv/lib/python3.8/site-packages/reportlab/rl_config.py", line 13, in _defaults_init
    from reportlab.lib.utils import rl_exec
  File "/Users/ryanwestlake/Documents/Dev/challenger-api/venv/lib/python3.8/site-packages/reportlab/lib/utils.py", line 15, in <module>
    from PIL import Image
  File "/Users/ryanwestlake/Documents/Dev/challenger-api/venv/lib/python3.8/site-packages/PIL/Image.py", line 100, in <module>
    from . import _imaging as core
ImportError: dlopen(/Users/ryanwestlake/Documents/Dev/challenger-api/venv/lib/python3.8/site-packages/PIL/_imaging.cpython-38-darwin.so, 0x0002): tried: '/Users/ryanwestlake/Documents/Dev/challenger-api/venv/lib/python3.8/site-packages/PIL/_imaging.cpython-38-darwin.so' (mach-o file, but is an incompatible architecture (have 'arm64', need 'x86_64'))
```

### What are your OS, Python and Pillow versions?

* OS: `12.3.1 (Monterey)`
* Python: `3.8.9`
* Pillow: `9.4.0`

**Comment by hugovk** [comment]
Does something like this help?

```sh
python -m pip uninstall -y pillow
python -m pip install pillow
```

**Comment by radarhere** [comment]
To check - your Mac is an M1 or an M2, yes? It's not a Mac with an Intel chip?

**Comment by radarhere** [comment]
If you're looking for an immediate solution, you may be interested in a universal2 wheel - [Pillow-9.4.0-cp38-cp38-macosx_10_10_universal2.whl.zip](https://github.com/python-pillow/Pillow/files/10508843/Pillow-9.4.0-cp38-cp38-macosx_10_10_universal2.whl.zip). You can install it with `python3 -m pip install Pillow-9.4.0-cp38-cp38-macosx_10_10_universal2.whl`

With that, it shouldn't matter what your architecture is.

**Comment by rcwestlake** [comment]
@hugovk - confirmed - this does not work.

@radarhere
- yes it is M1
<img width="220" alt="image" src="https://user-images.githubusercontent.com/9679076/214903890-a3984d72-5632-4ba7-b94e-9409a75daf07.png">
- I will try the universal wheel

**Comment by rcwestlake** [comment]
@radarhere - confirming this worked! thank you :). For a more permanent fix and one that uses the package as normal, have you seen anyone else run into this with a working solution?

**Comment by nulano** [comment]
https://github.com/python-pillow/Pillow/issues/5322 solved a similar issue by upgrading to Python 3.9.

**Comment by radarhere** [comment]
Interesting point! You're using Python 3.8.9, but Python 3.8.10 is the earliest Python version to support Big Sur (let alone Monterey) and Apple Silicon. See https://www.python.org/downloads/release/python-3810/

> But there's a bunch of important updates here regardless, the biggest being Big Sur and Apple Silicon build support.

**Comment by rcwestlake** [comment]
Thanks all for the quick responses and help - that was awesome. The universal wheel was a temporary fix. I'll look to upgrade to `3.8.10` for the better fix. I'll go ahead and close the issue.
