### ISSUE TITLE
Import error on termux

### ISSUE THREAD

**Issue by AngelDev06** [python-pillow/Pillow#7335]
### What did you do?
Run a script of mine
I installed Pillow on termux with the following command:
`LDFLAGS="-L/system/lib64/" CFLAGS="-I/data/data/com.termux/files/usr/include/" pip install Pillow`
### What did you expect to happen?
I expected an image to be generated listing members with progress bars & given fond
### What actually happened?
Got an import error with the following traceback:
```python
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/storage/repositories/transcript_analyser/.venv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 827, in _do_call
    return await self._callback(self.binding, interaction, **params)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/storage/repositories/transcript_analyser/commands.py", line 192, in analyse
    fp = await generate_image(interaction, char_counters_list, total_char_count)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/storage/repositories/transcript_analyser/PILutils.py", line 33, in generate_image
    fnt = ImageFont.truetype("fonts/chunkfive/ChunkFive-Regular.otf", size=100)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/storage/repositories/transcript_analyser/.venv/lib/python3.11/site-packages/PIL/ImageFont.py", line 791, in truetype
    return freetype(font)
           ^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/storage/repositories/transcript_analyser/.venv/lib/python3.11/site-packages/PIL/ImageFont.py", line 788, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/storage/repositories/transcript_analyser/.venv/lib/python3.11/site-packages/PIL/ImageFont.py", line 198, in __init__
    if core.HAVE_RAQM:
       ^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/storage/repositories/transcript_analyser/.venv/lib/python3.11/site-packages/PIL/_util.py", line 19, in __getattr__
    raise self.ex
  File "/data/data/com.termux/files/home/storage/repositories/transcript_analyser/.venv/lib/python3.11/site-packages/PIL/ImageFont.py", line 48, in <module>
    from . import _imagingft as core
ImportError: cannot import name '_imagingft' from 'PIL' (/data/data/com.termux/files/home/storage/repositories/transcript_analyser/.venv/lib/python3.11/site-packages/PIL/__init__.py)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/data/com.termux/files/home/storage/repositories/transcript_analyser/.venv/lib/python3.11/site-packages/discord/app_commands/tree.py", line 1248, in _call
    await command._invoke_with_namespace(interaction, namespace)
  File "/data/data/com.termux/files/home/storage/repositories/transcript_analyser/.venv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 853, in _invoke_with_namespace
    return await self._do_call(interaction, transformed_values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/storage/repositories/transcript_analyser/.venv/lib/python3.11/site-packages/discord/app_commands/commands.py", line 846, in _do_call
    raise CommandInvokeError(self, e) from e
discord.app_commands.errors.CommandInvokeError: Command 'analyse' raised an exception: ImportError: cannot import name '_imagingft' from 'PIL' (/data/data/com.termux/files/home/storage/repositories/transcript_analyser/.venv/lib/python3.11/site-packages/PIL/__init__.py)
```

Note: there was no such issue when I was running it on windows, however since I will be on vacation in the coming days I decided to run it on termux (on my android device) and the above occured

### What are your OS, Python and Pillow versions?

* OS: android 10 (QKQ1.190910.002)
* Python: 3.11.4
* Pillow: 10.0.0

```python
async def generate_image(
    interaction: discord.Interaction,
    char_counters: list[tuple[int, int]],
    total_char_count: int,
    start: int = 0,
    end: int = 4, /
) -> io.BytesIO:
    image = Image.new("RGB", (1920, 1080), "#0096C7")
    draw = ImageDraw.Draw(image)
    fnt = ImageFont.truetype("fonts/chunkfive/ChunkFive-Regular.otf", size=100)
    fnt2 = ImageFont.truetype("fonts/chunkfive/ChunkFive-Regular.otf", size=70)
    ymax = (image.size[1] // 5) + 20

    for index, (member_id, char_count) in enumerate(char_counters[start:end]):
        member = interaction.guild.get_member(member_id)
        member_color = f"#{member.color.r:02x}{member.color.g:02x}{member.color.b:02x}"
        percentage = round((char_count / total_char_count) * 100, 2)
        info_field = (image.size[0] // 16, ymax + (ymax * index))
        text_field = ((info_field[0] * 3) - 50, (ymax * index) + ((ymax // 5) - 10))
        small_text_field = ((info_field[0] * 3) - 50, (ymax * index) + ((ymax // 2) + 25))
        icon_field = (info_field[0], (ymax * index) + (ymax // 4))
        progress_bar_field = (info_field[0], info_field[1] - 10)

        avatar = io.BytesIO()
        await member.display_avatar.replace(format="png", static_format="png").save(avatar)

        with Image.open(avatar, formats=("PNG",)) as avatarpng:
            resized = avatarpng.resize((150, 150))
            image.paste(resized, icon_field)

        draw.text(text_field, f"{member.name} ({percentage}%)", member.color.value, font=fnt)
        draw.text(small_text_field, f"{char_count}/{total_char_count}", member.color.value, font=fnt2)
        draw_progress_bar(draw, progress_bar_field, (1000, 50), percentage / 100, fg=member_color)
```

**Comment by romanovj** [comment]
try termux package

pkg install python-pillow
