### ISSUE TITLE
AttributeError: module 'PIL.Image' has no attribute 'ImagePointHandler'

### ISSUE THREAD

**Issue by ArchangeGabriel** [python-pillow/Pillow#7342]
### What did you do?

```python
from PIL.ImageCms import ImageCmsProfile
```

### What did you expect to happen?

No error / successful import.

### What actually happened?

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 1
----> 1 from PIL.ImageCms import ImageCmsProfile

File /usr/lib/python3.11/site-packages/PIL/ImageCms.py:202
    192         """
    193         Returns the profile in a format suitable for embedding in
    194         saved images.
    195 
    196         :returns: a bytes object containing the ICC profile.
    197         """
    199         return core.profile_tobytes(self.profile)
--> 202 class ImageCmsTransform(Image.ImagePointHandler):
    204     """
    205     Transform.  This can be used with the procedural API, or with the standard
    206     :py:func:`~PIL.Image.Image.point` method.
    207 
    208     Will return the output profile in the ``output.info['icc_profile']``.
    209     """
    211     def __init__(
    212         self,
    213         input,
   (...)
    220         flags=0,
    221     ):

AttributeError: module 'PIL.Image' has no attribute 'ImagePointHandler'
```

### What are your OS, Python and Pillow versions?

* OS: Arch Linux
* Python: 3.11
* Pillow: 10.0.0

Rq: the issue was detected by trying to run pdfarranger, which resulted in:
```python
Traceback (most recent call last):
  File "/usr/bin/pdfarranger", line 5, in <module>
    from pdfarranger.pdfarranger import main
  File "/usr/lib/python3.11/site-packages/pdfarranger/pdfarranger.py", line 38, in <module>
    import pikepdf
  File "/usr/lib/python3.11/site-packages/pikepdf/__init__.py", line 53, in <module>
    from .models import (
  File "/usr/lib/python3.11/site-packages/pikepdf/models/__init__.py", line 16, in <module>
    from .image import PdfImage, PdfInlineImage, UnsupportedImageTypeError
  File "/usr/lib/python3.11/site-packages/pikepdf/models/image.py", line 18, in <module>
    from PIL.ImageCms import ImageCmsProfile
  File "/usr/lib/python3.11/site-packages/PIL/ImageCms.py", line 202, in <module>
    class ImageCmsTransform(Image.ImagePointHandler):
                            ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'PIL.Image' has no attribute 'ImagePointHandler'
```

**Comment by hugovk** [comment]
Hmm, `ImagePointHandler` was added in PIL 1.1.7 in 2009. 

Please can you check your `PIL.Image` module, and that it looks something like https://github.com/python-pillow/Pillow/blob/main/src/PIL/Image.py?

I'm wondering if you've got another file that's overriding the real one.

**Comment by ArchangeGabriel** [comment]
Very interesting. That file was actually empty, seems something is going wrong with my filesystem. Reinstalling pillow fixed the issue, thanks for this (en)lightning help and sorry for the noise!
