### ISSUE TITLE
Tried installing Pillow but it will not install

### ISSUE THREAD

**Issue by v84lol** [python-pillow/Pillow#7393]
Trying to install Pillow but it will not work.

When I installed I got this:

```
Defaulting to user installation because normal site-packages is not writeable
Collecting pillow
  Using cached Pillow-10.0.0.tar.gz (50.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: pillow
  Building wheel for pillow (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for pillow (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [198 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win32-cpython-38
      creating build\lib.win32-cpython-38\PIL
      copying src\PIL\BdfFontFile.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\BlpImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\BmpImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\BufrStubImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\ContainerIO.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\CurImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\DcxImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\DdsImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\EpsImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\ExifTags.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\features.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\FitsImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\FliImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\FontFile.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\FpxImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\FtexImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\GbrImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\GdImageFile.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\GifImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\GimpGradientFile.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\GimpPaletteFile.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\GribStubImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\Hdf5StubImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\IcnsImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\IcoImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\Image.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\ImageChops.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\ImageCms.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\ImageColor.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\ImageDraw.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\ImageDraw2.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\ImageEnhance.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\ImageFile.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\ImageFilter.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\ImageFont.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\ImageGrab.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\ImageMath.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\ImageMode.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\ImageMorph.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\ImageOps.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\ImagePalette.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\ImagePath.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\ImageQt.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\ImageSequence.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\ImageShow.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\ImageStat.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\ImageTk.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\ImageTransform.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\ImageWin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\ImImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\ImtImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\IptcImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\Jpeg2KImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\JpegImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\JpegPresets.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\McIdasImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\MicImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\MpegImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\MpoImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\MspImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\PaletteFile.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\PalmImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\PcdImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\PcfFontFile.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\PcxImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\PdfImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\PdfParser.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\PixarImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\PngImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\PpmImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\PsdImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\PSDraw.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\PyAccess.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\QoiImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\SgiImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\SpiderImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\SunImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\TarIO.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\TgaImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\TiffImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\TiffTags.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\WalImageFile.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\WebPImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\WmfImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\XbmImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\XpmImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\XVThumbImagePlugin.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\_binary.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\_deprecate.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\_tkinter_finder.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\_util.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\_version.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\__init__.py -> build\lib.win32-cpython-38\PIL
      copying src\PIL\__main__.py -> build\lib.win32-cpython-38\PIL
      running egg_info
      writing src\Pillow.egg-info\PKG-INFO
      writing dependency_links to src\Pillow.egg-info\dependency_links.txt
      writing requirements to src\Pillow.egg-info\requires.txt
      writing top-level names to src\Pillow.egg-info\top_level.txt
      reading manifest file 'src\Pillow.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.c'
      warning: no files found matching '*.h'
      warning: no files found matching '*.sh'
      warning: no files found matching '*.txt'
      warning: no previously-included files found matching '.appveyor.yml'
      warning: no previously-included files found matching '.clang-format'
      warning: no previously-included files found matching '.coveragerc'
      warning: no previously-included files found matching '.editorconfig'
      warning: no previously-included files found matching '.readthedocs.yml'
      warning: no previously-included files found matching 'codecov.yml'
      warning: no previously-included files found matching 'renovate.json'
      warning: no previously-included files matching '.git*' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      no previously-included directories found matching '.ci'
      adding license file 'LICENSE'
      writing manifest file 'src\Pillow.egg-info\SOURCES.txt'
      running build_ext


      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.

      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html

      Traceback (most recent call last):
        File "<string>", line 988, in <module>
        File "C:\Users\alloa026\AppData\Local\Temp\pip-build-env-m475hw1n\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\alloa026\AppData\Local\Temp\pip-build-env-m475hw1n\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
        File "C:\Users\alloa026\AppData\Local\Temp\pip-build-env-m475hw1n\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\alloa026\AppData\Local\Temp\pip-build-env-m475hw1n\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\alloa026\AppData\Local\Temp\pip-build-env-m475hw1n\overlay\Lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\alloa026\AppData\Local\Temp\pip-build-env-m475hw1n\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\alloa026\AppData\Local\Temp\pip-build-env-m475hw1n\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "C:\Users\alloa026\AppData\Local\Temp\pip-build-env-m475hw1n\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\alloa026\AppData\Local\Temp\pip-build-env-m475hw1n\overlay\Lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\alloa026\AppData\Local\Temp\pip-build-env-m475hw1n\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\alloa026\AppData\Local\Temp\pip-build-env-m475hw1n\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\alloa026\AppData\Local\Temp\pip-build-env-m475hw1n\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\alloa026\AppData\Local\Temp\pip-build-env-m475hw1n\overlay\Lib\site-packages\setuptools\dist.py", line 989, in run_command
          super().run_command(command)
        File "C:\Users\alloa026\AppData\Local\Temp\pip-build-env-m475hw1n\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\alloa026\AppData\Local\Temp\pip-build-env-m475hw1n\overlay\Lib\site-packages\setuptools\command\build_ext.py", line 88, in run
          _build_ext.run(self)
        File "C:\Users\alloa026\AppData\Local\Temp\pip-build-env-m475hw1n\overlay\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "<string>", line 811, in build_extensions
      __main__.RequiredDependencyException: zlib

      During handling of the above exception, another exception occurred:

      Traceback (most recent call last):
        File "C:\Users\alloa026\AppData\Roaming\Python\Python38\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\alloa026\AppData\Roaming\Python\Python38\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\alloa026\AppData\Roaming\Python\Python38\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
        File "C:\Users\alloa026\AppData\Local\Temp\pip-install-za6tm5qq\pillow_bfa4182b940249168c793c2a9ad46ca5\_custom_build\backend.py", line 53, in build_wheel
          return super().build_wheel(wheel_directory, config_settings, metadata_directory)
        File "C:\Users\alloa026\AppData\Local\Temp\pip-build-env-m475hw1n\overlay\Lib\site-packages\setuptools\build_meta.py", line 434, in build_wheel
          return self._build_with_temp_dir(
        File "C:\Users\alloa026\AppData\Local\Temp\pip-build-env-m475hw1n\overlay\Lib\site-packages\setuptools\build_meta.py", line 419, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\alloa026\AppData\Local\Temp\pip-install-za6tm5qq\pillow_bfa4182b940249168c793c2a9ad46ca5\_custom_build\backend.py", line 47, in run_setup
          return super().run_setup(setup_script)
        File "C:\Users\alloa026\AppData\Local\Temp\pip-build-env-m475hw1n\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 1005, in <module>
      __main__.RequiredDependencyException:

      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.

      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html


      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pillow
Failed to build pillow
ERROR: Could not build wheels for pillow, which is required to install pyproject.toml-based projects
```

OS: Windows 10 64bit
Python Version: 3.8
Pillow: 10.0.0

**Comment by radarhere** [comment]
Hi. Have you tried upgrading pip? `python3 -m pip install --upgrade pip`

**Comment by v84lol** [comment]
@radarhere Yes, though I cannot use the "python3" command due to weird privellege reasons, but I can use "py".

**Comment by radarhere** [comment]
So, somehow, pip is not finding our prebuilt wheel, and trying to build Pillow from source.

If you would like to continue trying to build from source, there are instructions at https://pillow.readthedocs.io/en/stable/installation.html#building-from-source

If you would like to try and figure out why the wheel isn't working, we can keep talking. If you will humour me, are you able to install Pillow 9.5.0? `py -m pip install Pillow==9.5.0`

**Comment by homm** [comment]
What is you CPU architecture? What happens if you try to download and run "pip install [Pillow-10.0.0-cp38-cp38-win_amd64.whl](https://files.pythonhosted.org/packages/5e/ae/0d98e3707678c96d86aec0fe5002637801892f17281cc123521ab929e8fd/Pillow-10.0.0-cp38-cp38-win_amd64.whl)"?

**Comment by Darskiy** [comment]
> If you would like to try and figure out why the wheel isn't working, we can keep talking. If you will humour me, are you able to install Pillow 9.5.0? `py -m pip install Pillow==9.5.0`

I have the same problem
Windows 11 22H2 (Build 22621.2283) 64bit
Python 3.11.5 (pip 23.2.1, wheel 0.41.2)
Pillow 9.5.0 is successfully installed, but everything above is not
I also noticed that everything is working on the linux server, in particular with the debian 12 distribution, the problem occurs only on windows OS

**Comment by radarhere** [comment]
The reason I mentioned Pillow 9.5.0 is that this is the last Pillow version where we released 32-bit wheels. Could you run `import sys;print(sys.maxsize)` in Python and let us know what it reports?

If it reports 2147483647, then yes, you are running Python in 32-bit mode.
If it reports 9223372036854775807, then you are running Python in 64-bit mode, and something else is happening.

**Comment by homm** [comment]
> radarhere removed the Awaiting OP Action

There was no reaction from OP

**Comment by homm** [comment]
I mean that another user could have another issue and we still need info from @v84lol. He also declared OS: as 64bit.

**Comment by Darskiy** [comment]
@radarhere 
> The reason I mentioned Pillow 9.5.0 is that this is the last Pillow version where we released 32-bit wheels. Could you run `import sys;print(sys.maxsize)` in Python and let us know what it reports?
> 
> If it reports 2147483647, then yes, you are running Python in 32-bit mode. If it reports 9223372036854775807, then you are running Python in 64-bit mode, and something else is happening.

Oh, sorry, I forgot to mention that I have a 32-bit python.
And, of course, here is the terminal output:
```
>>> import sys;print(sys.maxsize)
2147483647
```

**Comment by tdmart05** [comment]
I can also confirm that I was having the same issue and moved to 64bit python and the installation went flawlessly.

**Comment by hugovk** [comment]
Out of interest, what led to installing 32-bit Python in the first place?
