### ISSUE TITLE
PIL.UnidentifiedImage Error

### ISSUE THREAD

**Issue by AbhinavGopal** [python-pillow/Pillow#7533]
```
import io
import requests
from PIL import Image
from PIL import Image
r = requests.get('https://www.bimbaylola.com/media/catalog/product/1/8/182BAC104_T2200_P_T_XX_1.jpg', stream=True)
aux_im = Image.open(io.BytesIO(r.content))
//  Traceback (most recent call last):
//   File "<stdin>", line 1, in <module>
//   File "/Users/abhinavg/miniforge3/envs/block/lib/python3.10/site-packages/PIL/Image.py", line 2943, in open
//    raise UnidentifiedImageError(
// PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x102464ef0>
```

### What did you do?
I also tried to add 
>>> from PIL import ImageFile
>>> ImageFile.LOAD_TRUNCATED_IMAGES = True
before the code segment. I also receive this error when I remove the streaming functionality.

I also tried
```
import io
import requests
from PIL import Image
from PIL import Image
r = requests.get('https://www.bimbaylola.com/media/catalog/product/1/8/182BAC104_T2200_P_T_XX_1.jpg').raw
aux_im = Image.open(r)
//  Traceback (most recent call last):
//   File "<stdin>", line 1, in <module>
//   File "/Users/abhinavg/miniforge3/envs/block/lib/python3.10/site-packages/PIL/Image.py", line 2943, in open
//    raise UnidentifiedImageError(
// PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x100a32430>
```

### What did you expect to happen?
I expected the image to be loaded in.

### What are your OS, Python and Pillow versions?
I am running MacOS Ventura 13.5, Python 3.10.12 and PIL 10.0.0.

How do I avoid this issue? Should I be opening the image using another technique?

**Comment by homm** [comment]
```
$ curl -i https://www.bimbaylola.com/media/catalog/product/1/8/182BAC104_T2200_P_T_XX_1.jpg
HTTP/2 302 
date: Wed, 08 Nov 2023 07:57:27 GMT
content-type: text/html;charset=UTF-8
location: https://www.bimbaylola.com
x-dw-request-base-id: 0YX8gWY_S2UBAAB_
content-security-policy: frame-ancestors 'self'
x-content-type-options: nosniff
cache-control: no-cache, no-store, must-revalidate
pragma: no-cache
expires: Thu, 01 Dec 1994 16:00:00 GMT
cf-cache-status: MISS
server: cloudflare
cf-ray: 822c43e30a15a9e9-TBS

```
