### ISSUE TITLE
"OSError: cannot open resource" when opening truetype ImageFont with BytesIO twice

### ISSUE THREAD

**Issue by natuan62** [python-pillow/Pillow#7567]
### What did you do?

- Get font from URL
- Load font with ImageFont.truetype
- Resize font 

### What did you expect to happen?

- Pillow load correct

### What actually happened?

```pytb
Traceback (most recent call last):
  File "/Users//Documents/pet/python-font-thumbnail/generate/test-err.py", line 53, in <module>
    generateThumbnail()
  File "/Users//Documents/pet/python-font-thumbnail/generate/test-err.py", line 34, in generateThumbnail
    image_font = ImageFont.truetype(inputFileTmp, current_size)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/PIL/ImageFont.py", line 797, in truetype
    return freetype(font)
           ^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/PIL/ImageFont.py", line 794, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/PIL/ImageFont.py", line 230, in __init__
    load_from_bytes(font)
  File "/opt/homebrew/lib/python3.11/site-packages/PIL/ImageFont.py", line 211, in load_from_bytes
    self.font = core.getfont(
                ^^^^^^^^^^^^^
OSError: cannot open resource
```

### What are your OS, Python and Pillow versions?

* OS: macOS 14.1.1
* Python: 3.11.6
* Pillow: 10.1.0

```python

from PIL import Image, ImageDraw, ImageFont
import urllib.request
from io import BytesIO


def generateThumbnail():
    outputThumbTmp = "font-output.png"
    text = "My Font Thumbnail"

    buffer = urllib.request.urlopen(
        "https://fonts.gstatic.com/s/roboto/v30/KFOmCnqEu92Fr1Mu4mxKKTU1Kg.woff2"
    ).read()
    inputFileTmp = BytesIO(buffer)

    size = 90
    img = Image.new("RGBA", (2, 2), (255, 0, 0, 0))
    draw = ImageDraw.Draw(img)
    image_font = ImageFont.truetype(inputFileTmp, size)
    bounding_box = draw.textbbox((0, 0), text, font=image_font)
    print(bounding_box)

   # if comment reduce fontsize this block, nothing error happen
    if bounding_box[2] > 500:
        current_size = size
        while bounding_box[2] > 500:
            current_size -= 5
            image_font = ImageFont.truetype(inputFileTmp, current_size)
            bounding_box = draw.textbbox((0, 0), text, font=image_font)

    img_width = bounding_box[2] - bounding_box[0]
    img_height = bounding_box[3] - bounding_box[1]
    img_size = (img_width, img_height)
    img = img.resize(img_size)
    draw = ImageDraw.Draw(img)
    draw.text(
        (-bounding_box[0], -bounding_box[1]),
        text,
        fill="black",
        font=image_font,
        features=["-kern"],
    )
    img.save(outputThumbTmp)


generateThumbnail()

```

**Comment by radarhere** [comment]
The problem is that you are reading the font data from BytesIO, causing it to seek forward, and then reading from it again. You can see this by adding `print(inputFileTmp.tell())` before each `ImageFont.truetype(...)` call.

For a simple solution, you can just insert `inputFileTmp.seek(0)` like so
```python
current_size -= 5
inputFileTmp.seek(0)
image_font = ImageFont.truetype(inputFileTmp, current_size)
```

**Comment by radarhere** [comment]
If you would like a solution where you don't have to worry about manually seeking, you can use [`font_variant()`](https://pillow.readthedocs.io/en/stable/reference/ImageFont.html#PIL.ImageFont.FreeTypeFont.font_variant)

```python
current_size -= 5
image_font = image_font.font_variant(size=current_size)
bounding_box = draw.textbbox((0, 0), text, font=image_font)
```

**Comment by radarhere** [comment]
You reacted previously to this comments. Does that mean this is resolved?

**Comment by natuan62** [comment]
Many thanks for details and quick reply. Sorry for these days I'm busy. I tested this your implement and now it's works fine. @radarhere
