### ISSUE TITLE
Can’t access alpha information from PNG

### ISSUE THREAD

**Issue by Cimbali** [python-pillow/Pillow#7651]
I have a number of PNG images, for example this one: [tmpc31nu8fa.png](https://github.com/python-pillow/Pillow/assets/6126377/ec018fd2-6093-4a8f-99b0-24fc9f2424e1)

According to all the image viewers I can find, and according to image magick, it has an alpha channel. (In fact all of the data I’m interested in resides in the alpha channel!) However Pillow reports as `P` mode and displays no alpha channel that I can find, not in the palette, not in other colors:

```py
>>> from PIL import Image
>>> im = Image.open('tmpc31nu8fa.png')
>>> im.mode
'P'
>>> it = iter(im.get_palette()) 
>>> for tup in zip(it, it, it): print(tup)
... 
(237, 237, 237)
(254, 254, 254)
(237, 237, 237)
(237, 237, 237)
(237, 237, 237)
(239, 239, 239)
(239, 239, 239)
(238, 238, 238)
(0, 0, 0)
(0, 0, 0)
[…]
>>> im.getchannel('A')
Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/PIL/Image.py", line 2505, in getchannel
    channel = self.getbands().index(channel)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: tuple.index(x): x not in tuple

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.11/site-packages/PIL/Image.py", line 2508, in getchannel
    raise ValueError(msg) from e
ValueError: The image has no channel "A"
```

Here’s the info dump from image magick, you can see the color palette is the same with additional alpha:

```
> magick identify -verbose tmpc31nu8fa.png
Image:
  Filename: tmpc31nu8fa.png
  Permissions: rw-------
  Format: PNG (Portable Network Graphics)
  Mime type: image/png
  Class: PseudoClass
  Geometry: 2162x1481+0+0
  Units: Undefined
  Colorspace: sRGB
  Type: GrayscaleAlpha
  Base type: PaletteAlpha
  Endianness: Undefined
  Depth: 8-bit
  Channels: 5.0
  Channel depth:
    Red: 8-bit
    Green: 8-bit
    Blue: 8-bit
    Alpha: 8-bit
  Channel statistics:
    Pixels: 3201922
    Red:
      min: 237  (0.929412)
      max: 254 (0.996078)
      mean: 243.278 (0.954031)
      median: 237 (0.929412)
      standard deviation: 8.06159 (0.0316141)
      kurtosis: -1.66065
      skewness: 0.571174
      entropy: 0.702006
    Green:
      min: 237  (0.929412)
      max: 254 (0.996078)
      mean: 243.278 (0.954031)
      median: 237 (0.929412)
      standard deviation: 8.06159 (0.0316141)
      kurtosis: -1.66065
      skewness: 0.571174
      entropy: 0.702006
    Blue:
      min: 237  (0.929412)
      max: 254 (0.996078)
      mean: 243.278 (0.954031)
      median: 237 (0.929412)
      standard deviation: 8.06159 (0.0316141)
      kurtosis: -1.66065
      skewness: 0.571174
      entropy: 0.702006
    Alpha:
      min: 0  (0)
      max: 224 (0.878431)
      mean: 120.124 (0.471073)
      median: 160 (0.627451)
      standard deviation: 101.29 (0.397217)
      kurtosis: -1.80931
      skewness: -0.170044
      entropy: 0.72105
  Image statistics:
    Overall:
      min: 0  (0)
      max: 254 (0.996078)
      mean: 212.489 (0.833291)
      median: 217.75 (0.853922)
      standard deviation: 31.3688 (0.123015)
      kurtosis: 3.65222
      skewness: -2.29506
      entropy: 0.706767
  Alpha: srgba(254,254,254,0)   #FEFEFE00
  Colors: 8
  Histogram:
       1272412: (237,237,237,224) #EDEDEDE0 srgba(237,237,237,0.878431)
        219877: (237,237,237,192) #EDEDEDC0 srgba(237,237,237,0.752941)
        146917: (237,237,237,160) #EDEDEDA0 srgba(237,237,237,0.627451)
        116944: (237,237,237,128) #EDEDED80 srgba(237,237,237,0.501961)
         94823: (238,238,238,64) #EEEEEE40 srgba(238,238,238,0.25098)
        102053: (239,239,239,96) #EFEFEF60 srgba(239,239,239,0.376471)
         95273: (239,239,239,32) #EFEFEF20 srgba(239,239,239,0.12549)
       1153623: (254,254,254,0) #FEFEFE00 srgba(254,254,254,0)
  Colormap entries: 256
  Colormap:
    0: (237,237,237,0.878431) #EDEDEDE0 srgba(237,237,237,0.878431)
    1: (254,254,254,0) #FEFEFE00 srgba(254,254,254,0)
    2: (237,237,237,0.752941) #EDEDEDC0 srgba(237,237,237,0.752941)
    3: (237,237,237,0.627451) #EDEDEDA0 srgba(237,237,237,0.627451)
    4: (237,237,237,0.501961) #EDEDED80 srgba(237,237,237,0.501961)
    5: (239,239,239,0.376471) #EFEFEF60 srgba(239,239,239,0.376471)
    6: (239,239,239,0.12549) #EFEFEF20 srgba(239,239,239,0.12549)
    7: (238,238,238,0.25098) #EEEEEE40 srgba(238,238,238,0.25098)
    8: (0,0,0,0) #00000000 none
    9: (0,0,0,0) #00000000 none
    10: (0,0,0,0) #00000000 none
    11: (0,0,0,0) #00000000 none
    12: (0,0,0,0) #00000000 none
[…]
  Rendering intent: Perceptual
  Gamma: 0.454545
  Chromaticity:
    red primary: (0.64,0.33,0.03)
    green primary: (0.3,0.6,0.1)
    blue primary: (0.15,0.06,0.79)
    white point: (0.3127,0.329,0.3583)
  Matte color: grey74
  Background color: white
  Border color: srgb(223,223,223)
  Transparent color: black
  Interlace: None
  Intensity: Undefined
  Compose: Over
  Page geometry: 2162x1481+0+0
  Dispose: Undefined
  Iterations: 0
  Compression: Zip
  Orientation: Undefined
  Properties:
    date:create: 2023-12-28T20:45:50+00:00
    date:modify: 2023-12-28T20:45:50+00:00
    date:timestamp: 2023-12-29T07:54:07+00:00
    png:IHDR.bit-depth-orig: 8
    png:IHDR.bit_depth: 8
    png:IHDR.color-type-orig: 3
    png:IHDR.color_type: 3 (Indexed)
    png:IHDR.interlace_method: 0 (Not interlaced)
    png:IHDR.width,height: 2162, 1481
    png:PLTE.number_colors: 256
    png:tRNS: chunk was found
    signature: 589d9b3bcd7573a27f3e3a93f750c307a93895ec962fbac97b12d03cb6693af2
  Artifacts:
    verbose: true
  Tainted: False
  Filesize: 256792B
  Number pixels: 3.20192M
  Pixel cache type: Memory
  Pixels per second: 35.2544MP
  User time: 0.090u
  Elapsed time: 0:01.090
  Version: ImageMagick 7.1.1-21 Q16-HDRI x86_64 21667 https://imagemagick.org
```

### What did you do?

Open the image with PIL

### What did you expect to happen?

Be able to access the data displayed by other viewers

### What actually happened?

Alpha information missing (or all my attempts to find it have failed)

### What are your OS, Python and Pillow versions?

* OS: Linux kernel 6.6.3
* Python:  3.11
* Pillow:  10.1.0

**Comment by radarhere** [comment]
Hi. At https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#png, the docs mention that "transparency" might be part of the image's `info` dictionary. If you look at this,
```python
from PIL import Image
im = Image.open("in.png")
print(im.info)
```
you will see
```
{'transparency': b'\xe0\x00\xc0\xa0\x80` @\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00'}
```
If you use [`apply_transparency()`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.apply_transparency), you can move this to be part of the palette.
```python
from PIL import Image
im = Image.open("in.png")
im.apply_transparency()
print(im.palette.colors)
```
gives
```
{(237, 237, 237, 224): 0, (254, 254, 254, 0): 1, (237, 237, 237, 192): 2, (237, 237, 237, 160): 3, (237, 237, 237, 128): 4, (239, 239, 239, 96): 5, (239, 239, 239, 32): 6, (238, 238, 238, 64): 7, (0, 0, 0, 0): 8}
```

**Comment by Cimbali** [comment]
Ah thanks. I saw this `apply_transparency()` but understood it to mean adding another transparency layer.
