### ISSUE TITLE
PSD plugin errors on 16/32-bit channel files 

### ISSUE THREAD

**Issue by kporangehat** [python-pillow/Pillow#7705]
### What did you do?

Trying to process multiple Photoshop files primarily to gather size, mode, and resolution.

**16-bit example**
```python
from PIL import ImageFile, Image

ImageFile.LOAD_TRUNCATED_IMAGES = True

with Image.open("/Users/kp/dev/pil_psd_test/16-bit.psd") as img:
    print(img.format, img.size, img.mode)
```

**32-bit example**
```python
from PIL import ImageFile, Image

ImageFile.LOAD_TRUNCATED_IMAGES = True

with Image.open("/Users/kp/dev/pil_psd_test/32-bit.psd") as img:
    print(img.format, img.size, img.mode)
```

### What did you expect to happen?

The file to open and report the format, size, and mode

### What actually happened?

**16-bit example**
```python
Traceback (most recent call last):
  File "/Users/kp/dev/sandbox/pil_psd_test.py", line 48, in <module>
    with Image.open("/Users/kp/dev/pil_psd_test/16-bit.psd") as img:
  File "/Users/kp/dev/sandbox/.venv/lib/python3.9/site-packages/PIL/Image.py", line 3310, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/Users/kp/dev/pil_psd_test/16-bit.psd'
```

**32-bit example**
```python
Traceback (most recent call last):
  File "/Users/kp/dev/sandbox/pil_psd_test.py", line 51, in <module>
    with Image.open("/Users/kp/dev/pil_psd_test/32-bit.psd") as img:
  File "/Users/kp/dev/sandbox/.venv/lib/python3.9/site-packages/PIL/Image.py", line 3310, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/Users/kp/dev/pil_psd_test/32-bit.psd'
```

Turning on the debug log message [here](https://github.com/python-pillow/Pillow/blob/main/src/PIL/Image.py#L3284), I can see the **actual** error is:

**16-bit example**
```python
...
DEBUG:PIL.Image:
Traceback (most recent call last):
  File "/Users/kp/dev/sandbox/.venv/lib/python3.9/site-packages/PIL/ImageFile.py", line 137, in __init__
    self._open()
  File "/Users/kp/dev/sandbox/.venv/lib/python3.9/site-packages/PIL/PsdImagePlugin.py", line 76, in _open
    mode, channels = MODES[(psd_mode, psd_bits)]
KeyError: (3, 16)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/kp/dev/sandbox/.venv/lib/python3.9/site-packages/PIL/Image.py", line 3274, in _open_core
    im = factory(fp, filename)
  File "/Users/kp/dev/sandbox/.venv/lib/python3.9/site-packages/PIL/ImageFile.py", line 145, in __init__
    raise SyntaxError(v) from v
SyntaxError: (3, 16)
...
```

**32-bit example**
```python
...
DEBUG:PIL.Image:
Traceback (most recent call last):
  File "/Users/kp/dev/sandbox/.venv/lib/python3.9/site-packages/PIL/ImageFile.py", line 137, in __init__
    self._open()
  File "/Users/kp/dev/sandbox/.venv/lib/python3.9/site-packages/PIL/PsdImagePlugin.py", line 76, in _open
    mode, channels = MODES[(psd_mode, psd_bits)]
KeyError: (3, 32)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/kp/dev/sandbox/.venv/lib/python3.9/site-packages/PIL/Image.py", line 3274, in _open_core
    im = factory(fp, filename)
  File "/Users/kp/dev/sandbox/.venv/lib/python3.9/site-packages/PIL/ImageFile.py", line 145, in __init__
    raise SyntaxError(v) from v
SyntaxError: (3, 32)
...
```

Sample 16-bit color image: 
[16-bit.psd.zip](https://github.com/python-pillow/Pillow/files/13875513/16-bit.psd.zip)

Sample 32-bit color image: 
[32-bit.psd.zip](https://github.com/python-pillow/Pillow/files/13875514/32-bit.psd.zip)

### What are your OS, Python and Pillow versions?

* OS:  MacOS 14.2.1 (23C71)
* Python:   3.9.17
* Pillow:   10.2.0

```python
see above
```

**Comment by kporangehat** [comment]
Ah yes, that is indeed what I'm referring to. Thank you for the update.

**Comment by homm** [comment]
At first glance, opening high-bit images should leads to reading in 8-bit modes, rather than errors.
