### ISSUE TITLE
Unimplemented feature when converting emojis to image

### ISSUE THREAD

**Issue by BenjaminOddou** [python-pillow/Pillow#7854]
### What did you do?

Converting emoji text using `Apple Color Emoji.ttc` font to png file using `pillow`. The behavior is different between two macs. On one configuration (see below) the script is correctly generating images from all emoji and on the other hand, for another configuration, the script is returning an error for some emojis.

### What did you expect to happen?

![309490886-557c029a-ed98-45d5-aed2-4990dbd1366b](https://github.com/python-pillow/Pillow/assets/85166574/50591d31-cc31-4d33-ae60-15ff80fc5a4b)

### What actually happened?

With the second cofiguration, the script returns 

```shell
❯ python3 test.py
unimplemented feature
```

Note that it seems to be a problem only for [emojis from 15.1 version](https://emojipedia.org/fr/emoji-15.1), see this [issue](https://github.com/BenjaminOddou/alfred-emoji-wine/issues/8).

### What are your OS, Python and Pillow versions?

Configuration where the script is working:
* OS: macOS 14.4
* Python: 3.12.2
* Pillow: 10.2.0
* Intel Core i7

Configuration where the script returns an error:
* OS: macOS 14.4
* Python: 3.12.2
* Pillow: 10.2.0
* Apple M1 Max

```python
from PIL import Image, ImageDraw, ImageFont

def convert_emoji_to_png(emoji):
    image_size = (74 , 74) # set image size
    image = Image.new("RGBA", image_size, (0, 0, 0, 0))  # Set transparent background
    font_size = 64  # Adjusted font size
    font_path = "/System/Library/Fonts/Apple Color Emoji.ttc"
    font = ImageFont.truetype(font_path, font_size, encoding='unic')
    draw_position = (int((image_size[0] - font_size) / 2), int((image_size[1] - font_size) / 2))
    draw = ImageDraw.Draw(image)
    draw.text(draw_position, emoji, font=font, embedded_color=True)
    image.show()

try:
    convert_emoji_to_png("🚶‍➡️")
except Exception as e:
    print(e)
```

**Comment by nulano** [comment]
> unimplemented feature

This sounds like it might be a message from FreeType, the library used by Pillow to render text: https://github.com/python-pillow/Pillow/blob/1b7bcfb6e71bc2c8a02ee4334b8dbd3b5db6e6e6/Tests/test_imagefont.py#L983-L985

---

How did you install Pillow (on both systems)?

What is the output of `python3 -m PIL` (please paste the first 26 lines of output from each system)?

**Comment by radarhere** [comment]
If it's helpful information, I'm on an M1 with macOS 14.3.1, and I don't see the error.

Investigating, https://stackoverflow.com/questions/63742055/freetype-colour-rendering-ft-load-glyph-returns-unimplemented-feature suggests that FreeType being built without `FT_CONFIG_OPTION_USE_PNG` would raise this error when you're using `embedded_color=True`.

**Comment by BenjaminOddou** [comment]
Hello,

for my system (intel mac chip) I installed pillow using brew.

```python
> python3 -m PIL     
--------------------------------------------------------------------
Pillow 10.2.0
Python 3.12.2 (main, Feb  6 2024, 20:19:44) [Clang 15.0.0 (clang-1500.1.0.2.5)]
--------------------------------------------------------------------
Python modules loaded from /usr/local/lib/python3.12/site-packages/PIL
Binary modules loaded from /usr/local/lib/python3.12/site-packages/PIL
--------------------------------------------------------------------
--- PIL CORE support ok, compiled for 10.2.0
*** TKINTER support not installed
--- FREETYPE2 support ok, loaded 2.13.2
--- LITTLECMS2 support ok, loaded 2.16
--- WEBP support ok, loaded 1.3.2
--- WEBP Transparency support ok
--- WEBPMUX support ok
--- WEBP Animation support ok
--- JPEG support ok, compiled for libjpeg-turbo 3.0.1
--- OPENJPEG (JPEG2000) support ok, loaded 2.5.0
--- ZLIB (PNG/ZIP) support ok, loaded 1.2.12
--- LIBTIFF support ok, loaded 4.6.0
--- RAQM (Bidirectional Text) support ok, loaded 0.10.1
--- LIBIMAGEQUANT (Quantization method) support ok, loaded 4.2.2
--- XCB (X protocol) support ok
--------------------------------------------------------------------
BLP
Extensions: .blp
Features: open, save, encode
--------------------------------------------------------------------
```
@garymh could you share the results from your mac ?

**Comment by radarhere** [comment]
So @garymh is the environment with the error? How did he install Pillow?

**Comment by nulano** [comment]
@garymh I'm assuming you also installed Pillow using brew?

Could you please provide the output of `brew list --versions`?

**Comment by nulano** [comment]
Everything related to the font stack. Unless I'm forgetting something, that should be freetype, harfbuzz, fribidi, libraqm, libpng.

**Comment by radarhere** [comment]
Could you run the script without `embedded_color=True`? I expect that difference will allow it to run successfully.

**Comment by radarhere** [comment]
It may or may not be helpful, but could we get the full traceback, not just the error string?

So the output of
```python
convert_emoji_to_png("🚶‍➡️")
```
not just
```python
try:
    convert_emoji_to_png("🚶‍➡️")
except Exception as e:
    print(e)
```

**Comment by radarhere** [comment]
I attempted to replicate in macOS 14 arm64 on GitHub Actions, with
```
brew update
brew install python@3.12 pillow freetype fribidi harfbuzz libpng libraqm
```
but [it passed](https://github.com/radarhere/Pillow/actions/runs/8201885913/job/22431524939).

**Comment by radarhere** [comment]
If you install Pillow from this PyPI wheel, does the problem still occur?
https://files.pythonhosted.org/packages/9d/a0/28756da34d6b58c3c5f6c1d5589e4e8f4e73472b55875524ae9d6e7e98fe/pillow-10.2.0-cp312-cp312-macosx_11_0_arm64.whl

I don't expect it to fix it, but if the error still occurs with this, that means I could potentially put together a wheel with better logging for you to run.

**Comment by BenjaminOddou** [comment]
The problem still persist on Pillow 10.3.0 @radarhere.

```shell
--------------------------------------------------------------------
Pillow 10.3.0
Python 3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.3.9.4)]
--------------------------------------------------------------------
Python executable is /opt/homebrew/opt/python@3.12/bin/python3.12
System Python files loaded from /opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12
--------------------------------------------------------------------
Python Pillow modules loaded from /opt/homebrew/lib/python3.12/site-packages/PIL
Binary Pillow modules loaded from /opt/homebrew/lib/python3.12/site-packages/PIL
--------------------------------------------------------------------
--- PIL CORE support ok, compiled for 10.3.0
*** TKINTER support not installed
--- FREETYPE2 support ok, loaded 2.13.2
--- LITTLECMS2 support ok, loaded 2.16
--- WEBP support ok, loaded 1.4.0
--- WEBP Transparency support ok
--- WEBPMUX support ok
--- WEBP Animation support ok
--- JPEG support ok, compiled for libjpeg-turbo 3.0.2
--- OPENJPEG (JPEG2000) support ok, loaded 2.5.2
--- ZLIB (PNG/ZIP) support ok, loaded 1.2.12
--- LIBTIFF support ok, loaded 4.6.0
--- RAQM (Bidirectional Text) support ok, loaded 0.10.1
--- LIBIMAGEQUANT (Quantization method) support ok, loaded 4.2.2
--- XCB (X protocol) support ok
```

using a `test.py` script : 

```python
from PIL import Image, ImageDraw, ImageFont

def convert_emoji_to_png(emoji, name):
    image_size = (64, 64) # set image size
    image = Image.new("RGBA", image_size, (0, 0, 0, 0))  # Set transparent background
    font_size = 64  # Adjusted font size
    font_path = "/System/Library/Fonts/Apple Color Emoji.ttc"
    font = ImageFont.truetype(font_path, font_size, encoding='unic')
    draw_position = (int((image_size[0] - font_size) / 2), int((image_size[1] - font_size) / 2))
    draw = ImageDraw.Draw(image)
    draw.text(draw_position, emoji, font=font, embedded_color=True)
    image.save(f"{name.replace(':', '')}.png", "PNG")

convert_emoji_to_png("👩‍🦽‍➡️", 'test')
```

outputs :

```shell
python3 test.py
Traceback (most recent call last):
  File "/Users/user/Documents/GitHub/alfred-emoji-wine/test.py", line 14, in <module>
    convert_emoji_to_png("👩‍🦽‍➡️", 'test')
  File "/Users/user/Documents/GitHub/alfred-emoji-wine/test.py", line 11, in convert_emoji_to_png
    draw.text(draw_position, emoji, font=font, embedded_color=True)
  File "/opt/homebrew/lib/python3.12/site-packages/PIL/ImageDraw.py", line 590, in text
    draw_text(ink)
  File "/opt/homebrew/lib/python3.12/site-packages/PIL/ImageDraw.py", line 529, in draw_text
    mask, offset = font.getmask2(
                   ^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/PIL/ImageFont.py", line 592, in getmask2
    return self.font.render(
           ^^^^^^^^^^^^^^^^^
OSError: unimplemented feature
```

I tried the following without any positive result

```shell
brew update
brew install python@3.12 pillow freetype fribidi harfbuzz libpng libraqm
```

**Comment by radarhere** [comment]
Could you describe  in words what you're expecting? The sequence of unicode characters being requested is - woman, zero width joiner, manual wheelchair, zero width joiner, black rightwards arrow, variation selector-16.

If I trim the last two characters from the string, then it renders fine on my machine.

![test](https://github.com/python-pillow/Pillow/assets/3112309/5d4dbb9f-1213-4155-a501-bd3b8d62db4c)

**Comment by BenjaminOddou** [comment]
I was trying to create an image from emoji using the native emoji font on macOS. What character did you trim exactly ? Is my emoji sequence not correct 🤨 ? FYI I am using this list as my [emoji source](https://unicode.org/Public/emoji/latest/emoji-test.txt)

**Comment by nulano** [comment]
> ```text
> --- RAQM (Bidirectional Text) support ok, loaded 0.10.1
> ```

It seems you are still using brew to install Pillow.

If you are using a wheel from PyPI (e.g. the one linked by @radarhere above), you should see the following:

```text
--- RAQM (Bidirectional Text) support ok, loaded 0.10.1, fribidi 1.0.13, harfbuzz 8.3.0
```

Could you please test with Pillow installed from PyPI?

This one should work: https://files.pythonhosted.org/packages/5e/77/4cf407e7b033b4d8e5fcaac295b6e159cf1c70fa105d769f01ea2e1e5eca/pillow-10.3.0-cp312-cp312-macosx_11_0_arm64.whl

**Comment by BenjaminOddou** [comment]
@nulano now

```shell
Pillow 10.3.0
Python 3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.3.9.4)]
--------------------------------------------------------------------
Python executable is /opt/homebrew/opt/python@3.12/bin/python3.12
System Python files loaded from /opt/homebrew/opt/python@3.12/Frameworks/Python.framework/Versions/3.12
--------------------------------------------------------------------
Python Pillow modules loaded from /opt/homebrew/lib/python3.12/site-packages/PIL
Binary Pillow modules loaded from /opt/homebrew/lib/python3.12/site-packages/PIL
--------------------------------------------------------------------
--- PIL CORE support ok, compiled for 10.3.0
*** TKINTER support not installed
--- FREETYPE2 support ok, loaded 2.13.2
--- LITTLECMS2 support ok, loaded 2.16
--- WEBP support ok, loaded 1.3.2
--- WEBP Transparency support ok
--- WEBPMUX support ok
--- WEBP Animation support ok
--- JPEG support ok, compiled for libjpeg-turbo 3.0.2
--- OPENJPEG (JPEG2000) support ok, loaded 2.5.2
--- ZLIB (PNG/ZIP) support ok, loaded 1.3.1
--- LIBTIFF support ok, loaded 4.6.0
--- RAQM (Bidirectional Text) support ok, loaded 0.10.1, fribidi 1.0.14, harfbuzz 8.4.0
*** LIBIMAGEQUANT (Quantization method) support not installed
--- XCB (X protocol) support ok
```

```shell
python3 test.py
Traceback (most recent call last):
  File "/Users/user/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.AE55F6CA-27EF-4215-979B-D0CE54F501D7/test.py", line 14, in <module>
    convert_emoji_to_png("👩‍🦽‍➡️", 'test')
  File "/Users/user/Library/Application Support/Alfred/Alfred.alfredpreferences/workflows/user.workflow.AE55F6CA-27EF-4215-979B-D0CE54F501D7/test.py", line 11, in convert_emoji_to_png
    draw.text(draw_position, emoji, font=font, embedded_color=True)
  File "/opt/homebrew/lib/python3.12/site-packages/PIL/ImageDraw.py", line 590, in text
    draw_text(ink)
  File "/opt/homebrew/lib/python3.12/site-packages/PIL/ImageDraw.py", line 529, in draw_text
    mask, offset = font.getmask2(
                   ^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.12/site-packages/PIL/ImageFont.py", line 592, in getmask2
    return self.font.render(
           ^^^^^^^^^^^^^^^^^
OSError: unimplemented feature
```

**Comment by radarhere** [comment]
> What character did you trim exactly ?

I find that running
```python
convert_emoji_to_png("👩‍🦽‍➡️"[:-2], 'test')
```
works. So from your [emoji source](https://unicode.org/Public/emoji/latest/emoji-test.txt), I find that 'woman in manual wheelchair', [works](https://github.com/radarhere/Pillow/actions/runs/9229707410), but 'woman in manual wheelchair facing right' [doesn't.](https://github.com/radarhere/Pillow/actions/runs/9229705733)

**Comment by BenjaminOddou** [comment]
@radarhere I think the problem comes from the right arrow modifier then. Example [here](https://emojipedia.org/person_with_white_cane_facing_right)

here are the emojis causing problems :

```log
2024-05-24 22:01:22,360 - ERROR - 🚶‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,361 - ERROR - 🚶🏻‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,362 - ERROR - 🚶🏼‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,362 - ERROR - 🚶🏽‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,363 - ERROR - 🚶🏾‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,364 - ERROR - 🚶🏿‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,365 - ERROR - 🚶‍♀️‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,366 - ERROR - 🚶🏻‍♀️‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,366 - ERROR - 🚶🏼‍♀️‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,367 - ERROR - 🚶🏽‍♀️‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,368 - ERROR - 🚶🏾‍♀️‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,369 - ERROR - 🚶🏿‍♀️‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,369 - ERROR - 🚶‍♂️‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,370 - ERROR - 🚶🏻‍♂️‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,371 - ERROR - 🚶🏼‍♂️‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,372 - ERROR - 🚶🏽‍♂️‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,373 - ERROR - 🚶🏾‍♂️‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,373 - ERROR - 🚶🏿‍♂️‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,417 - ERROR - 🧎‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,418 - ERROR - 🧎🏻‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,419 - ERROR - 🧎🏼‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,419 - ERROR - 🧎🏽‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,420 - ERROR - 🧎🏾‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,421 - ERROR - 🧎🏿‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,422 - ERROR - 🧎‍♀️‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,423 - ERROR - 🧎🏻‍♀️‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,423 - ERROR - 🧎🏼‍♀️‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,424 - ERROR - 🧎🏽‍♀️‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,425 - ERROR - 🧎🏾‍♀️‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,426 - ERROR - 🧎🏿‍♀️‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,426 - ERROR - 🧎‍♂️‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,427 - ERROR - 🧎🏻‍♂️‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,428 - ERROR - 🧎🏼‍♂️‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,429 - ERROR - 🧎🏽‍♂️‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,430 - ERROR - 🧎🏾‍♂️‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,430 - ERROR - 🧎🏿‍♂️‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,439 - ERROR - 🧑‍🦯‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,439 - ERROR - 🧑🏻‍🦯‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,440 - ERROR - 🧑🏼‍🦯‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,441 - ERROR - 🧑🏽‍🦯‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,442 - ERROR - 🧑🏾‍🦯‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,443 - ERROR - 🧑🏿‍🦯‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,451 - ERROR - 👨‍🦯‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,452 - ERROR - 👨🏻‍🦯‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,453 - ERROR - 👨🏼‍🦯‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,453 - ERROR - 👨🏽‍🦯‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,454 - ERROR - 👨🏾‍🦯‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,455 - ERROR - 👨🏿‍🦯‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,464 - ERROR - 👩‍🦯‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,465 - ERROR - 👩🏻‍🦯‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,465 - ERROR - 👩🏼‍🦯‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,466 - ERROR - 👩🏽‍🦯‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,467 - ERROR - 👩🏾‍🦯‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,468 - ERROR - 👩🏿‍🦯‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,477 - ERROR - 🧑‍🦼‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,477 - ERROR - 🧑🏻‍🦼‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,478 - ERROR - 🧑🏼‍🦼‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,479 - ERROR - 🧑🏽‍🦼‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,480 - ERROR - 🧑🏾‍🦼‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,481 - ERROR - 🧑🏿‍🦼‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,489 - ERROR - 👨‍🦼‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,490 - ERROR - 👨🏻‍🦼‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,491 - ERROR - 👨🏼‍🦼‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,492 - ERROR - 👨🏽‍🦼‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,493 - ERROR - 👨🏾‍🦼‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,493 - ERROR - 👨🏿‍🦼‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,502 - ERROR - 👩‍🦼‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,503 - ERROR - 👩🏻‍🦼‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,504 - ERROR - 👩🏼‍🦼‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,505 - ERROR - 👩🏽‍🦼‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,506 - ERROR - 👩🏾‍🦼‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,506 - ERROR - 👩🏿‍🦼‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,520 - ERROR - 🧑‍🦽‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,521 - ERROR - 🧑🏻‍🦽‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,521 - ERROR - 🧑🏼‍🦽‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,522 - ERROR - 🧑🏽‍🦽‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,523 - ERROR - 🧑🏾‍🦽‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,524 - ERROR - 🧑🏿‍🦽‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,532 - ERROR - 👨‍🦽‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,533 - ERROR - 👨🏻‍🦽‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,534 - ERROR - 👨🏼‍🦽‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,535 - ERROR - 👨🏽‍🦽‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,536 - ERROR - 👨🏾‍🦽‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,536 - ERROR - 👨🏿‍🦽‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,546 - ERROR - 👩‍🦽‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,547 - ERROR - 👩🏻‍🦽‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,548 - ERROR - 👩🏼‍🦽‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,548 - ERROR - 👩🏽‍🦽‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,549 - ERROR - 👩🏾‍🦽‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,550 - ERROR - 👩🏿‍🦽‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,574 - ERROR - 🏃‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,575 - ERROR - 🏃🏻‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,576 - ERROR - 🏃🏼‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,577 - ERROR - 🏃🏽‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,578 - ERROR - 🏃🏾‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,578 - ERROR - 🏃🏿‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,579 - ERROR - 🏃‍♀️‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,580 - ERROR - 🏃🏻‍♀️‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,581 - ERROR - 🏃🏼‍♀️‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,582 - ERROR - 🏃🏽‍♀️‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,583 - ERROR - 🏃🏾‍♀️‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,583 - ERROR - 🏃🏿‍♀️‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,584 - ERROR - 🏃‍♂️‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,585 - ERROR - 🏃🏻‍♂️‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,586 - ERROR - 🏃🏼‍♂️‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,587 - ERROR - 🏃🏽‍♂️‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,587 - ERROR - 🏃🏾‍♂️‍➡️ cannot be transform into an image, unimplemented feature
2024-05-24 22:01:22,588 - ERROR - 🏃🏿‍♂️‍➡️ cannot be transform into an image, unimplemented feature
```

**Comment by radarhere** [comment]
I've sent an e-mail to FreeType asking them if they have any thoughts.

<details>
Hi,

Over at Python Pillow, a user has tried to render an emoji with macOS’ Apple Color Emoji.ttc - https://github.com/python-pillow/Pillow/issues/7854#issuecomment-2128088090. The emoji is the combination of ‘woman’ U+1F469, 'zero width joiner’ U+200D, 'manual wheelchair’ U+1F9BD, 'zero width joiner’ U+200D, 'black rightwards arrow’ U+27A1, 'variation selector-16’ U+FE0F, with the intention of being a woman in a manual wheelchair facing right.

However, FreeType returns an Unimplemented_Feature error. Interesting, it only doesn’t do this for just a woman in a manual wheelchair. To demonstrate, the following code attempts to use woman in a manual wheelchair, and then woman in a manual wheelchair facing right. The error only occurs in the second instance.
```c
FT_Library library;
FT_Init_FreeType(&library);
FT_Face face = NULL;
FT_New_Face(library, "/System/Library/Fonts/Apple Color Emoji.ttc", 0, &face);
FT_Set_Pixel_Sizes(face, 0, 64);
int error = FT_Load_Glyph(face, 1507, FT_LOAD_DEFAULT);
if (error) {
	printf("1507: error %d\n", error);
}
error = FT_Load_Glyph(face, 1508, FT_LOAD_DEFAULT);
if (error) {
	printf("1508: error %d\n", error);
}
```
I’ve attached images that, as far as I can see, show that both indexes are present in the font.

Any thoughts as to why one should fail but not the other would be appreciated. Thanks.
![1507](https://github.com/python-pillow/Pillow/assets/3112309/48c84cd5-2705-4c90-90d6-36e867a39b6d)
![1508](https://github.com/python-pillow/Pillow/assets/3112309/33268087-4677-4206-b56c-7f9668e08448)
</details>

**Comment by radarhere** [comment]
I still need to continue the conversation with FreeType, but here is part of the initial response.

> Looking at this report it seems that somehow the image should be mirrored horizontally – I guess this is the problem with FreeType.
> 
> Please remember that color emoji rendering support within FreeType is *very* limited and only partially implemented – it is *not* intended as a general solution but rather as a last resort for people who won't do the color bitmap blitting by themselves.
> 
> Rendering support of Emojis is a border case, since FreeType is decidedly *not* a graphics library.

**Comment by BenjaminOddou** [comment]
@radarhere Thanks for the update ! I look forward to get a solution. Please, tell me if you need any other information / tests.

**Comment by radarhere** [comment]
Ok, after some further investigation, I found that the graphic type 'flip' is being used. This is a new feature from Apple (I can't even find documentation about it), and something that FreeType doesn't support yet.

In my e-mails with FreeType, they have said that supporting this feature would be nice, and so I've created https://gitlab.freedesktop.org/freetype/freetype/-/issues/1282

**Comment by radarhere** [comment]
The FreeType issue has now been resolved. The next step is to wait for a FreeType release.

**Comment by BenjaminOddou** [comment]
Many thanks for the update @radarhere 😊

**Comment by radarhere** [comment]
FreeType 2.14.0 has been released, so this should now be fixed. Are you able to try again?

**Comment by BenjaminOddou** [comment]
Hello @radarhere, not sure it helped. The script doesn't work anymore. Every emoji is now throwing an `unimplemented feature`

```python
from PIL import Image, ImageDraw, ImageFont

def convert_emoji_to_png(emoji, name):
    image_size = (64, 64) # set image size
    image = Image.new("RGBA", image_size, (0, 0, 0, 0))  # Set transparent background
    font_size = 64  # Adjusted font size
    font_path = "/System/Library/Fonts/Apple Color Emoji.ttc"
    font = ImageFont.truetype(font_path, font_size, encoding='unic')
    draw_position = (int((image_size[0] - font_size) / 2), int((image_size[1] - font_size) / 2))
    draw = ImageDraw.Draw(image)
    draw.text(draw_position, emoji, font=font, embedded_color=True)
    image.save(f"{name.replace(':', '')}.png", "PNG")

convert_emoji_to_png("😀", 'test')
```

outputs

```sh
Traceback (most recent call last):
  File "/Users/user/Documents/GitHub/biblo/test.py", line 14, in <module>
    convert_emoji_to_png("😀", 'test')
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "/Users/user/Documents/GitHub/biblo/test.py", line 11, in convert_emoji_to_png
    draw.text(draw_position, emoji, font=font, embedded_color=True)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.13/site-packages/PIL/ImageDraw.py", line 670, in text
    draw_text(ink)
    ~~~~~~~~~^^^^^
  File "/opt/homebrew/lib/python3.13/site-packages/PIL/ImageDraw.py", line 609, in draw_text
    mask, offset = font.getmask2(  # type: ignore[union-attr,misc]
                   ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        text,
        ^^^^^
    ...<10 lines>...
        **kwargs,
        ^^^^^^^^^
    )
    ^
  File "/opt/homebrew/lib/python3.13/site-packages/PIL/ImageFont.py", line 640, in getmask2
    return self.font.render(
           ~~~~~~~~~~~~~~~~^
        text,
        ^^^^^
    ...<9 lines>...
        start,
        ^^^^^^
    )
    ^
OSError: unimplemented feature
```

```sh
==> freetype: stable 2.14.0 (bottled)
Software library to render fonts
https://www.freetype.org/
Installed
/opt/homebrew/Cellar/freetype/2.14.0 (68 files, 2.6MB) *
  Poured from bottle using the formulae.brew.sh API on 2025-09-11 at 21:37:07
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/f/freetype.rb
License: FTL
==> Dependencies
Build: pkgconf ✔
Required: libpng ✔
==> Downloading https://formulae.brew.sh/api/formula/freetype.json
==> Analytics
install: 89,504 (30 days), 221,071 (90 days), 1,035,405 (365 days)
install-on-request: 4,628 (30 days), 8,368 (90 days), 48,239 (365 days)
build-error: 1 (30 days)
```

**Comment by radarhere** [comment]
I created https://gitlab.freedesktop.org/freetype/freetype/-/issues/1358 about this new problem. Discussion there has revealed that there was another code change between freetype 2.13.3 and 2.14.0 that isn't playing well with all `sed` variations.

**Comment by radarhere** [comment]
https://github.com/Homebrew/homebrew-core/pull/242712 has been merged to workaround the problem. Could you try again?

**Comment by BenjaminOddou** [comment]
Hello @radarhere,

it's working ! Many thanks for your help on this ! 🙏

<img width="768" height="655" alt="Image" src="https://github.com/user-attachments/assets/5d020ca5-7de8-43e2-b949-dd6517eb5e88" />
