### ISSUE TITLE
Windows `pip install Pillow` failure

### ISSUE THREAD

**Issue by pahaz** [python-pillow/Pillow#793]
Hello, I have some problem. Trace:

```
(venv) ...\.test\project-name>__data__\venv\Scripts\pip install Pillow
Downloading/unpacking Pillow
  Downloading Pillow-2.5.1.zip (6.9MB): 6.9MB downloaded
  Running setup.py egg_info for package Pillow

    warning: no files found matching '*.bdf' under directory 'Images'
    warning: no files found matching '*.fli' under directory 'Images'
    warning: no files found matching '*.gif' under directory 'Images'
    warning: no files found matching '*.icns' under directory 'Images'
    warning: no files found matching '*.ico' under directory 'Images'
    warning: no files found matching '*.jpg' under directory 'Images'
    warning: no files found matching '*.pbm' under directory 'Images'
    warning: no files found matching '*.pil' under directory 'Images'
    warning: no files found matching '*.png' under directory 'Images'
    warning: no files found matching '*.ppm' under directory 'Images'
    warning: no files found matching '*.psd' under directory 'Images'
    warning: no files found matching '*.tar' under directory 'Images'
    warning: no files found matching '*.webp' under directory 'Images'
    warning: no files found matching '*.xpm' under directory 'Images'
    warning: no files found matching 'README' under directory 'Sane'
    warning: no files found matching 'README' under directory 'Scripts'
    warning: no files found matching '*.txt' under directory 'Tk'
Installing collected packages: Pillow
  Running setup.py install for Pillow

    Exception installing mp_compile, proceeding without:
                Attempt to start a new process before the current process
                has finished its bootstrapping phase.

                This probably means that you are on Windows and you have
                forgotten to use the proper idiom in the main module:

                    if __name__ == '__main__':
                        freeze_support()
                        ...

                The "freeze_support()" line can be omitted if the program
                is not going to be frozen to produce a Windows executable.
    warning: no files found matching '*.bdf' under directory 'Images'
    warning: no files found matching '*.fli' under directory 'Images'
    warning: no files found matching '*.gif' under directory 'Images'
    warning: no files found matching '*.icns' under directory 'Images'
    warning: no files found matching '*.ico' under directory 'Images'
    warning: no files found matching '*.jpg' under directory 'Images'
    warning: no files found matching '*.pbm' under directory 'Images'
    warning: no files found matching '*.pil' under directory 'Images'
    warning: no files found matching '*.png' under directory 'Images'
    warning: no files found matching '*.ppm' under directory 'Images'
    warning: no files found matching '*.psd' under directory 'Images'
    warning: no files found matching '*.tar' under directory 'Images'
    warning: no files found matching '*.webp' under directory 'Images'
    warning: no files found matching '*.xpm' under directory 'Images'
    warning: no files found matching 'README' under directory 'Sane'
    warning: no files found matching 'README' under directory 'Scripts'
    Exception installing mp_compile, proceeding without:
                Attempt to start a new process before the current process
                has finished its bootstrapping phase.

                This probably means that you are on Windows and you have
                forgotten to use the proper idiom in the main module:

                    if __name__ == '__main__':
                        freeze_support()
                        ...

                The "freeze_support()" line can be omitted if the program
                is not going to be frozen to produce a Windows executable.
    warning: no files found matching '*.txt' under directory 'Tk'

    building 'PIL._imaging' extension
    warning: no files found matching '*.bdf' under directory 'Images'
    warning: no files found matching '*.fli' under directory 'Images'
    warning: no files found matching '*.gif' under directory 'Images'
    warning: no files found matching '*.icns' under directory 'Images'
    warning: no files found matching '*.ico' under directory 'Images'
    warning: no files found matching '*.jpg' under directory 'Images'
    warning: no files found matching '*.pbm' under directory 'Images'
    warning: no files found matching '*.pil' under directory 'Images'
    warning: no files found matching '*.png' under directory 'Images'
    warning: no files found matching '*.ppm' under directory 'Images'
    warning: no files found matching '*.psd' under directory 'Images'
    warning: no files found matching '*.tar' under directory 'Images'
    warning: no files found matching '*.webp' under directory 'Images'
    warning: no files found matching '*.xpm' under directory 'Images'
    warning: no files found matching 'README' under directory 'Sane'
    warning: no files found matching 'README' under directory 'Scripts'

    warning: no files found matching '*.txt' under directory 'Tk'
    warning: no files found matching '*.bdf' under directory 'Images'
    warning: no files found matching '*.fli' under directory 'Images'
    warning: no files found matching '*.gif' under directory 'Images'
    warning: no files found matching '*.icns' under directory 'Images'
    warning: no files found matching '*.ico' under directory 'Images'
    warning: no files found matching '*.jpg' under directory 'Images'
    warning: no files found matching '*.pbm' under directory 'Images'
    warning: no files found matching '*.pil' under directory 'Images'
    warning: no files found matching '*.png' under directory 'Images'
    warning: no files found matching '*.ppm' under directory 'Images'
    warning: no files found matching '*.psd' under directory 'Images'
    warning: no files found matching '*.tar' under directory 'Images'
    warning: no files found matching '*.webp' under directory 'Images'
    warning: no files found matching '*.xpm' under directory 'Images'
    warning: no files found matching 'README' under directory 'Sane'
    warning: no files found matching 'README' under directory 'Scripts'
    building 'PIL._imaging' extension
    warning: no files found matching '*.txt' under directory 'Tk'
    building 'PIL._imaging' extension
    C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\...\django-project-stub\.test\project-name\__data__\venv\build\Pillow\libImaging -IC:\...\django-project-stub\.test\project-name\__data__\venv\include -IC:\Python27\include -IC:\...\django-project-stub\.test\project-name\__data__\venv\PC /Tc_imaging.c /Fobuild\temp.win32-2.7\Release\_imaging.obj
    C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\...\django-project-stub\.test\project-name\__data__\venv\build\Pillow\libImaging -IC:\...\django-project-stub\.test\project-name\__data__\venv\include -IC:\Python27\include -IC:\...\django-project-stub\.test\project-name\__data__\venv\PC /Tc_imaging.c /Fobuild\temp.win32-2.7\Release\_imaging.obj
    C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\...\django-project-stub\.test\project-name\__data__\venv\build\Pillow\libImaging -IC:\...\django-project-stub\.test\project-name\__data__\venv\include -IC:\Python27\include -IC:\...\django-project-stub\.test\project-name\__data__\venv\PC /Tc_imaging.c /Fobuild\temp.win32-2.7\Release\_imaging.obj
    _imaging.c
    _imaging.c
    _imaging.c
    ...\pycharmprojects\github\django-project-stub\.test\project-name\__data__\venv\include\pyconfig.h(227) : fatal error C1083: Не удается открыть файл include: basetsd.h: No such file or directory
    ...\pycharmprojects\github\django-project-stub\.test\project-name\__data__\venv\include\pyconfig.h(227) : fatal error C1083: Не удается открыть файл include: basetsd.h: No such file or directory
    error: CompileError(DistutilsExecError('command \'"C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\BIN\\cl.exe"\' failed with exit status 2',),)
    ...\pycharmprojects\github\django-project-stub\.test\project-name\__data__\venv\include\pyconfig.h(227) : fatal error C1083: Не удается открыть файл include: basetsd.h: No such file or directory
    error: CompileError(DistutilsExecError('command \'"C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\BIN\\cl.exe"\' failed with exit status 2',),)
    error: CompileError(DistutilsExecError('command \'"C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\BIN\\cl.exe"\' failed with exit status 2',),)
    Complete output from command C:\...\django-project-stub\.test\project-name\__data__\venv\Scripts\python.exe -c "import setuptools;__file__='C:\\...django-project-stub\\.test\\project-name\\__data__\\venv\\build\\Pillow\\setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\windows\temp\pip-kzwixo-record\install-record.txt --single-version-externally-managed --install-headers C:\...\django-project-stub\.test\project-name\__data__\venv\include\site\python2.7:
    running install

running build

running build_py

creating build

creating build\lib.win32-2.7

creating build\lib.win32-2.7\PIL

copying PIL\BdfFontFile.py -> build\lib.win32-2.7\PIL

copying PIL\BmpImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\BufrStubImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\ContainerIO.py -> build\lib.win32-2.7\PIL

copying PIL\CurImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\DcxImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\EpsImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\ExifTags.py -> build\lib.win32-2.7\PIL

copying PIL\FitsStubImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\FliImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\FontFile.py -> build\lib.win32-2.7\PIL

copying PIL\FpxImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\GbrImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\GdImageFile.py -> build\lib.win32-2.7\PIL

copying PIL\GifImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\GimpGradientFile.py -> build\lib.win32-2.7\PIL

copying PIL\GimpPaletteFile.py -> build\lib.win32-2.7\PIL

copying PIL\GribStubImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\Hdf5StubImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\IcnsImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\IcoImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\Image.py -> build\lib.win32-2.7\PIL

copying PIL\ImageChops.py -> build\lib.win32-2.7\PIL

copying PIL\ImageCms.py -> build\lib.win32-2.7\PIL

copying PIL\ImageColor.py -> build\lib.win32-2.7\PIL

copying PIL\ImageDraw.py -> build\lib.win32-2.7\PIL

copying PIL\ImageDraw2.py -> build\lib.win32-2.7\PIL

copying PIL\ImageEnhance.py -> build\lib.win32-2.7\PIL

copying PIL\ImageFile.py -> build\lib.win32-2.7\PIL

copying PIL\ImageFileIO.py -> build\lib.win32-2.7\PIL

copying PIL\ImageFilter.py -> build\lib.win32-2.7\PIL

copying PIL\ImageFont.py -> build\lib.win32-2.7\PIL

copying PIL\ImageGrab.py -> build\lib.win32-2.7\PIL

copying PIL\ImageMath.py -> build\lib.win32-2.7\PIL

copying PIL\ImageMode.py -> build\lib.win32-2.7\PIL

copying PIL\ImageMorph.py -> build\lib.win32-2.7\PIL

copying PIL\ImageOps.py -> build\lib.win32-2.7\PIL

copying PIL\ImagePalette.py -> build\lib.win32-2.7\PIL

copying PIL\ImagePath.py -> build\lib.win32-2.7\PIL

copying PIL\ImageQt.py -> build\lib.win32-2.7\PIL

copying PIL\ImageSequence.py -> build\lib.win32-2.7\PIL

copying PIL\ImageShow.py -> build\lib.win32-2.7\PIL

copying PIL\ImageStat.py -> build\lib.win32-2.7\PIL

copying PIL\ImageTk.py -> build\lib.win32-2.7\PIL

copying PIL\ImageTransform.py -> build\lib.win32-2.7\PIL

copying PIL\ImageWin.py -> build\lib.win32-2.7\PIL

copying PIL\ImImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\ImtImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\IptcImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\Jpeg2KImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\JpegImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\JpegPresets.py -> build\lib.win32-2.7\PIL

copying PIL\McIdasImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\MicImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\MpegImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\MspImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\OleFileIO.py -> build\lib.win32-2.7\PIL

copying PIL\PaletteFile.py -> build\lib.win32-2.7\PIL

copying PIL\PalmImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\PcdImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\PcfFontFile.py -> build\lib.win32-2.7\PIL

copying PIL\PcxImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\PdfImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\PixarImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\PngImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\PpmImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\PsdImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\PSDraw.py -> build\lib.win32-2.7\PIL

copying PIL\PyAccess.py -> build\lib.win32-2.7\PIL

copying PIL\SgiImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\SpiderImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\SunImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\TarIO.py -> build\lib.win32-2.7\PIL

copying PIL\TgaImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\TiffImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\TiffTags.py -> build\lib.win32-2.7\PIL

copying PIL\WalImageFile.py -> build\lib.win32-2.7\PIL

copying PIL\WebPImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\WmfImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\XbmImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\XpmImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\XVThumbImagePlugin.py -> build\lib.win32-2.7\PIL

copying PIL\_binary.py -> build\lib.win32-2.7\PIL

copying PIL\_util.py -> build\lib.win32-2.7\PIL

copying PIL\__init__.py -> build\lib.win32-2.7\PIL

running egg_info

writing Pillow.egg-info\PKG-INFO

writing top-level names to Pillow.egg-info\top_level.txt

writing dependency_links to Pillow.egg-info\dependency_links.txt

warning: manifest_maker: standard file '-c' not found



reading manifest file 'Pillow.egg-info\SOURCES.txt'

Exception installing mp_compile, proceeding without:

            Attempt to start a new process before the current process

            has finished its bootstrapping phase.



            This probably means that you are on Windows and you have

            forgotten to use the proper idiom in the main module:



                if __name__ == '__main__':

                    freeze_support()

                    ...



            The "freeze_support()" line can be omitted if the program

            is not going to be frozen to produce a Windows executable.

running install

running build

running build_py

reading manifest template 'MANIFEST.in'

warning: no files found matching '*.bdf' under directory 'Images'

warning: no files found matching '*.fli' under directory 'Images'

running egg_info

warning: no files found matching '*.gif' under directory 'Images'

writing Pillow.egg-info\PKG-INFO

warning: no files found matching '*.icns' under directory 'Images'

warning: no files found matching '*.ico' under directory 'Images'

warning: no files found matching '*.jpg' under directory 'Images'

warning: no files found matching '*.pbm' under directory 'Images'

warning: no files found matching '*.pil' under directory 'Images'

warning: no files found matching '*.png' under directory 'Images'

writing top-level names to Pillow.egg-info\top_level.txt

warning: no files found matching '*.ppm' under directory 'Images'

warning: no files found matching '*.psd' under directory 'Images'

warning: no files found matching '*.tar' under directory 'Images'

warning: no files found matching '*.webp' under directory 'Images'

warning: no files found matching '*.xpm' under directory 'Images'

writing dependency_links to Pillow.egg-info\dependency_links.txt

warning: no files found matching 'README' under directory 'Sane'

warning: no files found matching 'README' under directory 'Scripts'

Exception installing mp_compile, proceeding without:

            Attempt to start a new process before the current process

            has finished its bootstrapping phase.



            This probably means that you are on Windows and you have

            forgotten to use the proper idiom in the main module:



                if __name__ == '__main__':

                    freeze_support()

                    ...



            The "freeze_support()" line can be omitted if the program

            is not going to be frozen to produce a Windows executable.

running install

running build

running build_py

warning: no files found matching '*.txt' under directory 'Tk'

running egg_info

writing Pillow.egg-info\PKG-INFO

writing top-level names to Pillow.egg-info\top_level.txt

writing dependency_links to Pillow.egg-info\dependency_links.txt

writing manifest file 'Pillow.egg-info\SOURCES.txt'

copying PIL\OleFileIO-README.md -> build\lib.win32-2.7\PIL

running build_ext

warning: manifest_maker: standard file '-c' not found



reading manifest file 'Pillow.egg-info\SOURCES.txt'

building 'PIL._imaging' extension

reading manifest template 'MANIFEST.in'

warning: no files found matching '*.bdf' under directory 'Images'

warning: no files found matching '*.fli' under directory 'Images'

warning: no files found matching '*.gif' under directory 'Images'

warning: no files found matching '*.icns' under directory 'Images'

warning: no files found matching '*.ico' under directory 'Images'

warning: no files found matching '*.jpg' under directory 'Images'

warning: no files found matching '*.pbm' under directory 'Images'

warning: no files found matching '*.pil' under directory 'Images'

warning: no files found matching '*.png' under directory 'Images'

warning: no files found matching '*.ppm' under directory 'Images'

warning: no files found matching '*.psd' under directory 'Images'

warning: no files found matching '*.tar' under directory 'Images'

warning: no files found matching '*.webp' under directory 'Images'

warning: no files found matching '*.xpm' under directory 'Images'

warning: no files found matching 'README' under directory 'Sane'

warning: no files found matching 'README' under directory 'Scripts'

warning: manifest_maker: standard file '-c' not found



reading manifest file 'Pillow.egg-info\SOURCES.txt'

warning: no files found matching '*.txt' under directory 'Tk'

reading manifest template 'MANIFEST.in'

warning: no files found matching '*.bdf' under directory 'Images'

warning: no files found matching '*.fli' under directory 'Images'

warning: no files found matching '*.gif' under directory 'Images'

writing manifest file 'Pillow.egg-info\SOURCES.txt'

warning: no files found matching '*.icns' under directory 'Images'

warning: no files found matching '*.ico' under directory 'Images'

warning: no files found matching '*.jpg' under directory 'Images'

warning: no files found matching '*.pbm' under directory 'Images'

warning: no files found matching '*.pil' under directory 'Images'

warning: no files found matching '*.png' under directory 'Images'

warning: no files found matching '*.ppm' under directory 'Images'

warning: no files found matching '*.psd' under directory 'Images'

warning: no files found matching '*.tar' under directory 'Images'

warning: no files found matching '*.webp' under directory 'Images'

warning: no files found matching '*.xpm' under directory 'Images'

running build_ext

warning: no files found matching 'README' under directory 'Sane'

warning: no files found matching 'README' under directory 'Scripts'

building 'PIL._imaging' extension

warning: no files found matching '*.txt' under directory 'Tk'

writing manifest file 'Pillow.egg-info\SOURCES.txt'

running build_ext

building 'PIL._imaging' extension

creating build\temp.win32-2.7

creating build\temp.win32-2.7\Release

creating build\temp.win32-2.7\Release\libImaging

C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\...\django-project-stub\.test\project-name\__data__\venv\build\Pillow\libImaging -IC:\...\django-project-stub\.test\project-name\__data__\venv\include -IC:\Python27\include -IC:\...\django-project-stub\.test\project-name\__data__\venv\PC /Tc_imaging.c /Fobuild\temp.win32-2.7\Release\_imaging.obj

C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\...\django-project-stub\.test\project-name\__data__\venv\build\Pillow\libImaging -IC:\...\django-project-stub\.test\project-name\__data__\venv\include -IC:\Python27\include -IC:\...\django-project-stub\.test\project-name\__data__\venv\PC /Tc_imaging.c /Fobuild\temp.win32-2.7\Release\_imaging.obj

C:\Program Files (x86)\Microsoft Visual Studio 9.0\VC\BIN\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\...\django-project-stub\.test\project-name\__data__\venv\build\Pillow\libImaging -IC:\...\django-project-stub\.test\project-name\__data__\venv\include -IC:\Python27\include -IC:\...\django-project-stub\.test\project-name\__data__\venv\PC /Tc_imaging.c /Fobuild\temp.win32-2.7\Release\_imaging.obj

_imaging.c

_imaging.c

_imaging.c

...\pycharmprojects\github\django-project-stub\.test\project-name\__data__\venv\include\pyconfig.h(227) : fatal error
 C1083: Не удается открыть файл include: basetsd.h: No such file or directory

...\pycharmprojects\github\django-project-stub\.test\project-name\__data__\venv\include\pyconfig.h(227) : fatal error
 C1083: Не удается открыть файл include: basetsd.h: No such file or directory

error: CompileError(DistutilsExecError('command \'"C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\BIN\\cl.exe"\' failed
 with exit status 2',),)

...\pycharmprojects\github\django-project-stub\.test\project-name\__data__\venv\include\pyconfig.h(227) : fatal error
 C1083: Не удается открыть файл include: basetsd.h: No such file or directory

error: CompileError(DistutilsExecError('command \'"C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\BIN\\cl.exe"\' failed
 with exit status 2',),)

error: CompileError(DistutilsExecError('command \'"C:\\Program Files (x86)\\Microsoft Visual Studio 9.0\\VC\\BIN\\cl.exe"\' failed
 with exit status 2',),)

----------------------------------------
Cleaning up...
Command C:\...\django-project-stub\.test\project-name\__data__\venv\Scripts\python.exe -c "import setuptools;__file__='C:\\...django-project-stub\\.test\\project-name\\__data__\\venv\\build\\Pillow\\setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record c:\windows\temp\pip-kzwixo-record\install-record.txt --single-version-externally-managed --install-headers C:\...\django-project-stub\.test\project-name\__data__\venv\include\site\python2.7 failed with error code 1 in C:\...\django-project-stub\.test\project-name\__data__\venv\build\Pillow
Traceback (most recent call last):
  File "C:\...\django-project-stub\.test\project-name\__data__\venv\Scripts\pip-script.py", line9, in <module>
    load_entry_point('pip==1.4.1', 'console_scripts', 'pip')()
  File "C:\...\django-project-stub\.test\project-name\__data__\venv\lib\site-packages\pip\__init__.py", line 148, in main
    return command.main(args[1:], options)
  File "C:\...\django-project-stub\.test\project-name\__data__\venv\lib\site-packages\pip\basecommand.py", line 169, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8d in position 142: ordinal not in range(128)
```

Similar error for pip==1.5.6.

Now I use `easy_install PIL`:

```
C:\...\django-project-stub\.test\project-name>__data__\venv\Scripts\easy_install PIL
Searching for PIL
Reading https://pypi.python.org/simple/PIL/
Reading http://effbot.org/downloads/#Imaging
Reading http://effbot.org/zone/pil-changes-115.htm
Reading http://www.pythonware.com/products/pil
Best match: PIL 1.1.7
Downloading http://effbot.org/media/downloads/PIL-1.1.7.win32-py2.7.exe
Processing PIL-1.1.7.win32-py2.7.exe
Image: module references __file__
creating 'c:\windows\temp\easy_install-en9xkp\PIL-1.1.7-py2.7-win32.egg' and adding 'c:\windows\temp\easy_install-en9xkp\PIL-1.1.7-py2.7-win32.egg.tmp' to it
creating c:\...\django-project-stub\.test\project-name\__data__\venv\lib\site-packages\PIL-1.1.7-py2.7-win32.egg
Extracting PIL-1.1.7-py2.7-win32.egg to c:\...\django-project-stub\.test\project-name\__data__\venv\lib\site-packages
Adding PIL 1.1.7 to easy-install.pth file
Installing pilconvert.py script to C:\...\django-project-stub\.test\project-name\__data__\venv\Scripts
Installing pilconvert.pyc script to C:\...\django-project-stub\.test\project-name\__data__\venv\Scripts
Installing pildriver.py script to C:\...\django-project-stub\.test\project-name\__data__\venv\Scripts
Installing pildriver.pyc script to C:\...\django-project-stub\.test\project-name\__data__\venv\Scripts
Installing pilfile.py script to C:\...\django-project-stub\.test\project-name\__data__\venv\Scripts
Installing pilfile.pyc script to C:\...\django-project-stub\.test\project-name\__data__\venv\Scripts
Installing pilfont.py script to C:\...\django-project-stub\.test\project-name\__data__\venv\Scripts
Installing pilfont.pyc script to C:\...\django-project-stub\.test\project-name\__data__\venv\Scripts
Installing pilprint.py script to C:\...\django-project-stub\.test\project-name\__data__\venv\Scripts
Installing pilprint.pyc script to C:\...\django-project-stub\.test\project-name\__data__\venv\Scripts

Installed c:\...\django-project-stub\.test\project-name\__data__\venv\lib\site-packages\pil-1.1.7-py2.7-win32.egg
Processing dependencies for PIL
Finished processing dependencies for PIL
```

It work fine for me.

**Comment by linzhi** [comment]
when I install Pillow on linux, have the same problem.......use easy_install on linux

**Comment by jaisonvipoint** [comment]
@aclark4life 
===>> pip install Pillow==2.5.0

Works like a charm!!

**Comment by hugovk** [comment]
@jaisonvipoint That's three year old advice, try this:
```bash
pip install -U pillow
```

**Comment by jaisonvipoint** [comment]
@hugovk Yup, but it still worked. I tried "pip install -U pillow" but that threw a ton of errors. 

I'm just a beginner who is trying to play with python and controlling application gui using python. So if I start debugging even in the initial setup phase, I might get bored.

Anyway, thank you for the heart that you showed to help. 

Have a great day ahead!!
