### ISSUE TITLE
Python 3.13 not supported

### ISSUE THREAD

**Issue by daniKayran** [python-pillow/Pillow#8075]
this leb not supported python3.13

**Comment by jm-nab** [comment]
same here:

python 3.13.0b1

```
genai-qa:$ pip install -U pillow
Collecting pillow
  Using cached pillow-10.3.0.tar.gz (46.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "/home/jm/repos/northgpt/vertexai_loaders/venv_313/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
          ~~~~^^
        File "/home/jm/repos/northgpt/vertexai_loaders/venv_313/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ~~~~^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/jm/repos/northgpt/vertexai_loaders/venv_313/lib/python3.13/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-7r2m69xg/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-7r2m69xg/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 295, in _get_build_requires
          self.run_setup()
          ~~~~~~~~~~~~~~^^
        File "/tmp/pip-build-env-7r2m69xg/overlay/lib/python3.13/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
          ~~~~^^^^^^^^^^^^^^^^
        File "<string>", line 33, in <module>
        File "<string>", line 27, in get_version
      KeyError: '__version__'
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by Yay295** [comment]
#8050 fixed this yesterday.

**Comment by jm-nab** [comment]
> #8050 fixed this yesterday.

Yes thank you! Looks like I'm unblocked via this change in pyproject.toml

```
pillow = {git = "https://github.com/python-pillow/Pillow.git" ,rev = "d879f397112d1cb50af7d27f16eaf2c7bb221043"}
```

**Comment by radarhere** [comment]
Pillow should work with 3.13 alpha 6. The change that caused this problem only appeared in 3.13 beta 1. It is indeed fixed by #8050. On July 1, Pillow 10.4.0 is scheduled to be released, which should include that, and I expect also include Python 3.13 beta wheels with #8071.

However, Pillow will not officially support Python 3.13 until Pillow 11.0.0 on October 15, because that is the first release after Python 3.13 final is released.

**Comment by radarhere** [comment]
Pillow 10.4.0 has just been released. If you try again now, the problem should be resolved.

**Comment by Aramis7609** [comment]
Python 3.13.2

PyAutoGUIException: PyAutoGUI was unable to import pyscreeze, (This is likely because you're running a version of Python that Pillow (which pyscreeze depends on) doesn't support currently.) Please install this module to enable the function you tried to call.
