### ISSUE TITLE
New uncaught exception: AttributeError: module 'logging' has no attribute 'getLogger'

### ISSUE THREAD

**Issue by xioren** [python-pillow/Pillow#8147]
### What did you do?
import pillow
### What did you expect to happen?
import pillow
### What actually happened?
multitude of files downloaded followed by an uncaught exception.
### What are your OS, Python and Pillow versions?

* OS: Debian
* Python: 3.11.9
* Pillow: 10.3.0

```text
--------------------------------------------------------------------
Pillow 10.3.0
Python 3.11.9 (main, Apr 10 2024, 13:16:36) [GCC 13.2.0]
--------------------------------------------------------------------
Python executable is /home/xioren/.venv/main/bin/python3
Environment Python files loaded from /home/xioren/.venv/main
System Python files loaded from /usr
--------------------------------------------------------------------
Python Pillow modules loaded from /home/xioren/.venv/main/lib/python3.11/site-packages/PIL
Binary Pillow modules loaded from /home/xioren/.venv/main/lib/python3.11/site-packages/PIL
--------------------------------------------------------------------
--- PIL CORE support ok, compiled for 10.3.0
*** TKINTER support not installed
--- FREETYPE2 support ok, loaded 2.13.2
--- LITTLECMS2 support ok, loaded 2.16
--- WEBP support ok, loaded 1.3.2
--- WEBP Transparency support ok
--- WEBPMUX support ok
--- WEBP Animation support ok
--- JPEG support ok, compiled for libjpeg-turbo 3.0.2
--- OPENJPEG (JPEG2000) support ok, loaded 2.5.2
--- ZLIB (PNG/ZIP) support ok, loaded 1.3.1
--- LIBTIFF support ok, loaded 4.6.0
--- RAQM (Bidirectional Text) support ok, loaded 0.10.1, fribidi 1.0.13, harfbuzz 8.4.0
*** LIBIMAGEQUANT (Quantization method) support not installed
--- XCB (X protocol) support ok
--------------------------------------------------------------------
```

```python
from PIL import Image
```

```python
File 94 complete
File 97 complete
File 93 complete
File 96 complete
File 95 complete
File 99 complete
File 98 complete
File 100 complete

Downloads completed
Traceback (most recent call last):
  File "/home/xioren/Documents/coding/python/misc/zip_utils.py", line 6, in <module>
    from PIL import Image
  File "/home/xioren/.venv/main/lib/python3.11/site-packages/PIL/Image.py", line 67, in <module>
    logger = logging.getLogger(__name__)
             ^^^^^^^^^^^^^^^^^
AttributeError: module 'logging' has no attribute 'getLogger'
```

**Comment by xioren** [comment]
The issue was I had a script called logging.py in the same directory.

**Comment by hugovk** [comment]
It's a common problem, the good news is Python 3.13 will have a better error message for this case:

https://docs.python.org/3.13/whatsnew/3.13.html#improved-error-messages

```pytb
Python 3.13.0b2 (v3.13.0b2:3a83b172af, Jun  5 2024, 12:50:24) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
Traceback (most recent call last):
  File "<python-input-0>", line 1, in <module>
    from PIL import Image
  File "/Users/hugo/github/Pillow/src/PIL/Image.py", line 68, in <module>
    logger = logging.getLogger(__name__)
             ^^^^^^^^^^^^^^^^^
AttributeError: module 'logging' has no attribute 'getLogger' (consider renaming 
'/Users/hugo/my-project/logging.py' since it has the same name as the standard 
library module named 'logging' and the import system gives it precedence)
```

**Comment by xioren** [comment]
@hugovk Good to know. That will save some headaches.
