### ISSUE TITLE
Cannot install Tkdesigner

### ISSUE THREAD

**Issue by yoboy1102** [python-pillow/Pillow#8277]
### Windows, Python 3.12.0 64-bit and Pillow 10.4.0 versions

```text
PS C:\Users\user> pip install Tkdesigner
Collecting Tkdesigner
  Using cached tkdesigner-1.0.7-py3-none-any.whl.metadata (8.5 kB)
Collecting Jinja2==3.0.1 (from Tkdesigner)
  Using cached Jinja2-3.0.1-py3-none-any.whl.metadata (3.5 kB)
Collecting Pillow<9.0.0,>=8.4.0 (from Tkdesigner)
  Using cached Pillow-8.4.0.tar.gz (49.4 MB)
  Preparing metadata (setup.py) ... done
Collecting requests==2.25.1 (from Tkdesigner)
  Using cached requests-2.25.1-py2.py3-none-any.whl.metadata (4.2 kB)
Collecting urllib3<2.0.0,>=1.26.6 (from Tkdesigner)
  Using cached urllib3-1.26.19-py2.py3-none-any.whl.metadata (49 kB)
Collecting MarkupSafe>=2.0 (from Jinja2==3.0.1->Tkdesigner)
  Using cached MarkupSafe-2.1.5-cp311-cp311-win32.whl.metadata (3.1 kB)
Collecting chardet<5,>=3.0.2 (from requests==2.25.1->Tkdesigner)
  Using cached chardet-4.0.0-py2.py3-none-any.whl.metadata (3.5 kB)
Collecting idna<3,>=2.5 (from requests==2.25.1->Tkdesigner)
  Using cached idna-2.10-py2.py3-none-any.whl.metadata (9.1 kB)
Collecting certifi>=2017.4.17 (from requests==2.25.1->Tkdesigner)
  Using cached certifi-2024.7.4-py3-none-any.whl.metadata (2.2 kB)
Using cached tkdesigner-1.0.7-py3-none-any.whl (14 kB)
Using cached Jinja2-3.0.1-py3-none-any.whl (133 kB)
Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Using cached urllib3-1.26.19-py2.py3-none-any.whl (143 kB)
Using cached certifi-2024.7.4-py3-none-any.whl (162 kB)
Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Using cached MarkupSafe-2.1.5-cp311-cp311-win32.whl (16 kB)
Building wheels for collected packages: Pillow
  Building wheel for Pillow (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [187 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win32-cpython-311
      creating build\lib.win32-cpython-311\PIL
      copying src\PIL\BdfFontFile.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\BlpImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\BmpImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\BufrStubImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ContainerIO.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\CurImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\DcxImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\DdsImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\EpsImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ExifTags.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\features.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\FitsStubImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\FliImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\FontFile.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\FpxImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\FtexImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\GbrImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\GdImageFile.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\GifImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\GimpGradientFile.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\GimpPaletteFile.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\GribStubImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\Hdf5StubImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\IcnsImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\IcoImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\Image.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageChops.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageCms.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageColor.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageDraw.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageDraw2.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageEnhance.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageFile.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageFilter.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageFont.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageGrab.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageMath.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageMode.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageMorph.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageOps.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImagePalette.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImagePath.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageQt.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageSequence.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageShow.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageStat.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageTk.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageTransform.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageWin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImtImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\IptcImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\Jpeg2KImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\JpegImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\JpegPresets.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\McIdasImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\MicImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\MpegImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\MpoImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\MspImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\PaletteFile.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\PalmImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\PcdImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\PcfFontFile.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\PcxImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\PdfImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\PdfParser.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\PixarImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\PngImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\PpmImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\PsdImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\PSDraw.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\PyAccess.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\SgiImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\SpiderImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\SunImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\TarIO.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\TgaImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\TiffImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\TiffTags.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\WalImageFile.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\WebPImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\WmfImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\XbmImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\XpmImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\XVThumbImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\_binary.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\_tkinter_finder.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\_util.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\_version.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\__init__.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\__main__.py -> build\lib.win32-cpython-311\PIL
      running egg_info
      writing src\Pillow.egg-info\PKG-INFO
      writing dependency_links to src\Pillow.egg-info\dependency_links.txt
      writing top-level names to src\Pillow.egg-info\top_level.txt
      reading manifest file 'src\Pillow.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.c'
      warning: no files found matching '*.h'
      warning: no files found matching '*.sh'
      warning: no previously-included files found matching '.appveyor.yml'
      warning: no previously-included files found matching '.clang-format'
      warning: no previously-included files found matching '.coveragerc'
      warning: no previously-included files found matching '.editorconfig'
      warning: no previously-included files found matching '.readthedocs.yml'
      warning: no previously-included files found matching 'codecov.yml'
      warning: no previously-included files matching '.git*' found anywhere in distribution
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      no previously-included directories found matching '.ci'
      adding license file 'LICENSE'
      writing manifest file 'src\Pillow.egg-info\SOURCES.txt'
      running build_ext
     
     
      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.
     
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
     
      Traceback (most recent call last):
        File "C:\Users\user\AppData\Local\Temp\pip-install-zny8bn5g\pillow_c8bbb00c12cb45cd9d1f2bcc338457a8\setup.py", line 978, in <module>
          setup(
        File "E:\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "E:\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "E:\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "E:\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "E:\Lib\site-packages\setuptools\dist.py", line 1001, in run_command
          super().run_command(command)
        File "E:\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "E:\Lib\site-packages\wheel\bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "E:\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "E:\Lib\site-packages\setuptools\dist.py", line 1001, in run_command
          super().run_command(command)
        File "E:\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "E:\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "E:\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "E:\Lib\site-packages\setuptools\dist.py", line 1001, in run_command
          super().run_command(command)
        File "E:\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "E:\Lib\site-packages\setuptools\command\build_ext.py", line 88, in run
          _build_ext.run(self)
          self.build_extensions()
        File "C:\Users\user\AppData\Local\Temp\pip-install-zny8bn5g\pillow_c8bbb00c12cb45cd9d1f2bcc338457a8\setup.py", line 790, in build_extensions
          raise RequiredDependencyException(f)
      RequiredDependencyException: zlib
     
      During handling of the above exception, another exception occurred:
     
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\user\AppData\Local\Temp\pip-install-zny8bn5g\pillow_c8bbb00c12cb45cd9d1f2bcc338457a8\setup.py", line 1037, in <module>
          raise RequiredDependencyException(msg)
      RequiredDependencyException:
     
      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.
     
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
     
     
      C:\Users\user\AppData\Local\Temp\pip-install-zny8bn5g\pillow_c8bbb00c12cb45cd9d1f2bcc338457a8\setup.py:46: RuntimeWarning: Pillow 8.4.0 does not support Python 3.11 and does not provide prebuilt 
Windows binaries. We do not recommend building from source on Windows.
        lambda: warnings.warn(
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for Pillow
  Running setup.py clean for Pillow
Failed to build Pillow
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (Pillow)
PS C:\Users\user> pip install pillow==8.4.0
Collecting pillow==8.4.0
  Using cached Pillow-8.4.0.tar.gz (49.4 MB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pillow
  Building wheel for pillow (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [187 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win32-cpython-311
      creating build\lib.win32-cpython-311\PIL
      copying src\PIL\BdfFontFile.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\BlpImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\BmpImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\BufrStubImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ContainerIO.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\CurImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\DcxImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\DdsImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\EpsImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ExifTags.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\features.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\FitsStubImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\FliImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\FontFile.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\FpxImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\FtexImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\GbrImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\GdImageFile.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\GifImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\GimpGradientFile.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\GimpPaletteFile.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\GribStubImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\Hdf5StubImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\IcnsImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\IcoImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\Image.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageChops.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageCms.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageColor.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageDraw.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageDraw2.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageEnhance.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageFile.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageFilter.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageFont.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageGrab.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageMath.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageMode.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageMorph.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageOps.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImagePalette.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImagePath.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageQt.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageSequence.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageShow.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageStat.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageTk.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageTransform.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImageWin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\ImtImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\IptcImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\Jpeg2KImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\JpegImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\JpegPresets.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\McIdasImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\MicImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\MpegImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\MpoImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\MspImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\PaletteFile.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\PalmImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\PcdImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\PcfFontFile.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\PcxImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\PdfImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\PdfParser.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\PixarImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\PngImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\PpmImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\PsdImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\PSDraw.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\PyAccess.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\SgiImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\SpiderImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\SunImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\TarIO.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\TgaImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\TiffImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\TiffTags.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\WalImageFile.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\WebPImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\WmfImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\XbmImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\XpmImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\XVThumbImagePlugin.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\_binary.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\_tkinter_finder.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\_util.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\_version.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\__init__.py -> build\lib.win32-cpython-311\PIL
      copying src\PIL\__main__.py -> build\lib.win32-cpython-311\PIL
      running egg_info
      writing src\Pillow.egg-info\PKG-INFO
      writing dependency_links to src\Pillow.egg-info\dependency_links.txt
      writing top-level names to src\Pillow.egg-info\top_level.txt
      reading manifest file 'src\Pillow.egg-info\SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.c'
      warning: no files found matching '*.h'
      warning: no files found matching '*.sh'
      warning: no previously-included files found matching '.appveyor.yml'
      warning: no previously-included files found matching '.clang-format'
      warning: no previously-included files found matching '.coveragerc'
      warning: no previously-included files found matching '.editorconfig'
      warning: no previously-included files found matching '.readthedocs.yml'
      warning: no previously-included files found matching 'codecov.yml'
      warning: no previously-included files matching '.git*' found anywhere in distribution
      warning: no previously-included files matching '*.pyc' found anywhere in distribution
      warning: no previously-included files matching '*.so' found anywhere in distribution
      no previously-included directories found matching '.ci'
      adding license file 'LICENSE'
      writing manifest file 'src\Pillow.egg-info\SOURCES.txt'
      running build_ext
     
     
      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.
     
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
     
      Traceback (most recent call last):
        File "C:\Users\user\AppData\Local\Temp\pip-install-76ozcfij\pillow_8917acbc33aa488eaab5626227efeb39\setup.py", line 978, in <module>
          setup(
        File "E:\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "E:\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "E:\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "E:\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "E:\Lib\site-packages\setuptools\dist.py", line 1001, in run_command
          super().run_command(command)
        File "E:\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "E:\Lib\site-packages\wheel\bdist_wheel.py", line 364, in run
          self.run_command("build")
        File "E:\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "E:\Lib\site-packages\setuptools\dist.py", line 1001, in run_command
          super().run_command(command)
        File "E:\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "E:\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "E:\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "E:\Lib\site-packages\setuptools\dist.py", line 1001, in run_command
          super().run_command(command)
        File "E:\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "E:\Lib\site-packages\setuptools\command\build_ext.py", line 88, in run
          _build_ext.run(self)
        File "E:\Lib\site-packages\setuptools\_distutils\command\build_ext.py", line 345, in run
          self.build_extensions()
        File "C:\Users\user\AppData\Local\Temp\pip-install-76ozcfij\pillow_8917acbc33aa488eaab5626227efeb39\setup.py", line 790, in build_extensions
          raise RequiredDependencyException(f)
      RequiredDependencyException: zlib
     
      During handling of the above exception, another exception occurred:
     
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\user\AppData\Local\Temp\pip-install-76ozcfij\pillow_8917acbc33aa488eaab5626227efeb39\setup.py", line 1037, in <module>
          raise RequiredDependencyException(msg)
      RequiredDependencyException:
     
      The headers or library files could not be found for zlib,
      a required dependency when compiling Pillow from source.
     
      Please see the install instructions at:
         https://pillow.readthedocs.io/en/latest/installation.html
     
     
      C:\Users\user\AppData\Local\Temp\pip-install-76ozcfij\pillow_8917acbc33aa488eaab5626227efeb39\setup.py:46: RuntimeWarning: Pillow 8.4.0 does not support Python 3.11 and does not provide prebuilt 
Windows binaries. We do not recommend building from source on Windows.
        lambda: warnings.warn(
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pillow
  Running setup.py clean for pillow
Failed to build pillow
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (pillow)
```

```python
pip3 install Tkdesigner
```

###Note: I run this command in vs code terminal, if i open a new window(vs code) and type in python --version
it says No pyvenv.cfg found, same happens in CMD, I only am able to know the version of python if i go in a python file`s terminal and run the code python --version, 
Also, I was never able to find python`s IDLE or Command line center(MySQL), I Simply worked around it using vs code

These are just backround issues I have that are possibly and probably related to the issue I have rn, I dont realistically need a solution for these but it could help you Identify the Issue I have rn

Thanks

**Comment by radarhere** [comment]
You are running Python 3.11, except tkdesigner is has specified that it wants Pillow >= 8.4 < 9, and [those Pillow versions don't support Python 3.11](https://pillow.readthedocs.io/en/stable/installation/python-support.html). You are not the first to experience this - see https://github.com/ParthJadhav/Tkinter-Designer/issues/425 and https://github.com/ParthJadhav/Tkinter-Designer/issues/405 for example.

The simplest solution would be to switch to Python 3.10.

**Comment by yoboy1102** [comment]
Thanks

**Comment by radarhere** [comment]
Cool. So you were able to solve the problem and this is resolved then?

**Comment by yoboy1102** [comment]
yea I watched his video and just did workarounds finally got it, Thanks
btw i still have those problems i mentioned at the end, I havent even been able to identify the cause, yk anything abt it?

**Comment by radarhere** [comment]
> I run this command in vs code terminal, if i open a new window(vs code) and type in python --version
it says No pyvenv.cfg found, same happens in CMD, I only am able to know the version of python if i go in a python files terminal and run the code python --version,  Also, I was never able to find pythons IDLE or Command line center(MySQL), I Simply worked around it using vs code

These problems? I'm not a VSCode user personally, but Googling, take a look at https://stackoverflow.com/questions/61026458/no-pyvenv-cfg-file and see if anything there is helpful.

If you can't find IDLE, then it would be helpful to know how you installed Python. You may need to [re-install it](https://www.python.org/downloads/).

I don't follow the change of topic to MySQL.

**Comment by yoboy1102** [comment]
I see, but VSCODE is just something I am currently using, but let it be pycharm or anything, even the mysql command line centre is missing VSCode was just a workaround for many things, I have many more problems and applied 100`s of solutions but eventually I have to figure a workaround

For python however again I have reinstalled like 100k times using different methods and especially adding to path, I added to path manually, using code, just by clicking tick mark on the python installation window, many other tutorials but again I settled for a workaround

Although this aint a big issue rn it seems interconnected especially "no pyven.cfg found", would just want to know the actual problem or cause to this, If you would know pls tell

**Comment by radarhere** [comment]
Could you include a screenshot of the error so that we can see more information?

See what you think of https://bugs.python.org/issue41365 - I expect running `where python` to reveal that you're not running the standard Python executable, but are running Python from within a virtual environment. I expect that there is [something extra in your path variable](https://au.mathworks.com/matlabcentral/answers/94933-how-do-i-edit-my-system-path-in-windows) causing this confusion.

> even the mysql command line centre is missing

I don't understand how this relates to your Python problems.

**Comment by yoboy1102** [comment]
> I don't understand how this relates to your Python problems.
it doesnt, but seems to be a similar problem

**Comment by yoboy1102** [comment]
My bad but i didnt understand what ss to provide exactly

**Comment by radarhere** [comment]
> it says No pyvenv.cfg found, same happens in CMD

Could you provide a screenshot of this error, happening outside of VSCode? Because it is happening everywhere for you, let's keep things simple.

Could you also run `where python` and let us know what the output is?

**Comment by yoboy1102** [comment]
![image](https://github.com/user-attachments/assets/4071a5cc-cd81-4a26-8c5f-04aff9846e0f)
@

**Comment by radarhere** [comment]
So I expect E:\python.exe and E:\Scripts\python.exe are part of the virtual environment. Unless your intention is to use a virtual environment, remove them, and try again.

**Comment by radarhere** [comment]
@yoboy1102 did that resolve your problem?

**Comment by yoboy1102** [comment]
not really, i just worked around for now, thanks tho
