### ISSUE TITLE
Tests/test_file_palm.py:TestFilePalm.test_monochrome() fails

### ISSUE THREAD

**Issue by Arfrever** [python-pillow/Pillow#940]
`Tests/test_file_palm.py:TestFilePalm.test_monochrome()` fails in Pillow 2.6.0 and trunk.
Result for trunk:

```
$ PYTHONPATH="build/lib.linux-x86_64-3.4" python3.4 Tests/test_file_palm.py
/tmp/Pillow/build/lib.linux-x86_64-3.4/PIL/Image.py:829: ResourceWarning: unclosed file <_io.BufferedReader name='Tests/images/hopper.ppm'>
  self.load()
/tmp/Pillow/build/lib.linux-x86_64-3.4/PIL/Image.py:647: ResourceWarning: unclosed file <_io.BufferedReader name='/tmp/tempnsk4jojm.png'>
  self.load()
F/tmp/Pillow/build/lib.linux-x86_64-3.4/PIL/Image.py:829: ResourceWarning: unclosed file <_io.BufferedReader name='Tests/images/hopper.ppm'>
  self.load()
=== orphaned temp file: /tmp/tempy2a4m8lw_P.palm
s/tmp/Pillow/build/lib.linux-x86_64-3.4/PIL/Image.py:1652: ResourceWarning: unclosed file <_io.BufferedReader name='Tests/images/hopper.ppm'>
  self.load()
=== orphaned temp file: /tmp/temp1y0tnb5d_RGB.palm
.
======================================================================
FAIL: TestFilePalm.test_monochrome
----------------------------------------------------------------------
Traceback (most recent call last):
  File "Tests/test_file_palm.py", line 38, in test_monochrome
    self.roundtrip(mode)
  File "Tests/test_file_palm.py", line 30, in roundtrip
    self.assert_image_equal(converted, im)
  File "/tmp/Pillow/Tests/helper.py", line 81, in assert_image_equal
    self.fail(msg or "got different content")
AssertionError: got different content

----------------------------------------------------------------------
Ran 3 tests in 0.109s

FAILED (failures=1, skipped=1)
```

**Comment by aclark4life** [comment]
Valid or not? If this is still an issue, please reopen.

**Comment by Arfrever** [comment]
This bug is still reproducible in Pillow 2.8.1 and trunk.
Please re-open this bug.
This bug tracker is misconfigured and even reporter of given bug cannot re-open it.

**Comment by radarhere** [comment]
While I could easily be wrong, but reading http://www.imagemagick.org/discourse-server/viewtopic.php?t=26446 makes me think that this is due to HDRI mode.

**Comment by hugovk** [comment]
@Arfrever Does this still occur for you with the latest version of Pillow?

It's still passing on CI (Travis and AppVeyor) and also for me with Python 2.7.13 and 3.6.0 on macOS Sierra.

**Comment by Arfrever** [comment]
This test now passes for me.
